package model;
// Generated 14/02/2019 19:19:16 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "SEMESTRE")
@NamedQueries({ @NamedQuery(name = "Semestre.findAll", query = "select s from Semestre as s order by s.smsId")})
public class Semestre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer smsId;
	private String smsDescripcion;
	private String smsEstado;
	private Set<MallaCurricularMateria> mallaCurricularMaterias = new HashSet<MallaCurricularMateria>(0);

	public Semestre() {
	}

	public Semestre(Integer smsId) {
		this.smsId = smsId;
	}

	public Semestre(Integer smsId, String smsDescripcion, String smsEstado,
			Set<MallaCurricularMateria> mallaCurricularMaterias) {
		this.smsId = smsId;
		this.smsDescripcion = smsDescripcion;
		this.smsEstado = smsEstado;
		this.mallaCurricularMaterias = mallaCurricularMaterias;
	}

	@Id

	@Column(name = "SMS_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Integer getSmsId() {
		return this.smsId;
	}

	public void setSmsId(Integer smsId) {
		this.smsId = smsId;
	}

	@Column(name = "SMS_DESCRIPCION", length = 25)
	public String getSmsDescripcion() {
		return this.smsDescripcion;
	}

	public void setSmsDescripcion(String smsDescripcion) {
		this.smsDescripcion = smsDescripcion;
	}

	@Column(name = "SMS_ESTADO", length = 10)
	public String getSmsEstado() {
		return this.smsEstado;
	}

	public void setSmsEstado(String smsEstado) {
		this.smsEstado = smsEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestre")
	public Set<MallaCurricularMateria> getMallaCurricularMaterias() {
		return this.mallaCurricularMaterias;
	}

	public void setMallaCurricularMaterias(Set<MallaCurricularMateria> mallaCurricularMaterias) {
		this.mallaCurricularMaterias = mallaCurricularMaterias;
	}

}
