package model;
// Generated 17/02/2019 21:49:48 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleMatricula generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_MATRICULA")
public class DetalleMatricula implements java.io.Serializable {

	private BigDecimal dtmtId;
	private MallaCurricularParalelo mallaCurricularParalelo;
	private FichaMatricula fichaMatricula;

	public DetalleMatricula() {
	}

	public DetalleMatricula(BigDecimal dtmtId, MallaCurricularParalelo mallaCurricularParalelo,
			FichaMatricula fichaMatricula) {
		this.dtmtId = dtmtId;
		this.mallaCurricularParalelo = mallaCurricularParalelo;
		this.fichaMatricula = fichaMatricula;
	}

	@Id

	@Column(name = "DTMT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDtmtId() {
		return this.dtmtId;
	}

	public void setDtmtId(BigDecimal dtmtId) {
		this.dtmtId = dtmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRPR_ID", nullable = false)
	public MallaCurricularParalelo getMallaCurricularParalelo() {
		return this.mallaCurricularParalelo;
	}

	public void setMallaCurricularParalelo(MallaCurricularParalelo mallaCurricularParalelo) {
		this.mallaCurricularParalelo = mallaCurricularParalelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCMT_ID", nullable = false)
	public FichaMatricula getFichaMatricula() {
		return this.fichaMatricula;
	}

	public void setFichaMatricula(FichaMatricula fichaMatricula) {
		this.fichaMatricula = fichaMatricula;
	}

}
