package model;
// Generated 15/04/2019 20:41:59 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FichaEmpleado generated by hbm2java
 */
@Entity
@Table(name = "FICHA_EMPLEADO")
public class FichaEmpleado implements java.io.Serializable {

	private BigDecimal fcemId;
	private String fcemCi;
	private String fcemApellidos;
	private String fcemPrimerNombre;
	private String fcemSegundoNombre;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public FichaEmpleado() {
	}

	public FichaEmpleado(BigDecimal fcemId) {
		this.fcemId = fcemId;
	}

	public FichaEmpleado(BigDecimal fcemId, String fcemCi, String fcemApellidos, String fcemPrimerNombre,
			String fcemSegundoNombre, Set<DetallePuesto> detallePuestos, Set<Usuario> usuarios) {
		this.fcemId = fcemId;
		this.fcemCi = fcemCi;
		this.fcemApellidos = fcemApellidos;
		this.fcemPrimerNombre = fcemPrimerNombre;
		this.fcemSegundoNombre = fcemSegundoNombre;
		this.detallePuestos = detallePuestos;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "FCEM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getFcemId() {
		return this.fcemId;
	}

	public void setFcemId(BigDecimal fcemId) {
		this.fcemId = fcemId;
	}

	@Column(name = "FCEM_CI", length = 10)
	public String getFcemCi() {
		return this.fcemCi;
	}

	public void setFcemCi(String fcemCi) {
		this.fcemCi = fcemCi;
	}

	@Column(name = "FCEM_APELLIDOS", length = 50)
	public String getFcemApellidos() {
		return this.fcemApellidos;
	}

	public void setFcemApellidos(String fcemApellidos) {
		this.fcemApellidos = fcemApellidos;
	}

	@Column(name = "FCEM_PRIMER_NOMBRE", length = 20)
	public String getFcemPrimerNombre() {
		return this.fcemPrimerNombre;
	}

	public void setFcemPrimerNombre(String fcemPrimerNombre) {
		this.fcemPrimerNombre = fcemPrimerNombre;
	}

	@Column(name = "FCEM_SEGUNDO_NOMBRE", length = 20)
	public String getFcemSegundoNombre() {
		return this.fcemSegundoNombre;
	}

	public void setFcemSegundoNombre(String fcemSegundoNombre) {
		this.fcemSegundoNombre = fcemSegundoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEmpleado")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEmpleado")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
