package model;
// Generated 13/02/2019 17:29:01 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MallaCurricularParalelo generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR_PARALELO")
public class MallaCurricularParalelo implements java.io.Serializable {

	private BigDecimal mlcrprId;
	private Paralelo paralelo;
	private MallaCurricularMateria mallaCurricularMateria;
	private BigDecimal mlcrprInscritos;
	private Set<DetalleMatricula> detalleMatriculas = new HashSet<DetalleMatricula>(0);

	public MallaCurricularParalelo() {
	}

	public MallaCurricularParalelo(BigDecimal mlcrprId, Paralelo paralelo,
			MallaCurricularMateria mallaCurricularMateria) {
		this.mlcrprId = mlcrprId;
		this.paralelo = paralelo;
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	public MallaCurricularParalelo(BigDecimal mlcrprId, Paralelo paralelo,
			MallaCurricularMateria mallaCurricularMateria, BigDecimal mlcrprInscritos,
			Set<DetalleMatricula> detalleMatriculas) {
		this.mlcrprId = mlcrprId;
		this.paralelo = paralelo;
		this.mallaCurricularMateria = mallaCurricularMateria;
		this.mlcrprInscritos = mlcrprInscritos;
		this.detalleMatriculas = detalleMatriculas;
	}

	@Id

	@Column(name = "MLCRPR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMlcrprId() {
		return this.mlcrprId;
	}

	public void setMlcrprId(BigDecimal mlcrprId) {
		this.mlcrprId = mlcrprId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRL_ID", nullable = false)
	public Paralelo getParalelo() {
		return this.paralelo;
	}

	public void setParalelo(Paralelo paralelo) {
		this.paralelo = paralelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRMT_ID", nullable = false)
	public MallaCurricularMateria getMallaCurricularMateria() {
		return this.mallaCurricularMateria;
	}

	public void setMallaCurricularMateria(MallaCurricularMateria mallaCurricularMateria) {
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	@Column(name = "MLCRPR_INSCRITOS", precision = 22, scale = 0)
	public BigDecimal getMlcrprInscritos() {
		return this.mlcrprInscritos;
	}

	public void setMlcrprInscritos(BigDecimal mlcrprInscritos) {
		this.mlcrprInscritos = mlcrprInscritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mallaCurricularParalelo")
	public Set<DetalleMatricula> getDetalleMatriculas() {
		return this.detalleMatriculas;
	}

	public void setDetalleMatriculas(Set<DetalleMatricula> detalleMatriculas) {
		this.detalleMatriculas = detalleMatriculas;
	}

}
