package model;
// Generated 14/02/2019 12:12:32 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoHuella generated by hbm2java
 */
@Entity
@Table(name = "TIPO_HUELLA")
public class TipoHuella implements java.io.Serializable {

	private BigDecimal tphlId;
	private String tphlDescripcionDedo;
	private Set<HuellaDactilar> huellaDactilars = new HashSet<HuellaDactilar>(0);

	public TipoHuella() {
	}

	public TipoHuella(BigDecimal tphlId, String tphlDescripcionDedo) {
		this.tphlId = tphlId;
		this.tphlDescripcionDedo = tphlDescripcionDedo;
	}

	public TipoHuella(BigDecimal tphlId, String tphlDescripcionDedo, Set<HuellaDactilar> huellaDactilars) {
		this.tphlId = tphlId;
		this.tphlDescripcionDedo = tphlDescripcionDedo;
		this.huellaDactilars = huellaDactilars;
	}

	@Id

	@Column(name = "TPHL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTphlId() {
		return this.tphlId;
	}

	public void setTphlId(BigDecimal tphlId) {
		this.tphlId = tphlId;
	}

	@Column(name = "TPHL_DESCRIPCION_DEDO", nullable = false, length = 20)
	public String getTphlDescripcionDedo() {
		return this.tphlDescripcionDedo;
	}

	public void setTphlDescripcionDedo(String tphlDescripcionDedo) {
		this.tphlDescripcionDedo = tphlDescripcionDedo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoHuella")
	public Set<HuellaDactilar> getHuellaDactilars() {
		return this.huellaDactilars;
	}

	public void setHuellaDactilars(Set<HuellaDactilar> huellaDactilars) {
		this.huellaDactilars = huellaDactilars;
	}

}
