package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "HORARIO", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "HRR_INICIO", "HRR_FIN", "FCDC_ID", "DSM_ID" }),
		@UniqueConstraint(columnNames = { "HRR_INICIO", "HRR_FIN", "ALA_ID", "DSM_ID", "FCDC_ID", "MTR_ID" }) })
public class Horario implements java.io.Serializable {

	private BigDecimal hrrId;
	private TipoHorario tipoHorario;
	private Aula aula;
	private DiaSemana diaSemana;
	private FichaDocente fichaDocente;
	private Materia materia;
	private String hrrInicio;
	private String hrrFin;
	private Set<HorarioFichaEstudiante> horarioFichaEstudiantes = new HashSet<HorarioFichaEstudiante>(0);

	public Horario() {
	}

	public Horario(BigDecimal hrrId, TipoHorario tipoHorario, Aula aula, DiaSemana diaSemana, FichaDocente fichaDocente,
			Materia materia) {
		this.hrrId = hrrId;
		this.tipoHorario = tipoHorario;
		this.aula = aula;
		this.diaSemana = diaSemana;
		this.fichaDocente = fichaDocente;
		this.materia = materia;
	}

	public Horario(BigDecimal hrrId, TipoHorario tipoHorario, Aula aula, DiaSemana diaSemana, FichaDocente fichaDocente,
			Materia materia, String hrrInicio, String hrrFin, Set<HorarioFichaEstudiante> horarioFichaEstudiantes) {
		this.hrrId = hrrId;
		this.tipoHorario = tipoHorario;
		this.aula = aula;
		this.diaSemana = diaSemana;
		this.fichaDocente = fichaDocente;
		this.materia = materia;
		this.hrrInicio = hrrInicio;
		this.hrrFin = hrrFin;
		this.horarioFichaEstudiantes = horarioFichaEstudiantes;
	}

	@Id

	@Column(name = "HRR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHrrId() {
		return this.hrrId;
	}

	public void setHrrId(BigDecimal hrrId) {
		this.hrrId = hrrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPHR_ID", nullable = false)
	public TipoHorario getTipoHorario() {
		return this.tipoHorario;
	}

	public void setTipoHorario(TipoHorario tipoHorario) {
		this.tipoHorario = tipoHorario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALA_ID", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DSM_ID", nullable = false)
	public DiaSemana getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(DiaSemana diaSemana) {
		this.diaSemana = diaSemana;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCDC_ID", nullable = false)
	public FichaDocente getFichaDocente() {
		return this.fichaDocente;
	}

	public void setFichaDocente(FichaDocente fichaDocente) {
		this.fichaDocente = fichaDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTR_ID", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "HRR_INICIO", length = 10)
	public String getHrrInicio() {
		return this.hrrInicio;
	}

	public void setHrrInicio(String hrrInicio) {
		this.hrrInicio = hrrInicio;
	}

	@Column(name = "HRR_FIN", length = 10)
	public String getHrrFin() {
		return this.hrrFin;
	}

	public void setHrrFin(String hrrFin) {
		this.hrrFin = hrrFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<HorarioFichaEstudiante> getHorarioFichaEstudiantes() {
		return this.horarioFichaEstudiantes;
	}

	public void setHorarioFichaEstudiantes(Set<HorarioFichaEstudiante> horarioFichaEstudiantes) {
		this.horarioFichaEstudiantes = horarioFichaEstudiantes;
	}

}
