package ec.edu.uce.biometrico.jpa;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDAD")
public class Actividad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer actId;
	private ContenidoCurricular actContenidoCurricular;
	private String actDescripcion;

	public Actividad() {
	}

	public Actividad(Integer actId) {
		this.actId = actId;
	}

	public Actividad(Integer actId, ContenidoCurricular contenidoCurricular) {
		this.actId = actId;
		this.actContenidoCurricular = contenidoCurricular;
	}

	public Actividad(Integer actId, ContenidoCurricular contenidoCurricular, String actDescripcion) {
		this.actId = actId;
		this.actContenidoCurricular = contenidoCurricular;
		this.actDescripcion = actDescripcion;
	}

	@Id

	@Column(name = "ACT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getActId() {
		return this.actId;
	}

	public void setActId(Integer actId) {
		this.actId = actId;
	}

	@ManyToOne
	@JoinColumn(name = "CNT_ID", nullable = false)
	public ContenidoCurricular getActContenidoCurricular() {
		return this.actContenidoCurricular;
	}

	public void setActContenidoCurricular(ContenidoCurricular contenidoCurricular) {
		this.actContenidoCurricular = contenidoCurricular;
	}

	@Column(name = "ACT_DESCRIPCION", length = 400)
	public String getActDescripcion() {
		return this.actDescripcion;
	}

	public void setActDescripcion(String actDescripcion) {
		this.actDescripcion = actDescripcion;
	}

}
