package ec.edu.uce.biometrico.jpa;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "ASISTENCIA_DOCENTE")
@NamedQueries({
		@NamedQuery(name = "Asistencia.findAll", query = "select a from Asistencia as a where a.assFichaDocente.fcdcId=:fcdcId") })

public class Asistencia implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -7010698401038115812L;
	private int assId;
	private FichaDocente assFichaDocente;
	private HorarioAcademico assHorarioAcademico;
	private HorarioAcademicoExamen assHorarioAcademicoExamen;
	private Date assFecha;
	private String assHoraEntrada;
	private String assHoraSalida;
	private String assEstado;
	private List<Seguimiento> assSeguimientos = new ArrayList<>();

	public Asistencia() {
	}

	public Asistencia(int assId, FichaDocente fichaDocente, HorarioAcademico horarioAcademico,
			HorarioAcademicoExamen horarioAcademicoExamen) {
		this.assId = assId;
		this.assFichaDocente = fichaDocente;
		this.assHorarioAcademico = horarioAcademico;
		this.assHorarioAcademicoExamen = horarioAcademicoExamen;
	}

	public Asistencia(int assId, FichaDocente fichaDocente, HorarioAcademico horarioAcademico,
			HorarioAcademicoExamen horarioAcademicoExamen, Date assFecha, String assHoraEntrada, String assHoraSalida,
			String assEstado, List<Seguimiento> seguimientos) {
		this.assId = assId;
		this.assFichaDocente = fichaDocente;
		this.assHorarioAcademico = horarioAcademico;
		this.assHorarioAcademicoExamen = horarioAcademicoExamen;
		this.assFecha = assFecha;
		this.assHoraEntrada = assHoraEntrada;
		this.assHoraSalida = assHoraSalida;
		this.assEstado = assEstado;
		this.assSeguimientos = seguimientos;

	}

	@Id
	@Column(name = "ASDC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getAssId() {
		return this.assId;
	}

	public void setAssId(int assId) {
		this.assId = assId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCDC_ID", nullable = false)
	public FichaDocente getAssFichaDocente() {
		return this.assFichaDocente;
	}

	public void setAssFichaDocente(FichaDocente fichaDocente) {
		this.assFichaDocente = fichaDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HRAC_ID")
	public HorarioAcademico getAssHorarioAcademico() {
		return this.assHorarioAcademico;
	}

	public void setAssHorarioAcademico(HorarioAcademico horarioAcademico) {
		this.assHorarioAcademico = horarioAcademico;
	}

	/**
	 * @return the horarioAcademicoExamen
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HRACEX_ID")
	public HorarioAcademicoExamen getAssHorarioAcademicoExamen() {
		return assHorarioAcademicoExamen;
	}

	/**
	 * @param horarioAcademicoExamen
	 *            the horarioAcademicoExamen to set
	 */
	public void setAssHorarioAcademicoExamen(HorarioAcademicoExamen horarioAcademicoExamen) {
		this.assHorarioAcademicoExamen = horarioAcademicoExamen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASDC_FECHA", length = 7)
	public Date getAssFecha() {
		return this.assFecha;
	}

	public void setAssFecha(Date assFecha) {
		this.assFecha = assFecha;
	}

	@Column(name = "ASDC_HORA_ENTRADA", length = 8)
	public String getAssHoraEntrada() {
		return this.assHoraEntrada;
	}

	public void setAssHoraEntrada(String assHoraEntrada) {
		this.assHoraEntrada = assHoraEntrada;
	}

	@Column(name = "ASDC_HORA_SALIDA", length = 8)
	public String getAssHoraSalida() {
		return this.assHoraSalida;
	}

	public void setAssHoraSalida(String assHoraSalida) {
		this.assHoraSalida = assHoraSalida;
	}

	@Column(name = "ASDC_ESTADO", length = 20)
	public String getAssEstado() {
		return this.assEstado;
	}

	public void setAssEstado(String assEstado) {
		this.assEstado = assEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asistencia")
	public List<Seguimiento> getAssSeguimientos() {
		return this.assSeguimientos;
	}

	public void setAssSeguimientos(List<Seguimiento> seguimientos) {
		this.assSeguimientos = seguimientos;
	}
}
