package ec.edu.uce.biometrico.jpa;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DiaSemana generated by hbm2java
 */
@Entity
@Table(name = "DIA_SEMANA")
public class DiaSemana implements java.io.Serializable {

	private Integer dsmId;
	private String dsmNombreDia;
	

	public DiaSemana() {
	}

	public DiaSemana(Integer dsmId) {
		this.dsmId = dsmId;
	}

	public DiaSemana(Integer dsmId, String dsmNombreDia) {
		this.dsmId = dsmId;
		this.dsmNombreDia = dsmNombreDia;
		
	}

	@Id

	@Column(name = "DSM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getDsmId() {
		return this.dsmId;
	}

	public void setDsmId(Integer dsmId) {
		this.dsmId = dsmId;
	}

	@Column(name = "DSM_NOMBRE_DIA", length = 10)
	public String getDsmNombreDia() {
		return this.dsmNombreDia;
	}

	public void setDsmNombreDia(String dsmNombreDia) {
		this.dsmNombreDia = dsmNombreDia;
	}


}
