package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "GRUPO")
public class Grupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer grpId;
	private String grpDescripcion;
	private Integer grpEstado;
	private String grpCodigo;
	private Integer grpCrrId;
	private List<Materia> materias = new ArrayList<Materia>(0);
	private List<RolFlujoGrupo> rolFlujoGrupos = new ArrayList<RolFlujoGrupo>(0);

	public Grupo() {
	}

	public Grupo(Integer grpId) {
		this.grpId = grpId;
	}

	public Grupo(Integer grpId, String grpDescripcion, Integer grpEstado, String grpCodigo, Integer grpCrrId,
			List<Materia> materias, List<RolFlujoGrupo> rolFlujoGrupos) {
		this.grpId = grpId;
		this.grpDescripcion = grpDescripcion;
		this.grpEstado = grpEstado;
		this.grpCodigo = grpCodigo;
		this.grpCrrId = grpCrrId;
		this.materias = materias;
		this.rolFlujoGrupos = rolFlujoGrupos;
	}

	@Id

	@Column(name = "GRP_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getGrpId() {
		return this.grpId;
	}

	public void setGrpId(Integer grpId) {
		this.grpId = grpId;
	}

	@Column(name = "GRP_DESCRIPCION", length = 1024)
	public String getGrpDescripcion() {
		return this.grpDescripcion;
	}

	public void setGrpDescripcion(String grpDescripcion) {
		this.grpDescripcion = grpDescripcion;
	}

	@Column(name = "GRP_ESTADO", precision = 22, scale = 0)
	public Integer getGrpEstado() {
		return this.grpEstado;
	}

	public void setGrpEstado(Integer grpEstado) {
		this.grpEstado = grpEstado;
	}

	@Column(name = "GRP_CODIGO", length = 256)
	public String getGrpCodigo() {
		return this.grpCodigo;
	}

	public void setGrpCodigo(String grpCodigo) {
		this.grpCodigo = grpCodigo;
	}

	@Column(name = "GRP_CRR_ID", precision = 22, scale = 0)
	public Integer getGrpCrrId() {
		return this.grpCrrId;
	}

	public void setGrpCrrId(Integer grpCrrId) {
		this.grpCrrId = grpCrrId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mtrGrupo")
	public List<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(List<Materia> materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public List<RolFlujoGrupo> getRolFlujoGrupos() {
		return this.rolFlujoGrupos;
	}

	public void setRolFlujoGrupos(List<RolFlujoGrupo> rolFlujoGrupos) {
		this.rolFlujoGrupos = rolFlujoGrupos;
	}

}
