package ec.edu.uce.biometrico.jpa;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Herramienta generated by hbm2java
 */
@Entity
@Table(name = "HERRAMIENTA")
public class Herramienta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer hrrId;
	private ContenidoCurricular hrrContenidoCurricular;
	private String hrrNombre;

	public Herramienta() {
	}

	public Herramienta(Integer hrrId) {
		this.hrrId = hrrId;
	}

	public Herramienta(Integer hrrId, ContenidoCurricular contenidoCurricular) {
		this.hrrId = hrrId;
		this.hrrContenidoCurricular = contenidoCurricular;
	}

	public Herramienta(Integer hrrId, ContenidoCurricular contenidoCurricular, String hrrNombre) {
		this.hrrId = hrrId;
		this.hrrContenidoCurricular = contenidoCurricular;
		this.hrrNombre = hrrNombre;
	}

	@Id

	@Column(name = "HRR_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Integer getHrrId() {
		return this.hrrId;
	}

	public void setHrrId(Integer hrrId) {
		this.hrrId = hrrId;
	}

	@ManyToOne
	@JoinColumn(name = "CNT_ID", nullable = false)
	public ContenidoCurricular getHrrContenidoCurricular() {
		return this.hrrContenidoCurricular;
	}

	public void setHrrContenidoCurricular(ContenidoCurricular contenidoCurricular) {
		this.hrrContenidoCurricular = contenidoCurricular;
	}

	@Column(name = "HRR_NOMBRE", length = 400)
	public String getHrrNombre() {
		return this.hrrNombre;
	}

	public void setHrrNombre(String hrrNombre) {
		this.hrrNombre = hrrNombre;
	}

}
