package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HoraClaseAula generated by hbm2java
 */
@Entity
@Table(name = "HORA_CLASE_AULA")
public class HoraClaseAula implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int hoclalId;
	private Aula hoclalAula;
	private HoraClase hoclalHoraClase;
	private Integer hoclalEstado;
	private List<HorarioAcademico> horarioAcademicos = new ArrayList<HorarioAcademico>(0);

	public HoraClaseAula() {
	}

	public HoraClaseAula(int hoclalId) {
		this.hoclalId = hoclalId;
	}

	public HoraClaseAula(int hoclalId, Aula aula, HoraClase horaClase, Integer hoclalEstado,
			List<HorarioAcademico> horarioAcademicos) {
		this.hoclalId = hoclalId;
		this.hoclalAula = aula;
		this.hoclalHoraClase = horaClase;
		this.hoclalEstado = hoclalEstado;
		this.horarioAcademicos = horarioAcademicos;
	}

	@Id

	@Column(name = "HOCLAL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHoclalId() {
		return this.hoclalId;
	}

	public void setHoclalId(int hoclalId) {
		this.hoclalId = hoclalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALA_ID")
	public Aula getHoclalAula() {
		return this.hoclalAula;
	}

	public void setHoclalAula(Aula aula) {
		this.hoclalAula = aula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOCL_ID")
	public HoraClase getHoclalHoraClase() {
		return this.hoclalHoraClase;
	}

	public void setHoclalHoraClase(HoraClase horaClase) {
		this.hoclalHoraClase = horaClase;
	}

	@Column(name = "HOCLAL_ESTADO", precision = 38, scale = 0)
	public Integer getHoclalEstado() {
		return this.hoclalEstado;
	}

	public void setHoclalEstado(Integer hoclalEstado) {
		this.hoclalEstado = hoclalEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hracHoraClaseAula")
	public List<HorarioAcademico> getHorarioAcademicos() {
		return this.horarioAcademicos;
	}

	public void setHorarioAcademicos(List<HorarioAcademico> horarioAcademicos) {
		this.horarioAcademicos = horarioAcademicos;
	}

}
