package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MallaPeriodo generated by hbm2java
 */
@Entity
@Table(name = "MALLA_PERIODO")
public class MallaPeriodo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer mlprId;
	private PeriodoAcademico mlprPeriodoAcademico;
	private MallaCurricular mlprMallaCurricular;
	private Integer mlprEstado;

	public MallaPeriodo() {
	}

	public MallaPeriodo(Integer mlprId, PeriodoAcademico periodoAcademico, MallaCurricular mallaCurricular) {
		this.mlprId = mlprId;
		this.mlprPeriodoAcademico = periodoAcademico;
		this.mlprMallaCurricular = mallaCurricular;
	}

	public MallaPeriodo(Integer mlprId, PeriodoAcademico periodoAcademico, MallaCurricular mallaCurricular,
			Integer mlprEstado) {
		this.mlprId = mlprId;
		this.mlprPeriodoAcademico = periodoAcademico;
		this.mlprMallaCurricular = mallaCurricular;
		this.mlprEstado = mlprEstado;
	}

	@Id

	@Column(name = "MLPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getMlprId() {
		return this.mlprId;
	}

	public void setMlprId(Integer mlprId) {
		this.mlprId = mlprId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRAC_ID", nullable = false)
	public PeriodoAcademico getMlprPeriodoAcademico() {
		return this.mlprPeriodoAcademico;
	}

	public void setMlprPeriodoAcademico(PeriodoAcademico periodoAcademico) {
		this.mlprPeriodoAcademico = periodoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCR_ID", nullable = false)
	public MallaCurricular getMlprMallaCurricular() {
		return this.mlprMallaCurricular;
	}

	public void setMlprMallaCurricular(MallaCurricular mallaCurricular) {
		this.mlprMallaCurricular = mallaCurricular;
	}

	@Column(name = "MLPR_ESTADO", precision = 22, scale = 0)
	public Integer getMlprEstado() {
		return this.mlprEstado;
	}

	public void setMlprEstado(Integer mlprEstado) {
		this.mlprEstado = mlprEstado;
	}

}
