package ec.edu.uce.biometrico.jpa;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MallaCurricularMateria generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR_MATERIA")
public class MallaCurricularMateria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer mlcrmtId;
	private Nivel nivelByNvlSubId;
	private Nivel mlcrmtNivel;
	private UnidadFormacion mlcrmtUnidadFormacion;
	private MallaCurricular mlcrmtMallaCurricular;
	private Materia mlcrmtMateria;
	private Integer mlcrmtEstado;
	private List<MallaCurricularParalelo> mallaCurricularParalelos = new ArrayList<MallaCurricularParalelo>(0);
	private List<Syllabo> syllabos = new ArrayList<Syllabo>(0);

	public MallaCurricularMateria() {
	}

	public MallaCurricularMateria(Integer mlcrmtId, MallaCurricular mallaCurricular, Materia materia) {
		this.mlcrmtId = mlcrmtId;
		this.mlcrmtMallaCurricular = mallaCurricular;
		this.mlcrmtMateria = materia;
	}

	public MallaCurricularMateria(Integer mlcrmtId, Nivel nivelByNvlSubId, Nivel nivelByNvlId,
			UnidadFormacion unidadFormacion, MallaCurricular mallaCurricular, Materia materia, Integer mlcrmtEstado,
			List<MallaCurricularParalelo> mallaCurricularParalelos, List<Syllabo> syllabos) {
		this.mlcrmtId = mlcrmtId;
		this.nivelByNvlSubId = nivelByNvlSubId;
		this.mlcrmtNivel = nivelByNvlId;
		this.mlcrmtUnidadFormacion = unidadFormacion;
		this.mlcrmtMallaCurricular = mallaCurricular;
		this.mlcrmtMateria = materia;
		this.mlcrmtEstado = mlcrmtEstado;
		this.mallaCurricularParalelos = mallaCurricularParalelos;
		this.syllabos = syllabos;
	}

	@Id

	@Column(name = "MLCRMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getMlcrmtId() {
		return this.mlcrmtId;
	}

	public void setMlcrmtId(Integer mlcrmtId) {
		this.mlcrmtId = mlcrmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVL_SUB_ID")
	public Nivel getNivelByNvlSubId() {
		return this.nivelByNvlSubId;
	}

	public void setNivelByNvlSubId(Nivel nivelByNvlSubId) {
		this.nivelByNvlSubId = nivelByNvlSubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVL_ID")
	public Nivel getMlcrmtNivel() {
		return this.mlcrmtNivel;
	}

	public void setMlcrmtNivel(Nivel nivelByNvlId) {
		this.mlcrmtNivel = nivelByNvlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNFR_ID")
	public UnidadFormacion getMlcrmtUnidadFormacion() {
		return this.mlcrmtUnidadFormacion;
	}

	public void setMlcrmtUnidadFormacion(UnidadFormacion unidadFormacion) {
		this.mlcrmtUnidadFormacion = unidadFormacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCR_ID", nullable = false)
	public MallaCurricular getMlcrmtMallaCurricular() {
		return this.mlcrmtMallaCurricular;
	}

	public void setMlcrmtMallaCurricular(MallaCurricular mallaCurricular) {
		this.mlcrmtMallaCurricular = mallaCurricular;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTR_ID", nullable = false)
	public Materia getMlcrmtMateria() {
		return this.mlcrmtMateria;
	}

	public void setMlcrmtMateria(Materia materia) {
		this.mlcrmtMateria = materia;
	}

	@Column(name = "MLCRMT_ESTADO", precision = 38, scale = 0)
	public Integer getMlcrmtEstado() {
		return this.mlcrmtEstado;
	}

	public void setMlcrmtEstado(Integer mlcrmtEstado) {
		this.mlcrmtEstado = mlcrmtEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mlcrprMallaCurricularMateria")
	public List<MallaCurricularParalelo> getMallaCurricularParalelos() {
		return this.mallaCurricularParalelos;
	}

	public void setMallaCurricularParalelos(List<MallaCurricularParalelo> mallaCurricularParalelos) {
		this.mallaCurricularParalelos = mallaCurricularParalelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sylMallaCurricularMateria")
	public List<Syllabo> getSyllabos() {
		return this.syllabos;
	}

	public void setSyllabos(List<Syllabo> syllabos) {
		this.syllabos = syllabos;
	}

}
