package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MallaCurricularNivel generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR_NIVEL")
public class MallaCurricularNivel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer mlcrnvId;
	private Nivel nivel;
	private MallaCurricular mallaCurricular;
	private Integer mlcrnvCreditos;
	private Integer mlcrnvCreditosAcumulado;

	public MallaCurricularNivel() {
	}

	public MallaCurricularNivel(Integer mlcrnvId, Nivel nivel, MallaCurricular mallaCurricular) {
		this.mlcrnvId = mlcrnvId;
		this.nivel = nivel;
		this.mallaCurricular = mallaCurricular;
	}

	public MallaCurricularNivel(Integer mlcrnvId, Nivel nivel, MallaCurricular mallaCurricular, Integer mlcrnvCreditos,
			Integer mlcrnvCreditosAcumulado) {
		this.mlcrnvId = mlcrnvId;
		this.nivel = nivel;
		this.mallaCurricular = mallaCurricular;
		this.mlcrnvCreditos = mlcrnvCreditos;
		this.mlcrnvCreditosAcumulado = mlcrnvCreditosAcumulado;
	}

	@Id

	@Column(name = "MLCRNV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getMlcrnvId() {
		return this.mlcrnvId;
	}

	public void setMlcrnvId(Integer mlcrnvId) {
		this.mlcrnvId = mlcrnvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVL_ID", nullable = false)
	public Nivel getNivel() {
		return this.nivel;
	}

	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCR_ID", nullable = false)
	public MallaCurricular getMallaCurricular() {
		return this.mallaCurricular;
	}

	public void setMallaCurricular(MallaCurricular mallaCurricular) {
		this.mallaCurricular = mallaCurricular;
	}

	@Column(name = "MLCRNV_CREDITOS", precision = 22, scale = 0)
	public Integer getMlcrnvCreditos() {
		return this.mlcrnvCreditos;
	}

	public void setMlcrnvCreditos(Integer mlcrnvCreditos) {
		this.mlcrnvCreditos = mlcrnvCreditos;
	}

	@Column(name = "MLCRNV_CREDITOS_ACUMULADO", precision = 22, scale = 0)
	public Integer getMlcrnvCreditosAcumulado() {
		return this.mlcrnvCreditosAcumulado;
	}

	public void setMlcrnvCreditosAcumulado(Integer mlcrnvCreditosAcumulado) {
		this.mlcrnvCreditosAcumulado = mlcrnvCreditosAcumulado;
	}

}
