package ec.edu.uce.biometrico.jpa;
// Generated 14/06/2019 23:30:02 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Metodologia generated by hbm2java
 */
@Entity
@Table(name = "METODOLOGIA")
public class Metodologia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer mtdId;
	private UnidadCurricular mtdUnidadCurricular;
	private String mtdDescripcion;

	public Metodologia() {
	}

	public Metodologia(Integer mtdId) {
		this.mtdId = mtdId;
	}

	public Metodologia(Integer mtdId, UnidadCurricular unidadCurricular) {
		this.mtdId = mtdId;
		this.mtdUnidadCurricular = unidadCurricular;
	}

	public Metodologia(Integer mtdId, UnidadCurricular unidadCurricular, String mtdDescripcion) {
		this.mtdId = mtdId;
		this.mtdUnidadCurricular = unidadCurricular;
		this.mtdDescripcion = mtdDescripcion;
	}

	@Id

	@Column(name = "MTD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getMtdId() {
		return this.mtdId;
	}

	public void setMtdId(Integer mtdId) {
		this.mtdId = mtdId;
	}

	@ManyToOne
	@JoinColumn(name = "UNCR_ID", nullable = false)
	public UnidadCurricular getMtdUnidadCurricular() {
		return this.mtdUnidadCurricular;
	}

	public void setMtdUnidadCurricular(UnidadCurricular unidadCurricular) {
		this.mtdUnidadCurricular = unidadCurricular;
	}

	@Column(name = "MTD_DESCRIPCION", length = 100)
	public String getMtdDescripcion() {
		return this.mtdDescripcion;
	}

	public void setMtdDescripcion(String mtdDescripcion) {
		this.mtdDescripcion = mtdDescripcion;
	}

}
