package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paralelo generated by hbm2java
 */
@Entity
@Table(name = "PARALELO")
public class Paralelo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer prlId;
	private PeriodoAcademico prlPeriodoAcademico;
	private Carrera prlCarrera;
	private String prlCodigo;
	private String prlDescripcion;
	private Integer prlEstado;
	private Integer prlCupo;
	private List<MallaCurricularParalelo> mallaCurricularParalelos = new ArrayList<MallaCurricularParalelo>(0);

	public Paralelo() {
	}

	public Paralelo(Integer prlId, Carrera carrera) {
		this.prlId = prlId;
		this.prlCarrera = carrera;
	}

	public Paralelo(Integer prlId, PeriodoAcademico periodoAcademico, Carrera carrera, String prlCodigo,
			String prlDescripcion, Integer prlEstado, Integer prlCupo,
			List<MallaCurricularParalelo> mallaCurricularParalelos) {
		this.prlId = prlId;
		this.prlPeriodoAcademico = periodoAcademico;
		this.prlCarrera = carrera;
		this.prlCodigo = prlCodigo;
		this.prlDescripcion = prlDescripcion;
		this.prlEstado = prlEstado;
		this.prlCupo = prlCupo;
		this.mallaCurricularParalelos = mallaCurricularParalelos;
	}

	@Id

	@Column(name = "PRL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getPrlId() {
		return this.prlId;
	}

	public void setPrlId(Integer prlId) {
		this.prlId = prlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getPrlPeriodoAcademico() {
		return this.prlPeriodoAcademico;
	}

	public void setPrlPeriodoAcademico(PeriodoAcademico periodoAcademico) {
		this.prlPeriodoAcademico = periodoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRR_ID", nullable = false)
	public Carrera getPrlCarrera() {
		return this.prlCarrera;
	}

	public void setPrlCarrera(Carrera carrera) {
		this.prlCarrera = carrera;
	}

	@Column(name = "PRL_CODIGO", length = 128)
	public String getPrlCodigo() {
		return this.prlCodigo;
	}

	public void setPrlCodigo(String prlCodigo) {
		this.prlCodigo = prlCodigo;
	}

	@Column(name = "PRL_DESCRIPCION", length = 256)
	public String getPrlDescripcion() {
		return this.prlDescripcion;
	}

	public void setPrlDescripcion(String prlDescripcion) {
		this.prlDescripcion = prlDescripcion;
	}

	@Column(name = "PRL_ESTADO", precision = 38, scale = 0)
	public Integer getPrlEstado() {
		return this.prlEstado;
	}

	public void setPrlEstado(Integer prlEstado) {
		this.prlEstado = prlEstado;
	}

	@Column(name = "PRL_CUPO", precision = 38, scale = 0)
	public Integer getPrlCupo() {
		return this.prlCupo;
	}

	public void setPrlCupo(Integer prlCupo) {
		this.prlCupo = prlCupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mlcrprParalelo")
	public List<MallaCurricularParalelo> getMallaCurricularParalelos() {
		return this.mallaCurricularParalelos;
	}

	public void setMallaCurricularParalelos(List<MallaCurricularParalelo> mallaCurricularParalelos) {
		this.mallaCurricularParalelos = mallaCurricularParalelos;
	}

}
