package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoFuncionCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_FUNCION_CARGA_HORARIA")
public class TipoFuncionCargaHoraria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tifncrhrId;
	private FuncionCargaHoraria funcionCargaHoraria;
	private TipoCargaHoraria tipoCargaHoraria;
	private Integer tifncrhrEstado;
	private List<CargaHoraria> cargaHorarias = new ArrayList<CargaHoraria>(0);

	public TipoFuncionCargaHoraria() {
	}

	public TipoFuncionCargaHoraria(Integer tifncrhrId, FuncionCargaHoraria funcionCargaHoraria,
			TipoCargaHoraria tipoCargaHoraria) {
		this.tifncrhrId = tifncrhrId;
		this.funcionCargaHoraria = funcionCargaHoraria;
		this.tipoCargaHoraria = tipoCargaHoraria;
	}

	public TipoFuncionCargaHoraria(Integer tifncrhrId, FuncionCargaHoraria funcionCargaHoraria,
			TipoCargaHoraria tipoCargaHoraria, Integer tifncrhrEstado, List<CargaHoraria> cargaHorarias) {
		this.tifncrhrId = tifncrhrId;
		this.funcionCargaHoraria = funcionCargaHoraria;
		this.tipoCargaHoraria = tipoCargaHoraria;
		this.tifncrhrEstado = tifncrhrEstado;
		this.cargaHorarias = cargaHorarias;
	}

	@Id

	@Column(name = "TIFNCRHR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getTifncrhrId() {
		return this.tifncrhrId;
	}

	public void setTifncrhrId(Integer tifncrhrId) {
		this.tifncrhrId = tifncrhrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FNCRHR_ID", nullable = false)
	public FuncionCargaHoraria getFuncionCargaHoraria() {
		return this.funcionCargaHoraria;
	}

	public void setFuncionCargaHoraria(FuncionCargaHoraria funcionCargaHoraria) {
		this.funcionCargaHoraria = funcionCargaHoraria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TICRHR_ID", nullable = false)
	public TipoCargaHoraria getTipoCargaHoraria() {
		return this.tipoCargaHoraria;
	}

	public void setTipoCargaHoraria(TipoCargaHoraria tipoCargaHoraria) {
		this.tipoCargaHoraria = tipoCargaHoraria;
	}

	@Column(name = "TIFNCRHR_ESTADO", precision = 22, scale = 0)
	public Integer getTifncrhrEstado() {
		return this.tifncrhrEstado;
	}

	public void setTifncrhrEstado(Integer tifncrhrEstado) {
		this.tifncrhrEstado = tifncrhrEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crhrTipoFuncionCargaHoraria")
	public List<CargaHoraria> getCargaHorarias() {
		return this.cargaHorarias;
	}

	public void setCargaHorarias(List<CargaHoraria> cargaHorarias) {
		this.cargaHorarias = cargaHorarias;
	}

}
