package ec.edu.uce.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadFormacion generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_FORMACION")
public class UnidadFormacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer unfrId;
	private String unfrDescripcion;
	private Integer unfrEstado;
	private List<MallaCurricularMateria> mallaCurricularMaterias = new ArrayList<MallaCurricularMateria>(0);

	public UnidadFormacion() {
	}

	public UnidadFormacion(Integer unfrId) {
		this.unfrId = unfrId;
	}

	public UnidadFormacion(Integer unfrId, String unfrDescripcion, Integer unfrEstado,
			List<MallaCurricularMateria> mallaCurricularMaterias) {
		this.unfrId = unfrId;
		this.unfrDescripcion = unfrDescripcion;
		this.unfrEstado = unfrEstado;
		this.mallaCurricularMaterias = mallaCurricularMaterias;
	}

	@Id

	@Column(name = "UNFR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getUnfrId() {
		return this.unfrId;
	}

	public void setUnfrId(Integer unfrId) {
		this.unfrId = unfrId;
	}

	@Column(name = "UNFR_DESCRIPCION", length = 256)
	public String getUnfrDescripcion() {
		return this.unfrDescripcion;
	}

	public void setUnfrDescripcion(String unfrDescripcion) {
		this.unfrDescripcion = unfrDescripcion;
	}

	@Column(name = "UNFR_ESTADO", precision = 22, scale = 0)
	public Integer getUnfrEstado() {
		return this.unfrEstado;
	}

	public void setUnfrEstado(Integer unfrEstado) {
		this.unfrEstado = unfrEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mlcrmtUnidadFormacion")
	public List<MallaCurricularMateria> getMallaCurricularMaterias() {
		return this.mallaCurricularMaterias;
	}

	public void setMallaCurricularMaterias(List<MallaCurricularMateria> mallaCurricularMaterias) {
		this.mallaCurricularMaterias = mallaCurricularMaterias;
	}

}
