package ec.edu.uce.biometrico.jpa;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * UnidadCurricular generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_CURRICULAR")
@NamedQuery(name = "UnidadCurricular.findAllBySylId", query = "select uc from UnidadCurricular as uc where uc.syllabo.sylMallaCurricularMateria.mlcrmtMateria.mtrId=:mtrId")
public class UnidadCurricular implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int uncrId;
	private Syllabo syllabo;
	private String uncrDescripcion;
	private Integer uncrTotalHoras;
	private String uncrNombre;
	private String uncrObjetivo;
	private String uncrResultado;
	private Integer uncrHorasTeoricas;
	private Integer uncrHorasPracticas;
	private Integer uncrHorasPresenciales;
	private Integer uncrHorasVirtual;
	private Double uncrPorcentaje;
	private List<Metodologia> metodologias = new ArrayList<>();
	private List<RecursoDidactico> recursosDidacticoses = new ArrayList<>();
	private List<ContenidoCurricular> contenidoCurriculars = new ArrayList<>();
	private List<Bibliografia> bibliografias = new ArrayList<>();

	public UnidadCurricular() {
	}

	public UnidadCurricular(int uncrId) {
		this.uncrId = uncrId;
	}

	public UnidadCurricular(int uncrId, Syllabo syllabo) {
		this.uncrId = uncrId;
		this.syllabo = syllabo;
	}

	public UnidadCurricular(int uncrId, Syllabo syllabo, String uncrDescripcion, Integer uncrTotalHoras,
			String uncrNombre, String uncrObjetivo, String uncrResultado, Integer uncrHorasTeoricas,
			Integer uncrHorasPracticas, Integer uncrHorasPresenciales, Integer uncrHorasVirtual,
			List<Metodologia> metodologias, List<RecursoDidactico> recursosDidacticoses,
			List<ContenidoCurricular> contenidoCurriculars, List<Bibliografia> bibliografias) {
		this.uncrId = uncrId;
		this.syllabo = syllabo;
		this.uncrDescripcion = uncrDescripcion;
		this.uncrTotalHoras = uncrTotalHoras;
		this.uncrNombre = uncrNombre;
		this.uncrObjetivo = uncrObjetivo;
		this.uncrResultado = uncrResultado;
		this.uncrHorasTeoricas = uncrHorasTeoricas;
		this.uncrHorasPracticas = uncrHorasPracticas;
		this.uncrHorasPresenciales = uncrHorasPresenciales;
		this.uncrHorasVirtual = uncrHorasVirtual;
		this.metodologias = metodologias;
		this.recursosDidacticoses = recursosDidacticoses;
		this.contenidoCurriculars = contenidoCurriculars;
		this.bibliografias = bibliografias;
	}

	@Id

	@Column(name = "UNCR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getUncrId() {
		return this.uncrId;
	}

	public void setUncrId(int uncrId) {
		this.uncrId = uncrId;
	}

	@ManyToOne
	@JoinColumn(name = "SYL_ID", nullable = false)
	public Syllabo getSyllabo() {
		return this.syllabo;
	}

	public void setSyllabo(Syllabo syllabo) {
		this.syllabo = syllabo;
	}

	@Column(name = "UNCR_DESCRIPCION", length = 100)
	public String getUncrDescripcion() {
		return this.uncrDescripcion;
	}

	public void setUncrDescripcion(String uncrDescripcion) {
		this.uncrDescripcion = uncrDescripcion;
	}

	@Column(name = "UNCR_TOTAL_HORAS", precision = 22, scale = 0)
	public Integer getUncrTotalHoras() {
		return this.uncrTotalHoras;
	}

	public void setUncrTotalHoras(Integer uncrTotalHoras) {
		this.uncrTotalHoras = uncrTotalHoras;
	}

	@Column(name = "UNCR_NOMBRE", length = 100)
	public String getUncrNombre() {
		return this.uncrNombre;
	}

	public void setUncrNombre(String uncrNombre) {
		this.uncrNombre = uncrNombre;
	}

	@Column(name = "UNCR_OBJETIVO", length = 400)
	public String getUncrObjetivo() {
		return this.uncrObjetivo;
	}

	public void setUncrObjetivo(String uncrObjetivo) {
		this.uncrObjetivo = uncrObjetivo;
	}

	@Column(name = "UNCR_RESULTADO", length = 400)
	public String getUncrResultado() {
		return this.uncrResultado;
	}

	public void setUncrResultado(String uncrResultado) {
		this.uncrResultado = uncrResultado;
	}

	@Column(name = "UNCR_HORAS_TEORICAS", precision = 22, scale = 0)
	public Integer getUncrHorasTeoricas() {
		return this.uncrHorasTeoricas;
	}

	public void setUncrHorasTeoricas(Integer uncrHorasTeoricas) {
		this.uncrHorasTeoricas = uncrHorasTeoricas;
	}

	@Column(name = "UNCR_HORAS_PRACTICAS", precision = 22, scale = 0)
	public Integer getUncrHorasPracticas() {
		return this.uncrHorasPracticas;
	}

	public void setUncrHorasPracticas(Integer uncrHorasPracticas) {
		this.uncrHorasPracticas = uncrHorasPracticas;
	}

	@Column(name = "UNCR_HORAS_PRESENCIALES", precision = 22, scale = 0)
	public Integer getUncrHorasPresenciales() {
		return this.uncrHorasPresenciales;
	}

	public void setUncrHorasPresenciales(Integer uncrHorasPresenciales) {
		this.uncrHorasPresenciales = uncrHorasPresenciales;
	}

	@Column(name = "UNCR_HORAS_VIRTUAL", precision = 22, scale = 0)
	public Integer getUncrHorasVirtual() {
		return this.uncrHorasVirtual;
	}

	public void setUncrHorasVirtual(Integer uncrHorasVirtual) {
		this.uncrHorasVirtual = uncrHorasVirtual;
	}

	@OneToMany(mappedBy = "mtdUnidadCurricular")
	public List<Metodologia> getMetodologias() {
		return this.metodologias;
	}

	public void setMetodologias(List<Metodologia> metodologias) {
		this.metodologias = metodologias;
	}

	@OneToMany(mappedBy = "rcddUnidadCurricular")
	public List<RecursoDidactico> getRecursosDidacticoses() {
		return this.recursosDidacticoses;
	}

	public void setRecursosDidacticoses(List<RecursoDidactico> recursosDidacticoses) {
		this.recursosDidacticoses = recursosDidacticoses;
	}

	@OneToMany(mappedBy = "unidadCurricular")
	public List<ContenidoCurricular> getContenidos() {
		return this.contenidoCurriculars;
	}

	public void setContenidos(List<ContenidoCurricular> contenidoCurriculars) {
		this.contenidoCurriculars = contenidoCurriculars;
	}

	@OneToMany(mappedBy = "bblUnidadCurricular")
	public List<Bibliografia> getBibliografias() {
		return this.bibliografias;
	}

	public void setBibliografias(List<Bibliografia> bibliografias) {
		this.bibliografias = bibliografias;
	}

	@Transient
	public Double getUncrPorcentaje() {
		return uncrPorcentaje;
	}

	public void setUncrPorcentaje(Double uncrPorcentaje) {
		this.uncrPorcentaje = uncrPorcentaje;
	}

}
