package model;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "CARRERA")
@NamedQueries({ @NamedQuery(name = "Carrera.findAll", query = "select c from Carrera as c"),
		@NamedQuery(name = "Carrera.findByMtrId", query = "select m.carrera from Materia as m where m.mtrId=:mtrId") })

public class Carrera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer crrId;
	private String crrNombre;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);
	private Set<Materia> materias = new HashSet<Materia>(0);
	private Set<MallaCurricular> mallaCurriculars = new HashSet<MallaCurricular>(0);

	public Carrera() {
	}

	public Carrera(Integer crrId) {
		this.crrId = crrId;
	}

	public Carrera(Integer crrId, String crrNombre, Set<DetallePuesto> detallePuestos, Set<Materia> materias,
			Set<MallaCurricular> mallaCurriculars) {
		this.crrId = crrId;
		this.crrNombre = crrNombre;
		this.detallePuestos = detallePuestos;
		this.materias = materias;
		this.mallaCurriculars = mallaCurriculars;
	}

	@Id

	@Column(name = "CRR_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Integer getCrrId() {
		return this.crrId;
	}

	public void setCrrId(Integer crrId) {
		this.crrId = crrId;
	}

	@Column(name = "CRR_NOMBRE", length = 400)
	public String getCrrNombre() {
		return this.crrNombre;
	}

	public void setCrrNombre(String crrNombre) {
		this.crrNombre = crrNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<MallaCurricular> getMallaCurriculars() {
		return this.mallaCurriculars;
	}

	public void setMallaCurriculars(Set<MallaCurricular> mallaCurriculars) {
		this.mallaCurriculars = mallaCurriculars;
	}

}
