package model;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Herramienta generated by hbm2java
 */
@Entity
@Table(name = "HERRAMIENTA")
@NamedQuery(name = "Herramienta.findAllByCnId", query = "select hrr from Herramienta as hrr where hrr.contenido.cntId=:cntId")
public class Herramienta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer hrrId;
	private Contenido contenido;
	private String hrrNombre;

	public Herramienta() {
	}

	public Herramienta(Integer hrrId, Contenido contenido) {
		this.hrrId = hrrId;
		this.contenido = contenido;
	}

	public Herramienta(Integer hrrId, Contenido contenido, String hrrNombre) {
		this.hrrId = hrrId;
		this.contenido = contenido;
		this.hrrNombre = hrrNombre;
	}

	@Id

	@Column(name = "HRR_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public Integer getHrrId() {
		return this.hrrId;
	}

	public void setHrrId(Integer hrrId) {
		this.hrrId = hrrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNT_ID", nullable = false)
	public Contenido getContenido() {
		return this.contenido;
	}

	public void setContenido(Contenido contenido) {
		this.contenido = contenido;
	}

	@Column(name = "HRR_NOMBRE", length = 400)
	public String getHrrNombre() {
		return this.hrrNombre;
	}

	public void setHrrNombre(String hrrNombre) {
		this.hrrNombre = hrrNombre;
	}

}
