package model;
// Generated 23/02/2019 19:40:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HorarioFichaEstudiante generated by hbm2java
 */
@Entity
@Table(name = "HORARIO_FICHA_ESTUDIANTE")
public class HorarioFichaEstudiante implements java.io.Serializable {

	private Integer hrfcdcId;
	private Horario horario;
	private FichaEstudiante fichaEstudiante;

	public HorarioFichaEstudiante() {
	}

	public HorarioFichaEstudiante(Integer hrfcdcId, Horario horario, FichaEstudiante fichaEstudiante) {
		this.hrfcdcId = hrfcdcId;
		this.horario = horario;
		this.fichaEstudiante = fichaEstudiante;
	}

	@Id

	@Column(name = "HRFCDC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getHrfcdcId() {
		return this.hrfcdcId;
	}

	public void setHrfcdcId(Integer hrfcdcId) {
		this.hrfcdcId = hrfcdcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HRR_ID", nullable = false)
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCES_ID", nullable = false)
	public FichaEstudiante getFichaEstudiante() {
		return this.fichaEstudiante;
	}

	public void setFichaEstudiante(FichaEstudiante fichaEstudiante) {
		this.fichaEstudiante = fichaEstudiante;
	}

}
