package model;
// Generated 15/01/2019 9:06:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Seguimiento generated by hbm2java
 */
@Entity
@Table(name = "SEGUIMIENTO")
public class Seguimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer sgmId;
	private Asistencia asistencia;
	private MallaCurricularMateria mallaCurricularMateria;
	private String sgmTemaClase;
	private Integer sgmHoraClaseRestante;
	private String sgmObservacion;

	public Seguimiento() {
	}

	public Seguimiento(Integer sgmId, Asistencia asistencia, MallaCurricularMateria mallaCurricularMateria) {
		this.sgmId = sgmId;
		this.asistencia = asistencia;
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	public Seguimiento(Integer sgmId, Asistencia asistencia, MallaCurricularMateria mallaCurricularMateria,
			String sgmTemaClase, Integer sgmHoraClaseRestante, String sgmObservacion) {
		this.sgmId = sgmId;
		this.asistencia = asistencia;
		this.mallaCurricularMateria = mallaCurricularMateria;
		this.sgmTemaClase = sgmTemaClase;
		this.sgmHoraClaseRestante = sgmHoraClaseRestante;
		this.sgmObservacion = sgmObservacion;
	}

	@Id

	@Column(name = "SGM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getSgmId() {
		return this.sgmId;
	}

	public void setSgmId(Integer sgmId) {
		this.sgmId = sgmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASS_ID", nullable = false)
	public Asistencia getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Asistencia asistencia) {
		this.asistencia = asistencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRMT_ID", nullable = false)
	public MallaCurricularMateria getMallaCurricularMateria() {
		return this.mallaCurricularMateria;
	}

	public void setMallaCurricularMateria(MallaCurricularMateria mallaCurricularMateria) {
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	@Column(name = "SGM_TEMA_CLASE", length = 4000)
	public String getSgmTemaClase() {
		return this.sgmTemaClase;
	}

	public void setSgmTemaClase(String sgmTemaClase) {
		this.sgmTemaClase = sgmTemaClase;
	}

	@Column(name = "SGM_HORA_CLASE_RESTANTE", precision = 22, scale = 0)
	public Integer getSgmHoraClaseRestante() {
		return this.sgmHoraClaseRestante;
	}

	public void setSgmHoraClaseRestante(Integer sgmHoraClaseRestante) {
		this.sgmHoraClaseRestante = sgmHoraClaseRestante;
	}

	@Column(name = "SGM_OBSERVACION", length = 400)
	public String getSgmObservacion() {
		return this.sgmObservacion;
	}

	public void setSgmObservacion(String sgmObservacion) {
		this.sgmObservacion = sgmObservacion;
	}

}
