package model;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Syllabo generated by hbm2java
 */
@Entity
@Table(name = "SYLLABO", uniqueConstraints = @UniqueConstraint(columnNames = "MCM_ID"))
public class Syllabo implements java.io.Serializable {

	private Integer sylId;
	private MallaCurricularMateria mallaCurricularMateria;
	private String sylDescripcion;
	private Set<UnidadCurricular> unidadCurriculars = new HashSet<UnidadCurricular>(0);

	public Syllabo() {
	}

	public Syllabo(Integer sylId, MallaCurricularMateria mallaCurricularMateria) {
		this.sylId = sylId;
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	public Syllabo(Integer sylId, MallaCurricularMateria mallaCurricularMateria, String sylDescripcion,
			Set<UnidadCurricular> unidadCurriculars) {
		this.sylId = sylId;
		this.mallaCurricularMateria = mallaCurricularMateria;
		this.sylDescripcion = sylDescripcion;
		this.unidadCurriculars = unidadCurriculars;
	}

	@Id

	@Column(name = "SYL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getSylId() {
		return this.sylId;
	}

	public void setSylId(Integer sylId) {
		this.sylId = sylId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MCM_ID", unique = true, nullable = false)
	public MallaCurricularMateria getMallaCurricularMateria() {
		return this.mallaCurricularMateria;
	}

	public void setMallaCurricularMateria(MallaCurricularMateria mallaCurricularMateria) {
		this.mallaCurricularMateria = mallaCurricularMateria;
	}

	@Column(name = "SYL_DESCRIPCION", length = 100)
	public String getSylDescripcion() {
		return this.sylDescripcion;
	}

	public void setSylDescripcion(String sylDescripcion) {
		this.sylDescripcion = sylDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syllabo")
	public Set<UnidadCurricular> getUnidadCurriculars() {
		return this.unidadCurriculars;
	}

	public void setUnidadCurriculars(Set<UnidadCurricular> unidadCurriculars) {
		this.unidadCurriculars = unidadCurriculars;
	}

}
