package model;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadCurricular generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_CURRICULAR")
@NamedQuery(name = "UnidadCurricular.findAllBySylId", query = "select uc from UnidadCurricular as uc where uc.syllabo.mallaCurricularMateria.materia.mtrId=:mtrId")
public class UnidadCurricular implements java.io.Serializable {

	private Integer uncrId;
	private Syllabo syllabo;
	private String uncrDescripcion;
	private Integer uncrTotalHoras;
	private String uncrNombre;
	private String uncrObjetivo;
	private String uncrResultado;
	private List<Contenido> contenidos = new ArrayList<Contenido>(0);

	public UnidadCurricular() {
	}

	public UnidadCurricular(Integer uncrId, Syllabo syllabo) {
		this.uncrId = uncrId;
		this.syllabo = syllabo;
	}

	public UnidadCurricular(Integer uncrId, Syllabo syllabo, String uncrDescripcion, Integer uncrTotalHoras,
			String uncrNombre, String uncrObjetivo, String uncrResultado, List<Contenido> contenidos) {
		this.uncrId = uncrId;
		this.syllabo = syllabo;
		this.uncrDescripcion = uncrDescripcion;
		this.uncrTotalHoras = uncrTotalHoras;
		this.uncrNombre = uncrNombre;
		this.uncrObjetivo = uncrObjetivo;
		this.uncrResultado = uncrResultado;
		this.contenidos = contenidos;
	}

	@Id

	@Column(name = "UNCR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUncrId() {
		return this.uncrId;
	}

	public void setUncrId(Integer uncrId) {
		this.uncrId = uncrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYL_ID", nullable = false)
	public Syllabo getSyllabo() {
		return this.syllabo;
	}

	public void setSyllabo(Syllabo syllabo) {
		this.syllabo = syllabo;
	}

	@Column(name = "UNCR_DESCRIPCION", length = 100)
	public String getUncrDescripcion() {
		return this.uncrDescripcion;
	}

	public void setUncrDescripcion(String uncrDescripcion) {
		this.uncrDescripcion = uncrDescripcion;
	}

	@Column(name = "UNCR_TOTAL_HORAS", precision = 22, scale = 0)
	public Integer getUncrTotalHoras() {
		return this.uncrTotalHoras;
	}

	public void setUncrTotalHoras(Integer uncrTotalHoras) {
		this.uncrTotalHoras = uncrTotalHoras;
	}

	@Column(name = "UNCR_NOMBRE", length = 100)
	public String getUncrNombre() {
		return this.uncrNombre;
	}

	public void setUncrNombre(String uncrNombre) {
		this.uncrNombre = uncrNombre;
	}

	@Column(name = "UNCR_OBJETIVO", length = 400)
	public String getUncrObjetivo() {
		return this.uncrObjetivo;
	}

	public void setUncrObjetivo(String uncrObjetivo) {
		this.uncrObjetivo = uncrObjetivo;
	}

	@Column(name = "UNCR_RESULTADO", length = 400)
	public String getUncrResultado() {
		return this.uncrResultado;
	}

	public void setUncrResultado(String uncrResultado) {
		this.uncrResultado = uncrResultado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadCurricular")
	public List<Contenido> getContenidos() {
		return this.contenidos;
	}

	public void setContenidos(List<Contenido> contenidos) {
		this.contenidos = contenidos;
	}

}
