package ec.uce.edu.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "CARGA_HORARIA")
public class CargaHoraria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer crhrId;
	private PeriodoAcademico periodoAcademico;
	private TipoFuncionCargaHoraria tipoFuncionCargaHoraria;
	private MallaCurricularParalelo mallaCurricularParalelo;
	private DetallePuesto detallePuesto;
	private String crhrObservacion;
	private Integer crhrEstado;
	private Integer crhrNumHoras;
	private Integer crhrEstadoEliminacion;
	private Integer crhrCarreraId;
	private Integer mlcrprIdPrincipal;
	private List<DetalleCargaHoraria> detalleCargaHorarias = new ArrayList<DetalleCargaHoraria>(0);

	public CargaHoraria() {
	}

	public CargaHoraria(Integer crhrId, PeriodoAcademico periodoAcademico,
			TipoFuncionCargaHoraria tipoFuncionCargaHoraria, MallaCurricularParalelo mallaCurricularParalelo,
			DetallePuesto detallePuesto) {
		this.crhrId = crhrId;
		this.periodoAcademico = periodoAcademico;
		this.tipoFuncionCargaHoraria = tipoFuncionCargaHoraria;
		this.mallaCurricularParalelo = mallaCurricularParalelo;
		this.detallePuesto = detallePuesto;
	}

	public CargaHoraria(Integer crhrId, PeriodoAcademico periodoAcademico,
			TipoFuncionCargaHoraria tipoFuncionCargaHoraria, MallaCurricularParalelo mallaCurricularParalelo,
			DetallePuesto detallePuesto, String crhrObservacion, Integer crhrEstado, Integer crhrNumHoras,
			Integer crhrEstadoEliminacion, Integer crhrCarreraId, Integer mlcrprIdPrincipal,
			List<DetalleCargaHoraria> detalleCargaHorarias) {
		this.crhrId = crhrId;
		this.periodoAcademico = periodoAcademico;
		this.tipoFuncionCargaHoraria = tipoFuncionCargaHoraria;
		this.mallaCurricularParalelo = mallaCurricularParalelo;
		this.detallePuesto = detallePuesto;
		this.crhrObservacion = crhrObservacion;
		this.crhrEstado = crhrEstado;
		this.crhrNumHoras = crhrNumHoras;
		this.crhrEstadoEliminacion = crhrEstadoEliminacion;
		this.crhrCarreraId = crhrCarreraId;
		this.mlcrprIdPrincipal = mlcrprIdPrincipal;
		this.detalleCargaHorarias = detalleCargaHorarias;
	}

	@Id

	@Column(name = "CRHR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCrhrId() {
		return this.crhrId;
	}

	public void setCrhrId(Integer crhrId) {
		this.crhrId = crhrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRAC_ID", nullable = false)
	public PeriodoAcademico getPeriodoAcademico() {
		return this.periodoAcademico;
	}

	public void setPeriodoAcademico(PeriodoAcademico periodoAcademico) {
		this.periodoAcademico = periodoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIFNCRHR_ID", nullable = false)
	public TipoFuncionCargaHoraria getTipoFuncionCargaHoraria() {
		return this.tipoFuncionCargaHoraria;
	}

	public void setTipoFuncionCargaHoraria(TipoFuncionCargaHoraria tipoFuncionCargaHoraria) {
		this.tipoFuncionCargaHoraria = tipoFuncionCargaHoraria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRPR_ID", nullable = false)
	public MallaCurricularParalelo getMallaCurricularParalelo() {
		return this.mallaCurricularParalelo;
	}

	public void setMallaCurricularParalelo(MallaCurricularParalelo mallaCurricularParalelo) {
		this.mallaCurricularParalelo = mallaCurricularParalelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID", nullable = false)
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@Column(name = "CRHR_OBSERVACION", length = 1024)
	public String getCrhrObservacion() {
		return this.crhrObservacion;
	}

	public void setCrhrObservacion(String crhrObservacion) {
		this.crhrObservacion = crhrObservacion;
	}

	@Column(name = "CRHR_ESTADO", precision = 22, scale = 0)
	public Integer getCrhrEstado() {
		return this.crhrEstado;
	}

	public void setCrhrEstado(Integer crhrEstado) {
		this.crhrEstado = crhrEstado;
	}

	@Column(name = "CRHR_NUM_HORAS", precision = 22, scale = 0)
	public Integer getCrhrNumHoras() {
		return this.crhrNumHoras;
	}

	public void setCrhrNumHoras(Integer crhrNumHoras) {
		this.crhrNumHoras = crhrNumHoras;
	}

	@Column(name = "CRHR_ESTADO_ELIMINACION", precision = 38, scale = 0)
	public Integer getCrhrEstadoEliminacion() {
		return this.crhrEstadoEliminacion;
	}

	public void setCrhrEstadoEliminacion(Integer crhrEstadoEliminacion) {
		this.crhrEstadoEliminacion = crhrEstadoEliminacion;
	}

	@Column(name = "CRHR_CARRERA_ID", precision = 38, scale = 0)
	public Integer getCrhrCarreraId() {
		return this.crhrCarreraId;
	}

	public void setCrhrCarreraId(Integer crhrCarreraId) {
		this.crhrCarreraId = crhrCarreraId;
	}

	@Column(name = "MLCRPR_ID_PRINCIPAL", precision = 22, scale = 0)
	public Integer getMlcrprIdPrincipal() {
		return this.mlcrprIdPrincipal;
	}

	public void setMlcrprIdPrincipal(Integer mlcrprIdPrincipal) {
		this.mlcrprIdPrincipal = mlcrprIdPrincipal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargaHoraria")
	public List<DetalleCargaHoraria> getDetalleCargaHorarias() {
		return this.detalleCargaHorarias;
	}

	public void setDetalleCargaHorarias(List<DetalleCargaHoraria> detalleCargaHorarias) {
		this.detalleCargaHorarias = detalleCargaHorarias;
	}

}
