package ec.uce.edu.biometrico.jpa;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contenido generated by hbm2java
 */
@Entity
@Table(name = "CONTENIDO_CURRICULAR")
@NamedQueries({
		@NamedQuery(name = "Contenido.findAllByUcId", query = "select cnt from ContenidoCurricular as cnt where cnt.unidadCurricular.uncrId=:ucId"),
		@NamedQuery(name = "Contenido.findAllByFdId", query = "select cnt from ContenidoCurricular as cnt "
				+ "where cnt.unidadCurricular.syllabo.mallaCurricularMateria.mlcrmtId in (select sgm.mallaCurricularMateria.mlcrmtId from Seguimiento as sgm "
				+ "where sgm.asistencia.fichaDocente.fcdcId=:fdId)"),
		@NamedQuery(name = "Contenido.findAllByMtrId", query = "select cnt from ContenidoCurricular as cnt where cnt.unidadCurricular.syllabo.mallaCurricularMateria.materia.mtrId=:mtId") })

public class ContenidoCurricular implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cncrId;
	private UnidadCurricular unidadCurricular;
	private String cncrDescripcion;
	private String cncrEstado;
	private List<Actividad> actividads = new ArrayList<>();
	private List<Herramienta> herramientas = new ArrayList<>();

	public ContenidoCurricular() {
	}

	public ContenidoCurricular(Integer cncrId, UnidadCurricular unidadCurricular) {
		this.cncrId = cncrId;
		this.unidadCurricular = unidadCurricular;
	}

	public ContenidoCurricular(Integer cncrId, UnidadCurricular unidadCurricular, String cncrDescripcion,
			String cncrEstado, List<Actividad> actividads, List<Herramienta> herramientas) {
		this.cncrId = cncrId;
		this.unidadCurricular = unidadCurricular;
		this.cncrDescripcion = cncrDescripcion;
		this.cncrEstado = cncrEstado;
		this.actividads = actividads;
		this.herramientas = herramientas;
	}

	@Id

	@Column(name = "CNCR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getCncrId() {
		return this.cncrId;
	}

	public void setCncrId(Integer cncrId) {
		this.cncrId = cncrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNCR_ID", nullable = false)
	public UnidadCurricular getUnidadCurricular() {
		return this.unidadCurricular;
	}

	public void setUnidadCurricular(UnidadCurricular unidadCurricular) {
		this.unidadCurricular = unidadCurricular;
	}

	@Column(name = "CNCR_DESCRIPCION", length = 400)
	public String getCncrDescripcion() {
		return this.cncrDescripcion;
	}

	public void setCncrDescripcion(String cncrDescripcion) {
		this.cncrDescripcion = cncrDescripcion;
	}

	@Column(name = "CNCR_ESTADO", length = 15)
	public String getCncrEstado() {
		return this.cncrEstado;
	}

	public void setCncrEstado(String cncrEstado) {
		this.cncrEstado = cncrEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenidoCurricular")
	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contenidoCurricular")
	public List<Herramienta> getHerramientas() {
		return this.herramientas;
	}

	public void setHerramientas(List<Herramienta> herramientas) {
		this.herramientas = herramientas;
	}

}
