package ec.uce.edu.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edificio generated by hbm2java
 */
@Entity
@Table(name = "EDIFICIO")
public class Edificio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer edfId;
	private Dependencia dependencia;
	private String edfDescripcion;
	private Integer edfEstado;
	private String edfCodigo;
	private Integer edfLocalizacion;
	private List<Aula> aulas = new ArrayList<Aula>(0);

	public Edificio() {
	}

	public Edificio(Integer edfId) {
		this.edfId = edfId;
	}

	public Edificio(Integer edfId, Dependencia dependencia, String edfDescripcion, Integer edfEstado, String edfCodigo,
			Integer edfLocalizacion, List<Aula> aulas) {
		this.edfId = edfId;
		this.dependencia = dependencia;
		this.edfDescripcion = edfDescripcion;
		this.edfEstado = edfEstado;
		this.edfCodigo = edfCodigo;
		this.edfLocalizacion = edfLocalizacion;
		this.aulas = aulas;
	}

	@Id

	@Column(name = "EDF_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getEdfId() {
		return this.edfId;
	}

	public void setEdfId(Integer edfId) {
		this.edfId = edfId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPN_ID")
	public Dependencia getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(Dependencia dependencia) {
		this.dependencia = dependencia;
	}

	@Column(name = "EDF_DESCRIPCION", length = 256)
	public String getEdfDescripcion() {
		return this.edfDescripcion;
	}

	public void setEdfDescripcion(String edfDescripcion) {
		this.edfDescripcion = edfDescripcion;
	}

	@Column(name = "EDF_ESTADO", precision = 38, scale = 0)
	public Integer getEdfEstado() {
		return this.edfEstado;
	}

	public void setEdfEstado(Integer edfEstado) {
		this.edfEstado = edfEstado;
	}

	@Column(name = "EDF_CODIGO", length = 256)
	public String getEdfCodigo() {
		return this.edfCodigo;
	}

	public void setEdfCodigo(String edfCodigo) {
		this.edfCodigo = edfCodigo;
	}

	@Column(name = "EDF_LOCALIZACION", precision = 38, scale = 0)
	public Integer getEdfLocalizacion() {
		return this.edfLocalizacion;
	}

	public void setEdfLocalizacion(Integer edfLocalizacion) {
		this.edfLocalizacion = edfLocalizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edificio")
	public List<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(List<Aula> aulas) {
		this.aulas = aulas;
	}

}
