package ec.uce.edu.biometrico.jpa;
// Generated 29/01/2019 23:19:04 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FichaEstudiante generated by hbm2java
 */
@Entity
@Table(name = "FICHA_ESTUDIANTE")
public class FichaEstudiante implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer fcesId;
	private List<HorarioFichaEstudiante> horarioFichaEstudiantes = new ArrayList<HorarioFichaEstudiante>(0);

	public FichaEstudiante() {
	}

	public FichaEstudiante(Integer fcesId) {
		this.fcesId = fcesId;
	}

	public FichaEstudiante(Integer fcesId, List<HorarioFichaEstudiante> horarioFichaEstudiantes) {
		this.fcesId = fcesId;
	}

	@Id

	@Column(name = "FCES_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getFcesId() {
		return this.fcesId;
	}

	public void setFcesId(Integer fcesId) {
		this.fcesId = fcesId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEstudiante")
	public List<HorarioFichaEstudiante> getHorarioFichaEstudiantes() {
		return this.horarioFichaEstudiantes;
	}

	public void setHorarioFichaEstudiantes(List<HorarioFichaEstudiante> horarioFichaEstudiantes) {
		this.horarioFichaEstudiantes = horarioFichaEstudiantes;
	}

}
