package ec.uce.edu.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table(name = "NIVEL")
public class Nivel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer nvlId;
	private String nvlDescripcion;
	private Integer nvlEstado;
	private Byte nvlNumeral;
	private List<MallaCurricularNivel> mallaCurricularNivels = new ArrayList<MallaCurricularNivel>(0);
	private List<MallaCurricularMateria> mallaCurricularMateriasForNvlSubId = new ArrayList<MallaCurricularMateria>(0);
	private List<MallaCurricularMateria> mallaCurricularMateriasForNvlId = new ArrayList<MallaCurricularMateria>(0);

	public Nivel() {
	}

	public Nivel(Integer nvlId) {
		this.nvlId = nvlId;
	}

	public Nivel(Integer nvlId, String nvlDescripcion, Integer nvlEstado, Byte nvlNumeral,
			List<MallaCurricularNivel> mallaCurricularNivels,
			List<MallaCurricularMateria> mallaCurricularMateriasForNvlSubId,
			List<MallaCurricularMateria> mallaCurricularMateriasForNvlId) {
		this.nvlId = nvlId;
		this.nvlDescripcion = nvlDescripcion;
		this.nvlEstado = nvlEstado;
		this.nvlNumeral = nvlNumeral;
		this.mallaCurricularNivels = mallaCurricularNivels;
		this.mallaCurricularMateriasForNvlSubId = mallaCurricularMateriasForNvlSubId;
		this.mallaCurricularMateriasForNvlId = mallaCurricularMateriasForNvlId;
	}

	@Id

	@Column(name = "NVL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getNvlId() {
		return this.nvlId;
	}

	public void setNvlId(Integer nvlId) {
		this.nvlId = nvlId;
	}

	@Column(name = "NVL_DESCRIPCION", length = 50)
	public String getNvlDescripcion() {
		return this.nvlDescripcion;
	}

	public void setNvlDescripcion(String nvlDescripcion) {
		this.nvlDescripcion = nvlDescripcion;
	}

	@Column(name = "NVL_ESTADO", precision = 22, scale = 0)
	public Integer getNvlEstado() {
		return this.nvlEstado;
	}

	public void setNvlEstado(Integer nvlEstado) {
		this.nvlEstado = nvlEstado;
	}

	@Column(name = "NVL_NUMERAL", precision = 2, scale = 0)
	public Byte getNvlNumeral() {
		return this.nvlNumeral;
	}

	public void setNvlNumeral(Byte nvlNumeral) {
		this.nvlNumeral = nvlNumeral;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivel")
	public List<MallaCurricularNivel> getMallaCurricularNivels() {
		return this.mallaCurricularNivels;
	}

	public void setMallaCurricularNivels(List<MallaCurricularNivel> mallaCurricularNivels) {
		this.mallaCurricularNivels = mallaCurricularNivels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelByNvlSubId")
	public List<MallaCurricularMateria> getMallaCurricularMateriasForNvlSubId() {
		return this.mallaCurricularMateriasForNvlSubId;
	}

	public void setMallaCurricularMateriasForNvlSubId(List<MallaCurricularMateria> mallaCurricularMateriasForNvlSubId) {
		this.mallaCurricularMateriasForNvlSubId = mallaCurricularMateriasForNvlSubId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelByNvlId")
	public List<MallaCurricularMateria> getMallaCurricularMateriasForNvlId() {
		return this.mallaCurricularMateriasForNvlId;
	}

	public void setMallaCurricularMateriasForNvlId(List<MallaCurricularMateria> mallaCurricularMateriasForNvlId) {
		this.mallaCurricularMateriasForNvlId = mallaCurricularMateriasForNvlId;
	}

}
