package ec.uce.edu.biometrico.jpa;
// Generated 08/07/2019 20:53:07 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMateria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_MATERIA")
public class TipoMateria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer timtId;
	private String timtDescripcion;
	private Integer timtEstado;
	private List<Materia> materias = new ArrayList<Materia>(0);

	public TipoMateria() {
	}

	public TipoMateria(Integer timtId) {
		this.timtId = timtId;
	}

	public TipoMateria(Integer timtId, String timtDescripcion, Integer timtEstado, List<Materia> materias) {
		this.timtId = timtId;
		this.timtDescripcion = timtDescripcion;
		this.timtEstado = timtEstado;
		this.materias = materias;
	}

	@Id

	@Column(name = "TIMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getTimtId() {
		return this.timtId;
	}

	public void setTimtId(Integer timtId) {
		this.timtId = timtId;
	}

	@Column(name = "TIMT_DESCRIPCION", length = 256)
	public String getTimtDescripcion() {
		return this.timtDescripcion;
	}

	public void setTimtDescripcion(String timtDescripcion) {
		this.timtDescripcion = timtDescripcion;
	}

	@Column(name = "TIMT_ESTADO", precision = 22, scale = 0)
	public Integer getTimtEstado() {
		return this.timtEstado;
	}

	public void setTimtEstado(Integer timtEstado) {
		this.timtEstado = timtEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMateria")
	public List<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(List<Materia> materias) {
		this.materias = materias;
	}

}
