package model;
// Generated 22/06/2019 19:40:53 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Feriado generated by hbm2java
 */
@Entity
@Table(name = "FERIADO")
public class Feriado implements java.io.Serializable {

	private FeriadoId id;
	private Facultad facultad;

	public Feriado() {
	}

	public Feriado(FeriadoId id, Facultad facultad) {
		this.id = id;
		this.facultad = facultad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "frdId", column = @Column(name = "FRD_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "frdDescripcion", column = @Column(name = "FRD_DESCRIPCION", length = 30)),
			@AttributeOverride(name = "frdFecha", column = @Column(name = "FRD_FECHA", length = 7)),
			@AttributeOverride(name = "frdFin", column = @Column(name = "FRD_FIN", length = 10)),
			@AttributeOverride(name = "frdInicio", column = @Column(name = "FRD_INICIO", length = 10)),
			@AttributeOverride(name = "fclId", column = @Column(name = "FCL_ID", nullable = false, precision = 22, scale = 0)) })
	public FeriadoId getId() {
		return this.id;
	}

	public void setId(FeriadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCL_ID", nullable = false, insertable = false, updatable = false)
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

}
