package model;
// Generated 16/06/2019 20:52:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HuellaDactilar generated by hbm2java
 */
@Entity
@Table(name = "HUELLA_DACTILAR", uniqueConstraints = @UniqueConstraint(columnNames = { "FCDC_ID", "TPHL_ID" }))
public class HuellaDactilar implements java.io.Serializable {

	private BigDecimal hldcId;
	private TipoHuella tipoHuella;
	private FichaDocente fichaDocente;
	private Blob hldPrimerHuella;
	private Blob hldSegundaHuella;
	private BigDecimal hldcCodigoAuxiliar;

	public HuellaDactilar() {
	}

	public HuellaDactilar(BigDecimal hldcId, TipoHuella tipoHuella, FichaDocente fichaDocente) {
		this.hldcId = hldcId;
		this.tipoHuella = tipoHuella;
		this.fichaDocente = fichaDocente;
	}

	public HuellaDactilar(BigDecimal hldcId, TipoHuella tipoHuella, FichaDocente fichaDocente, Blob hldPrimerHuella,
			Blob hldSegundaHuella, BigDecimal hldcCodigoAuxiliar) {
		this.hldcId = hldcId;
		this.tipoHuella = tipoHuella;
		this.fichaDocente = fichaDocente;
		this.hldPrimerHuella = hldPrimerHuella;
		this.hldSegundaHuella = hldSegundaHuella;
		this.hldcCodigoAuxiliar = hldcCodigoAuxiliar;
	}

	@Id

	@Column(name = "HLDC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHldcId() {
		return this.hldcId;
	}

	public void setHldcId(BigDecimal hldcId) {
		this.hldcId = hldcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPHL_ID", nullable = false)
	public TipoHuella getTipoHuella() {
		return this.tipoHuella;
	}

	public void setTipoHuella(TipoHuella tipoHuella) {
		this.tipoHuella = tipoHuella;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCDC_ID", nullable = false)
	public FichaDocente getFichaDocente() {
		return this.fichaDocente;
	}

	public void setFichaDocente(FichaDocente fichaDocente) {
		this.fichaDocente = fichaDocente;
	}

	@Column(name = "HLD_PRIMER_HUELLA")
	public Blob getHldPrimerHuella() {
		return this.hldPrimerHuella;
	}

	public void setHldPrimerHuella(Blob hldPrimerHuella) {
		this.hldPrimerHuella = hldPrimerHuella;
	}

	@Column(name = "HLD_SEGUNDA_HUELLA")
	public Blob getHldSegundaHuella() {
		return this.hldSegundaHuella;
	}

	public void setHldSegundaHuella(Blob hldSegundaHuella) {
		this.hldSegundaHuella = hldSegundaHuella;
	}

	@Column(name = "HLDC_CODIGO_AUXILIAR", precision = 22, scale = 0)
	public BigDecimal getHldcCodigoAuxiliar() {
		return this.hldcCodigoAuxiliar;
	}

	public void setHldcCodigoAuxiliar(BigDecimal hldcCodigoAuxiliar) {
		this.hldcCodigoAuxiliar = hldcCodigoAuxiliar;
	}

}
