package model;
// Generated 22/06/2019 19:40:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Metodologia generated by hbm2java
 */
@Entity
@Table(name = "METODOLOGIA")
public class Metodologia implements java.io.Serializable {

	private BigDecimal mtdId;
	private UnidadCurricular unidadCurricular;
	private String mtdDescripcion;

	public Metodologia() {
	}

	public Metodologia(BigDecimal mtdId, UnidadCurricular unidadCurricular) {
		this.mtdId = mtdId;
		this.unidadCurricular = unidadCurricular;
	}

	public Metodologia(BigDecimal mtdId, UnidadCurricular unidadCurricular, String mtdDescripcion) {
		this.mtdId = mtdId;
		this.unidadCurricular = unidadCurricular;
		this.mtdDescripcion = mtdDescripcion;
	}

	@Id

	@Column(name = "MTD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMtdId() {
		return this.mtdId;
	}

	public void setMtdId(BigDecimal mtdId) {
		this.mtdId = mtdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNCR_ID", nullable = false)
	public UnidadCurricular getUnidadCurricular() {
		return this.unidadCurricular;
	}

	public void setUnidadCurricular(UnidadCurricular unidadCurricular) {
		this.unidadCurricular = unidadCurricular;
	}

	@Column(name = "MTD_DESCRIPCION", length = 100)
	public String getMtdDescripcion() {
		return this.mtdDescripcion;
	}

	public void setMtdDescripcion(String mtdDescripcion) {
		this.mtdDescripcion = mtdDescripcion;
	}

}
