package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RelacionLaboral generated by hbm2java
 */
@Entity
@Table(name = "RELACION_LABORAL")
public class RelacionLaboral implements java.io.Serializable {

	private int rllbId;
	private String rllbDescripcion;
	private BigDecimal rllbEstado;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);

	public RelacionLaboral() {
	}

	public RelacionLaboral(int rllbId) {
		this.rllbId = rllbId;
	}

	public RelacionLaboral(int rllbId, String rllbDescripcion, BigDecimal rllbEstado,
			Set<DetallePuesto> detallePuestos) {
		this.rllbId = rllbId;
		this.rllbDescripcion = rllbDescripcion;
		this.rllbEstado = rllbEstado;
		this.detallePuestos = detallePuestos;
	}

	@Id

	@Column(name = "RLLB_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRllbId() {
		return this.rllbId;
	}

	public void setRllbId(int rllbId) {
		this.rllbId = rllbId;
	}

	@Column(name = "RLLB_DESCRIPCION", length = 256)
	public String getRllbDescripcion() {
		return this.rllbDescripcion;
	}

	public void setRllbDescripcion(String rllbDescripcion) {
		this.rllbDescripcion = rllbDescripcion;
	}

	@Column(name = "RLLB_ESTADO", precision = 22, scale = 0)
	public BigDecimal getRllbEstado() {
		return this.rllbEstado;
	}

	public void setRllbEstado(BigDecimal rllbEstado) {
		this.rllbEstado = rllbEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relacionLaboral")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

}
