--<ScriptOptions statementTerminator=";"/>

CREATE TABLE GRUPO (
		GRP_ID NUMBER(6 , 0) NOT NULL,
		GRP_DESCRIPCION VARCHAR2(1024),
		GRP_ESTADO NUMBER(38 , 0),
		GRP_CODIGO VARCHAR2(256),
		GRP_CRR_ID NUMBER
	);

CREATE TABLE CRONOGRAMA (
		CRN_ID NUMBER(6 , 0) NOT NULL,
		PRAC_ID NUMBER(38 , 0),
		CRN_TIPO NUMBER(38 , 0),
		CRN_DESCRIPCION VARCHAR2(256),
		CRN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE MATERIA_REQUISITO (
		MTR_ID NUMBER(38 , 0) NOT NULL,
		MTRQ_ID NUMBER(6 , 0) NOT NULL,
		MTRQ_DESCRIPCION VARCHAR2(1024),
		MTRQ_TIPO NUMBER(38 , 0)
	);

CREATE TABLE CONTRATO (
		CNT_ID NUMBER(6 , 0) NOT NULL,
		TICN_ID NUMBER(38 , 0),
		TIFN_ID NUMBER(38 , 0)
	);

CREATE TABLE FICHA_INSCRIPCION (
		FCIN_ID NUMBER(38 , 0) NOT NULL,
		USRO_ID NUMBER(38 , 0),
		CNCR_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		FCIN_FECHA_INSCRIPCION TIMESTAMP(11),
		FCIN_OBSERVACION VARCHAR2(256),
		FCIN_TIPO NUMBER(38 , 0),
		FCIN_MATRICULADO NUMBER(38 , 0),
		FCIN_ESTADO NUMBER(38 , 0),
		FCIN_ENCUESTA NUMBER(38 , 0),
		FCIN_NOTA_ENES NUMBER(38 , 0),
		FCIN_CARRERA NUMBER(38 , 0),
		FCIN_CARRERA_SIIU NUMBER(38 , 0),
		FCIN_CNCR_AREA NUMBER(38 , 0),
		FCIN_FCIN_NIVELACION NUMBER(38 , 0),
		FCIN_NIVEL_INGRESO NUMBER(38 , 0),
		FCIN_BLOQ_TER_MATR NUMBER(38 , 0),
		FCIN_ESTADO_RETIRO NUMBER,
		FCIN_TIPO_MODALIDAD NUMBER,
		FCIN_NUM_MAX_CREDITOS NUMBER,
		FCIN_TIPO_INGRESO NUMBER(38 , 0),
		FCIN_ESTADO_INGRESO NUMBER(38 , 0),
		FCIN_OBSERVACION_INGRESO VARCHAR2(256),
		FCIN_DOCUMENTO_INGRESO VARCHAR2(256),
		FCIN_ANIO_ABANDONA_CARRERA NUMBER(38 , 0),
		FCIN_CRR_ANTERIOR_ID NUMBER(38 , 0),
		FCIN_CNCR_ID_NIVELACION NUMBER(38 , 0),
		FCIN_FCIN_ANTERIOR_ID NUMBER(38 , 0),
		FCIN_NOTA_UBICACION FLOAT(126),
		FCIN_REINICIO_ORIGEN NUMBER,
		FCIN_VIGENTE NUMBER(38 , 0),
		FCIN_APLICA_NOTA_ENES NUMBER(38 , 0)
	);

CREATE TABLE GRUPO_OCUPACIONAL (
		GROC_ID NUMBER(6 , 0) NOT NULL,
		GROC_DESCRIPCION VARCHAR2(128),
		GROC_GRADO NUMBER(38 , 0),
		GROC_RMU NUMBER(6 , 2),
		RGM_ID NUMBER(38 , 0),
		GROC_RMU_HORA NUMBER(6 , 2)
	);

CREATE TABLE FICHA_ESTUDIANTE (
		FCES_ID NUMBER(6 , 0) NOT NULL,
		FCES_FECHA_INICIO DATE,
		FCES_FECHA_EGRESAMIENTO DATE,
		FCES_FECHA_ACTA_GRADO DATE,
		FCES_NUM_ACTA_GRADO VARCHAR2(40),
		FCES_FECHA_REFRENDACION DATE,
		FCES_NUM_REFRENDACION VARCHAR2(20),
		FCES_CRR_ESTUD_PREVIOS VARCHAR2(512),
		FCES_TIEMPO_ESTUD_REC NUMBER(38 , 0),
		FCES_TIPO_DURAC_REC NUMBER(38 , 0),
		FCES_TIPO_COLEGIO NUMBER(38 , 0),
		FCES_TIPO_COLEGIO_SNIESE VARCHAR2(1),
		FCES_NOTA_PROM_ACUMULADO NUMBER(4 , 2),
		FCES_NOTA_TRAB_TITULACION NUMBER(4 , 2),
		FCES_LINK_TESIS VARCHAR2(512),
		FCES_REC_ESTUD_PREVIOS NUMBER(38 , 0),
		FCES_REC_ESTUD_PREV_SNIESE VARCHAR2(1),
		FCES_FECHA_CREACION TIMESTAMP(11),
		PRS_ID NUMBER(38 , 0),
		INAC_ID NUMBER(38 , 0),
		FCIN_ID NUMBER(38 , 0),
		FCES_ESTADO_UNIVERSITARIO NUMBER(38 , 0),
		FCES_ESTADO_MATRICULA NUMBER(38 , 0),
		FCES_OBSERVACION VARCHAR2(256),
		FCES_TITULO_BACHILLER VARCHAR2(256),
		FCES_FECHA_ACTUALIZACION_DATOS TIMESTAMP(11),
		FCES_INAC_TTL_ID NUMBER(6 , 0),
		FCES_NOTA_GRADO_SECUNDARIA FLOAT(126),
		FCES_UBC_COLEGIO NUMBER(38 , 0),
		FCES_COLEGIO_ID NUMBER(38 , 0),
		FCES_TIPO_UNIV_ESTUD_PREV NUMBER(38 , 0),
		FCES_ESTADO_ESTUD_PREV NUMBER(38 , 0),
		FCES_UNIV_ESTUD_PREV_ID NUMBER(38 , 0),
		FCES_TIT_ESTUD_PREV_ID NUMBER(38 , 0),
		FCES_REG_TITULO_PREV VARCHAR2(128)
	);

CREATE TABLE CARRERA_AREA (
		CRAR_ID NUMBER(6 , 0) NOT NULL,
		CRR_ID NUMBER(6 , 0),
		AREA_ID NUMBER(6 , 0)
	);

CREATE TABLE DETALLE_PUESTO (
		DTPS_ID NUMBER(38 , 0) NOT NULL,
		PST_ID NUMBER(38 , 0),
		FCES_ID NUMBER(38 , 0),
		FCDC_ID NUMBER(38 , 0),
		FCEM_ID NUMBER(38 , 0),
		RLLB_ID NUMBER(38 , 0),
		TIDC_ID NUMBER(38 , 0),
		CRR_ID NUMBER(38 , 0),
		DTPS_ESTADO NUMBER(38 , 0),
		DTPS_ESTADO_CATEGORIA NUMBER,
		DTPS_PRAC_ID NUMBER(6 , 0),
		DTPS_TIPO_CARRERA NUMBER(6 , 0),
		DTPS_FECHA_REGISTRO TIMESTAMP(11),
		DTPS_USUARIO VARCHAR2(64),
		DTPS_PROCESO_REGISTRO NUMBER(6 , 0)
	);

CREATE TABLE HORA_CLASE (
		HOCL_ID NUMBER(6 , 0) NOT NULL,
		HOCL_DESCRIPCION VARCHAR2(128),
		HOCL_ESTADO NUMBER(38 , 0),
		HOCL_HORA_INICIO NUMBER(38 , 0),
		HOCL_HORA_FIN NUMBER(38 , 0)
	);

CREATE TABLE ACTIVIDAD_PUESTO (
		ACPS_ID NUMBER(6 , 0) NOT NULL,
		ACES_ID NUMBER(38 , 0),
		PST_ID NUMBER(38 , 0)
	);

CREATE TABLE INSTITUCION_ACADEMICA (
		INAC_ID NUMBER(6 , 0) NOT NULL,
		INAC_CODIGO_SNIESE VARCHAR2(6),
		INAC_DESCRIPCION VARCHAR2(512),
		INAC_NIVEL NUMBER(38 , 0),
		INAC_TIPO NUMBER(38 , 0),
		INAC_TIPO_SNIESE VARCHAR2(4),
		UBC_ID NUMBER(38 , 0)
	);

CREATE TABLE CONFIGURACION_CARRERA (
		CNCR_ID NUMBER(6 , 0) NOT NULL,
		CRR_ID NUMBER(38 , 0),
		VGN_ID NUMBER(38 , 0),
		MDL_ID NUMBER(38 , 0),
		TTL_ID NUMBER(38 , 0),
		UBC_ID NUMBER(38 , 0),
		TISE_ID NUMBER(38 , 0),
		TIFR_ID NUMBER(38 , 0),
		DRC_ID NUMBER(38 , 0)
	);

CREATE TABLE FICHA_EMPLEADO (
		FCEM_ID NUMBER(6 , 0) NOT NULL,
		PRS_ID NUMBER(38 , 0)
	);

CREATE TABLE FUNCION_PUESTO (
		FNPS_ID NUMBER(6 , 0) NOT NULL,
		PST_ID NUMBER(38 , 0),
		FNC_ID NUMBER(38 , 0)
	);

CREATE TABLE FUNCION_EVALUACION (
		FNEV_ID NUMBER(6 , 0) NOT NULL,
		FNEV_DESCRIPCION VARCHAR2(256),
		FNEV_ESTADO NUMBER(38 , 0),
		FNEV_FECHA TIMESTAMP(11),
		FNEV_USUARIO VARCHAR2(256)
	);

CREATE TABLE FICHA_DOCENTE (
		FCDC_ID NUMBER(6 , 0) NOT NULL,
		PRS_ID NUMBER(38 , 0),
		FCDC_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE COREQUISITO (
		CRQ_ID NUMBER(6 , 0) NOT NULL,
		MTR_ID NUMBER(38 , 0),
		MTR_COREQUISITO_ID NUMBER(38 , 0),
		CRQ_CODIGO VARCHAR2(128),
		CRQ_DESCRIPCION VARCHAR2(256),
		CRQ_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE COMPETENCIA_PUESTO (
		CMPS_ID NUMBER(6 , 0) NOT NULL,
		PST_ID NUMBER(38 , 0),
		NVCM_ID NUMBER(38 , 0)
	);

CREATE TABLE CONTENIDO (
		CNTN_ID NUMBER(10 , 0) NOT NULL,
		TPCNFNTPEV_ID NUMBER(6 , 0),
		ASEV_ID NUMBER(6 , 0),
		EVA_ID NUMBER(6 , 0),
		CNTN_DESCRIPCION VARCHAR2(2000),
		CNTN_SELECCION NUMBER(38 , 0),
		CNTN_FECHA TIMESTAMP(11),
		CNTN_USUARIO VARCHAR2(256),
		CNTN_SELECCION_INICIAL NUMBER,
		CNTN_REGISTRO_APELACION TIMESTAMP(11),
		CNTN_USUARIO_APELACION VARCHAR2(50),
		CNTN_OFICIO_APELACION VARCHAR2(100),
		CNTN_ESTADO_APELACION NUMBER
	);

CREATE TABLE ARANCEL (
		ARN_ID NUMBER(6 , 0) NOT NULL,
		MDL_ID NUMBER(38 , 0),
		TIGR_ID NUMBER(38 , 0),
		ARN_DESCRIPCION VARCHAR2(256),
		ARN_TIPO_MATRICULA NUMBER(38 , 0),
		ARN_TIPO_NUM_MATRICULA NUMBER(38 , 0),
		ARN_VALOR NUMBER(6 , 2),
		ARN_TIPO NUMBER(38 , 0),
		ARN_CODIGO_ARANCEL NUMBER
	);

CREATE TABLE ITINERARIO (
		ITN_ID NUMBER(6 , 0) NOT NULL,
		CRR_ID NUMBER(38 , 0),
		ITN_DESCRIPCION VARCHAR2(256),
		ITN_ESTADO NUMBER(38 , 0),
		ITN_OBSERVACION VARCHAR2(256)
	);

CREATE TABLE MALLA_CURRICULAR (
		MLCR_ID NUMBER(6 , 0) NOT NULL,
		TIFRML_ID NUMBER(38 , 0),
		CRR_ID NUMBER(38 , 0),
		MLCR_CODIGO VARCHAR2(128),
		MLCR_DESCRIPCION VARCHAR2(256),
		MLCR_ESTADO NUMBER(38 , 0),
		MLCR_FECHA_INICIO DATE,
		MLCR_FECHA_FIN DATE,
		MLCR_TOTAL_HORAS NUMBER(38 , 0),
		MLCR_TOTAL_MATERIAS NUMBER(38 , 0),
		MLCR_TIPO_ORG_APRENDIZAJE NUMBER(38 , 0),
		MLCR_VIGENTE NUMBER(38 , 0),
		MLCR_TIPO_APROBACION NUMBER(38 , 0)
	);

CREATE TABLE MATERIA (
		MTR_ID NUMBER(6 , 0) NOT NULL,
		CMFR_ID NUMBER(38 , 0),
		TIMT_ID NUMBER(38 , 0),
		MTR_SUB_ID NUMBER(38 , 0),
		NCPRCR_ID NUMBER(38 , 0),
		CRR_ID NUMBER(38 , 0),
		MTR_CODIGO VARCHAR2(128),
		MTR_CODIGO_SNIESE VARCHAR2(128),
		MTR_DESCRIPCION VARCHAR2(512),
		MTR_ESTADO NUMBER(38 , 0),
		MTR_HORAS NUMBER(38 , 0),
		MTR_INTEGRADORA_HORAS NUMBER(38 , 0),
		MTR_PRE_PROFESIONAL_HORAS NUMBER(38 , 0),
		MTR_HORAS_CIEN NUMBER(38 , 0),
		MTR_RELACION_TRABAJO NUMBER(38 , 0),
		MTR_UNIDAD_MEDIDA NUMBER(38 , 0),
		MTR_CREDITOS NUMBER(6 , 2),
		GRP_ID NUMBER(38 , 0),
		MTR_SEQ_SAU NUMBER,
		MTR_HORAS_PRACTICAS NUMBER(6 , 2),
		MTR_HORAS_TRAB_AUTONOMO NUMBER(6 , 2),
		MTR_HORAS_PRAC_SEMA NUMBER(38 , 0),
		MTR_HORAS_AUTONO_SEMA NUMBER(6 , 2)
	);

CREATE TABLE CONVALIDACION (
		CNV_ID NUMBER(6 , 0) NOT NULL,
		MTR_ID NUMBER(38 , 0),
		MLCRMT_ID NUMBER(38 , 0)
	);

CREATE TABLE CARRERA (
		CRR_ID NUMBER(6 , 0) NOT NULL,
		DPN_ID NUMBER(38 , 0),
		CRR_DESCRIPCION VARCHAR2(128),
		CRR_COD_SNIESE VARCHAR2(32),
		CRR_DETALLE VARCHAR2(256),
		CRR_FECHA_CREACION DATE,
		CRR_RESOLUCION VARCHAR2(128),
		CRR_TIPO NUMBER(38 , 0),
		CRR_CUPO NUMBER(38 , 0),
		CRR_ARANCEL NUMBER(8 , 2),
		CRR_ESPE_CODIGO NUMBER(38 , 0),
		CRR_PROCESO NUMBER(38 , 0),
		CRR_NUM_MAX_CREDITOS NUMBER,
		CRR_REAJUSTE_MATRICULA NUMBER(38 , 0),
		CRR_ID_ARANCEL NUMBER(8 , 0),
		CRR_TIPO_EVALUACION NUMBER(1 , 0)
	);

CREATE TABLE ITINERARIO_MALLA_MATERIA (
		ITMLMT_ID NUMBER(6 , 0) NOT NULL,
		ITMLMT_ESTADO NUMBER(38 , 0),
		MLCRMT_ID NUMBER(38 , 0),
		ITN_ID NUMBER(38 , 0)
	);

CREATE TABLE CARGA_HORARIA_CONTRATO (
		CRHRCN_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		CRHRCN_HORA_CLASE NUMBER(38 , 0),
		CRHRCN_HORA_VINCULACION NUMBER(38 , 0),
		CRHRCN_TUTORIA NUMBER(38 , 0),
		CRHRCN_PREPARACION_CLASE NUMBER(38 , 0)
	);

CREATE TABLE HORA_CLASE_AULA (
		HOCLAL_ID NUMBER(6 , 0) NOT NULL,
		HOCL_ID NUMBER(38 , 0),
		ALA_ID NUMBER(38 , 0),
		HOCLAL_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE CONTROL_PROCESO (
		CNPR_ID NUMBER(6 , 0) NOT NULL,
		TIPR_ID NUMBER(38 , 0),
		USRO_ID NUMBER(38 , 0),
		CNPR_DETALLE_PROCESO VARCHAR2(512),
		CNPR_TIPO_ACCION NUMBER(38 , 0),
		CNPR_FECHA_ACCION TIMESTAMP(11),
		CNPR_OBSERVACION_ACCION VARCHAR2(512)
	);

CREATE TABLE CAUSAL (
		CSL_ID NUMBER(6 , 0) NOT NULL,
		TICS_ID NUMBER(38 , 0),
		CSL_DESCRIPCION VARCHAR2(512),
		CSL_ESTADO NUMBER(38 , 0),
		CSL_CODIGO VARCHAR2(10)
	);

CREATE TABLE COMPETENCIA (
		CMP_ID NUMBER(6 , 0) NOT NULL,
		CMP_DENOMINACION VARCHAR2(512),
		CMP_DEFINICION VARCHAR2(512),
		CMP_TIPO NUMBER(38 , 0)
	);

CREATE TABLE MALLA_CURRICULAR_MATERIA (
		MLCRMT_ID NUMBER(6 , 0) NOT NULL,
		MLCR_ID NUMBER(38 , 0),
		MTR_ID NUMBER(38 , 0),
		UNFR_ID NUMBER(38 , 0),
		NVL_ID NUMBER(38 , 0),
		NVL_SUB_ID NUMBER(38 , 0),
		MLCRMT_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE FICHA_MATRICULA (
		FCMT_ID NUMBER(38 , 0) NOT NULL,
		FCES_ID NUMBER(38 , 0),
		PLCR_ID NUMBER(38 , 0),
		FCMT_NIVEL_UBICACION NUMBER(38 , 0),
		FCMT_ESTADO NUMBER(38 , 0),
		FCMT_FECHA_CONVALIDACION DATE,
		FCMT_TIPO NUMBER(38 , 0),
		FCMT_MODALIDAD NUMBER(38 , 0),
		FCMT_VALOR_TOTAL NUMBER(8 , 2),
		FCMT_FECHA_MATRICULA TIMESTAMP(11),
		FCMT_FECHA_ESTADO TIMESTAMP(11),
		FCMT_PRAC_ID NUMBER(3 , 0)
	);

CREATE TABLE MATERIA_INTERCAMBIO (
		MTIN_ID NUMBER(6 , 0) NOT NULL,
		CRIN_ID NUMBER(38 , 0) NOT NULL,
		MTR_ID NUMBER(38 , 0) NOT NULL,
		MTIN_DESCRIPCION VARCHAR2(1024),
		MTIN_CODIGO VARCHAR2(32),
		MTIN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE APRUEBA_SOLICITUD (
		APSL_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		APSL_FECHA_APROBACION TIMESTAMP(11),
		APSL_ESTADO NUMBER(38 , 0),
		APSL_OBSERVACION VARCHAR2(512)
	);

CREATE TABLE FUNCION (
		FNC_ID NUMBER(6 , 0) NOT NULL,
		FNC_DESCRIPCION VARCHAR2(256)
	);

CREATE TABLE EVALUACION (
		EVA_ID NUMBER(6 , 0) NOT NULL,
		PRAC_ID NUMBER(6 , 0),
		TPEV_ID NUMBER(6 , 0),
		EVA_DESCRIPCION VARCHAR2(2000),
		EVA_USUARIO VARCHAR2(256),
		EVA_CRONOGRAMA_INICIO TIMESTAMP(11),
		EVA_ESTADO NUMBER(38 , 0),
		EVA_CRONOGRAMA_FIN TIMESTAMP(11),
		EVA_PRFL_ID NUMBER(38 , 0),
		EVA_FECHA TIMESTAMP(11)
	);

CREATE TABLE EVALUADOR_EVALUADO (
		EVEV_ID NUMBER(6 , 0) NOT NULL,
		USRO_ID NUMBER(6 , 0),
		EVEV_EVALUADOR NUMBER(38 , 0)
	);

CREATE TABLE MALLA_CURRICULAR_PARALELO (
		MLCRPR_ID NUMBER(6 , 0) NOT NULL,
		PRL_ID NUMBER(38 , 0),
		MLCRMT_ID NUMBER(38 , 0),
		MLCRPR_INSCRITOS NUMBER(38 , 0),
		MLCRPR_CUPO NUMBER(38 , 0),
		MLCRPR_RESERVA_REPETIDOS NUMBER(38 , 0),
		MLCRPR_NIVELACION_CRR_ID NUMBER(38 , 0),
		MLCRPR_MODALIDAD NUMBER
	);

CREATE TABLE EDIFICIO (
		EDF_ID NUMBER(6 , 0) NOT NULL,
		DPN_ID NUMBER(38 , 0),
		EDF_DESCRIPCION VARCHAR2(256),
		EDF_ESTADO NUMBER(38 , 0),
		EDF_CODIGO VARCHAR2(256),
		EDF_LOCALIZACION NUMBER(38 , 0)
	);

CREATE TABLE HORARIO_FUNCION (
		HRFN_ID NUMBER(6 , 0) NOT NULL,
		HRFN_DESCRIPCION VARCHAR2(256),
		HRFN_HORA_INICIO NUMBER(38 , 0),
		HRFN_HORA_FIN NUMBER(38 , 0),
		HRFN_ESTADO NUMBER(38 , 0),
		HRFN_DTPS_ID NUMBER(38 , 0),
		HRFN_DIA NUMBER(38 , 0),
		HRFN_PRAC_ID NUMBER(38 , 0),
		HOCL_ID NUMBER(38 , 0),
		HRFN_FUNCION NUMBER(38 , 0),
		HRFN_ACTIVIDAD NUMBER(38 , 0)
	);

CREATE TABLE COMPROBANTE_PAGO (
		CMPA_ID NUMBER(38 , 0) NOT NULL,
		FCMT_ID NUMBER(38 , 0),
		CMPA_CODIGO VARCHAR2(128),
		CMPA_ESTADO NUMBER(38 , 0),
		CMPA_VALOR_TOTAL NUMBER(6 , 2),
		CMPA_FECHA_EMISION TIMESTAMP(11),
		CMPA_FECHA_CADUCIDAD DATE,
		CMPA_TIPO NUMBER(38 , 0),
		CMPA_FECHA_PAGO DATE,
		CMPA_NUM_COMP_SECUENCIAL NUMBER(38 , 0),
		CMPA_NUM_COMPROBANTE VARCHAR2(256),
		CMPA_DESCRIPCION VARCHAR2(128),
		CMPA_TOTAL_PAGO NUMBER(8 , 2),
		CMPA_TOTAL_FACULTAD NUMBER(8 , 2),
		CMPA_FECHA_CADUCA TIMESTAMP(11),
		CMPA_ESPE_CODIGO NUMBER(38 , 0),
		CMPA_MODALIDAD NUMBER(38 , 0),
		CMPA_MATR_TIPO NUMBER(38 , 0),
		CMPA_APLICA_GRATUIDAD NUMBER(38 , 0),
		CMPA_PAI_CODIGO NUMBER(38 , 0),
		CMPA_ID_ARANCEL NUMBER(38 , 0),
		CMPA_CANTIDAD NUMBER(38 , 0),
		CMPA_VALOR_PAGADO NUMBER(8 , 2),
		CMPA_TIPO_UNIDAD NUMBER(38 , 0),
		CMPA_PROC_SAU NUMBER(38 , 0),
		CMPA_FECHA_ENVIO TIMESTAMP(11),
		CMPA_ESTADO_PAGO NUMBER(38 , 0),
		CMPA_OBSERVACION VARCHAR2(512)
	);

CREATE TABLE FUNCION_CARGA_HORARIA (
		FNCRHR_ID NUMBER(38 , 0) NOT NULL,
		FNCRHR_DESCRIPCION VARCHAR2(128),
		FNCRHR_HORAS_ASIGNADAS NUMBER(38 , 0),
		FNCRHR_HORAS_MINIMO NUMBER(38 , 0),
		FNCRHR_HORAS_MAXIMO NUMBER(38 , 0),
		FNCRHR_TIEMPO_DEDICACION NUMBER
	);

CREATE TABLE CRONOGRAMA_PROCESO_FLUJO (
		PRFL_ID NUMBER(38 , 0),
		CRN_ID NUMBER(38 , 0),
		CRPRFL_ID NUMBER(6 , 0) NOT NULL,
		CRPRFL_ORDINAL NUMBER
	);

CREATE TABLE ACTIVIDAD_ESENCIAL (
		ACES_ID NUMBER(6 , 0) NOT NULL,
		ACES_DESCRIPCION VARCHAR2(512)
	);

CREATE TABLE EXPERIENCIA_LABORAL_CONTR (
		CNCN_ID NUMBER(38 , 0),
		EXLBCN_ID NUMBER(6 , 0) NOT NULL,
		EXLBCN_TIPO_INSTITUCION NUMBER(38 , 0),
		EXLBCN_DESCRIPCION VARCHAR2(256),
		EXLBCN_UNIDAD VARCHAR2(256),
		EXLBCN_PUESTO VARCHAR2(256),
		EXLBCN_FECHA_INGRESO DATE,
		EXLBCN_FECHA_SALIDA DATE,
		EXLBCN_MOTIVO_INGRESO NUMBER(38 , 0),
		EXLBCN_MOTIVO_SALIDA NUMBER(38 , 0),
		EXLBCN_TIPO NUMBER(38 , 0)
	);

CREATE TABLE DEPENDENCIA (
		DPN_ID NUMBER(6 , 0) NOT NULL,
		DPN_SUB_ID NUMBER(38 , 0),
		UBC_ID NUMBER(38 , 0),
		DPN_DESCRIPCION VARCHAR2(512),
		DPN_JERARQUIA NUMBER(38 , 0),
		DPN_ESTADO NUMBER(38 , 0),
		DPN_CAMPUS NUMBER(38 , 0),
		DPN_COD_SORI VARCHAR2(4),
		DPN_UEJ VARCHAR2(4),
		DPN_FAC_CODIGO NUMBER(38 , 0)
	);

CREATE TABLE DETALLE_CARGA_HORARIA (
		DTCRHR_ID NUMBER(6 , 0) NOT NULL,
		CRHR_ID NUMBER(38 , 0),
		DTCRHR_FECHA_INICIO DATE,
		DTCRHR_FECHA_FIN DATE,
		DTCRHR_NUM_PROYECTO NUMBER(38 , 0),
		DTCRHR_AREA VARCHAR2(2000),
		DTCRHR_SUBAREA VARCHAR2(2000),
		DTCRHR_UNIDAD_ACADEMICA VARCHAR2(2000),
		DTCRHR_ASIGNATURA_CLINICAS VARCHAR2(2000),
		DTCRHR_NUM_ALUMNOS_CLINICAS NUMBER(38 , 0),
		DTCRHR_UNIVERSIDAD_DOCTORADO VARCHAR2(2000),
		DTCRHR_TITULO_DOCTORADO VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO1 NUMBER(38 , 0),
		DTCRHR_PROYECTO1 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO2 NUMBER(38 , 0),
		DTCRHR_PROYECTO2 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO3 NUMBER(38 , 0),
		DTCRHR_PROYECTO3 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO4 NUMBER(38 , 0),
		DTCRHR_PROYECTO4 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO5 NUMBER(38 , 0),
		DTCRHR_PROYECTO5 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO6 NUMBER(38 , 0),
		DTCRHR_PROYECTO6 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO7 NUMBER(38 , 0),
		DTCRHR_PROYECTO7 VARCHAR2(2000),
		DTCRHR_NIVEL_PROYECTO8 NUMBER(38 , 0),
		DTCRHR_PROYECTO8 VARCHAR2(2000),
		DTCRHR_CARRERA_ID NUMBER(38 , 0),
		DTCRHR_PROYECTO1_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO2_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO3_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO4_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO5_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO6_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO7_HORAS NUMBER(38 , 0),
		DTCRHR_PROYECTO8_HORAS NUMBER(38 , 0),
		DTCRHR_ESTADO NUMBER(38 , 0),
		DTCRHR_ESTADO_ELIMINACION NUMBER(38 , 0),
		DTCRHR_NUM_HORAS NUMBER(38 , 0),
		DTCRHR_NOMBRE_PROYECTO VARCHAR2(2000),
		DTCRHR_FUNCION VARCHAR2(2000),
		DTCRHR_NUM_ALUMNOS_TITULACION NUMBER(38 , 0)
	);

CREATE TABLE INSTRUCCION_PUESTO (
		INPS_ID NUMBER(6 , 0) NOT NULL,
		NVIN_ID NUMBER(38 , 0),
		PST_ID NUMBER(38 , 0),
		INPS_ANIO NUMBER(38 , 0),
		INPS_MES NUMBER(38 , 0)
	);

CREATE TABLE DETALLE_MATRICULA (
		DTMT_ID NUMBER(38 , 0) NOT NULL,
		ARN_ID NUMBER(38 , 0),
		CMPA_ID NUMBER(38 , 0),
		MLCRPR_ID NUMBER(38 , 0),
		DTMT_NUMERO NUMBER(38 , 0),
		DTMT_ESTADO NUMBER(38 , 0),
		DTMT_ARCHIVO_ESTUDIANTES VARCHAR2(512),
		DTMT_ESTADO_HISTORICO NUMBER(38 , 0),
		DTMT_ESTADO_CAMBIO NUMBER(38 , 0),
		DTMT_OBSERVACION_HISTORICO VARCHAR2(512),
		DTMT_OBSERVACION_CAMBIO VARCHAR2(512),
		DTMT_VALOR_PARCIAL NUMBER(8 , 2),
		DTMT_FECHA_HISTORICO TIMESTAMP(11),
		DTMT_FECHA_CAMBIO TIMESTAMP(11),
		DTMT_VALOR_POR_MATERIA NUMBER(10 , 2),
		DTMT_USUARIO VARCHAR2(256),
		DTMT_MODIFICACION TIMESTAMP(11),
		DTMT_ESTADO_SOLICITUD NUMBER(38 , 0),
		DTMT_FECHA_SOLICITUD TIMESTAMP(11),
		DTMT_ESTADO_RESPUESTA NUMBER(38 , 0),
		DTMT_FECHA_RESPUESTA TIMESTAMP(11),
		DTMT_ARCHIVO_RESPUESTA VARCHAR2(512),
		DTMT_ARCHIVO_SOLICITUD VARCHAR2(512),
		CSL_RETIRO_ID NUMBER(38 , 0),
		DTMT_FECHA_VERIFICACION_RETIRO TIMESTAMP(11),
		DTMT_TIPO_ANULACION NUMBER(2 , 0),
		DTMT_FECHA_ANULACION TIMESTAMP(11),
		DTMT_REGISTRANTE_ANULACION VARCHAR2(512),
		DTMT_OBSERVACION_ANULACION VARCHAR2(512),
		DTMT_OBSERVACION_FINAL_RETIRO VARCHAR2(512),
		DTMT_ARCHIVO_ANULACION VARCHAR2(512)
	);

CREATE TABLE CALIFICACION (
		CLF_ID NUMBER(38 , 0) NOT NULL,
		RCES_ID NUMBER(38 , 0),
		CLF_NOTA1 FLOAT(126),
		CLF_NOTA2 FLOAT(126),
		CLF_EXAMEN FLOAT(126),
		CLF_SUPLETORIO FLOAT(126),
		CLF_ASISTENCIA1 FLOAT(126),
		CLF_ASISTENCIA2 FLOAT(126),
		CLF_TOTAL_ASISTENCIA1 FLOAT(126),
		CLF_TOTAL_ASISTENCIA2 FLOAT(126),
		CLF_PROMEDIO_NOTAS FLOAT(126),
		CLF_PROMEDIO_ASISTENCIA FLOAT(126),
		CLF_ASISTENCIA_TOTAL FLOAT(126),
		CLF_PARAM_RECUPERACION1 FLOAT(126),
		CLF_PARAM_RECUPERACION2 FLOAT(126),
		CLF_NOTA_FINAL_SEMESTRE FLOAT(126),
		CLF_ESTADO NUMBER(38 , 0),
		CLF_ASISTENCIA_DOCENTE1 FLOAT(126),
		CLF_ASISTENCIA_DOCENTE2 FLOAT(126),
		CLF_SUMA_P1_P2 FLOAT(126),
		CLF_ASISTENCIA_TOTAL_DOC FLOAT(126)
	);

CREATE TABLE AREA_CONOCIMIENTO (
		ARCN_ID NUMBER(6 , 0) NOT NULL,
		ARCN_DESCRIPCION VARCHAR2(128),
		ARCN_CODIGO VARCHAR2(10),
		ARCN_JERARQUIA NUMBER(38 , 0),
		ARCN_SUB_ID NUMBER(38 , 0)
	);

CREATE TABLE FORMATO_CONTRATO (
		FRCN_ID NUMBER(6 , 0) NOT NULL,
		TICN_ID NUMBER(38 , 0),
		FRCN_DESCRIPCON VARCHAR2(512),
		FRCN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE DESTREZA_PUESTO (
		DSPS_ID NUMBER(38 , 0) NOT NULL,
		DST_ID NUMBER(38 , 0),
		PST_ID NUMBER(38 , 0)
	);

CREATE TABLE CAMPO_FORMACION (
		CMFR_ID NUMBER(6 , 0) NOT NULL,
		CMFR_TIPO NUMBER(38 , 0),
		CMFR_DESCRIPCION VARCHAR2(256),
		CMFR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE DESTREZA (
		DST_ID NUMBER(6 , 0) NOT NULL,
		DST_DESCRIPCION VARCHAR2(512)
	);

CREATE TABLE CARRERA_INTERCAMBIO (
		CRIN_ID NUMBER(6 , 0) NOT NULL,
		FCIN_ID NUMBER(38 , 0) NOT NULL,
		CRR_ID NUMBER(38 , 0) NOT NULL,
		CRIN_AUTORIZACION VARCHAR2(1024),
		CRIN_USER_REGISTRO VARCHAR2(256),
		CRIN_FECHA_REGISTRO TIMESTAMP(11),
		CRIN_OBSERVACION VARCHAR2(256),
		CRIN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE CALIFICACION_MODULO (
		CLMD_ID NUMBER(38 , 0) NOT NULL,
		RCES_ID NUMBER(38 , 0),
		CLMD_NOTA1 FLOAT(126),
		CLMD_NOTA2 FLOAT(126),
		CLMD_EXAMEN FLOAT(126),
		CLMD_SUPLETORIO FLOAT(126),
		CLMD_ASISTENCIA1 FLOAT(126),
		CLMD_ASISTENCIA2 FLOAT(126),
		CLMD_TOTAL_ASISTENCIA1 FLOAT(126),
		CLMD_TOTAL_ASISTENCIA2 FLOAT(126),
		CLMD_PROMEDIO_NOTAS FLOAT(126),
		CLMD_PROMEDIO_ASISTENCIA FLOAT(126),
		CLMD_ASISTENCIA_TOTAL FLOAT(126),
		CLMD_PARAM_RECUPERACION1 FLOAT(126),
		CLMD_PARAM_RECUPERACION2 FLOAT(126),
		CLMD_NOTA_FINAL_SEMESTRE FLOAT(126),
		CLMD_ESTADO NUMBER(38 , 0),
		CLMD_ASISTENCIA_DOCENTE1 FLOAT(126),
		CLMD_ASISTENCIA_DOCENTE2 FLOAT(126),
		CLMD_SUMA_P1_P2 FLOAT(126),
		CLMD_ASISTENCIA_TOTAL_DOC FLOAT(126),
		MLCRPR_ID_MODULO NUMBER(38 , 0)
	);

CREATE TABLE MALLA_CURRICULAR_NIVEL (
		MLCRNV_ID NUMBER NOT NULL,
		MLCRNV_CREDITOS NUMBER,
		MLCRNV_CREDITOS_ACUMULADO NUMBER,
		NVL_ID NUMBER,
		MLCR_ID NUMBER
	);

CREATE TABLE MALLA_PERIODO (
		MLPR_ID NUMBER(6 , 0) NOT NULL,
		MLCR_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		MLPR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE INFORME_TECNICO (
		INTC_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		INTC_OBSERVACION VARCHAR2(512),
		INTC_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE DETALLE_TRAMITE_CONTRATO (
		DTTRCN_ID NUMBER(6 , 0) NOT NULL,
		DTPS_ID NUMBER(38 , 0),
		TRM_ID NUMBER(38 , 0),
		CNT_ID NUMBER(38 , 0),
		DTTRCN_SUB_ID NUMBER(38 , 0),
		DTTRCN_NUM_TRAMITE VARCHAR2(32),
		DTTRCN_ESTADO_TRAMITE NUMBER(38 , 0),
		DTTRCN_ESTADO_PROCESO NUMBER(38 , 0),
		DTTRCN_OBSERVACION VARCHAR2(512),
		DTTRCN_FECHA_INICIO DATE,
		DTTRCN_FECHA_FIN DATE,
		DTTRCN_ARCHIVO_RESOLUCION VARCHAR2(256)
	);

CREATE TABLE DURACION (
		DRC_ID NUMBER(6 , 0) NOT NULL,
		DRC_TIPO NUMBER(38 , 0),
		DRC_TIEMPO NUMBER(38 , 0),
		DRC_TIPO_SNIESE VARCHAR2(6)
	);

CREATE TABLE ASIGNA_PRESUPUESTO (
		ASPR_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		ASPR_PARTIDA_PRESUPUESTO VARCHAR2(50),
		ASPR_ESTADO NUMBER(38 , 0),
		ASPR_ARCHIVO_CERTIFICACION VARCHAR2(256)
	);

CREATE TABLE CONOCIMIENTO (
		CNC_ID NUMBER(6 , 0) NOT NULL,
		CNC_DESCRIPCION VARCHAR2(512)
	);

CREATE TABLE FUNCION_TIPO_EVALUACION (
		FNCTPEV_ID NUMBER(38 , 0) NOT NULL,
		TPEV_ID NUMBER(6 , 0),
		FNEV_ID NUMBER(6 , 0),
		FNCTPEV_USUARIO VARCHAR2(256),
		FNCTPEV_FECHA TIMESTAMP(11),
		FNCTPEV_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE CONOCIMIENTO_PUESTO (
		CNPS_ID NUMBER(6 , 0) NOT NULL,
		PST_ID NUMBER(38 , 0),
		CNC_ID NUMBER(38 , 0)
	);

CREATE TABLE ASIGNACION_EVALUADOR (
		ASEV_ID NUMBER(6 , 0) NOT NULL,
		CRHR_ID NUMBER(6 , 0),
		EVEV_ID NUMBER(6 , 0),
		ASEV_ESTADO NUMBER(38 , 0),
		ASEV_USUARIO VARCHAR2(256),
		ASEV_FECHA TIMESTAMP(11),
		ASEV_EVALUADOR_CRR_ID NUMBER(38 , 0)
	);

CREATE TABLE CAUSAL_DETALLE_MATRICULA (
		CSDTMT_ID NUMBER(6 , 0) NOT NULL,
		CSL_ID NUMBER(38 , 0),
		DTMT_ID NUMBER(38 , 0)
	);

CREATE TABLE GRATUIDAD (
		GRT_ID NUMBER(38 , 0) NOT NULL,
		FCES_ID NUMBER(38 , 0),
		TIGR_ID NUMBER(38 , 0),
		FCMT_ID NUMBER(38 , 0),
		GRT_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE CANDIDATO_CONTRATO (
		CNCN_ID NUMBER(6 , 0) NOT NULL,
		PRS_ID NUMBER(38 , 0),
		PRTRCN_ID NUMBER(38 , 0),
		CNCN_ESTADO NUMBER(38 , 0),
		CNCN_OBS_RECTORADO VARCHAR2(512),
		CNCN_TERCER_NIVEL VARCHAR2(512),
		CNCN_CUARTO_NIVEL VARCHAR2(512),
		CNCN_IMPEDIMENTO NUMBER(38 , 0),
		CNCN_OBS_IMPEDIMENTO VARCHAR2(512),
		CNCN_ARCHIVO_IMPEDIMENTO VARCHAR2(256),
		CNCN_LABORA_OTRA_INST NUMBER(38 , 0),
		CNCN_OBS_LABORA_OTRA_INST VARCHAR2(256),
		CNCN_ARCHIVO_LABORA_INST VARCHAR2(256)
	);

CREATE TABLE AULA (
		ALA_ID NUMBER(38 , 0) NOT NULL,
		EDF_ID NUMBER(38 , 0),
		ALA_DESCRIPCION VARCHAR2(256),
		ALA_CODIGO VARCHAR2(256),
		ALA_TIPO NUMBER(38 , 0),
		ALA_CAPACIDAD NUMBER(38 , 0),
		ALA_PISO NUMBER(38 , 0),
		ALA_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE ETNIA (
		ETN_ID NUMBER(6 , 0) NOT NULL,
		ETN_CODIGO_SNIESE VARCHAR2(1),
		ETN_DESCRIPCION VARCHAR2(20)
	);

CREATE TABLE CARGA_HORARIA (
		CRHR_ID NUMBER(38 , 0) NOT NULL,
		TIFNCRHR_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		DTPS_ID NUMBER(38 , 0),
		MLCRPR_ID NUMBER(38 , 0),
		CRHR_OBSERVACION VARCHAR2(1024),
		CRHR_ESTADO NUMBER(38 , 0),
		CRHR_NUM_HORAS NUMBER(38 , 0),
		CRHR_ESTADO_ELIMINACION NUMBER(38 , 0),
		CRHR_CARRERA_ID NUMBER(38 , 0),
		MLCRPR_ID_PRINCIPAL NUMBER
	);

CREATE TABLE HORARIO_ACADEMICO (
		HRAC_ID NUMBER(6 , 0) NOT NULL,
		HRAC_DESCRIPCION VARCHAR2(256),
		HRAC_DIA NUMBER(38 , 0),
		HRAC_HORA_INICIO NUMBER(38 , 0),
		HRAC_HORA_FIN NUMBER(38 , 0),
		HRAC_ESTADO NUMBER(38 , 0),
		HOCLAL_ID NUMBER(38 , 0),
		MLCRPR_ID NUMBER(38 , 0),
		MLCRPR_ID_COMP NUMBER(38 , 0),
		HRAC_HORA_TIPO NUMBER
	);

CREATE TABLE EXCEDENTE (
		EXC_ID NUMBER(6 , 0) NOT NULL,
		EXC_DESCRIPCION VARCHAR2(128),
		EXC_ESTADO NUMBER(38 , 0),
		EXC_TIPO NUMBER(38 , 0)
	);

CREATE INDEX TIFNCRHR_CRHR_FK ON CARGA_HORARIA (TIFNCRHR_ID ASC);

CREATE INDEX FCEM_DTPS_FK ON DETALLE_PUESTO (FCEM_ID ASC);

CREATE INDEX CMFR_MTR_FK ON MATERIA (CMFR_ID ASC);

CREATE INDEX CNCN_EXLBCN_FK ON EXPERIENCIA_LABORAL_CONTR (CNCN_ID ASC);

CREATE INDEX VGN_CNCR_FK ON CONFIGURACION_CARRERA (VGN_ID ASC);

CREATE INDEX MLCRMT_MLCRPR_FK ON MALLA_CURRICULAR_PARALELO (MLCRMT_ID ASC);

CREATE INDEX RGM_GROC_FK ON GRUPO_OCUPACIONAL (RGM_ID ASC);

CREATE UNIQUE INDEX PK_EXPERIENCIA_LABORAL_CONTR ON EXPERIENCIA_LABORAL_CONTR (EXLBCN_ID ASC);

CREATE INDEX USRO_EVEV_FK ON EVALUADOR_EVALUADO (USRO_ID ASC);

CREATE INDEX PRFL_CRPRFL_FK ON CRONOGRAMA_PROCESO_FLUJO (PRFL_ID ASC);

CREATE INDEX CRR_DTPS_FK ON DETALLE_PUESTO (CRR_ID ASC);

CREATE INDEX MLCRMT_ITMLMT_FK ON ITINERARIO_MALLA_MATERIA (MLCRMT_ID ASC);

CREATE INDEX MTR_SUB_MTR_FK ON MATERIA (MTR_SUB_ID ASC);

CREATE INDEX FCDC_DTPS_FK ON DETALLE_PUESTO (FCDC_ID ASC);

CREATE INDEX TIGR_GRT_FK ON GRATUIDAD (TIGR_ID ASC);

CREATE UNIQUE INDEX PK_FICHA_EMPLEADO ON FICHA_EMPLEADO (FCEM_ID ASC);

CREATE UNIQUE INDEX PK_MALLA_CURRICULAR_NIVEL ON MALLA_CURRICULAR_NIVEL (MLCRNV_ID ASC);

CREATE INDEX MLCRPR_CRHR_FK ON CARGA_HORARIA (MLCRPR_ID ASC);

CREATE INDEX PST_DSPS_FK ON DESTREZA_PUESTO (PST_ID ASC);

CREATE UNIQUE INDEX PK_DEPENDENCIA ON DEPENDENCIA (DPN_ID ASC);

CREATE UNIQUE INDEX PK_COMPETENCIA_PUESTO ON COMPETENCIA_PUESTO (CMPS_ID ASC);

CREATE INDEX TICS_CSL_FK ON CAUSAL (TICS_ID ASC);

CREATE UNIQUE INDEX PK_DESTREZA_PUESTO ON DESTREZA_PUESTO (DSPS_ID ASC);

CREATE INDEX PS_DTPS_FK ON DETALLE_PUESTO (PST_ID ASC);

CREATE UNIQUE INDEX PK_CONFIGURACION_CARRERA ON CONFIGURACION_CARRERA (CNCR_ID ASC);

CREATE INDEX TIFR_CNCR_FK ON CONFIGURACION_CARRERA (TIFR_ID ASC);

CREATE UNIQUE INDEX PK_FORMATO_CONTRATO ON FORMATO_CONTRATO (FRCN_ID ASC);

CREATE INDEX USRO_CNPR_FK ON CONTROL_PROCESO (USRO_ID ASC);

CREATE INDEX PRL_MLCRPR_FK ON MALLA_CURRICULAR_PARALELO (PRL_ID ASC);

CREATE INDEX TIMT_MT_FK ON MATERIA (TIMT_ID ASC);

CREATE INDEX TIPR_CNPR_FK ON CONTROL_PROCESO (TIPR_ID ASC);

CREATE INDEX TPCN_FUNCION_TPEV_CN_FK ON CONTENIDO (TPCNFNTPEV_ID ASC);

CREATE INDEX MLCR_MLCRMT_FK ON MALLA_CURRICULAR_MATERIA (MLCR_ID ASC);

CREATE INDEX PRS_CNCN_FK ON CANDIDATO_CONTRATO (PRS_ID ASC);

CREATE INDEX CRR_MLCR_FK ON MALLA_CURRICULAR (CRR_ID ASC);

CREATE UNIQUE INDEX PK_FUNCION_EVALUACION ON FUNCION_EVALUACION (FNEV_ID ASC);

CREATE INDEX DTTRCN_DTTRCN_FK ON DETALLE_TRAMITE_CONTRATO (DTTRCN_SUB_ID ASC);

CREATE UNIQUE INDEX PK_MALLA_CURRICULAR_PARALELO ON MALLA_CURRICULAR_PARALELO (MLCRPR_ID ASC);

CREATE UNIQUE INDEX PK_CAUSAL_DETALLE_MATRICULA ON CAUSAL_DETALLE_MATRICULA (CSDTMT_ID ASC);

CREATE UNIQUE INDEX PK_EXCEDENTE ON EXCEDENTE (EXC_ID ASC);

CREATE INDEX PRAC_MLPR_FK ON MALLA_PERIODO (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_CARGA_HORARIA ON CARGA_HORARIA (CRHR_ID ASC);

CREATE UNIQUE INDEX PK_EVALUADOR_EVALUADO ON EVALUADOR_EVALUADO (EVEV_ID ASC);

CREATE INDEX MTR_CRQ_FK ON COREQUISITO (MTR_ID ASC);

CREATE UNIQUE INDEX PK_CARGA_HORARIA_CONTRATO ON CARGA_HORARIA_CONTRATO (CRHRCN_ID ASC);

CREATE INDEX ARCN_ARCN_FK ON AREA_CONOCIMIENTO (ARCN_SUB_ID ASC);

CREATE UNIQUE INDEX PK_MALLA_PERIODO ON MALLA_PERIODO (MLPR_ID ASC);

CREATE UNIQUE INDEX PK_CARRERA ON CARRERA (CRR_ID ASC);

CREATE UNIQUE INDEX PK_CANDIDATO_CONTRATO ON CANDIDATO_CONTRATO (CNCN_ID ASC);

CREATE INDEX CMPA_DTMT_FK ON DETALLE_MATRICULA (CMPA_ID ASC);

CREATE INDEX PRAC_CRHR_FK ON CARGA_HORARIA (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_CALIFICACION_MODUL0 ON CALIFICACION_MODULO (CLMD_ID ASC);

CREATE INDEX RCES_CLMD_FK ON CALIFICACION_MODULO (RCES_ID ASC);

CREATE INDEX DTPS_CRHR_FK ON CARGA_HORARIA (DTPS_ID ASC);

CREATE UNIQUE INDEX PK_FICHA_MATRICULA ON FICHA_MATRICULA (FCMT_ID ASC);

CREATE INDEX CRHR_DTCRHR_FK ON DETALLE_CARGA_HORARIA (CRHR_ID ASC);

CREATE INDEX DTPS_DTTRCN_FK ON DETALLE_TRAMITE_CONTRATO (DTPS_ID ASC);

CREATE INDEX PRTRCN_CRHRCN_FK ON CARGA_HORARIA_CONTRATO (PRTRCN_ID ASC);

CREATE INDEX MLCRMT_CNV_FK ON CONVALIDACION (MLCRMT_ID ASC);

CREATE INDEX HOCL_HOCLAL_FK ON HORA_CLASE_AULA (HOCL_ID ASC);

CREATE INDEX CNCR_FCIN_FK ON FICHA_INSCRIPCION (CNCR_ID ASC);

CREATE UNIQUE INDEX PK_ITINERARIO_MALLA_MATERIA ON ITINERARIO_MALLA_MATERIA (ITMLMT_ID ASC);

CREATE INDEX CHHR_ASEV_FK ON ASIGNACION_EVALUADOR (CRHR_ID ASC);

CREATE UNIQUE INDEX PK_MALLA_CURRICULAR_MATERIA ON MALLA_CURRICULAR_MATERIA (MLCRMT_ID ASC);

CREATE INDEX CRR_ITN_FK ON ITINERARIO (CRR_ID ASC);

CREATE INDEX FCMT_CMPA_FK ON COMPROBANTE_PAGO (FCMT_ID ASC);

CREATE INDEX UBC_CNCR_FK ON CONFIGURACION_CARRERA (UBC_ID ASC);

CREATE UNIQUE INDEX PK_DETALLE_TRAMITE_CONTRATO ON DETALLE_TRAMITE_CONTRATO (DTTRCN_ID ASC);

CREATE INDEX UNFR_MLCRMT_FK ON MALLA_CURRICULAR_MATERIA (UNFR_ID ASC);

CREATE INDEX ASEV_CNT_FK ON CONTENIDO (ASEV_ID ASC);

CREATE INDEX UBC_DPN_FK ON DEPENDENCIA (UBC_ID ASC);

CREATE INDEX DRC_CNCR_FK ON CONFIGURACION_CARRERA (DRC_ID ASC);

CREATE INDEX MTR_CNV_FK ON CONVALIDACION (MTR_ID ASC);

CREATE INDEX FCES_GRT_FK ON GRATUIDAD (FCES_ID ASC);

CREATE UNIQUE INDEX PK_ARANCEL ON ARANCEL (ARN_ID ASC);

CREATE INDEX FCIN_FCES_FK ON FICHA_ESTUDIANTE (FCIN_ID ASC);

CREATE UNIQUE INDEX PK_EVALUACION ON EVALUACION (EVA_ID ASC);

CREATE INDEX NVCM_CMPS_FK ON COMPETENCIA_PUESTO (NVCM_ID ASC);

CREATE INDEX TIGR_ARN_FK ON ARANCEL (TIGR_ID ASC);

CREATE UNIQUE INDEX PK_CONOCIMIENTO_PUESTO ON CONOCIMIENTO_PUESTO (CNPS_ID ASC);

CREATE INDEX DTMT_CSDTMT_FK ON CAUSAL_DETALLE_MATRICULA (DTMT_ID ASC);

CREATE UNIQUE INDEX PK_INSTITUCION_ACADEMICA ON INSTITUCION_ACADEMICA (INAC_ID ASC);

CREATE UNIQUE INDEX PK_COMPROBANTE_PAGO ON COMPROBANTE_PAGO (CMPA_ID ASC);

CREATE UNIQUE INDEX PK_CAUSAL ON CAUSAL (CSL_ID ASC);

CREATE INDEX TPCN_FRCN_FK ON FORMATO_CONTRATO (TICN_ID ASC);

CREATE INDEX UBC_INAC_FK ON INSTITUCION_ACADEMICA (UBC_ID ASC);

CREATE INDEX NVIN_INPS_FK ON INSTRUCCION_PUESTO (NVIN_ID ASC);

CREATE UNIQUE INDEX PK_CONOCIMIENTO ON CONOCIMIENTO (CNC_ID ASC);

CREATE INDEX PRAC_FCIN_FK ON FICHA_INSCRIPCION (PRAC_ID ASC);

CREATE INDEX ARN_DTMT_FK ON DETALLE_MATRICULA (ARN_ID ASC);

CREATE INDEX PRTRCN_CNCN_FK ON CANDIDATO_CONTRATO (PRTRCN_ID ASC);

CREATE UNIQUE INDEX PK_DETALLE_PUESTO ON DETALLE_PUESTO (DTPS_ID ASC);

CREATE INDEX ITN_ITDP_FK ON ITINERARIO_MALLA_MATERIA (ITN_ID ASC);

CREATE UNIQUE INDEX PK_ASIGNA_PRESUPUESTO ON ASIGNA_PRESUPUESTO (ASPR_ID ASC);

CREATE INDEX PS_INPS_FK ON INSTRUCCION_PUESTO (PST_ID ASC);

CREATE INDEX ACES_ACPS_FK ON ACTIVIDAD_PUESTO (ACES_ID ASC);

CREATE INDEX DPN_DPN_FK ON DEPENDENCIA (DPN_SUB_ID ASC);

CREATE INDEX CNC_CNPS_FK ON CONOCIMIENTO_PUESTO (CNC_ID ASC);

CREATE UNIQUE INDEX PK_CONTROL_PROCESO ON CONTROL_PROCESO (CNPR_ID ASC);

CREATE INDEX REL_CRR_CNCR_FK ON CONFIGURACION_CARRERA (CRR_ID ASC);

CREATE INDEX EDF_ALA_FK ON AULA (EDF_ID ASC);

CREATE UNIQUE INDEX PK_INFORME_TECNICO ON INFORME_TECNICO (INTC_ID ASC);

CREATE UNIQUE INDEX PK_CRONOGRAMA ON CRONOGRAMA (CRN_ID ASC);

CREATE INDEX MDL_CNCR_FK ON CONFIGURACION_CARRERA (MDL_ID ASC);

CREATE UNIQUE INDEX PK_FUNCION_TIPO_EVALUACION ON FUNCION_TIPO_EVALUACION (FNCTPEV_ID ASC);

CREATE INDEX TIFN_CNT_FK ON CONTRATO (TIFN_ID ASC);

CREATE UNIQUE INDEX PK_HORA_CLASE_AULA ON HORA_CLASE_AULA (HOCLAL_ID ASC);

CREATE INDEX PRTRCN_ASPR_FK ON ASIGNA_PRESUPUESTO (PRTRCN_ID ASC);

CREATE INDEX PS_CMPS_FK ON COMPETENCIA_PUESTO (PST_ID ASC);

CREATE UNIQUE INDEX PK_GRATUIDAD ON GRATUIDAD (GRT_ID ASC);

CREATE INDEX MTR_MLCRMT_FK ON MALLA_CURRICULAR_MATERIA (MTR_ID ASC);

CREATE UNIQUE INDEX PK_MALLA_CURRICULAR ON MALLA_CURRICULAR (MLCR_ID ASC);

CREATE INDEX TPCN_CNT_FK ON CONTRATO (TICN_ID ASC);

CREATE INDEX PRS_FCDC_FK ON FICHA_DOCENTE (PRS_ID ASC);

CREATE UNIQUE INDEX PK_ETNIA ON ETNIA (ETN_ID ASC);

CREATE INDEX MLCRPR_HRAC_FK ON HORARIO_ACADEMICO (MLCRPR_ID ASC);

CREATE INDEX PRS_FCES_FK ON FICHA_ESTUDIANTE (PRS_ID ASC);

CREATE UNIQUE INDEX PK_DURACION ON DURACION (DRC_ID ASC);

CREATE INDEX PST_FNPS_FK ON FUNCION_PUESTO (PST_ID ASC);

CREATE INDEX CRN_CRPRFL_FK ON CRONOGRAMA_PROCESO_FLUJO (CRN_ID ASC);

CREATE INDEX EVEV_ASEV_FK ON ASIGNACION_EVALUADOR (EVEV_ID ASC);

CREATE UNIQUE INDEX PK_CARRERA_AREA ON CARRERA_AREA (CRAR_ID ASC);

CREATE UNIQUE INDEX PK_GRUPO_OCUPACIONAL ON GRUPO_OCUPACIONAL (GROC_ID ASC);

CREATE INDEX TTL_CNCR_FK ON CONFIGURACION_CARRERA (TTL_ID ASC);

CREATE UNIQUE INDEX PK_CAMPO_FORMACION ON CAMPO_FORMACION (CMFR_ID ASC);

CREATE INDEX TRM_DTTRCN_FK ON DETALLE_TRAMITE_CONTRATO (TRM_ID ASC);

CREATE UNIQUE INDEX PK_FUNCION_PUESTO ON FUNCION_PUESTO (FNPS_ID ASC);

CREATE UNIQUE INDEX PK_MATERIA_INTERCAMBIO ON MATERIA_INTERCAMBIO (MTIN_ID ASC);

CREATE INDEX CSL_CSDTMT_FK ON CAUSAL_DETALLE_MATRICULA (CSL_ID ASC);

CREATE INDEX DPN_EDF_FK ON EDIFICIO (DPN_ID ASC);

CREATE INDEX MLCR_MLPR_FK ON MALLA_PERIODO (MLCR_ID ASC);

CREATE INDEX TIFRML_MLCR_FK ON MALLA_CURRICULAR (TIFRML_ID ASC);

CREATE UNIQUE INDEX PK_MATERIA ON MATERIA (MTR_ID ASC);

CREATE UNIQUE INDEX PK_AULA ON AULA (ALA_ID ASC);

CREATE UNIQUE INDEX PK_CONVALIDACION ON CONVALIDACION (CNV_ID ASC);

CREATE INDEX PST_ACPS_FK ON ACTIVIDAD_PUESTO (PST_ID ASC);

CREATE INDEX CRR_CRIN_FK ON CARRERA_INTERCAMBIO (CRR_ID ASC);

CREATE INDEX PST_CNPS_FK ON CONOCIMIENTO_PUESTO (PST_ID ASC);

CREATE INDEX EV_CN_FK ON CONTENIDO (EVA_ID ASC);

CREATE INDEX ALA_HOCLAL_FK ON HORA_CLASE_AULA (ALA_ID ASC);

CREATE UNIQUE INDEX PK_ITINERARIO ON ITINERARIO (ITN_ID ASC);

CREATE INDEX PRAC_CRN_FK ON CRONOGRAMA (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_CRONOGRAMA_PROCESO_FLUJO ON CRONOGRAMA_PROCESO_FLUJO (CRPRFL_ID ASC);

CREATE UNIQUE INDEX PK_COMPETENCIA ON COMPETENCIA (CMP_ID ASC);

CREATE INDEX FCMT_GRT_FK ON GRATUIDAD (FCMT_ID ASC);

CREATE UNIQUE INDEX PK_FICHA_INSCRIPCION ON FICHA_INSCRIPCION (FCIN_ID ASC);

CREATE UNIQUE INDEX PK_FUNCION_CARGA_HORARIA ON FUNCION_CARGA_HORARIA (FNCRHR_ID ASC);

CREATE UNIQUE INDEX PK_COREQUISITO ON COREQUISITO (CRQ_ID ASC);

CREATE UNIQUE INDEX PK_AREA_CONOCIMIENTO ON AREA_CONOCIMIENTO (ARCN_ID ASC);

CREATE INDEX FNC_FNPS_FK ON FUNCION_PUESTO (FNC_ID ASC);

CREATE UNIQUE INDEX PK_APRUEBA_SOLICITUD ON APRUEBA_SOLICITUD (APSL_ID ASC);

CREATE INDEX PRTRCN_INTE_FK ON INFORME_TECNICO (PRTRCN_ID ASC);

CREATE INDEX HOCLAL_HRAC_FK ON HORARIO_ACADEMICO (HOCLAL_ID ASC);

CREATE UNIQUE INDEX PK_INSTRUCCION_PUESTO ON INSTRUCCION_PUESTO (INPS_ID ASC);

CREATE UNIQUE INDEX PK_ASIGNACION_EVALUADOR ON ASIGNACION_EVALUADOR (ASEV_ID ASC);

CREATE INDEX INAC_FCES_FK ON FICHA_ESTUDIANTE (INAC_ID ASC);

CREATE INDEX PRTRCN_APSL_FK ON APRUEBA_SOLICITUD (PRTRCN_ID ASC);

CREATE INDEX CRIN_MTIN_FK ON MATERIA_INTERCAMBIO (CRIN_ID ASC);

CREATE UNIQUE INDEX PK_HORA_CLASE ON HORA_CLASE (HOCL_ID ASC);

CREATE INDEX FCES_DTPS_FK ON DETALLE_PUESTO (FCES_ID ASC);

CREATE INDEX MTR_MTRQ_FK ON MATERIA_REQUISITO (MTR_ID ASC);

CREATE INDEX RLLB_DTPS_FK ON DETALLE_PUESTO (RLLB_ID ASC);

CREATE UNIQUE INDEX PK_DETALLE_CARGA_HORARIA ON DETALLE_CARGA_HORARIA (DTCRHR_ID ASC);

CREATE INDEX PRAC_EVA_FK ON EVALUACION (PRAC_ID ASC);

CREATE INDEX GRP_MTR_FK ON MATERIA (GRP_ID ASC);

CREATE INDEX PLCR_FCMT_FK ON FICHA_MATRICULA (PLCR_ID ASC);

CREATE UNIQUE INDEX PK_ACTIVIDAD_ESENCIAL ON ACTIVIDAD_ESENCIAL (ACES_ID ASC);

CREATE INDEX PRS_FCEM_FK ON FICHA_EMPLEADO (PRS_ID ASC);

CREATE INDEX FCIN_CRIN_FK ON CARRERA_INTERCAMBIO (FCIN_ID ASC);

CREATE INDEX NVL_SUB_FK ON MALLA_CURRICULAR_MATERIA (NVL_SUB_ID ASC);

CREATE INDEX DPN_CRR_FK ON CARRERA (DPN_ID ASC);

CREATE UNIQUE INDEX PK_DETALLE_MATRICULA ON DETALLE_MATRICULA (DTMT_ID ASC);

CREATE INDEX RCES_CLF_FK ON CALIFICACION (RCES_ID ASC);

CREATE INDEX CRR_MTR_FK ON MATERIA (CRR_ID ASC);

CREATE UNIQUE INDEX PK_EDIFICIO ON EDIFICIO (EDF_ID ASC);

CREATE INDEX TPEV_EV_FK ON EVALUACION (TPEV_ID ASC);

CREATE INDEX NVL_MLCRMT_FK ON MALLA_CURRICULAR_MATERIA (NVL_ID ASC);

CREATE UNIQUE INDEX PK_CALIFICACION ON CALIFICACION (CLF_ID ASC);

CREATE UNIQUE INDEX PK_GRUPO ON GRUPO (GRP_ID ASC);

CREATE INDEX USRO_FCIN_FK ON FICHA_INSCRIPCION (USRO_ID ASC);

CREATE UNIQUE INDEX PK_HORARIO_FUNCION ON HORARIO_FUNCION (HRFN_ID ASC);

CREATE UNIQUE INDEX PK_HORARIO_ACADEMICO ON HORARIO_ACADEMICO (HRAC_ID ASC);

CREATE UNIQUE INDEX PK_FUNCION ON FUNCION (FNC_ID ASC);

CREATE INDEX TISE_CNCR_FK ON CONFIGURACION_CARRERA (TISE_ID ASC);

CREATE INDEX FNEV_FNTPEV_FK ON FUNCION_TIPO_EVALUACION (FNEV_ID ASC);

CREATE UNIQUE INDEX PK_CARRERA_INTERCAMBIO ON CARRERA_INTERCAMBIO (CRIN_ID ASC);

CREATE UNIQUE INDEX PK_FICHA_ESTUDIANTE ON FICHA_ESTUDIANTE (FCES_ID ASC);

CREATE INDEX FCES_FCMT_FK ON FICHA_MATRICULA (FCES_ID ASC);

CREATE INDEX MLCRPR_DTMT_FK ON DETALLE_MATRICULA (MLCRPR_ID ASC);

CREATE INDEX MDL_ARN_FK ON ARANCEL (MDL_ID ASC);

CREATE UNIQUE INDEX PK_FICHA_DOCENTE ON FICHA_DOCENTE (FCDC_ID ASC);

CREATE INDEX MTR_MTIN_FK ON MATERIA_INTERCAMBIO (MTR_ID ASC);

CREATE INDEX MTR_CRQ_CRQ_FK ON COREQUISITO (MTR_COREQUISITO_ID ASC);

CREATE UNIQUE INDEX PK_CONTENIDO ON CONTENIDO (CNTN_ID ASC);

CREATE UNIQUE INDEX PK_DESTREZA ON DESTREZA (DST_ID ASC);

CREATE INDEX CNT_DTTRCN_FK ON DETALLE_TRAMITE_CONTRATO (CNT_ID ASC);

CREATE INDEX TPEV_FNTPEV_FK ON FUNCION_TIPO_EVALUACION (TPEV_ID ASC);

CREATE INDEX NCPRCR_MTR_FK ON MATERIA (NCPRCR_ID ASC);

CREATE UNIQUE INDEX PK_CONTRATO ON CONTRATO (CNT_ID ASC);

CREATE INDEX DST_DSPS_FK ON DESTREZA_PUESTO (DST_ID ASC);

CREATE INDEX TIDC_DTPS_FK ON DETALLE_PUESTO (TIDC_ID ASC);

CREATE UNIQUE INDEX PK_ACTIVIDAD_PUESTO ON ACTIVIDAD_PUESTO (ACPS_ID ASC);

ALTER TABLE CALIFICACION_MODULO ADD CONSTRAINT PK_CALIFICACION_MODUL0 PRIMARY KEY (CLMD_ID);

ALTER TABLE EXCEDENTE ADD CONSTRAINT PK_EXCEDENTE PRIMARY KEY (EXC_ID);

ALTER TABLE AULA ADD CONSTRAINT PK_AULA PRIMARY KEY (ALA_ID);

ALTER TABLE FICHA_EMPLEADO ADD CONSTRAINT PK_FICHA_EMPLEADO PRIMARY KEY (FCEM_ID);

ALTER TABLE EVALUACION ADD CONSTRAINT PK_EVALUACION PRIMARY KEY (EVA_ID);

ALTER TABLE CONOCIMIENTO ADD CONSTRAINT PK_CONOCIMIENTO PRIMARY KEY (CNC_ID);

ALTER TABLE COMPETENCIA_PUESTO ADD CONSTRAINT PK_COMPETENCIA_PUESTO PRIMARY KEY (CMPS_ID);

ALTER TABLE CONTRATO ADD CONSTRAINT PK_CONTRATO PRIMARY KEY (CNT_ID);

ALTER TABLE FORMATO_CONTRATO ADD CONSTRAINT PK_FORMATO_CONTRATO PRIMARY KEY (FRCN_ID);

ALTER TABLE HORARIO_ACADEMICO ADD CONSTRAINT PK_HORARIO_ACADEMICO PRIMARY KEY (HRAC_ID);

ALTER TABLE ETNIA ADD CONSTRAINT PK_ETNIA PRIMARY KEY (ETN_ID);

ALTER TABLE CARRERA_AREA ADD CONSTRAINT PK_CARRERA_AREA PRIMARY KEY (CRAR_ID);

ALTER TABLE FUNCION_TIPO_EVALUACION ADD CONSTRAINT PK_FUNCION_TIPO_EVALUACION PRIMARY KEY (FNCTPEV_ID);

ALTER TABLE FICHA_ESTUDIANTE ADD CONSTRAINT PK_FICHA_ESTUDIANTE PRIMARY KEY (FCES_ID);

ALTER TABLE CALIFICACION ADD CONSTRAINT PK_CALIFICACION PRIMARY KEY (CLF_ID);

ALTER TABLE ARANCEL ADD CONSTRAINT PK_ARANCEL PRIMARY KEY (ARN_ID);

ALTER TABLE FUNCION_PUESTO ADD CONSTRAINT PK_FUNCION_PUESTO PRIMARY KEY (FNPS_ID);

ALTER TABLE ASIGNACION_EVALUADOR ADD CONSTRAINT PK_ASIGNACION_EVALUADOR PRIMARY KEY (ASEV_ID);

ALTER TABLE FICHA_DOCENTE ADD CONSTRAINT PK_FICHA_DOCENTE PRIMARY KEY (FCDC_ID);

ALTER TABLE GRUPO ADD CONSTRAINT PK_GRUPO PRIMARY KEY (GRP_ID);

ALTER TABLE DETALLE_CARGA_HORARIA ADD CONSTRAINT PK_DETALLE_CARGA_HORARIA PRIMARY KEY (DTCRHR_ID);

ALTER TABLE CAUSAL_DETALLE_MATRICULA ADD CONSTRAINT PK_CAUSAL_DETALLE_MATRICULA PRIMARY KEY (CSDTMT_ID);

ALTER TABLE COMPETENCIA ADD CONSTRAINT PK_COMPETENCIA PRIMARY KEY (CMP_ID);

ALTER TABLE ITINERARIO_MALLA_MATERIA ADD CONSTRAINT PK_ITINERARIO_MALLA_MATERIA PRIMARY KEY (ITMLMT_ID);

ALTER TABLE GRATUIDAD ADD CONSTRAINT PK_GRATUIDAD PRIMARY KEY (GRT_ID);

ALTER TABLE DESTREZA_PUESTO ADD CONSTRAINT PK_DESTREZA_PUESTO PRIMARY KEY (DSPS_ID);

ALTER TABLE FUNCION ADD CONSTRAINT PK_FUNCION PRIMARY KEY (FNC_ID);

ALTER TABLE INSTITUCION_ACADEMICA ADD CONSTRAINT PK_INSTITUCION_ACADEMICA PRIMARY KEY (INAC_ID);

ALTER TABLE CARGA_HORARIA_CONTRATO ADD CONSTRAINT PK_CARGA_HORARIA_CONTRATO PRIMARY KEY (CRHRCN_ID);

ALTER TABLE CONTROL_PROCESO ADD CONSTRAINT PK_CONTROL_PROCESO PRIMARY KEY (CNPR_ID);

ALTER TABLE HORA_CLASE_AULA ADD CONSTRAINT PK_HORA_CLASE_AULA PRIMARY KEY (HOCLAL_ID);

ALTER TABLE GRUPO_OCUPACIONAL ADD CONSTRAINT PK_GRUPO_OCUPACIONAL PRIMARY KEY (GROC_ID);

ALTER TABLE CAUSAL ADD CONSTRAINT PK_CAUSAL PRIMARY KEY (CSL_ID);

ALTER TABLE ITINERARIO ADD CONSTRAINT PK_ITINERARIO PRIMARY KEY (ITN_ID);

ALTER TABLE CARGA_HORARIA ADD CONSTRAINT PK_CARGA_HORARIA PRIMARY KEY (CRHR_ID);

ALTER TABLE MATERIA_INTERCAMBIO ADD CONSTRAINT PK_MATERIA_INTERCAMBIO PRIMARY KEY (MTIN_ID);

ALTER TABLE AREA_CONOCIMIENTO ADD CONSTRAINT PK_AREA_CONOCIMIENTO PRIMARY KEY (ARCN_ID);

ALTER TABLE COREQUISITO ADD CONSTRAINT PK_COREQUISITO PRIMARY KEY (CRQ_ID);

ALTER TABLE CARRERA ADD CONSTRAINT PK_CARRERA PRIMARY KEY (CRR_ID);

ALTER TABLE EVALUADOR_EVALUADO ADD CONSTRAINT PK_EVALUADOR_EVALUADO PRIMARY KEY (EVEV_ID);

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT PK_CONFIGURACION_CARRERA PRIMARY KEY (CNCR_ID);

ALTER TABLE HORARIO_FUNCION ADD CONSTRAINT PK_HORARIO_FUNCION PRIMARY KEY (HRFN_ID);

ALTER TABLE FICHA_INSCRIPCION ADD CONSTRAINT PK_FICHA_INSCRIPCION PRIMARY KEY (FCIN_ID);

ALTER TABLE CONOCIMIENTO_PUESTO ADD CONSTRAINT PK_CONOCIMIENTO_PUESTO PRIMARY KEY (CNPS_ID);

ALTER TABLE EDIFICIO ADD CONSTRAINT PK_EDIFICIO PRIMARY KEY (EDF_ID);

ALTER TABLE APRUEBA_SOLICITUD ADD CONSTRAINT PK_APRUEBA_SOLICITUD PRIMARY KEY (APSL_ID);

ALTER TABLE HORA_CLASE ADD CONSTRAINT PK_HORA_CLASE PRIMARY KEY (HOCL_ID);

ALTER TABLE CRONOGRAMA ADD CONSTRAINT PK_CRONOGRAMA PRIMARY KEY (CRN_ID);

ALTER TABLE CARRERA_INTERCAMBIO ADD CONSTRAINT PK_CARRERA_INTERCAMBIO PRIMARY KEY (CRIN_ID);

ALTER TABLE CONTENIDO ADD CONSTRAINT PK_CONTENIDO PRIMARY KEY (CNTN_ID);

ALTER TABLE DESTREZA ADD CONSTRAINT PK_DESTREZA PRIMARY KEY (DST_ID);

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT PK_MALLA_CURRICULAR_MATERIA PRIMARY KEY (MLCRMT_ID);

ALTER TABLE ACTIVIDAD_ESENCIAL ADD CONSTRAINT PK_ACTIVIDAD_ESENCIAL PRIMARY KEY (ACES_ID);

ALTER TABLE DETALLE_MATRICULA ADD CONSTRAINT PK_DETALLE_MATRICULA PRIMARY KEY (DTMT_ID);

ALTER TABLE ASIGNA_PRESUPUESTO ADD CONSTRAINT PK_ASIGNA_PRESUPUESTO PRIMARY KEY (ASPR_ID);

ALTER TABLE CRONOGRAMA_PROCESO_FLUJO ADD CONSTRAINT PK_CRONOGRAMA_PROCESO_FLUJO PRIMARY KEY (CRPRFL_ID);

ALTER TABLE COMPROBANTE_PAGO ADD CONSTRAINT PK_COMPROBANTE_PAGO PRIMARY KEY (CMPA_ID);

ALTER TABLE CAMPO_FORMACION ADD CONSTRAINT PK_CAMPO_FORMACION PRIMARY KEY (CMFR_ID);

ALTER TABLE DURACION ADD CONSTRAINT PK_DURACION PRIMARY KEY (DRC_ID);

ALTER TABLE DETALLE_TRAMITE_CONTRATO ADD CONSTRAINT PK_DETALLE_TRAMITE_CONTRATO PRIMARY KEY (DTTRCN_ID);

ALTER TABLE MATERIA ADD CONSTRAINT PK_MATERIA PRIMARY KEY (MTR_ID);

ALTER TABLE INFORME_TECNICO ADD CONSTRAINT PK_INFORME_TECNICO PRIMARY KEY (INTC_ID);

ALTER TABLE EXPERIENCIA_LABORAL_CONTR ADD CONSTRAINT PK_EXPERIENCIA_LABORAL_CONTR PRIMARY KEY (EXLBCN_ID);

ALTER TABLE MALLA_PERIODO ADD CONSTRAINT PK_MALLA_PERIODO PRIMARY KEY (MLPR_ID);

ALTER TABLE ACTIVIDAD_PUESTO ADD CONSTRAINT PK_ACTIVIDAD_PUESTO PRIMARY KEY (ACPS_ID);

ALTER TABLE MALLA_CURRICULAR_NIVEL ADD CONSTRAINT PK_MALLA_CURRICULAR_NIVEL PRIMARY KEY (MLCRNV_ID);

ALTER TABLE CANDIDATO_CONTRATO ADD CONSTRAINT PK_CANDIDATO_CONTRATO PRIMARY KEY (CNCN_ID);

ALTER TABLE FUNCION_CARGA_HORARIA ADD CONSTRAINT PK_FUNCION_CARGA_HORARIA PRIMARY KEY (FNCRHR_ID);

ALTER TABLE MALLA_CURRICULAR ADD CONSTRAINT PK_MALLA_CURRICULAR PRIMARY KEY (MLCR_ID);

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT PK_DETALLE_PUESTO PRIMARY KEY (DTPS_ID);

ALTER TABLE FUNCION_EVALUACION ADD CONSTRAINT PK_FUNCION_EVALUACION PRIMARY KEY (FNEV_ID);

ALTER TABLE INSTRUCCION_PUESTO ADD CONSTRAINT PK_INSTRUCCION_PUESTO PRIMARY KEY (INPS_ID);

ALTER TABLE DEPENDENCIA ADD CONSTRAINT PK_DEPENDENCIA PRIMARY KEY (DPN_ID);

ALTER TABLE FICHA_MATRICULA ADD CONSTRAINT PK_FICHA_MATRICULA PRIMARY KEY (FCMT_ID);

ALTER TABLE CONVALIDACION ADD CONSTRAINT PK_CONVALIDACION PRIMARY KEY (CNV_ID);

ALTER TABLE MALLA_CURRICULAR_PARALELO ADD CONSTRAINT PK_MALLA_CURRICULAR_PARALELO PRIMARY KEY (MLCRPR_ID);

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_TTL_CNCR_TITULO FOREIGN KEY (TTL_ID)
	REFERENCES TITULO (TTL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE COREQUISITO ADD CONSTRAINT FK_COREQUIS_MTR_CRQ_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA_INTERCAMBIO ADD CONSTRAINT FK_MATERIA__CRIN_MT_CARRERA_ FOREIGN KEY (CRIN_ID)
	REFERENCES CARRERA_INTERCAMBIO (CRIN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONVALIDACION ADD CONSTRAINT FK_CONVALID_MLCRMT_CN_MALLA_CU FOREIGN KEY (MLCRMT_ID)
	REFERENCES MALLA_CURRICULAR_MATERIA (MLCRMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_MATRICULA ADD CONSTRAINT FK_DETALLE__MLCRPR_DT_MALLA_CU FOREIGN KEY (MLCRPR_ID)
	REFERENCES MALLA_CURRICULAR_PARALELO (MLCRPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_ESTUDIANTE ADD CONSTRAINT FK_FICHA_ES_PRS_FCES_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_CARGA_HORARIA ADD CONSTRAINT FK_DETALLE__CRHR_DTCR_CARGA_HO FOREIGN KEY (CRHR_ID)
	REFERENCES CARGA_HORARIA (CRHR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_NIVEL ADD CONSTRAINT FK_MLCR_MLCRNV FOREIGN KEY (MLCR_ID)
	REFERENCES MALLA_CURRICULAR (MLCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT FK_MALLA_CU_MLCR_MLCR_MALLA_CU FOREIGN KEY (MLCR_ID)
	REFERENCES MALLA_CURRICULAR (MLCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA_INTERCAMBIO ADD CONSTRAINT FK_MATERIA__MTR_MTRIN_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE INSTRUCCION_PUESTO ADD CONSTRAINT FK_INSTRUCC_NVIN_INPS_NIVEL_IN FOREIGN KEY (NVIN_ID)
	REFERENCES NIVEL_INSTRUCCION (NVIN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT FK_MALLA_CU_MTR_MLCRM_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CRONOGRAMA ADD CONSTRAINT FK_CRONOGRA_PRAC_CRN_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ARANCEL ADD CONSTRAINT FK_ARANCEL_MDL_ARN_MODALIDA FOREIGN KEY (MDL_ID)
	REFERENCES MODALIDAD (MDL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ASIGNA_PRESUPUESTO ADD CONSTRAINT FK_ASIGNA_P_PRTRCN_AS_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ACTIVIDAD_PUESTO ADD CONSTRAINT FK_ACTIVIDA_ACES_ACPS_ACTIVIDA FOREIGN KEY (ACES_ID)
	REFERENCES ACTIVIDAD_ESENCIAL (ACES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DESTREZA_PUESTO ADD CONSTRAINT FK_DESTREZA_DST_DSPS_DESTREZA FOREIGN KEY (DST_ID)
	REFERENCES DESTREZA (DST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_TRAMITE_CONTRATO ADD CONSTRAINT FK_DETALLE__DTTRCN_DT_DETALLE_ FOREIGN KEY (DTTRCN_SUB_ID)
	REFERENCES DETALLE_TRAMITE_CONTRATO (DTTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_TIFR_CNCR_TIPO_FOR FOREIGN KEY (TIFR_ID)
	REFERENCES TIPO_FORMACION (TIFR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE COMPROBANTE_PAGO ADD CONSTRAINT FK_COMPROBA_FCMT_CMPA_FICHA_MA FOREIGN KEY (FCMT_ID)
	REFERENCES FICHA_MATRICULA (FCMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__CRR_DTPS_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DEPENDENCIA ADD CONSTRAINT FK_DEPENDEN_DPN_DPN_DEPENDEN FOREIGN KEY (DPN_SUB_ID)
	REFERENCES DEPENDENCIA (DPN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__FCEM_DTPS_FICHA_EM FOREIGN KEY (FCEM_ID)
	REFERENCES FICHA_EMPLEADO (FCEM_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DEPENDENCIA ADD CONSTRAINT FK_DEPENDEN_UBC_DPN_UBICACIO FOREIGN KEY (UBC_ID)
	REFERENCES UBICACION (UBC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR ADD CONSTRAINT FK_MALLA_CU_CRR_MLCR_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_DRC_CNCR_DURACION FOREIGN KEY (DRC_ID)
	REFERENCES DURACION (DRC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE COMPETENCIA_PUESTO ADD CONSTRAINT FK_COMPETEN_PS_CMPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_ESTUDIANTE ADD CONSTRAINT FK_FICHA_ES_FCIN_FCES_FICHA_IN FOREIGN KEY (FCIN_ID)
	REFERENCES FICHA_INSCRIPCION (FCIN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTENIDO ADD CONSTRAINT FK_CONTENID_ASEV_CNT_ASIGNACI FOREIGN KEY (ASEV_ID)
	REFERENCES ASIGNACION_EVALUADOR (ASEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HORARIO_ACADEMICO ADD CONSTRAINT FK_HORARIO__HOCLAL_HR_HORA_CLA FOREIGN KEY (HOCLAL_ID)
	REFERENCES HORA_CLASE_AULA (HOCLAL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__TIDC_DTPS_TIPO_DOC FOREIGN KEY (TIDC_ID)
	REFERENCES TIPO_DOCUMENTO (TIDC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__FCDC_DTPS_FICHA_DO FOREIGN KEY (FCDC_ID)
	REFERENCES FICHA_DOCENTE (FCDC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE INSTRUCCION_PUESTO ADD CONSTRAINT FK_INSTRUCC_PS_INPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE AREA_CONOCIMIENTO ADD CONSTRAINT FK_AREA_CON_ARCN_ARCN_AREA_CON FOREIGN KEY (ARCN_SUB_ID)
	REFERENCES AREA_CONOCIMIENTO (ARCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FORMATO_CONTRATO ADD CONSTRAINT FK_FORMATO__TPCN_FRCN_TIPO_CON FOREIGN KEY (TICN_ID)
	REFERENCES TIPO_CONTRATO (TICN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CAUSAL ADD CONSTRAINT FK_CAUSAL_TICS_CSL_TIPO_CAU FOREIGN KEY (TICS_ID)
	REFERENCES TIPO_CAUSAL (TICS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARGA_HORARIA ADD CONSTRAINT FK_CARGA_HO_TIFNCRHR__TIPO_FUN FOREIGN KEY (TIFNCRHR_ID)
	REFERENCES TIPO_FUNCION_CARGA_HORARIA (TIFNCRHR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CAUSAL_DETALLE_MATRICULA ADD CONSTRAINT FK_CAUSAL_D_DTMT_CSDT_DETALLE_ FOREIGN KEY (DTMT_ID)
	REFERENCES DETALLE_MATRICULA (DTMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DESTREZA_PUESTO ADD CONSTRAINT FK_DESTREZA_PST_DSPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_NIVEL ADD CONSTRAINT FK_NVL_MLCRNV FOREIGN KEY (NVL_ID)
	REFERENCES NIVEL (NVL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_TRAMITE_CONTRATO ADD CONSTRAINT FK_DETALLE__CNT_DTTRC_CONTRATO FOREIGN KEY (CNT_ID)
	REFERENCES CONTRATO (CNT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_EMPLEADO ADD CONSTRAINT FK_FICHA_EM_PRS_FCEM_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CANDIDATO_CONTRATO ADD CONSTRAINT FK_CANDIDAT_PRS_CNCN_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE INSTITUCION_ACADEMICA ADD CONSTRAINT FK_INSTITUC_UBC_INAC_UBICACIO FOREIGN KEY (UBC_ID)
	REFERENCES UBICACION (UBC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CANDIDATO_CONTRATO ADD CONSTRAINT FK_CANDIDAT_PRTRCN_CN_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CALIFICACION_MODULO ADD CONSTRAINT FK_CLFMDL_RCES_CLMD_RECORD_E FOREIGN KEY (RCES_ID)
	REFERENCES RECORD_ESTUDIANTE (RCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARRERA_AREA ADD CONSTRAINT FK_CARRERA_ID FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_GRP_MTR_GRUPO FOREIGN KEY (GRP_ID)
	REFERENCES GRUPO (GRP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__PS_DTPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_MATRICULA ADD CONSTRAINT FK_FICHA_MA_FCES_FCMT_FICHA_ES FOREIGN KEY (FCES_ID)
	REFERENCES FICHA_ESTUDIANTE (FCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FUNCION_PUESTO ADD CONSTRAINT FK_FUNCION__FNC_FNPS_FUNCION FOREIGN KEY (FNC_ID)
	REFERENCES FUNCION (FNC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARRERA_INTERCAMBIO ADD CONSTRAINT FK_CARRERA__FCIN_CRRI_FICHA_IN FOREIGN KEY (FCIN_ID)
	REFERENCES FICHA_INSCRIPCION (FCIN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARGA_HORARIA_CONTRATO ADD CONSTRAINT FK_CARGA_HO_PRTRCN_CR_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE APRUEBA_SOLICITUD ADD CONSTRAINT FK_APRUEBA__PRTRCN_AP_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARRERA ADD CONSTRAINT FK_CARRERA_DPN_CRR_DEPENDEN FOREIGN KEY (DPN_ID)
	REFERENCES DEPENDENCIA (DPN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT FK_MALLA_CU_NVL_SUB_NIVEL FOREIGN KEY (NVL_SUB_ID)
	REFERENCES NIVEL (NVL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_ESTUDIANTE ADD CONSTRAINT FK_FICHA_ES_INAC_FCES_INSTITUC FOREIGN KEY (INAC_ID)
	REFERENCES INSTITUCION_ACADEMICA (INAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_VGN_CNCR_VIGENCIA FOREIGN KEY (VGN_ID)
	REFERENCES VIGENCIA (VGN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_TRAMITE_CONTRATO ADD CONSTRAINT FK_DETALLE__DTPS_DTTR_DETALLE_ FOREIGN KEY (DTPS_ID)
	REFERENCES DETALLE_PUESTO (DTPS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FUNCION_PUESTO ADD CONSTRAINT FK_FUNCION__PST_FNPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARGA_HORARIA ADD CONSTRAINT FK_CARGA_HO_DTPS_CRHR_DETALLE_ FOREIGN KEY (DTPS_ID)
	REFERENCES DETALLE_PUESTO (DTPS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ARANCEL ADD CONSTRAINT FK_ARANCEL_TIGR_ARN_TIPO_GRA FOREIGN KEY (TIGR_ID)
	REFERENCES TIPO_GRATUIDAD (TIGR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARRERA_AREA ADD CONSTRAINT FK_CARRERA_AREA_ID FOREIGN KEY (AREA_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FUNCION_TIPO_EVALUACION ADD CONSTRAINT FK_FUNCION__TPEV_FNTP_TIPO_EVA FOREIGN KEY (TPEV_ID)
	REFERENCES TIPO_EVALUACION (TPEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HORARIO_FUNCION ADD CONSTRAINT FK_HOCL_HRFN FOREIGN KEY (HOCL_ID)
	REFERENCES HORA_CLASE (HOCL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_PERIODO ADD CONSTRAINT FK_MALLA_PE_MLCR_MLPR_MALLA_CU FOREIGN KEY (MLCR_ID)
	REFERENCES MALLA_CURRICULAR (MLCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ACTIVIDAD_PUESTO ADD CONSTRAINT FK_ACTIVIDA_PST_ACPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTROL_PROCESO ADD CONSTRAINT FK_CONTROL__TIPR_CNPR_TIPO_PRO FOREIGN KEY (TIPR_ID)
	REFERENCES TIPO_PROCESO (TIPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HORARIO_ACADEMICO ADD CONSTRAINT FK_HORARIO__MLCRPR_HR_MALLA_CU FOREIGN KEY (MLCRPR_ID)
	REFERENCES MALLA_CURRICULAR_PARALELO (MLCRPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_PARALELO ADD CONSTRAINT FK_MALLA_CU_MLCRMT_ML_MALLA_CU FOREIGN KEY (MLCRMT_ID)
	REFERENCES MALLA_CURRICULAR_MATERIA (MLCRMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HORA_CLASE_AULA ADD CONSTRAINT FK_HORA_CLA_HOCL_HOCL_HORA_CLA FOREIGN KEY (HOCL_ID)
	REFERENCES HORA_CLASE (HOCL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE COMPETENCIA_PUESTO ADD CONSTRAINT FK_COMPETEN_NVCM_CMPS_NIVEL_CO FOREIGN KEY (NVCM_ID)
	REFERENCES NIVEL_COMPETENCIA (NVCM_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONOCIMIENTO_PUESTO ADD CONSTRAINT FK_CONOCIMI_PST_CNPS_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_CMFR_MTR_CAMPO_FO FOREIGN KEY (CMFR_ID)
	REFERENCES CAMPO_FORMACION (CMFR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR ADD CONSTRAINT FK_MALLA_CU_TIFRML_ML_TIPO_FOR FOREIGN KEY (TIFRML_ID)
	REFERENCES TIPO_FORMACION_MALLA (TIFRML_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_CRR_MTR_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE GRATUIDAD ADD CONSTRAINT FK_GRATUIDA_TIGR_GRT_TIPO_GRA FOREIGN KEY (TIGR_ID)
	REFERENCES TIPO_GRATUIDAD (TIGR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CRONOGRAMA_PROCESO_FLUJO ADD CONSTRAINT FK_CRONOGRA_CRN_CRPRF_CRONOGRA FOREIGN KEY (CRN_ID)
	REFERENCES CRONOGRAMA (CRN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_TIMT_MT_TIPO_MAT FOREIGN KEY (TIMT_ID)
	REFERENCES TIPO_MATERIA (TIMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_TRAMITE_CONTRATO ADD CONSTRAINT FK_DETALLE__TRM_DTTRC_TRAMITE FOREIGN KEY (TRM_ID)
	REFERENCES TRAMITE (TRM_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_TPCN_CNT_TIPO_CON FOREIGN KEY (TICN_ID)
	REFERENCES TIPO_CONTRATO (TICN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARGA_HORARIA ADD CONSTRAINT FK_CARGA_HO_MLCRPR_CR_MALLA_CU FOREIGN KEY (MLCRPR_ID)
	REFERENCES MALLA_CURRICULAR_PARALELO (MLCRPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_REL_CRR_C_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_MATRICULA ADD CONSTRAINT FK_DETALLE__CMPA_DTMT_COMPROBA FOREIGN KEY (CMPA_ID)
	REFERENCES COMPROBANTE_PAGO (CMPA_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_UBC_CNCR_UBICACIO FOREIGN KEY (UBC_ID)
	REFERENCES UBICACION (UBC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_PERIODO ADD CONSTRAINT FK_MALLA_PE_PRAC_MLPR_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARRERA_INTERCAMBIO ADD CONSTRAINT FK_CARRERA__CRR_CRIN_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE GRATUIDAD ADD CONSTRAINT FK_GRATUIDA_FCMT_GRT_FICHA_MA FOREIGN KEY (FCMT_ID)
	REFERENCES FICHA_MATRICULA (FCMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT FK_MALLA_CU_UNFR_MLCR_UNIDAD_F FOREIGN KEY (UNFR_ID)
	REFERENCES UNIDAD_FORMACION (UNFR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ITINERARIO_MALLA_MATERIA ADD CONSTRAINT FK_ITINERAR_MLCRMT_IT_MALLA_CU FOREIGN KEY (MLCRMT_ID)
	REFERENCES MALLA_CURRICULAR_MATERIA (MLCRMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_TIFN_CNT_TIPO_FIN FOREIGN KEY (TIFN_ID)
	REFERENCES TIPO_FINANCIAMIENTO (TIFN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EVALUACION ADD CONSTRAINT FK_EVALUACI_PRAC_EVA_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EDIFICIO ADD CONSTRAINT FK_EDIFICIO_DPN_EDF_DEPENDEN FOREIGN KEY (DPN_ID)
	REFERENCES DEPENDENCIA (DPN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CALIFICACION ADD CONSTRAINT FK_CALIFICA_RCES_CLF_RECORD_E FOREIGN KEY (RCES_ID)
	REFERENCES RECORD_ESTUDIANTE (RCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE INFORME_TECNICO ADD CONSTRAINT FK_INFORME__PRTRCN_IN_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ASIGNACION_EVALUADOR ADD CONSTRAINT FK_ASIGNACI_EVEV_ASEV_EVALUADO FOREIGN KEY (EVEV_ID)
	REFERENCES EVALUADOR_EVALUADO (EVEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_NCPRCR_MT_NUCLEO_P FOREIGN KEY (NCPRCR_ID)
	REFERENCES NUCLEO_PROBLEMICO_CARRERA (NCPRCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CRONOGRAMA_PROCESO_FLUJO ADD CONSTRAINT FK_CRONOGRA_PRFL_CRPR_PROCESO_ FOREIGN KEY (PRFL_ID)
	REFERENCES PROCESO_FLUJO (PRFL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__RLLB_DTPS_RELACION FOREIGN KEY (RLLB_ID)
	REFERENCES RELACION_LABORAL (RLLB_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTROL_PROCESO ADD CONSTRAINT FK_CONTROL__USRO_CNPR_USUARIO_ FOREIGN KEY (USRO_ID)
	REFERENCES USUARIO_ROL (USRO_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ITINERARIO ADD CONSTRAINT FK_ITINERAR_CRR_ITN_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ITINERARIO_MALLA_MATERIA ADD CONSTRAINT FK_ITINERAR_ITN_ITDP_ITINERAR FOREIGN KEY (ITN_ID)
	REFERENCES ITINERARIO (ITN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_PARALELO ADD CONSTRAINT FK_MALLA_CU_PRL_MLCRP_PARALELO FOREIGN KEY (PRL_ID)
	REFERENCES PARALELO (PRL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ASIGNACION_EVALUADOR ADD CONSTRAINT FK_ASIGNACI_CHHR_ASEV_CARGA_HO FOREIGN KEY (CRHR_ID)
	REFERENCES CARGA_HORARIA (CRHR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CARGA_HORARIA ADD CONSTRAINT FK_CARGA_HO_PRAC_CRHR_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_MDL_CNCR_MODALIDA FOREIGN KEY (MDL_ID)
	REFERENCES MODALIDAD (MDL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EXPERIENCIA_LABORAL_CONTR ADD CONSTRAINT FK_EXPERIEN_CNCN_EXLB_CANDIDAT FOREIGN KEY (CNCN_ID)
	REFERENCES CANDIDATO_CONTRATO (CNCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA ADD CONSTRAINT FK_MATERIA_MTR_SUB_M_MATERIA FOREIGN KEY (MTR_SUB_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTENIDO ADD CONSTRAINT FK_CONTENID_EV_CN_EVALUACI FOREIGN KEY (EVA_ID)
	REFERENCES EVALUACION (EVA_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_MATRICULA ADD CONSTRAINT FK_FICHA_MA_PLCR_FCMT_PLANIFIC FOREIGN KEY (PLCR_ID)
	REFERENCES PLANIFICACION_CRONOGRAMA (PLCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EVALUADOR_EVALUADO ADD CONSTRAINT FK_EVALUADO_USRO_EVEV_USUARIO_ FOREIGN KEY (USRO_ID)
	REFERENCES USUARIO_ROL (USRO_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FUNCION_TIPO_EVALUACION ADD CONSTRAINT FK_FUNCION__FNEV_FNTP_FUNCION_ FOREIGN KEY (FNEV_ID)
	REFERENCES FUNCION_EVALUACION (FNEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_MATRICULA ADD CONSTRAINT FK_DETALLE__ARN_DTMT_ARANCEL FOREIGN KEY (ARN_ID)
	REFERENCES ARANCEL (ARN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EVALUACION ADD CONSTRAINT FK_EVALUACI_TPEV_EV_TIPO_EVA FOREIGN KEY (TPEV_ID)
	REFERENCES TIPO_EVALUACION (TPEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MALLA_CURRICULAR_MATERIA ADD CONSTRAINT FK_MALLA_CU_NVL_MLCRM_NIVEL FOREIGN KEY (NVL_ID)
	REFERENCES NIVEL (NVL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MATERIA_REQUISITO ADD CONSTRAINT FK_MATERIA__MTR_MTRQ_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HORA_CLASE_AULA ADD CONSTRAINT FK_HORA_CLA_ALA_HOCLA_AULA FOREIGN KEY (ALA_ID)
	REFERENCES AULA (ALA_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONTENIDO ADD CONSTRAINT FK_CONTENID_TPCN_FUNC_TPCN_FUN FOREIGN KEY (TPCNFNTPEV_ID)
	REFERENCES TPCN_FUNCION_TPEV (TPCNFNTPEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CAUSAL_DETALLE_MATRICULA ADD CONSTRAINT FK_CAUSAL_D_CSL_CSDTM_CAUSAL FOREIGN KEY (CSL_ID)
	REFERENCES CAUSAL (CSL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE FICHA_DOCENTE ADD CONSTRAINT FK_FICHA_DO_PRS_FCDC_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE GRATUIDAD ADD CONSTRAINT FK_GRATUIDA_FCES_GRT_FICHA_ES FOREIGN KEY (FCES_ID)
	REFERENCES FICHA_ESTUDIANTE (FCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE AULA ADD CONSTRAINT FK_AULA_EDF_ALA_EDIFICIO FOREIGN KEY (EDF_ID)
	REFERENCES EDIFICIO (EDF_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONOCIMIENTO_PUESTO ADD CONSTRAINT FK_CONOCIMI_CNC_CNPS_CONOCIMI FOREIGN KEY (CNC_ID)
	REFERENCES CONOCIMIENTO (CNC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE DETALLE_PUESTO ADD CONSTRAINT FK_DETALLE__FCES_DTPS_FICHA_ES FOREIGN KEY (FCES_ID)
	REFERENCES FICHA_ESTUDIANTE (FCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE GRUPO_OCUPACIONAL ADD CONSTRAINT FK_GRUPO_OC_RGM_GROC_REGIMEN FOREIGN KEY (RGM_ID)
	REFERENCES REGIMEN (RGM_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE COREQUISITO ADD CONSTRAINT FK_COREQUIS_MTR_CRQ_C_MATERIA FOREIGN KEY (MTR_COREQUISITO_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONFIGURACION_CARRERA ADD CONSTRAINT FK_CONFIGUR_TISE_CNCR_TIPO_SED FOREIGN KEY (TISE_ID)
	REFERENCES TIPO_SEDE (TISE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE CONVALIDACION ADD CONSTRAINT FK_CONVALID_MTR_CNV_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

