--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PUESTO_AREA_CONOCIMIENTO (
		PSARCN_ID NUMBER(6 , 0) NOT NULL,
		ARCN_ID NUMBER(38 , 0),
		PST_ID NUMBER(38 , 0)
	);

CREATE TABLE PORCENTAJE_GRATUIDAD (
		PRGR_ID NUMBER(6 , 0) NOT NULL,
		TIGR_ID NUMBER(38 , 0),
		PRGR_DESCRIPCION VARCHAR2(256),
		PRGR_VALOR NUMBER(6 , 2),
		PRGR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PROCESO_FLUJO (
		PRFL_ID NUMBER(6 , 0) NOT NULL,
		PRFL_DESCRIPCION VARCHAR2(256),
		PRFL_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PUESTO (
		PST_ID NUMBER(6 , 0) NOT NULL,
		PST_DENOMINACION VARCHAR2(256),
		PST_ESTADO NUMBER(38 , 0),
		PST_AMBITO NUMBER(38 , 0),
		PST_CODIGO VARCHAR2(256),
		PST_NIVEL NUMBER(38 , 0),
		PST_MISION VARCHAR2(512),
		PST_RESPONSABILIDAD VARCHAR2(512),
		PST_DESCRIPCION_EXPERIENCIA VARCHAR2(512),
		PST_INTERFAZ VARCHAR2(512),
		PST_FECHA_CREACION DATE,
		PST_NIVEL_RANGO_GRADUAL NUMBER(38 , 0),
		SER_ID NUMBER(38 , 0),
		GROC_ID NUMBER(38 , 0),
		TMDD_ID NUMBER(38 , 0),
		TIPS_ID NUMBER(38 , 0),
		GRD_ID NUMBER(38 , 0),
		NVJR_ID NUMBER(38 , 0),
		PST_TIPO_RMU NUMBER(38 , 0),
		PST_VALOR_HORA NUMBER(8 , 2),
		PST_CATEGORIA_DOCENTE NUMBER(6 , 0)
	);

CREATE TABLE PREREQUISITO (
		PRR_ID NUMBER(6 , 0) NOT NULL,
		MTR_ID NUMBER(38 , 0) NOT NULL,
		MTR_PREREQUISITO_ID NUMBER(38 , 0) NOT NULL,
		PRR_CODIGO NUMBER(38 , 0),
		PRR_DESCRIPCION VARCHAR2(256),
		PRR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PROCESO_CALIFICACION (
		PRCL_ID NUMBER(38 , 0) NOT NULL,
		CLF_ID NUMBER(38 , 0),
		PRCL_FECHA TIMESTAMP(11),
		PRCL_TIPO_PROCESO NUMBER(38 , 0),
		PRCL_OBSERVACION VARCHAR2(1024),
		PRCL_NOTA1 FLOAT(126),
		PRCL_NOTA2 FLOAT(126),
		PRCL_EXAMEN FLOAT(126),
		PRCL_SUPLETORIO FLOAT(126),
		PRCL_ASISTENCIA1 FLOAT(126),
		PRCL_ASISTENCIA2 FLOAT(126),
		PRCL_TOTAL_ASISTENCIA1 FLOAT(126),
		PRCL_TOTAL_ASISTENCIA2 FLOAT(126),
		PRCL_PROMEDIO_NOTAS FLOAT(126),
		PRCL_PROMEDIO_ASISTENCIA FLOAT(126),
		PRCL_ASISTENCIA_TOTAL FLOAT(126),
		PRCL_PARAM_RECUPERACION1 FLOAT(126),
		PRCL_PARAM_RECUPERACION2 FLOAT(126),
		PRCL_NOTA_FINAL_SEMESTRE FLOAT(126),
		PRCL_ASISTENCIA_DOCENTE1 FLOAT(126),
		PRCL_ASISTENCIA_DOCENTE2 FLOAT(126),
		PRCL_FECHA_NOTA2 TIMESTAMP(11),
		PRCL_FECHA_RECUPERACION TIMESTAMP(11),
		PRCL_OBSERVACION2 VARCHAR2(1024),
		PRCL_OBSERVACION3 VARCHAR2(1024),
		PRCL_SUMA_P1_P2 FLOAT(126),
		PRCL_ASISTENCIA_TOTAL_DOC FLOAT(126),
		CLMD_ID NUMBER(38 , 0)
	);

CREATE TABLE NIVEL_FORMACION (
		NVFR_ID NUMBER(6 , 0) NOT NULL,
		RGAC_ID NUMBER(38 , 0),
		NVFR_DESCRIPCION VARCHAR2(128)
	);

CREATE TABLE NIVEL (
		NVL_ID NUMBER(6 , 0) NOT NULL,
		NVL_DESCRIPCION VARCHAR2(50),
		NVL_ESTADO NUMBER(38 , 0),
		NVL_NUMERAL NUMBER(2 , 0)
	);

CREATE TABLE REQUISITO (
		RQS_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		RQS_PUBLICACIONES NUMBER(38 , 0),
		RQS_EXPERICIA_DOCENTE NUMBER(38 , 0),
		RQS_EXPERICIA_LABORAL NUMBER(38 , 0),
		RQS_CAPACITACION NUMBER(38 , 0),
		RQS_MECANIZADO_IESS NUMBER(38 , 0),
		RQS_DECLARACION_BIENES NUMBER(38 , 0),
		RQS_PLURIEMPLEO NUMBER(38 , 0),
		RQS_NEPOTISMO NUMBER(38 , 0),
		RQS_CERTIFICACION_BANCARIA NUMBER(38 , 0),
		RQS_CERTIFICADO_AFILIADO_IESS NUMBER(38 , 0),
		RQS_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PLANIFICACION_EVALUACION (
		PLEV_ID NUMBER NOT NULL,
		PLEV_FECHA_INICIO TIMESTAMP(11),
		PLEV_FECHA_FIN TIMESTAMP(11),
		PLEV_ESTADO NUMBER,
		EVL_ID NUMBER,
		PRFL_ID NUMBER
	);

CREATE TABLE REGIMEN_ACADEMICO (
		RGAC_ID NUMBER(6 , 0) NOT NULL,
		RGAC_DESCRIPCION VARCHAR2(32),
		RGAC_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PROCESO (
		PRC_ID NUMBER(6 , 0) NOT NULL,
		PRC_DESCRIPCION VARCHAR2(256)
	);

CREATE TABLE RELACION_LABORAL (
		RLLB_ID NUMBER(6 , 0) NOT NULL,
		RLLB_DESCRIPCION VARCHAR2(256),
		RLLB_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PLAN_TABLE (
		STATEMENT_ID VARCHAR2(30),
		PLAN_ID NUMBER,
		TIMESTAMP DATE,
		REMARKS VARCHAR2(4000),
		OPERATION VARCHAR2(30),
		OPTIONS VARCHAR2(255),
		OBJECT_NODE VARCHAR2(128),
		OBJECT_OWNER VARCHAR2(30),
		OBJECT_NAME VARCHAR2(30),
		OBJECT_ALIAS VARCHAR2(65),
		OBJECT_INSTANCE NUMBER(38 , 0),
		OBJECT_TYPE VARCHAR2(30),
		OPTIMIZER VARCHAR2(255),
		SEARCH_COLUMNS NUMBER,
		ID NUMBER(38 , 0),
		PARENT_ID NUMBER(38 , 0),
		DEPTH NUMBER(38 , 0),
		POSITION NUMBER(38 , 0),
		COST NUMBER(38 , 0),
		CARDINALITY NUMBER(38 , 0),
		BYTES NUMBER(38 , 0),
		OTHER_TAG VARCHAR2(255),
		PARTITION_START VARCHAR2(255),
		PARTITION_STOP VARCHAR2(255),
		PARTITION_ID NUMBER(38 , 0),
		OTHER null,
		DISTRIBUTION VARCHAR2(30),
		CPU_COST NUMBER(38 , 0),
		IO_COST NUMBER(38 , 0),
		TEMP_SPACE NUMBER(38 , 0),
		ACCESS_PREDICATES VARCHAR2(4000),
		FILTER_PREDICATES VARCHAR2(4000),
		PROJECTION VARCHAR2(4000),
		TIME NUMBER(38 , 0),
		QBLOCK_NAME VARCHAR2(30)
	);

CREATE TABLE PERSONA (
		PRS_ID NUMBER(6 , 0) NOT NULL,
		PRS_TIPO_IDENTIFICACION NUMBER(38 , 0),
		PRS_TIPO_IDENTIFICACION_SNIESE NUMBER(38 , 0),
		PRS_IDENTIFICACION VARCHAR2(13),
		PRS_PRIMER_APELLIDO VARCHAR2(32),
		PRS_SEGUNDO_APELLIDO VARCHAR2(32),
		PRS_NOMBRES VARCHAR2(50),
		PRS_SEXO NUMBER(38 , 0),
		PRS_SEXO_SNIESE NUMBER(38 , 0),
		PRS_MAIL_PERSONAL VARCHAR2(50),
		PRS_MAIL_INSTITUCIONAL VARCHAR2(50),
		PRS_TELEFONO VARCHAR2(10),
		PRS_FECHA_NACIMIENTO DATE,
		ETN_ID NUMBER(38 , 0),
		UBC_NACIMIENTO NUMBER(38 , 0),
		UBC_RESIDENCIA NUMBER(38 , 0),
		PRS_SECTOR_DOMICILIO VARCHAR2(256),
		PRS_CALLE_PRINCIPAL VARCHAR2(256),
		PRS_CALLE_SECUNDARIA VARCHAR2(256),
		PRS_NUMERO_CASA VARCHAR2(32),
		PRS_REFERENCIA_DOMICILIO VARCHAR2(256),
		PRS_CELULAR VARCHAR2(10),
		PRS_DISCAPACIDAD NUMBER(38 , 0),
		PRS_TIPO_DISCAPACIDAD NUMBER(38 , 0),
		PRS_PORCE_DISCAPACIDAD NUMBER(38 , 0),
		PRS_CARNET_CONADIS NUMBER(38 , 0),
		PRS_ESTADO_CIVIL NUMBER(38 , 0),
		PRS_FECHA_ACTUALIZACION_DATOS TIMESTAMP(11),
		PRS_NUM_CARNET_CONADIS VARCHAR2(10),
		PRS_FECHA_VINCULACION_SEGURO DATE,
		PRS_FECHA_REGISTRO_SEGURO TIMESTAMP(11),
		PRS_ESTADO_SEGURO NUMBER(38 , 0),
		PRS_FORMULARIO_SEGURO VARCHAR2(256),
		PRS_FECHA_FORMULARIO_SEGURO TIMESTAMP(11),
		PRS_EDAD NUMBER(38 , 0),
		PRS_CERTIFICADO_VOTACION VARCHAR2(512),
		PRS_TIPO_LICENCIA NUMBER(38 , 0),
		PRS_NUMERO_LICENCIA VARCHAR2(512),
		PRS_ETNIA_NACIONALIDAD NUMBER(38 , 0),
		PRS_ENFERMEDAD NUMBER(38 , 0),
		PRS_PERSONA_ESPECIAL NUMBER(38 , 0),
		PRS_TIPO_PERSONA_ESPECIAL NUMBER(38 , 0),
		PRS_ESPECIAL_DESCRIPCION VARCHAR2(1024),
		PRS_REFERENCIA VARCHAR2(1024),
		PRS_SECTOR VARCHAR2(1024)
	);

CREATE TABLE PROCESO_TRAMITE_CONTRATO (
		PRTRCN_ID NUMBER(6 , 0) NOT NULL,
		DTTRCN_ID NUMBER(38 , 0),
		PRTRCN_TIPO_PROCESO NUMBER(38 , 0),
		PRTRCN_FECHA_EJECUCION TIMESTAMP(11),
		PRTRCN_RESULTADO_PROCESO NUMBER(38 , 0)
	);

CREATE TABLE NIVEL_COMPETENCIA (
		NVCM_ID NUMBER(6 , 0) NOT NULL,
		CMP_ID NUMBER(38 , 0),
		NVCM_DESCRIPCION NUMBER(38 , 0),
		NVCM_COMPORTAMIENTO VARCHAR2(512)
	);

CREATE TABLE PROCESO_ESTUDIANTE (
		PRES_ID NUMBER(6 , 0) NOT NULL,
		FCES_ID NUMBER(38 , 0),
		PRES_DESCRIPCION VARCHAR2(256),
		PRES_TIPO NUMBER(38 , 0),
		PRES_ESTADO NUMBER(38 , 0),
		PRES_FECHA_EJECUCION TIMESTAMP(11)
	);

CREATE TABLE ROL_FLUJO_CARRERA (
		ROFLCR_ID NUMBER(6 , 0) NOT NULL,
		USRO_ID NUMBER(38 , 0),
		CRR_ID NUMBER(38 , 0),
		ROFLCR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE REGIMEN (
		RGM_ID NUMBER(6 , 0) NOT NULL,
		RGM_DESCRIPCION VARCHAR2(256),
		RGM_CODIGO VARCHAR2(8)
	);

CREATE TABLE NUCLEO_PROBLEMICO_CARRERA (
		NCPRCR_ID NUMBER(6 , 0) NOT NULL,
		CRR_ID NUMBER(38 , 0),
		NCPRCR_ESTADO NUMBER(38 , 0),
		NCPR_ID NUMBER(38 , 0)
	);

CREATE TABLE RECORD_ESTUDIANTE (
		RCES_ID NUMBER(38 , 0) NOT NULL,
		FCES_ID NUMBER(38 , 0),
		MLCRPR_ID NUMBER(38 , 0),
		RCES_ESTADO NUMBER(38 , 0),
		RCES_OBSERVACION VARCHAR2(512),
		RCES_INGRESO_NOTA NUMBER(38 , 0),
		RCES_INGRESO_NOTA2 NUMBER(38 , 0),
		RCES_INGRESO_NOTA3 NUMBER(38 , 0),
		RCES_ESTADO_TERCERA_MATRI NUMBER(38 , 0),
		RCES_USUARIO VARCHAR2(256),
		RCES_MODIFICACION TIMESTAMP(11),
		RCES_MODO_APROBACION NUMBER(38 , 0)
	);

CREATE TABLE SISTEMA_CALIFICACION (
		SSCL_ID NUMBER(6 , 0) NOT NULL,
		PRAC_ID NUMBER(38 , 0),
		TISSCL_ID NUMBER(38 , 0),
		SSCL_NOTA_MAXIMA FLOAT(126),
		SSCL_NOTA_MINIMA_APROBACION FLOAT(126),
		SSCL_NOTA_MINIMA_SUPLETORIO FLOAT(126),
		SSCL_PORCENTAJE_APROBACION FLOAT(126),
		SSCL_REDONDEO NUMBER(38 , 0),
		SSCL_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE PROYECCION (
		PRY_ID NUMBER(6 , 0) NOT NULL,
		EXC_ID NUMBER(38 , 0),
		MLCRMT_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		PRY_NUM_NUEVO NUMBER(38 , 0),
		PRY_NUM_REPETIDO NUMBER(38 , 0)
	);

CREATE TABLE REFERENCIA (
		RFR_ID NUMBER(6 , 0) NOT NULL,
		RFR_CEDULA VARCHAR2(256),
		RFR_NOMBRE VARCHAR2(512),
		RFR_DIRECCION VARCHAR2(512),
		RFR_PARENTESCO NUMBER(38 , 0),
		RFR_PORCENTAJE FLOAT(126),
		RFR_ESTADO NUMBER(38 , 0),
		PRS_ID NUMBER(38 , 0),
		RFR_TIPO NUMBER(38 , 0)
	);

CREATE TABLE MODALIDAD (
		MDL_ID NUMBER(6 , 0) NOT NULL,
		MDL_DESCRIPCION VARCHAR2(128)
	);

CREATE TABLE SERIE (
		SER_ID NUMBER(6 , 0) NOT NULL,
		PRC_ID NUMBER(38 , 0),
		SER_CODIGO VARCHAR2(8),
		SER_DESCRIPCION VARCHAR2(256)
	);

CREATE TABLE NUCLEO_PROBLEMICO (
		NCPR_ID NUMBER(6 , 0) NOT NULL,
		NCPR_DESCRIPCION VARCHAR2(512),
		NCPR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE NIVEL_APERTURA (
		NVAP_ID NUMBER(6 , 0) NOT NULL,
		NVAP_DESCRIPCION VARCHAR2(256),
		NVAP_NUMERAL NUMBER,
		CRR_ID NUMBER
	);

CREATE TABLE SOLICITUD_TERCERA_MATRICULA (
		SLTRMT_ID NUMBER(6 , 0) NOT NULL,
		CSL_ID NUMBER(38 , 0),
		RCES_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		SLTRMT_ESTADO NUMBER(38 , 0),
		SLTRMT_FECHA_SOLICITUD TIMESTAMP(11),
		SLTRMT_DOCUMENTO_RESOLUCION VARCHAR2(256),
		SLTRMT_OBSERVACION VARCHAR2(256),
		SLTRMT_DOCUMENTO_SOLICITUD VARCHAR2(256),
		SLTRMT_FECHA_VERIF_SOLICITUD TIMESTAMP(11),
		SLTRMT_FECHA_RESP_SOLICITUD TIMESTAMP(11),
		SLTRMT_TIPO NUMBER(38 , 0),
		SLTRMT_SUB_ID NUMBER(38 , 0),
		SLTRMT_FCES_ID NUMBER(38 , 0),
		SLTRMT_MTR_ID NUMBER(38 , 0),
		SLTRMT_OBSERVACION_FINAL VARCHAR2(512),
		SLTRMT_ESTADO_REGISTRO NUMBER(38 , 0)
	);

CREATE TABLE PARALELO (
		PRL_ID NUMBER(6 , 0) NOT NULL,
		CRR_ID NUMBER(38 , 0),
		PRAC_ID NUMBER(38 , 0),
		PRL_CODIGO VARCHAR2(128),
		PRL_DESCRIPCION VARCHAR2(256),
		PRL_ESTADO NUMBER(38 , 0),
		PRL_CUPO NUMBER(38 , 0),
		PRL_FECHA TIMESTAMP(11),
		PRL_INICIO_CLASE TIMESTAMP(11),
		PRL_FIN_CLASE TIMESTAMP(11)
	);

CREATE TABLE PLANIFICACION_CRONOGRAMA (
		PLCR_ID NUMBER(6 , 0) NOT NULL,
		CRPRFL_ID NUMBER(38 , 0),
		PLCR_ESTADO NUMBER(38 , 0),
		PLCR_FECHA_INICIO TIMESTAMP(11),
		PLCR_FECHA_FIN TIMESTAMP(11)
	);

CREATE TABLE ROL (
		ROL_ID NUMBER(6 , 0) NOT NULL,
		ROL_DESCRIPCION VARCHAR2(60),
		ROL_TIPO NUMBER(38 , 0),
		ROL_DETALLE VARCHAR2(1024)
	);

CREATE TABLE ROL_FLUJO_GRUPO (
		ROFLGR_ID NUMBER(6 , 0) NOT NULL,
		GRP_ID NUMBER(6 , 0) NOT NULL,
		USRO_ID NUMBER(6 , 0) NOT NULL,
		ROFLGR_ESTADO NUMBER(38 , 0),
		PRAC_ID NUMBER
	);

CREATE TABLE PERIODO_ACADEMICO (
		PRAC_ID NUMBER(6 , 0) NOT NULL,
		PRAC_DESCRIPCION VARCHAR2(256),
		PRAC_ESTADO NUMBER(38 , 0),
		PRAC_FECHA_INCIO DATE,
		PRAC_FECHA_FIN DATE,
		PRAC_TIPO NUMBER(38 , 0),
		PRAC_FK_PRAC_ID NUMBER
	);

CREATE TABLE NIVEL_INSTRUCCION (
		NVIN_ID NUMBER(6 , 0) NOT NULL,
		NVIN_DESCRIPCION VARCHAR2(256)
	);

CREATE UNIQUE INDEX PK_PROCESO_FLUJO ON PROCESO_FLUJO (PRFL_ID ASC);

CREATE UNIQUE INDEX PK_PROCESO_CALIFICACION ON PROCESO_CALIFICACION (PRCL_ID ASC);

CREATE UNIQUE INDEX PK_PERSONA ON PERSONA (PRS_ID ASC);

CREATE INDEX GROC_PST_FK ON PUESTO (GROC_ID ASC);

CREATE INDEX CRR_ROFLCR_FK ON ROL_FLUJO_CARRERA (CRR_ID ASC);

CREATE UNIQUE INDEX PK_PLANIFICACION_CRONOGRAMA ON PLANIFICACION_CRONOGRAMA (PLCR_ID ASC);

CREATE UNIQUE INDEX PK_PUESTO ON PUESTO (PST_ID ASC);

CREATE INDEX TIGR_PRGR_FK ON PORCENTAJE_GRATUIDAD (TIGR_ID ASC);

CREATE INDEX UBC_PRS_NCM_FK ON PERSONA (UBC_NACIMIENTO ASC);

CREATE UNIQUE INDEX PK_REGIMEN_ACADEMICO ON REGIMEN_ACADEMICO (RGAC_ID ASC);

CREATE INDEX CRR_PRL_FK ON PARALELO (CRR_ID ASC);

CREATE INDEX ARCN_PSARCN_FK ON PUESTO_AREA_CONOCIMIENTO (ARCN_ID ASC);

CREATE INDEX EXC_PRY_FK ON PROYECCION (EXC_ID ASC);

CREATE INDEX PRAC_SSCL_FK ON SISTEMA_CALIFICACION (PRAC_ID ASC);

CREATE INDEX DTTRCN_PRTRCN_FK ON PROCESO_TRAMITE_CONTRATO (DTTRCN_ID ASC);

CREATE UNIQUE INDEX PK_PARALELO ON PARALELO (PRL_ID ASC);

CREATE INDEX ETN_PRS_FK ON PERSONA (ETN_ID ASC);

CREATE INDEX PRS_RFR_FK ON REFERENCIA (PRS_ID ASC);

CREATE INDEX PST_PSARCN_FK ON PUESTO_AREA_CONOCIMIENTO (PST_ID ASC);

CREATE INDEX RGAC_NVFR_FK ON NIVEL_FORMACION (RGAC_ID ASC);

CREATE INDEX NVJR_PST_FK ON PUESTO (NVJR_ID ASC);

CREATE INDEX GRD_PST_FK ON PUESTO (GRD_ID ASC);

CREATE UNIQUE INDEX PK_PLANIFICACION_EVALUACION ON PLANIFICACION_EVALUACION (PLEV_ID ASC);

CREATE INDEX FCES_PRES_FK ON PROCESO_ESTUDIANTE (FCES_ID ASC);

CREATE UNIQUE INDEX PK_PORCENTAJE_GRATUIDAD ON PORCENTAJE_GRATUIDAD (PRGR_ID ASC);

CREATE UNIQUE INDEX PK_NIVEL_APERTURA ON NIVEL_APERTURA (NVAP_ID ASC);

CREATE UNIQUE INDEX PK_SISTEMA_CALIFICACION ON SISTEMA_CALIFICACION (SSCL_ID ASC);

CREATE INDEX FCES_RCES_FK ON RECORD_ESTUDIANTE (FCES_ID ASC);

CREATE INDEX RCES_SLTRMT_FK ON SOLICITUD_TERCERA_MATRICULA (RCES_ID ASC);

CREATE UNIQUE INDEX PK_ROL_FLUJO_GRUPO ON ROL_FLUJO_GRUPO (ROFLGR_ID ASC);

CREATE INDEX CMP_NVCM_FK ON NIVEL_COMPETENCIA (CMP_ID ASC);

CREATE INDEX CLF_PRCL_FK ON PROCESO_CALIFICACION (CLF_ID ASC);

CREATE UNIQUE INDEX PRSIDENTIFICADORUNICO ON PERSONA (PRS_IDENTIFICACION ASC);

CREATE UNIQUE INDEX PK_ROL ON ROL (ROL_ID ASC);

CREATE UNIQUE INDEX PK_SOLICITUD_TERCERA_MATRICULA ON SOLICITUD_TERCERA_MATRICULA (SLTRMT_ID ASC);

CREATE UNIQUE INDEX PK_REQUISITO ON REQUISITO (RQS_ID ASC);

CREATE UNIQUE INDEX PK_MODALIDAD ON MODALIDAD (MDL_ID ASC);

CREATE INDEX NCPR_NCPRCR_FK ON NUCLEO_PROBLEMICO_CARRERA (NCPR_ID ASC);

CREATE INDEX TISSCL_SSCL_FK ON SISTEMA_CALIFICACION (TISSCL_ID ASC);

CREATE UNIQUE INDEX PK_RELACION_LABORAL ON RELACION_LABORAL (RLLB_ID ASC);

CREATE INDEX MTR_PRR_PRR_FK ON PREREQUISITO (MTR_PREREQUISITO_ID ASC);

CREATE UNIQUE INDEX PK_PREREQUISITO ON PREREQUISITO (PRR_ID ASC);

CREATE INDEX UBC_PRS_RSD_FK ON PERSONA (UBC_RESIDENCIA ASC);

CREATE INDEX MLCRPR_RCES_FK ON RECORD_ESTUDIANTE (MLCRPR_ID ASC);

CREATE UNIQUE INDEX PK_PROYECCION ON PROYECCION (PRY_ID ASC);

CREATE INDEX PRC_SER_FK ON SERIE (PRC_ID ASC);

CREATE UNIQUE INDEX PK_REFERENCIA ON REFERENCIA (RFR_ID ASC);

CREATE INDEX PRAC_PRL_FK ON PARALELO (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_SERIE ON SERIE (SER_ID ASC);

CREATE UNIQUE INDEX PK_NUCLEO_PROBLEMICO_CARRERA ON NUCLEO_PROBLEMICO_CARRERA (NCPRCR_ID ASC);

CREATE UNIQUE INDEX PK_NIVEL_FORMACION ON NIVEL_FORMACION (NVFR_ID ASC);

CREATE INDEX CRR_NCPRCR_FK ON NUCLEO_PROBLEMICO_CARRERA (CRR_ID ASC);

CREATE UNIQUE INDEX PK_NUCLEO_PROBLEMICO ON NUCLEO_PROBLEMICO (NCPR_ID ASC);

CREATE INDEX PRAC_PRY_FK ON PROYECCION (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_PUESTO_AREA_CONOCIMIENTO ON PUESTO_AREA_CONOCIMIENTO (PSARCN_ID ASC);

CREATE UNIQUE INDEX PK_NIVEL ON NIVEL (NVL_ID ASC);

CREATE INDEX PRCTRCN_RQS_FK ON REQUISITO (PRTRCN_ID ASC);

CREATE INDEX GR_ROFLGR_FK ON ROL_FLUJO_GRUPO (GRP_ID ASC);

CREATE INDEX USRL_RLFJGR_FK ON ROL_FLUJO_GRUPO (USRO_ID ASC);

CREATE UNIQUE INDEX PK_PROCESO ON PROCESO (PRC_ID ASC);

CREATE UNIQUE INDEX PK_REGIMEN ON REGIMEN (RGM_ID ASC);

CREATE INDEX MTR_PRR_FK ON PREREQUISITO (MTR_ID ASC);

CREATE INDEX CRPRFL_PLCR_FK ON PLANIFICACION_CRONOGRAMA (CRPRFL_ID ASC);

CREATE INDEX SER_PST_FK ON PUESTO (SER_ID ASC);

CREATE INDEX TIPS_PST_FK ON PUESTO (TIPS_ID ASC);

CREATE UNIQUE INDEX PK_NIVEL_COMPETENCIA ON NIVEL_COMPETENCIA (NVCM_ID ASC);

CREATE INDEX CSL_SLRCMT_FK ON SOLICITUD_TERCERA_MATRICULA (CSL_ID ASC);

CREATE UNIQUE INDEX PK_NIVEL_INSTRUCCION ON NIVEL_INSTRUCCION (NVIN_ID ASC);

CREATE INDEX USRO_ROFLCR_FK ON ROL_FLUJO_CARRERA (USRO_ID ASC);

CREATE INDEX SLTRMT_SLTRMT_FK ON SOLICITUD_TERCERA_MATRICULA (SLTRMT_SUB_ID ASC);

CREATE UNIQUE INDEX PK_ROL_FLUJO_CARRERA ON ROL_FLUJO_CARRERA (ROFLCR_ID ASC);

CREATE INDEX PRAC_SLTRMT_FK ON SOLICITUD_TERCERA_MATRICULA (PRAC_ID ASC);

CREATE UNIQUE INDEX PK_PROCESO_TRAMITE_CONTRATO ON PROCESO_TRAMITE_CONTRATO (PRTRCN_ID ASC);

CREATE UNIQUE INDEX PK_RECORD_ESTUDIANTE ON RECORD_ESTUDIANTE (RCES_ID ASC);

CREATE INDEX TMDD_PST_FK ON PUESTO (TMDD_ID ASC);

CREATE UNIQUE INDEX PK_PROCESO_ESTUDIANTE ON PROCESO_ESTUDIANTE (PRES_ID ASC);

CREATE UNIQUE INDEX PK_PERIODO_ACADEMICO ON PERIODO_ACADEMICO (PRAC_ID ASC);

CREATE INDEX MLCRMT_PRY_FK ON PROYECCION (MLCRMT_ID ASC);

ALTER TABLE NIVEL_COMPETENCIA ADD CONSTRAINT PK_NIVEL_COMPETENCIA PRIMARY KEY (NVCM_ID);

ALTER TABLE PROCESO_ESTUDIANTE ADD CONSTRAINT PK_PROCESO_ESTUDIANTE PRIMARY KEY (PRES_ID);

ALTER TABLE NUCLEO_PROBLEMICO ADD CONSTRAINT PK_NUCLEO_PROBLEMICO PRIMARY KEY (NCPR_ID);

ALTER TABLE SOLICITUD_TERCERA_MATRICULA ADD CONSTRAINT PK_SOLICITUD_TERCERA_MATRICULA PRIMARY KEY (SLTRMT_ID);

ALTER TABLE PROYECCION ADD CONSTRAINT PK_PROYECCION PRIMARY KEY (PRY_ID);

ALTER TABLE NIVEL ADD CONSTRAINT PK_NIVEL PRIMARY KEY (NVL_ID);

ALTER TABLE PORCENTAJE_GRATUIDAD ADD CONSTRAINT PK_PORCENTAJE_GRATUIDAD PRIMARY KEY (PRGR_ID);

ALTER TABLE PLANIFICACION_EVALUACION ADD CONSTRAINT PK_PLANIFICACION_EVALUACION PRIMARY KEY (PLEV_ID);

ALTER TABLE PARALELO ADD CONSTRAINT PK_PARALELO PRIMARY KEY (PRL_ID);

ALTER TABLE PROCESO_CALIFICACION ADD CONSTRAINT PK_PROCESO_CALIFICACION PRIMARY KEY (PRCL_ID);

ALTER TABLE PUESTO ADD CONSTRAINT PK_PUESTO PRIMARY KEY (PST_ID);

ALTER TABLE PROCESO_TRAMITE_CONTRATO ADD CONSTRAINT PK_PROCESO_TRAMITE_CONTRATO PRIMARY KEY (PRTRCN_ID);

ALTER TABLE ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ROL_ID);

ALTER TABLE NIVEL_FORMACION ADD CONSTRAINT PK_NIVEL_FORMACION PRIMARY KEY (NVFR_ID);

ALTER TABLE MODALIDAD ADD CONSTRAINT PK_MODALIDAD PRIMARY KEY (MDL_ID);

ALTER TABLE PREREQUISITO ADD CONSTRAINT PK_PREREQUISITO PRIMARY KEY (PRR_ID);

ALTER TABLE PUESTO_AREA_CONOCIMIENTO ADD CONSTRAINT PK_PUESTO_AREA_CONOCIMIENTO PRIMARY KEY (PSARCN_ID);

ALTER TABLE SISTEMA_CALIFICACION ADD CONSTRAINT PK_SISTEMA_CALIFICACION PRIMARY KEY (SSCL_ID);

ALTER TABLE PERIODO_ACADEMICO ADD CONSTRAINT PK_PERIODO_ACADEMICO PRIMARY KEY (PRAC_ID);

ALTER TABLE NIVEL_INSTRUCCION ADD CONSTRAINT PK_NIVEL_INSTRUCCION PRIMARY KEY (NVIN_ID);

ALTER TABLE REQUISITO ADD CONSTRAINT PK_REQUISITO PRIMARY KEY (RQS_ID);

ALTER TABLE RECORD_ESTUDIANTE ADD CONSTRAINT PK_RECORD_ESTUDIANTE PRIMARY KEY (RCES_ID);

ALTER TABLE REFERENCIA ADD CONSTRAINT PK_REFERENCIA PRIMARY KEY (RFR_ID);

ALTER TABLE PROCESO_FLUJO ADD CONSTRAINT PK_PROCESO_FLUJO PRIMARY KEY (PRFL_ID);

ALTER TABLE SERIE ADD CONSTRAINT PK_SERIE PRIMARY KEY (SER_ID);

ALTER TABLE PROCESO ADD CONSTRAINT PK_PROCESO PRIMARY KEY (PRC_ID);

ALTER TABLE REGIMEN_ACADEMICO ADD CONSTRAINT PK_REGIMEN_ACADEMICO PRIMARY KEY (RGAC_ID);

ALTER TABLE NUCLEO_PROBLEMICO_CARRERA ADD CONSTRAINT PK_NUCLEO_PROBLEMICO_CARRERA PRIMARY KEY (NCPRCR_ID);

ALTER TABLE ROL_FLUJO_GRUPO ADD CONSTRAINT PK_ROL_FLUJO_GRUPO PRIMARY KEY (ROFLGR_ID);

ALTER TABLE NIVEL_APERTURA ADD CONSTRAINT PK_NIVEL_APERTURA PRIMARY KEY (NVAP_ID);

ALTER TABLE REGIMEN ADD CONSTRAINT PK_REGIMEN PRIMARY KEY (RGM_ID);

ALTER TABLE ROL_FLUJO_CARRERA ADD CONSTRAINT PK_ROL_FLUJO_CARRERA PRIMARY KEY (ROFLCR_ID);

ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY (PRS_ID);

ALTER TABLE RELACION_LABORAL ADD CONSTRAINT PK_RELACION_LABORAL PRIMARY KEY (RLLB_ID);

ALTER TABLE PLANIFICACION_CRONOGRAMA ADD CONSTRAINT PK_PLANIFICACION_CRONOGRAMA PRIMARY KEY (PLCR_ID);

ALTER TABLE PROYECCION ADD CONSTRAINT FK_PROYECCI_PRAC_PRY_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PLANIFICACION_CRONOGRAMA ADD CONSTRAINT FK_PLANIFIC_CRPRFL_PL_CRONOGRA FOREIGN KEY (CRPRFL_ID)
	REFERENCES CRONOGRAMA_PROCESO_FLUJO (CRPRFL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROCESO_ESTUDIANTE ADD CONSTRAINT FK_PROCESO__FCES_PRES_FICHA_ES FOREIGN KEY (FCES_ID)
	REFERENCES FICHA_ESTUDIANTE (FCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ROL_FLUJO_CARRERA ADD CONSTRAINT FK_ROL_FLUJ_USRO_ROFL_USUARIO_ FOREIGN KEY (USRO_ID)
	REFERENCES USUARIO_ROL (USRO_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE RECORD_ESTUDIANTE ADD CONSTRAINT FK_RECORD_E_FCES_RCES_FICHA_ES FOREIGN KEY (FCES_ID)
	REFERENCES FICHA_ESTUDIANTE (FCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SOLICITUD_TERCERA_MATRICULA ADD CONSTRAINT FK_SOLICITU_CSL_SLRCM_CAUSAL FOREIGN KEY (CSL_ID)
	REFERENCES CAUSAL (CSL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROCESO_CALIFICACION ADD CONSTRAINT FK_PROCESO_CLMD_PRCL_CALIFICA FOREIGN KEY (CLMD_ID)
	REFERENCES CALIFICACION_MODULO (CLMD_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PREREQUISITO ADD CONSTRAINT FK_PREREQUI_MTR_PRR_P_MATERIA FOREIGN KEY (MTR_PREREQUISITO_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PLANIFICACION_EVALUACION ADD CONSTRAINT FK_EVL_PLEV_FK FOREIGN KEY (EVL_ID)
	REFERENCES EVALUACION (EVA_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_UBC_PRS_N_UBICACIO FOREIGN KEY (UBC_NACIMIENTO)
	REFERENCES UBICACION (UBC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROCESO_CALIFICACION ADD CONSTRAINT FK_PROCESO__CLF_PRCL_CALIFICA FOREIGN KEY (CLF_ID)
	REFERENCES CALIFICACION (CLF_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SERIE ADD CONSTRAINT FK_SERIE_PRC_SER_PROCESO FOREIGN KEY (PRC_ID)
	REFERENCES PROCESO (PRC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PARALELO ADD CONSTRAINT FK_PARALELO_PRAC_PRL_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE REQUISITO ADD CONSTRAINT FK_REQUISIT_PRCTRCN_R_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO_AREA_CONOCIMIENTO ADD CONSTRAINT FK_PUESTO_A_ARCN_PSAR_AREA_CON FOREIGN KEY (ARCN_ID)
	REFERENCES AREA_CONOCIMIENTO (ARCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ROL_FLUJO_CARRERA ADD CONSTRAINT FK_ROL_FLUJ_CRR_ROFLC_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ROL_FLUJO_GRUPO ADD CONSTRAINT FK_PRAC_ROFLGR FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO ADD CONSTRAINT FK_PUESTO_GROC_PST_GRUPO_OC FOREIGN KEY (GROC_ID)
	REFERENCES GRUPO_OCUPACIONAL (GROC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO ADD CONSTRAINT FK_PUESTO_SER_PST_SERIE FOREIGN KEY (SER_ID)
	REFERENCES SERIE (SER_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ROL_FLUJO_GRUPO ADD CONSTRAINT FK_ROL_FLUJ_USRL_RLFJ_USUARIO_ FOREIGN KEY (USRO_ID)
	REFERENCES USUARIO_ROL (USRO_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROYECCION ADD CONSTRAINT FK_PROYECCI_EXC_PRY_EXCEDENT FOREIGN KEY (EXC_ID)
	REFERENCES EXCEDENTE (EXC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PORCENTAJE_GRATUIDAD ADD CONSTRAINT FK_PORCENTA_TIGR_PRGR_TIPO_GRA FOREIGN KEY (TIGR_ID)
	REFERENCES TIPO_GRATUIDAD (TIGR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE NUCLEO_PROBLEMICO_CARRERA ADD CONSTRAINT FK_NUCLEO_P_CRR_NCPRC_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE NUCLEO_PROBLEMICO_CARRERA ADD CONSTRAINT FK_NUCLEO_P_NCPR_NCPR_NUCLEO_P FOREIGN KEY (NCPR_ID)
	REFERENCES NUCLEO_PROBLEMICO (NCPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SOLICITUD_TERCERA_MATRICULA ADD CONSTRAINT FK_SOLICITU_RCES_SLTR_RECORD_E FOREIGN KEY (RCES_ID)
	REFERENCES RECORD_ESTUDIANTE (RCES_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROYECCION ADD CONSTRAINT FK_PROYECCI_MLCRMT_PR_MALLA_CU FOREIGN KEY (MLCRMT_ID)
	REFERENCES MALLA_CURRICULAR_MATERIA (MLCRMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PARALELO ADD CONSTRAINT FK_PARALELO_CRR_PRL_CARRERA FOREIGN KEY (CRR_ID)
	REFERENCES CARRERA (CRR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_ETN_PRS_ETNIA FOREIGN KEY (ETN_ID)
	REFERENCES ETNIA (ETN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE RECORD_ESTUDIANTE ADD CONSTRAINT FK_RECORD_E_MLCRPR_RC_MALLA_CU FOREIGN KEY (MLCRPR_ID)
	REFERENCES MALLA_CURRICULAR_PARALELO (MLCRPR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROCESO_TRAMITE_CONTRATO ADD CONSTRAINT FK_PROCESO__DTTRCN_PR_DETALLE_ FOREIGN KEY (DTTRCN_ID)
	REFERENCES DETALLE_TRAMITE_CONTRATO (DTTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PLANIFICACION_EVALUACION ADD CONSTRAINT FK_PRFL_PLEV_FK FOREIGN KEY (PRFL_ID)
	REFERENCES PROCESO_FLUJO (PRFL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO ADD CONSTRAINT FK_PUESTO_TMDD_PST_TIEMPO_D FOREIGN KEY (TMDD_ID)
	REFERENCES TIEMPO_DEDICACION (TMDD_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SISTEMA_CALIFICACION ADD CONSTRAINT FK_SISTEMA__TISSCL_SS_TIPO_SIS FOREIGN KEY (TISSCL_ID)
	REFERENCES TIPO_SISTEMA_CALIFICACION (TISSCL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PREREQUISITO ADD CONSTRAINT FK_PREREQUI_MTR_PRR_MATERIA FOREIGN KEY (MTR_ID)
	REFERENCES MATERIA (MTR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SISTEMA_CALIFICACION ADD CONSTRAINT FK_SISTEMA__PRAC_SSCL_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE REFERENCIA ADD CONSTRAINT FK_REFERENCIA_PRS_RFR_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO ADD CONSTRAINT FK_PUESTO_TIPS_PST_TIPO_PUE FOREIGN KEY (TIPS_ID)
	REFERENCES TIPO_PUESTO (TIPS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE NIVEL_FORMACION ADD CONSTRAINT FK_NIVEL_FO_RGAC_NVFR_REGIMEN_ FOREIGN KEY (RGAC_ID)
	REFERENCES REGIMEN_ACADEMICO (RGAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SOLICITUD_TERCERA_MATRICULA ADD CONSTRAINT FK_SOLICITU_SLTRMT_SL_SOLICITU FOREIGN KEY (SLTRMT_SUB_ID)
	REFERENCES SOLICITUD_TERCERA_MATRICULA (SLTRMT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE ROL_FLUJO_GRUPO ADD CONSTRAINT FK_ROL_FLUJ_GR_ROFLGR_GRUPO FOREIGN KEY (GRP_ID)
	REFERENCES GRUPO (GRP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE NIVEL_COMPETENCIA ADD CONSTRAINT FK_NIVEL_CO_CMP_NVCM_COMPETEN FOREIGN KEY (CMP_ID)
	REFERENCES COMPETENCIA (CMP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PUESTO_AREA_CONOCIMIENTO ADD CONSTRAINT FK_PUESTO_A_PST_PSARC_PUESTO FOREIGN KEY (PST_ID)
	REFERENCES PUESTO (PST_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE SOLICITUD_TERCERA_MATRICULA ADD CONSTRAINT FK_SOLICITU_PRAC_SLTR_PERIODO_ FOREIGN KEY (PRAC_ID)
	REFERENCES PERIODO_ACADEMICO (PRAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

