--<ScriptOptions statementTerminator=";"/>

CREATE TABLE TIPO_EVALUACION (
		TPEV_ID NUMBER(6 , 0) NOT NULL,
		TPEV_DESCRIPCION VARCHAR2(256),
		TPEV_INTRODUCCION VARCHAR2(2000),
		TPEV_INSTRUCCIONES VARCHAR2(2000),
		TPEV_FECHA TIMESTAMP(11),
		TPEV_USUARIO VARCHAR2(256),
		TPEV_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_APERTURA (
		TIAP_ID NUMBER(6 , 0) NOT NULL,
		TIAP_DESCRIPCION VARCHAR2(256),
		TIAP_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TURNERO (
		TRN_ID NUMBER(6 , 0) NOT NULL,
		PRTRCN_ID NUMBER(38 , 0),
		USRO_ID NUMBER(38 , 0),
		TRN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_PROCESO (
		TIPR_ID NUMBER(6 , 0) NOT NULL,
		TIPR_DESCRIPCION VARCHAR2(256),
		TIPR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_SISTEMA_CALIFICACION (
		TISSCL_ID NUMBER(6 , 0) NOT NULL,
		TISSCL_DESCRIPCION VARCHAR2(256),
		TISSCL_ESTADO NUMBER(38 , 0),
		TISSCL_OBSERVACION VARCHAR2(256)
	);

CREATE TABLE TRAMITE (
		TRM_ID NUMBER(6 , 0) NOT NULL,
		TRM_DESCRIPCION VARCHAR2(512),
		TRM_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_CONTENIDO (
		TPCN_ID NUMBER(6 , 0) NOT NULL,
		TPCN_DESCRIPCION VARCHAR2(2000),
		TPCN_ESTADO NUMBER(38 , 0),
		TPCN_TIPO NUMBER(38 , 0),
		TPCN_NUMERAL NUMBER,
		TPCN_TIPO_COMPONENTE NUMBER(38 , 0),
		TPCN_TIPO_SELECCION NUMBER(38 , 0),
		TPCN_NUM_MAX NUMBER(38 , 0),
		TPCN_FECHA TIMESTAMP(11),
		TPCN_USUARIO VARCHAR2(256),
		TPCN_OBLIGATORIEDAD NUMBER(38 , 0),
		TPCN_FK_TPCN_ID NUMBER(6 , 0)
	);

CREATE TABLE TIPO_EMPLEADO (
		TIEM_ID NUMBER(6 , 0) NOT NULL,
		TIEM_DESCRIPCION VARCHAR2(100),
		TIEM_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_FORMACION (
		TIFR_ID NUMBER(6 , 0) NOT NULL,
		TIFR_DESCRIPCION VARCHAR2(128),
		NVFR_ID NUMBER(38 , 0)
	);

CREATE TABLE TIPO_FORMACION_MALLA (
		TIFRML_ID NUMBER(6 , 0) NOT NULL,
		TIFRML_DESCRIPCION VARCHAR2(256),
		TIFRML_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_MATERIA (
		TIMT_ID NUMBER(6 , 0) NOT NULL,
		TIMT_DESCRIPCION VARCHAR2(256),
		TIMT_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_SEDE (
		TISE_ID NUMBER(6 , 0) NOT NULL,
		RGAC_ID NUMBER(38 , 0),
		TISE_DESCRIPCION VARCHAR2(128)
	);

CREATE TABLE UBICACION (
		UBC_ID NUMBER(6 , 0) NOT NULL,
		UBC_DESCRIPCION VARCHAR2(128),
		UBC_JERARQUIA NUMBER(38 , 0),
		UBC_GENTILICIO VARCHAR2(128),
		UBC_COD_SNIESE VARCHAR2(32),
		UBC_SUB_ID NUMBER(38 , 0)
	);

CREATE TABLE TIPO_DOCUMENTO (
		TIDC_ID NUMBER(6 , 0) NOT NULL,
		TIDC_SUB_ID NUMBER(38 , 0),
		TIDC_DESCRIPCION VARCHAR2(256),
		TIDC_NUMERO_DOCUMENTO VARCHAR2(256),
		TIDC_FECHA_INICIO DATE,
		TIDC_FECHA_FIN DATE,
		TIDC_INGRESO_CONCURSO NUMBER(38 , 0)
	);

CREATE TABLE TPCN_FUNCION_TPEV (
		TPCNFNTPEV_ID NUMBER(6 , 0) NOT NULL,
		FNCTPEV_ID NUMBER(6 , 0),
		TPCN_ID NUMBER(6 , 0),
		TPCNFNTPEV_USUARIO VARCHAR2(256),
		TPCNFNTPEV_FECHA TIMESTAMP(11),
		TPCNFNTPEV_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_NIVEL_APERTURA (
		TINVAP_ID NUMBER(6 , 0) NOT NULL,
		NVAP_ID NUMBER(38 , 0),
		TIAP_ID NUMBER(38 , 0),
		PLCR_ID NUMBER(38 , 0),
		TINVAP_FECHA_INICIO TIMESTAMP(11),
		TINVAP_FECHA_FIN TIMESTAMP(11),
		TINVAP_ESTADO NUMBER(38 , 0),
		TINVAP_OBSERVACION VARCHAR2(512)
	);

CREATE TABLE TIPO_FINANCIAMIENTO (
		TIFN_ID NUMBER(6 , 0) NOT NULL,
		TIFN_DESCRIPCION VARCHAR2(256)
	);

CREATE TABLE USUARIO (
		USR_ID NUMBER(6 , 0) NOT NULL,
		USR_IDENTIFICACION VARCHAR2(13),
		USR_NICK VARCHAR2(25),
		USR_PASSWORD VARCHAR2(64),
		USR_FECHA_CREACION TIMESTAMP(11),
		USR_FECHA_CADUCIDAD DATE,
		USR_FECHA_CAD_PASS DATE,
		USR_ESTADO NUMBER(38 , 0),
		USR_EST_SESION NUMBER(38 , 0),
		USR_ACTIVE_DIRECTORY NUMBER(38 , 0),
		PRS_ID NUMBER(38 , 0)
	);

CREATE TABLE TIEMPO_DEDICACION (
		TMDD_ID NUMBER(6 , 0) NOT NULL,
		TMDD_DESCRIPCION VARCHAR2(50),
		TMDD_HORAS NUMBER(38 , 0),
		TMDD_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_FUNCION_CARGA_HORARIA (
		TIFNCRHR_ID NUMBER(6 , 0) NOT NULL,
		TICRHR_ID NUMBER(38 , 0),
		TIFNCRHR_ESTADO NUMBER(38 , 0),
		FNCRHR_ID NUMBER(38 , 0)
	);

CREATE TABLE UNIDAD_FORMACION (
		UNFR_ID NUMBER(6 , 0) NOT NULL,
		UNFR_DESCRIPCION VARCHAR2(256),
		UNFR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE USUARIO_ROL (
		USRO_ID NUMBER(6 , 0) NOT NULL,
		USRO_ESTADO NUMBER(38 , 0),
		USR_ID NUMBER(38 , 0),
		ROL_ID NUMBER(38 , 0)
	);

CREATE TABLE TIPO_GRATUIDAD (
		TIGR_ID NUMBER(6 , 0) NOT NULL,
		TIGR_DESCRIPCION VARCHAR2(256),
		TIGR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_CARGA_HORARIA (
		TICRHR_ID NUMBER(6 , 0) NOT NULL,
		TICRHR_DESCRIPCION VARCHAR2(128),
		TICRHR_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE VIGENCIA (
		VGN_ID NUMBER(6 , 0) NOT NULL,
		VGN_DESCRIPCION VARCHAR2(128)
	);

CREATE TABLE TIPO_CAUSAL (
		TICS_ID NUMBER(6 , 0) NOT NULL,
		TICS_DESCRIPCION VARCHAR2(256),
		TICS_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_PUESTO (
		TIPS_ID NUMBER(6 , 0) NOT NULL,
		TIPS_DESCRIPCION VARCHAR2(256),
		TIPS_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TIPO_CONTRATO (
		TICN_ID NUMBER(6 , 0) NOT NULL,
		TIEM_ID NUMBER(38 , 0),
		TICN_DESCRIPCION VARCHAR2(200),
		TICN_ESTADO NUMBER(38 , 0)
	);

CREATE TABLE TITULO (
		TTL_ID NUMBER(6 , 0) NOT NULL,
		TTL_DESCRIPCION VARCHAR2(512),
		TTL_SEXO NUMBER(38 , 0),
		TTL_ESTADO NUMBER(38 , 0),
		TTL_TIPO NUMBER(38 , 0)
	);

CREATE UNIQUE INDEX PK_TIEMPO_DEDICACION ON TIEMPO_DEDICACION (TMDD_ID ASC);

CREATE INDEX USR_USRO_FK ON USUARIO_ROL (USR_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_PUESTO ON TIPO_PUESTO (TIPS_ID ASC);

CREATE INDEX TIEM_TICN_FK ON TIPO_CONTRATO (TIEM_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_CAUSAL ON TIPO_CAUSAL (TICS_ID ASC);

CREATE INDEX NVAP_TINVAP_FK ON TIPO_NIVEL_APERTURA (NVAP_ID ASC);

CREATE INDEX TIAP_TINVAP_FK ON TIPO_NIVEL_APERTURA (TIAP_ID ASC);

CREATE INDEX FNTPEV_TPCNFNTPEV_FK ON TPCN_FUNCION_TPEV (FNCTPEV_ID ASC);

CREATE UNIQUE INDEX PK_TRAMITE ON TRAMITE (TRM_ID ASC);

CREATE INDEX FNCRHR_TIFNCRHR_FK ON TIPO_FUNCION_CARGA_HORARIA (FNCRHR_ID ASC);

CREATE INDEX PRS_USR_FK ON USUARIO (PRS_ID ASC);

CREATE UNIQUE INDEX PK_UBICACION ON UBICACION (UBC_ID ASC);

CREATE INDEX TICRHR_TIFNCRHR_FK ON TIPO_FUNCION_CARGA_HORARIA (TICRHR_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_APERTURA ON TIPO_APERTURA (TIAP_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_FORMACION_MALLA ON TIPO_FORMACION_MALLA (TIFRML_ID ASC);

CREATE UNIQUE INDEX UK_USUARIO_ROL ON USUARIO_ROL (USR_ID ASC, ROL_ID ASC);

CREATE UNIQUE INDEX PK_USUARIO_ROL ON USUARIO_ROL (USRO_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_SEDE ON TIPO_SEDE (TISE_ID ASC);

CREATE INDEX TPCN_TPCN_FK ON TIPO_CONTENIDO (TPCN_FK_TPCN_ID ASC);

CREATE INDEX RGAC_TISE_FK ON TIPO_SEDE (RGAC_ID ASC);

CREATE INDEX USRO_TRN_FK ON TURNERO (USRO_ID ASC);

CREATE INDEX UBC_UBC_FK ON UBICACION (UBC_SUB_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_NIVEL_APERTURA ON TIPO_NIVEL_APERTURA (TINVAP_ID ASC);

CREATE UNIQUE INDEX PK_TPCN_FUNCION_TPEV ON TPCN_FUNCION_TPEV (TPCNFNTPEV_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_MATERIA ON TIPO_MATERIA (TIMT_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_PROCESO ON TIPO_PROCESO (TIPR_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_EMPLEADO ON TIPO_EMPLEADO (TIEM_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_FUNCION_CARGA_HORARIA ON TIPO_FUNCION_CARGA_HORARIA (TIFNCRHR_ID ASC);

CREATE INDEX ROL_USRO_FK ON USUARIO_ROL (ROL_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_FINANCIAMIENTO ON TIPO_FINANCIAMIENTO (TIFN_ID ASC);

CREATE UNIQUE INDEX PK_TITULO ON TITULO (TTL_ID ASC);

CREATE INDEX TIDC_TIDC_FK ON TIPO_DOCUMENTO (TIDC_SUB_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_CONTENIDO ON TIPO_CONTENIDO (TPCN_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_CARGA_HORARIA ON TIPO_CARGA_HORARIA (TICRHR_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_GRATUIDAD ON TIPO_GRATUIDAD (TIGR_ID ASC);

CREATE INDEX TPCN_TPFNEV_FK ON TPCN_FUNCION_TPEV (TPCN_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_FORMACION ON TIPO_FORMACION (TIFR_ID ASC);

CREATE UNIQUE INDEX PK_USUARIO ON USUARIO (USR_ID ASC);

CREATE INDEX PLCR_TINVAP_FK ON TIPO_NIVEL_APERTURA (PLCR_ID ASC);

CREATE INDEX NVFR_TPFR_FK ON TIPO_FORMACION (NVFR_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_EVALUACION ON TIPO_EVALUACION (TPEV_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_CONTRATO ON TIPO_CONTRATO (TICN_ID ASC);

CREATE INDEX PRTRCN_TRN_FK ON TURNERO (PRTRCN_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_DOCUMENTO ON TIPO_DOCUMENTO (TIDC_ID ASC);

CREATE UNIQUE INDEX PK_TIPO_SISTEMA_CALIFICACION ON TIPO_SISTEMA_CALIFICACION (TISSCL_ID ASC);

CREATE UNIQUE INDEX PK_TURNERO ON TURNERO (TRN_ID ASC);

CREATE UNIQUE INDEX PK_UNIDAD_FORMACION ON UNIDAD_FORMACION (UNFR_ID ASC);

CREATE UNIQUE INDEX PK_VIGENCIA ON VIGENCIA (VGN_ID ASC);

ALTER TABLE TIPO_PROCESO ADD CONSTRAINT PK_TIPO_PROCESO PRIMARY KEY (TIPR_ID);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (USR_ID);

ALTER TABLE TIPO_APERTURA ADD CONSTRAINT PK_TIPO_APERTURA PRIMARY KEY (TIAP_ID);

ALTER TABLE UBICACION ADD CONSTRAINT PK_UBICACION PRIMARY KEY (UBC_ID);

ALTER TABLE TIPO_NIVEL_APERTURA ADD CONSTRAINT PK_TIPO_NIVEL_APERTURA PRIMARY KEY (TINVAP_ID);

ALTER TABLE TITULO ADD CONSTRAINT PK_TITULO PRIMARY KEY (TTL_ID);

ALTER TABLE TIPO_EVALUACION ADD CONSTRAINT PK_TIPO_EVALUACION PRIMARY KEY (TPEV_ID);

ALTER TABLE TIPO_CAUSAL ADD CONSTRAINT PK_TIPO_CAUSAL PRIMARY KEY (TICS_ID);

ALTER TABLE TIPO_FINANCIAMIENTO ADD CONSTRAINT PK_TIPO_FINANCIAMIENTO PRIMARY KEY (TIFN_ID);

ALTER TABLE TRAMITE ADD CONSTRAINT PK_TRAMITE PRIMARY KEY (TRM_ID);

ALTER TABLE TIEMPO_DEDICACION ADD CONSTRAINT PK_TIEMPO_DEDICACION PRIMARY KEY (TMDD_ID);

ALTER TABLE VIGENCIA ADD CONSTRAINT PK_VIGENCIA PRIMARY KEY (VGN_ID);

ALTER TABLE TIPO_EMPLEADO ADD CONSTRAINT PK_TIPO_EMPLEADO PRIMARY KEY (TIEM_ID);

ALTER TABLE TIPO_PUESTO ADD CONSTRAINT PK_TIPO_PUESTO PRIMARY KEY (TIPS_ID);

ALTER TABLE TIPO_SEDE ADD CONSTRAINT PK_TIPO_SEDE PRIMARY KEY (TISE_ID);

ALTER TABLE TIPO_GRATUIDAD ADD CONSTRAINT PK_TIPO_GRATUIDAD PRIMARY KEY (TIGR_ID);

ALTER TABLE UNIDAD_FORMACION ADD CONSTRAINT PK_UNIDAD_FORMACION PRIMARY KEY (UNFR_ID);

ALTER TABLE TIPO_FORMACION_MALLA ADD CONSTRAINT PK_TIPO_FORMACION_MALLA PRIMARY KEY (TIFRML_ID);

ALTER TABLE TIPO_CONTENIDO ADD CONSTRAINT PK_TIPO_CONTENIDO PRIMARY KEY (TPCN_ID);

ALTER TABLE TPCN_FUNCION_TPEV ADD CONSTRAINT PK_TPCN_FUNCION_TPEV PRIMARY KEY (TPCNFNTPEV_ID);

ALTER TABLE TURNERO ADD CONSTRAINT PK_TURNERO PRIMARY KEY (TRN_ID);

ALTER TABLE TIPO_CONTRATO ADD CONSTRAINT PK_TIPO_CONTRATO PRIMARY KEY (TICN_ID);

ALTER TABLE TIPO_MATERIA ADD CONSTRAINT PK_TIPO_MATERIA PRIMARY KEY (TIMT_ID);

ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (TIDC_ID);

ALTER TABLE USUARIO_ROL ADD CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (USRO_ID);

ALTER TABLE TIPO_FUNCION_CARGA_HORARIA ADD CONSTRAINT PK_TIPO_FUNCION_CARGA_HORARIA PRIMARY KEY (TIFNCRHR_ID);

ALTER TABLE TIPO_SISTEMA_CALIFICACION ADD CONSTRAINT PK_TIPO_SISTEMA_CALIFICACION PRIMARY KEY (TISSCL_ID);

ALTER TABLE TIPO_FORMACION ADD CONSTRAINT PK_TIPO_FORMACION PRIMARY KEY (TIFR_ID);

ALTER TABLE TIPO_CARGA_HORARIA ADD CONSTRAINT PK_TIPO_CARGA_HORARIA PRIMARY KEY (TICRHR_ID);

ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT FK_TIPO_DOC_TIDC_TIDC_TIPO_DOC FOREIGN KEY (TIDC_SUB_ID)
	REFERENCES TIPO_DOCUMENTO (TIDC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TURNERO ADD CONSTRAINT FK_TURNERO_USRO_TRN_USUARIO_ FOREIGN KEY (USRO_ID)
	REFERENCES USUARIO_ROL (USRO_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PRS_USR_PERSONA FOREIGN KEY (PRS_ID)
	REFERENCES PERSONA (PRS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TPCN_FUNCION_TPEV ADD CONSTRAINT FK_TPCN_FUN_TPCN_TPFN_TIPO_CON FOREIGN KEY (TPCN_ID)
	REFERENCES TIPO_CONTENIDO (TPCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_FUNCION_CARGA_HORARIA ADD CONSTRAINT FK_TIPO_FUN_TICRHR_TI_TIPO_CAR FOREIGN KEY (TICRHR_ID)
	REFERENCES TIPO_CARGA_HORARIA (TICRHR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE UBICACION ADD CONSTRAINT FK_UBICACIO_UBC_UBC_UBICACIO FOREIGN KEY (UBC_SUB_ID)
	REFERENCES UBICACION (UBC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_FUNCION_CARGA_HORARIA ADD CONSTRAINT FK_TIPO_FUN_FNCRHR_TI_FUNCION_ FOREIGN KEY (FNCRHR_ID)
	REFERENCES FUNCION_CARGA_HORARIA (FNCRHR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_SEDE ADD CONSTRAINT FK_TIPO_SED_RGAC_TISE_REGIMEN_ FOREIGN KEY (RGAC_ID)
	REFERENCES REGIMEN_ACADEMICO (RGAC_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_CONTENIDO ADD CONSTRAINT FK_TIPO_CON_TPCN_TPCN_TIPO_CON FOREIGN KEY (TPCN_FK_TPCN_ID)
	REFERENCES TIPO_CONTENIDO (TPCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_FORMACION ADD CONSTRAINT FK_TIPO_FOR_NVFR_TPFR_NIVEL_FO FOREIGN KEY (NVFR_ID)
	REFERENCES NIVEL_FORMACION (NVFR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TURNERO ADD CONSTRAINT FK_TURNERO_PRTRCN_TR_PROCESO_ FOREIGN KEY (PRTRCN_ID)
	REFERENCES PROCESO_TRAMITE_CONTRATO (PRTRCN_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_NIVEL_APERTURA ADD CONSTRAINT FK_TIPO_NIV_PLCR_TINV_PLANIFIC FOREIGN KEY (PLCR_ID)
	REFERENCES PLANIFICACION_CRONOGRAMA (PLCR_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_NIVEL_APERTURA ADD CONSTRAINT FK_TIPO_NIV_TIAP_TINV_TIPO_APE FOREIGN KEY (TIAP_ID)
	REFERENCES TIPO_APERTURA (TIAP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_CONTRATO ADD CONSTRAINT FK_TIPO_CON_TIEM_TICN_TIPO_EMP FOREIGN KEY (TIEM_ID)
	REFERENCES TIPO_EMPLEADO (TIEM_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TPCN_FUNCION_TPEV ADD CONSTRAINT FK_TPCN_FUN_FNTPEV_TP_FUNCION_ FOREIGN KEY (FNCTPEV_ID)
	REFERENCES FUNCION_TIPO_EVALUACION (FNCTPEV_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE TIPO_NIVEL_APERTURA ADD CONSTRAINT FK_TIPO_NIV_NVAP_TINV_NIVEL_AP FOREIGN KEY (NVAP_ID)
	REFERENCES NIVEL_APERTURA (NVAP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

