package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;


/**
 * ActividadEsencial generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDAD_ESENCIAL", schema = ConstantesJpa.SCHEMA)
public class ActividadEsencial implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7415288071559066505L;
	private int acesId;
	private String acesDescripcion;
	private List<ActividadPuesto> acesActividadPuestos = new ArrayList<ActividadPuesto>(0);

	public ActividadEsencial() {
	}

	public ActividadEsencial(int acesId) {
		this.acesId = acesId;
	}

	public ActividadEsencial(int acesId, String acesDescripcion, List<ActividadPuesto> acesActividadPuestos) {
		this.acesId = acesId;
		this.acesDescripcion = acesDescripcion;
		this.acesActividadPuestos = acesActividadPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ACES_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcesId() {
		return this.acesId;
	}

	public void setAcesId(int acesId) {
		this.acesId = acesId;
	}

	@Column(name = "ACES_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getAcesDescripcion() {
		return this.acesDescripcion;
	}

	public void setAcesDescripcion(String acesDescripcion) {
		this.acesDescripcion = acesDescripcion;
	}

	@OneToMany( mappedBy = "acpsActividadEsencial")
	public List<ActividadPuesto> getAcesActividadPuestos() {
		return this.acesActividadPuestos;
	}

	public void setAcesActividadPuestos(List<ActividadPuesto> acesActividadPuestos) {
		this.acesActividadPuestos = acesActividadPuestos;
	}

}
