package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ActividadPuesto generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDAD_PUESTO", schema = ConstantesJpa.SCHEMA)
public class ActividadPuesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7966234059348078153L;
	private int acpsId;
	private ActividadEsencial acpsActividadEsencial;
	private Puesto acpsPuesto;

	public ActividadPuesto() {
	}

	public ActividadPuesto(int acpsId) {
		this.acpsId = acpsId;
	}

	public ActividadPuesto(int acpsId, ActividadEsencial acpsActividadEsencial, Puesto acpsPuesto) {
		this.acpsId = acpsId;
		this.acpsActividadEsencial = acpsActividadEsencial;
		this.acpsPuesto = acpsPuesto;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ACPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcpsId() {
		return this.acpsId;
	}

	public void setAcpsId(int acpsId) {
		this.acpsId = acpsId;
	}

	@ManyToOne
	@JoinColumn(name = "ACES_ID")
	public ActividadEsencial getAcpsActividadEsencial() {
		return this.acpsActividadEsencial;
	}

	public void setAcpsActividadEsencial(ActividadEsencial acpsActividadEsencial) {
		this.acpsActividadEsencial = acpsActividadEsencial;
	}

	@ManyToOne
	@JoinColumn(name = "PST_ID")
	public Puesto getAcpsPuesto() {
		return this.acpsPuesto;
	}

	public void setAcpsPuesto(Puesto acpsPuesto) {
		this.acpsPuesto = acpsPuesto;
	}

}
