package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ApruebaSolicitud generated by hbm2java
 */
@Entity
@Table(name = "APRUEBA_SOLICITUD", schema = ConstantesJpa.SCHEMA)
public class ApruebaSolicitud implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -726078972927368467L;
	private int apslId;
	private ProcesoTramiteContrato apslProcesoTramiteContrato;
	private Timestamp apslFechaAprobacion;
	private Integer apslEstado;
	private String apslObservacion;

	public ApruebaSolicitud() {
	}

	public ApruebaSolicitud(int apslId) {
		this.apslId = apslId;
	}

	public ApruebaSolicitud(int apslId, ProcesoTramiteContrato apslProcesoTramiteContrato, Timestamp apslFechaAprobacion,
			Integer apslEstado, String apslObservacion) {
		this.apslId = apslId;
		this.apslProcesoTramiteContrato = apslProcesoTramiteContrato;
		this.apslFechaAprobacion = apslFechaAprobacion;
		this.apslEstado = apslEstado;
		this.apslObservacion = apslObservacion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "APSL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getApslId() {
		return this.apslId;
	}

	public void setApslId(int apslId) {
		this.apslId = apslId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getApslProcesoTramiteContrato() {
		return this.apslProcesoTramiteContrato;
	}

	public void setApslProcesoTramiteContrato(ProcesoTramiteContrato apslProcesoTramiteContrato) {
		this.apslProcesoTramiteContrato = apslProcesoTramiteContrato;
	}

	@Column(name = "APSL_FECHA_APROBACION")
	public Timestamp getApslFechaAprobacion() {
		return this.apslFechaAprobacion;
	}

	public void setApslFechaAprobacion(Timestamp apslFechaAprobacion) {
		this.apslFechaAprobacion = apslFechaAprobacion;
	}

	@Column(name = "APSL_ESTADO", precision = 22, scale = 0)
	public Integer getApslEstado() {
		return this.apslEstado;
	}

	public void setApslEstado(Integer apslEstado) {
		this.apslEstado = apslEstado;
	}

	@Column(name = "APSL_OBSERVACION", length = 512)
	@Length(max = 512)
	public String getApslObservacion() {
		return this.apslObservacion;
	}

	public void setApslObservacion(String apslObservacion) {
		this.apslObservacion = apslObservacion;
	}

}
