package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Arancel generated by hbm2java
 */
@Entity
@Table(name = "ARANCEL", schema = ConstantesJpa.SCHEMA)
public class Arancel implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 5977565358234849358L;
	private int arnId;
	private TipoGratuidad arnTipoGratuidad;
	private Modalidad arnModalidad;
	private String arnDescripcion;
	private Integer arnTipoMatricula;
	private Integer arnTipoNumMatricula;
	private BigDecimal arnValor;
	private Integer arnTipo;
	private Integer arnCodigoArancel;
	private List<DetalleMatricula> arnDetalleMatriculas = new ArrayList<DetalleMatricula>(0);
	 
	public Arancel() {
	}

	public Arancel(int arnId) {
		this.arnId = arnId;
	}

	public Arancel(int arnId, TipoGratuidad arnTipoGratuidad, Modalidad arnModalidad, String arnDescripcion,
			Integer arnTipoMatricula, Integer arnTipoNumMatricula, BigDecimal arnValor,
			List<DetalleMatricula> arnDetalleMatriculas , Integer arnTipo) {
		this.arnId = arnId;
		this.arnTipoGratuidad = arnTipoGratuidad;
		this.arnModalidad = arnModalidad;
		this.arnDescripcion = arnDescripcion;
		this.arnTipoMatricula = arnTipoMatricula;
		this.arnTipoNumMatricula = arnTipoNumMatricula;
		this.arnValor = arnValor;
		this.arnTipo = arnTipo;
		this.arnDetalleMatriculas = arnDetalleMatriculas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ARN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getArnId() {
		return this.arnId;
	}

	public void setArnId(int arnId) {
		this.arnId = arnId;
	}

	@ManyToOne
	@JoinColumn(name = "TIGR_ID")
	public TipoGratuidad getArnTipoGratuidad() {
		return this.arnTipoGratuidad;
	}

	public void setArnTipoGratuidad(TipoGratuidad arnTipoGratuidad) {
		this.arnTipoGratuidad = arnTipoGratuidad;
	}

	@ManyToOne
	@JoinColumn(name = "MDL_ID")
	public Modalidad getArnModalidad() {
		return this.arnModalidad;
	}

	public void setArnModalidad(Modalidad arnModalidad) {
		this.arnModalidad = arnModalidad;
	}

	@Column(name = "ARN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getArnDescripcion() {
		return this.arnDescripcion;
	}

	public void setArnDescripcion(String arnDescripcion) {
		this.arnDescripcion = arnDescripcion;
	}

	@Column(name = "ARN_TIPO_MATRICULA", precision = 22, scale = 0)
	public Integer getArnTipoMatricula() {
		return this.arnTipoMatricula;
	}

	public void setArnTipoMatricula(Integer arnTipoMatricula) {
		this.arnTipoMatricula = arnTipoMatricula;
	}

	@Column(name = "ARN_CODIGO_ARANCEL")
	public Integer getArnCodigoArancel() {
		return arnCodigoArancel;
	}

	public void setArnCodigoArancel(Integer arnCodigoArancel) {
		this.arnCodigoArancel = arnCodigoArancel;
	}

	@Column(name = "ARN_TIPO_NUM_MATRICULA", precision = 22, scale = 0)
	public Integer getArnTipoNumMatricula() {
		return this.arnTipoNumMatricula;
	}

	public void setArnTipoNumMatricula(Integer arnTipoNumMatricula) {
		this.arnTipoNumMatricula = arnTipoNumMatricula;
	}

	@Column(name = "ARN_VALOR", precision = 6)
	public BigDecimal getArnValor() {
		return this.arnValor;
	}

	public void setArnValor(BigDecimal arnValor) {
		this.arnValor = arnValor;
	}
	
	@Column(name = "ARN_TIPO", precision = 22, scale = 0)
	public Integer getArnTipo() {
		return this.arnTipo;
	}

	public void setArnTipo(Integer arnTipo) {
		this.arnTipo = arnTipo;
	}

	@OneToMany( mappedBy = "dtmtArancel")
	public List<DetalleMatricula> getArnDetalleMatriculas() {
		return this.arnDetalleMatriculas;
	}

	public void setArnDetalleMatriculas(List<DetalleMatricula> arnDetalleMatriculas) {
		this.arnDetalleMatriculas = arnDetalleMatriculas;
	}

}
