package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * AreaConocimiento generated by hbm2java
 */
@Entity
@Table(name = "AREA_CONOCIMIENTO", schema = ConstantesJpa.SCHEMA)
public class AreaConocimiento implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6405287356626631089L;
	private int arcnId;
	private AreaConocimiento arcnAreaConocimiento;
	private String arcnDescripcion;
	private String arcnCodigo;
	private Integer arcnJerarquia;
	private List<PuestoAreaConocimiento> arcnPuestoAreaConocimientos = new ArrayList<PuestoAreaConocimiento>(0);
	private List<AreaConocimiento> arcnAreaConocimientos = new ArrayList<AreaConocimiento>(0);

	public AreaConocimiento() {
	}

	public AreaConocimiento(int arcnId) {
		this.arcnId = arcnId;
	}

	public AreaConocimiento(int arcnId, AreaConocimiento arcnAreaConocimiento, String arcnDescripcion, String arcnCodigo,
			Integer arcnJerarquia, List<PuestoAreaConocimiento> arcnPuestoAreaConocimientos,
			List<AreaConocimiento> arcnAreaConocimientos) {
		this.arcnId = arcnId;
		this.arcnAreaConocimiento = arcnAreaConocimiento;
		this.arcnDescripcion = arcnDescripcion;
		this.arcnCodigo = arcnCodigo;
		this.arcnJerarquia = arcnJerarquia;
		this.arcnPuestoAreaConocimientos = arcnPuestoAreaConocimientos;
		this.arcnAreaConocimientos = arcnAreaConocimientos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ARCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getArcnId() {
		return this.arcnId;
	}

	public void setArcnId(int arcnId) {
		this.arcnId = arcnId;
	}

	@ManyToOne
	@JoinColumn(name = "ARCN_SUB_ID")
	public AreaConocimiento getArcnAreaConocimiento() {
		return this.arcnAreaConocimiento;
	}

	public void setArcnAreaConocimiento(AreaConocimiento arcnAreaConocimiento) {
		this.arcnAreaConocimiento = arcnAreaConocimiento;
	}

	@Column(name = "ARCN_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getArcnDescripcion() {
		return this.arcnDescripcion;
	}

	public void setArcnDescripcion(String arcnDescripcion) {
		this.arcnDescripcion = arcnDescripcion;
	}

	@Column(name = "ARCN_CODIGO", length = 10)
	@Length(max = 10)
	public String getArcnCodigo() {
		return this.arcnCodigo;
	}

	public void setArcnCodigo(String arcnCodigo) {
		this.arcnCodigo = arcnCodigo;
	}

	@Column(name = "ARCN_JERARQUIA", precision = 22, scale = 0)
	public Integer getArcnJerarquia() {
		return this.arcnJerarquia;
	}

	public void setArcnJerarquia(Integer arcnJerarquia) {
		this.arcnJerarquia = arcnJerarquia;
	}

	@OneToMany( mappedBy = "psarcnAreaConocimiento")
	public List<PuestoAreaConocimiento> getArcnPuestoAreaConocimientos() {
		return this.arcnPuestoAreaConocimientos;
	}

	public void setArcnPuestoAreaConocimientos(List<PuestoAreaConocimiento> arcnPuestoAreaConocimientos) {
		this.arcnPuestoAreaConocimientos = arcnPuestoAreaConocimientos;
	}

	@OneToMany( mappedBy = "arcnAreaConocimiento")
	public List<AreaConocimiento> getArcnAreaConocimientos() {
		return this.arcnAreaConocimientos;
	}

	public void setArcnAreaConocimientos(List<AreaConocimiento> arcnAreaConocimientos) {
		this.arcnAreaConocimientos = arcnAreaConocimientos;
	}

}
