package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * AsignaPresupuesto generated by hbm2java
 */
@Entity
@Table(name = "ASIGNA_PRESUPUESTO", schema = ConstantesJpa.SCHEMA)
public class AsignaPresupuesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8208259838113068491L;
	private int asprId;
	private ProcesoTramiteContrato asprProcesoTramiteContrato;
	private String asprPartidaPresupuesto;
	private Integer asprEstado;
	private String asprArchivoCertificacion;

	public AsignaPresupuesto() {
	}

	public AsignaPresupuesto(int asprId) {
		this.asprId = asprId;
	}

	public AsignaPresupuesto(int asprId, ProcesoTramiteContrato asprProcesoTramiteContrato, String asprPartidaPresupuesto,
			Integer asprEstado, String asprArchivoCertificacion) {
		this.asprId = asprId;
		this.asprProcesoTramiteContrato = asprProcesoTramiteContrato;
		this.asprPartidaPresupuesto = asprPartidaPresupuesto;
		this.asprEstado = asprEstado;
		this.asprArchivoCertificacion = asprArchivoCertificacion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ASPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAsprId() {
		return this.asprId;
	}

	public void setAsprId(int asprId) {
		this.asprId = asprId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getAsprProcesoTramiteContrato() {
		return this.asprProcesoTramiteContrato;
	}

	public void setAsprProcesoTramiteContrato(ProcesoTramiteContrato asprProcesoTramiteContrato) {
		this.asprProcesoTramiteContrato = asprProcesoTramiteContrato;
	}

	@Column(name = "ASPR_PARTIDA_PRESUPUESTO", length = 50)
	@Length(max = 50)
	public String getAsprPartidaPresupuesto() {
		return this.asprPartidaPresupuesto;
	}

	public void setAsprPartidaPresupuesto(String asprPartidaPresupuesto) {
		this.asprPartidaPresupuesto = asprPartidaPresupuesto;
	}

	@Column(name = "ASPR_ESTADO", precision = 22, scale = 0)
	public Integer getAsprEstado() {
		return this.asprEstado;
	}

	public void setAsprEstado(Integer asprEstado) {
		this.asprEstado = asprEstado;
	}

	@Column(name = "ASPR_ARCHIVO_CERTIFICACION", length = 256)
	@Length(max = 256)
	public String getAsprArchivoCertificacion() {
		return this.asprArchivoCertificacion;
	}

	public void setAsprArchivoCertificacion(String asprArchivoCertificacion) {
		this.asprArchivoCertificacion = asprArchivoCertificacion;
	}

}
