package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Aula generated by hbm2java
 */
@Entity
@Table(name = "AULA", schema = ConstantesJpa.SCHEMA)
public class Aula implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7143395407547322201L;
	private int alaId;
	private Edificio alaEdificio;
	private String alaDescripcion;
	private String alaCodigo;
	private Integer alaTipo;
	private Integer alaCapacidad;
	private Integer alaPiso;
	private Integer alaEstado;
	private List<HoraClaseAula> alaHoraClaseAulas = new ArrayList<HoraClaseAula>(0);

	public Aula() {
	}

	public Aula(int alaId) {
		this.alaId = alaId;
	}

	public Aula(int alaId, Edificio alaEdificio, String alaDescripcion, String alaCodigo, Integer alaTipo,
			Integer alaCapacidad, Integer alaPiso, Integer alaEstado, List<HoraClaseAula> alaHoraClaseAulas) {
		this.alaId = alaId;
		this.alaEdificio = alaEdificio;
		this.alaDescripcion = alaDescripcion;
		this.alaCodigo = alaCodigo;
		this.alaTipo = alaTipo;
		this.alaCapacidad = alaCapacidad;
		this.alaPiso = alaPiso;
		this.alaEstado = alaEstado;
		this.alaHoraClaseAulas = alaHoraClaseAulas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ALA_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAlaId() {
		return this.alaId;
	}

	public void setAlaId(int alaId) {
		this.alaId = alaId;
	}

	@ManyToOne
	@JoinColumn(name = "EDF_ID")
	public Edificio getAlaEdificio() {
		return this.alaEdificio;
	}

	public void setAlaEdificio(Edificio alaEdificio) {
		this.alaEdificio = alaEdificio;
	}

	@Column(name = "ALA_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getAlaDescripcion() {
		return this.alaDescripcion;
	}

	public void setAlaDescripcion(String alaDescripcion) {
		this.alaDescripcion = alaDescripcion;
	}

	@Column(name = "ALA_CODIGO", length = 256)
	@Length(max = 256)
	public String getAlaCodigo() {
		return this.alaCodigo;
	}

	public void setAlaCodigo(String alaCodigo) {
		this.alaCodigo = alaCodigo;
	}

	@Column(name = "ALA_TIPO", precision = 22, scale = 0)
	public Integer getAlaTipo() {
		return this.alaTipo;
	}

	public void setAlaTipo(Integer alaTipo) {
		this.alaTipo = alaTipo;
	}

	@Column(name = "ALA_CAPACIDAD", precision = 22, scale = 0)
	public Integer getAlaCapacidad() {
		return this.alaCapacidad;
	}

	public void setAlaCapacidad(Integer alaCapacidad) {
		this.alaCapacidad = alaCapacidad;
	}

	@Column(name = "ALA_PISO", precision = 22, scale = 0)
	public Integer getAlaPiso() {
		return this.alaPiso;
	}

	public void setAlaPiso(Integer alaPiso) {
		this.alaPiso = alaPiso;
	}

	@OneToMany( mappedBy = "hoclalAula")
	public List<HoraClaseAula> getAlaHoraClaseAulas() {
		return this.alaHoraClaseAulas;
	}

	public void setAlaHoraClaseAulas(List<HoraClaseAula> alaHoraClaseAulas) {
		this.alaHoraClaseAulas = alaHoraClaseAulas;
	}
	
	@Column(name = "ALA_ESTADO", precision = 2, scale = 0)
	public Integer getAlaEstado() {
		return this.alaEstado;
	}

	public void setAlaEstado(Integer alaEstado) {
		this.alaEstado = alaEstado;
	}

}
