package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * CandidatoContrato generated by hbm2java
 */
@Entity
@Table(name = "CANDIDATO_CONTRATO", schema = ConstantesJpa.SCHEMA)
public class CandidatoContrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2312806778356055073L;
	private int cncnId;
	private Persona cncnPersona;
	private ProcesoTramiteContrato cncnProcesoTramiteContrato;
	private Integer cncnEstado;
	private String cncnObsRectorado;
	private String cncnTercerNivel;
	private String cncnCuartoNivel;
	private Integer cncnImpedimento;
	private String cncnObsImpedimento;
	private String cncnArchivoImpedimento;
	private Integer cncnLaboraOtraInst;
	private String cncnObsLaboraOtraInst;
	private String cncnArchivoLaboraInst;
	private List<ExperienciaLaboralContr> cncnExperienciaLaboralContrs = new ArrayList<ExperienciaLaboralContr>(0);

	public CandidatoContrato() {
	}

	public CandidatoContrato(int cncnId) {
		this.cncnId = cncnId;
	}

	public CandidatoContrato(int cncnId, Persona cncnPersona, ProcesoTramiteContrato cncnProcesoTramiteContrato,
			Integer cncnEstado, String cncnObsRectorado, String cncnTercerNivel, String cncnCuartoNivel,
			Integer cncnImpedimento, String cncnObsImpedimento, String cncnArchivoImpedimento,
			Integer cncnLaboraOtraInst, String cncnObsLaboraOtraInst, String cncnArchivoLaboraInst,
			List<ExperienciaLaboralContr> cncnExperienciaLaboralContrs) {
		this.cncnId = cncnId;
		this.cncnPersona = cncnPersona;
		this.cncnProcesoTramiteContrato = cncnProcesoTramiteContrato;
		this.cncnEstado = cncnEstado;
		this.cncnObsRectorado = cncnObsRectorado;
		this.cncnTercerNivel = cncnTercerNivel;
		this.cncnCuartoNivel = cncnCuartoNivel;
		this.cncnImpedimento = cncnImpedimento;
		this.cncnObsImpedimento = cncnObsImpedimento;
		this.cncnArchivoImpedimento = cncnArchivoImpedimento;
		this.cncnLaboraOtraInst = cncnLaboraOtraInst;
		this.cncnObsLaboraOtraInst = cncnObsLaboraOtraInst;
		this.cncnArchivoLaboraInst = cncnArchivoLaboraInst;
		this.cncnExperienciaLaboralContrs = cncnExperienciaLaboralContrs;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CNCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCncnId() {
		return this.cncnId;
	}

	public void setCncnId(int cncnId) {
		this.cncnId = cncnId;
	}

	@ManyToOne
	@JoinColumn(name = "PRS_ID")
	public Persona getCncnPersona() {
		return this.cncnPersona;
	}

	public void setCncnPersona(Persona cncnPersona) {
		this.cncnPersona = cncnPersona;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getCncnProcesoTramiteContrato() {
		return this.cncnProcesoTramiteContrato;
	}

	public void setCncnProcesoTramiteContrato(ProcesoTramiteContrato cncnProcesoTramiteContrato) {
		this.cncnProcesoTramiteContrato = cncnProcesoTramiteContrato;
	}

	@Column(name = "CNCN_ESTADO", precision = 22, scale = 0)
	public Integer getCncnEstado() {
		return this.cncnEstado;
	}

	public void setCncnEstado(Integer cncnEstado) {
		this.cncnEstado = cncnEstado;
	}

	@Column(name = "CNCN_OBS_RECTORADO", length = 512)
	@Length(max = 512)
	public String getCncnObsRectorado() {
		return this.cncnObsRectorado;
	}

	public void setCncnObsRectorado(String cncnObsRectorado) {
		this.cncnObsRectorado = cncnObsRectorado;
	}

	@Column(name = "CNCN_TERCER_NIVEL", length = 512)
	@Length(max = 512)
	public String getCncnTercerNivel() {
		return this.cncnTercerNivel;
	}

	public void setCncnTercerNivel(String cncnTercerNivel) {
		this.cncnTercerNivel = cncnTercerNivel;
	}

	@Column(name = "CNCN_CUARTO_NIVEL", length = 512)
	@Length(max = 512)
	public String getCncnCuartoNivel() {
		return this.cncnCuartoNivel;
	}

	public void setCncnCuartoNivel(String cncnCuartoNivel) {
		this.cncnCuartoNivel = cncnCuartoNivel;
	}

	@Column(name = "CNCN_IMPEDIMENTO", precision = 22, scale = 0)
	public Integer getCncnImpedimento() {
		return this.cncnImpedimento;
	}

	public void setCncnImpedimento(Integer cncnImpedimento) {
		this.cncnImpedimento = cncnImpedimento;
	}

	@Column(name = "CNCN_OBS_IMPEDIMENTO", length = 512)
	@Length(max = 512)
	public String getCncnObsImpedimento() {
		return this.cncnObsImpedimento;
	}

	public void setCncnObsImpedimento(String cncnObsImpedimento) {
		this.cncnObsImpedimento = cncnObsImpedimento;
	}

	@Column(name = "CNCN_ARCHIVO_IMPEDIMENTO", length = 256)
	@Length(max = 256)
	public String getCncnArchivoImpedimento() {
		return this.cncnArchivoImpedimento;
	}

	public void setCncnArchivoImpedimento(String cncnArchivoImpedimento) {
		this.cncnArchivoImpedimento = cncnArchivoImpedimento;
	}

	@Column(name = "CNCN_LABORA_OTRA_INST", precision = 22, scale = 0)
	public Integer getCncnLaboraOtraInst() {
		return this.cncnLaboraOtraInst;
	}

	public void setCncnLaboraOtraInst(Integer cncnLaboraOtraInst) {
		this.cncnLaboraOtraInst = cncnLaboraOtraInst;
	}

	@Column(name = "CNCN_OBS_LABORA_OTRA_INST", length = 256)
	@Length(max = 256)
	public String getCncnObsLaboraOtraInst() {
		return this.cncnObsLaboraOtraInst;
	}

	public void setCncnObsLaboraOtraInst(String cncnObsLaboraOtraInst) {
		this.cncnObsLaboraOtraInst = cncnObsLaboraOtraInst;
	}

	@Column(name = "CNCN_ARCHIVO_LABORA_INST", length = 256)
	@Length(max = 256)
	public String getCncnArchivoLaboraInst() {
		return this.cncnArchivoLaboraInst;
	}

	public void setCncnArchivoLaboraInst(String cncnArchivoLaboraInst) {
		this.cncnArchivoLaboraInst = cncnArchivoLaboraInst;
	}

	@OneToMany( mappedBy = "exlbcnCandidatoContrato")
	public List<ExperienciaLaboralContr> getCncnExperienciaLaboralContrs() {
		return this.cncnExperienciaLaboralContrs;
	}

	public void setCncnExperienciaLaboralContrs(List<ExperienciaLaboralContr> cncnExperienciaLaboralContrs) {
		this.cncnExperienciaLaboralContrs = cncnExperienciaLaboralContrs;
	}

}
