package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * CargaHorariaContrato generated by hbm2java
 */
@Entity
@Table(name = "CARGA_HORARIA_CONTRATO", schema = ConstantesJpa.SCHEMA)
public class CargaHorariaContrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1259138489738730284L;
	private int crhrcnId;
	private ProcesoTramiteContrato crhrProcesoTramiteContrato;
	private Integer crhrcnHoraClase;
	private Integer crhrcnHoraVinculacion;
	private Integer crhrcnTutoria;
	private Integer crhrcnPreparacionClase;

	public CargaHorariaContrato() {
	}

	public CargaHorariaContrato(int crhrcnId) {
		this.crhrcnId = crhrcnId;
	}

	public CargaHorariaContrato(int crhrcnId, ProcesoTramiteContrato crhrProcesoTramiteContrato, Integer crhrcnHoraClase,
			Integer crhrcnHoraVinculacion, Integer crhrcnTutoria, Integer crhrcnPreparacionClase) {
		this.crhrcnId = crhrcnId;
		this.crhrProcesoTramiteContrato = crhrProcesoTramiteContrato;
		this.crhrcnHoraClase = crhrcnHoraClase;
		this.crhrcnHoraVinculacion = crhrcnHoraVinculacion;
		this.crhrcnTutoria = crhrcnTutoria;
		this.crhrcnPreparacionClase = crhrcnPreparacionClase;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CRHRCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCrhrcnId() {
		return this.crhrcnId;
	}

	public void setCrhrcnId(int crhrcnId) {
		this.crhrcnId = crhrcnId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getCrhrProcesoTramiteContrato() {
		return this.crhrProcesoTramiteContrato;
	}

	public void setCrhrProcesoTramiteContrato(ProcesoTramiteContrato crhrProcesoTramiteContrato) {
		this.crhrProcesoTramiteContrato = crhrProcesoTramiteContrato;
	}

	@Column(name = "CRHRCN_HORA_CLASE", precision = 22, scale = 0)
	public Integer getCrhrcnHoraClase() {
		return this.crhrcnHoraClase;
	}

	public void setCrhrcnHoraClase(Integer crhrcnHoraClase) {
		this.crhrcnHoraClase = crhrcnHoraClase;
	}

	@Column(name = "CRHRCN_HORA_VINCULACION", precision = 22, scale = 0)
	public Integer getCrhrcnHoraVinculacion() {
		return this.crhrcnHoraVinculacion;
	}

	public void setCrhrcnHoraVinculacion(Integer crhrcnHoraVinculacion) {
		this.crhrcnHoraVinculacion = crhrcnHoraVinculacion;
	}

	@Column(name = "CRHRCN_TUTORIA", precision = 22, scale = 0)
	public Integer getCrhrcnTutoria() {
		return this.crhrcnTutoria;
	}

	public void setCrhrcnTutoria(Integer crhrcnTutoria) {
		this.crhrcnTutoria = crhrcnTutoria;
	}

	@Column(name = "CRHRCN_PREPARACION_CLASE", precision = 22, scale = 0)
	public Integer getCrhrcnPreparacionClase() {
		return this.crhrcnPreparacionClase;
	}

	public void setCrhrcnPreparacionClase(Integer crhrcnPreparacionClase) {
		this.crhrcnPreparacionClase = crhrcnPreparacionClase;
	}

}
