package ec.edu.uce.academico.jpa.entidades.publico;
//MQ: Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * CausalDetalleMatricula generated by hbm2java
 */
@Entity
@Table(name = "CAUSAL_DETALLE_MATRICULA", schema = ConstantesJpa.SCHEMA)
public class CausalDetalleMatricula implements java.io.Serializable {

	private static final long serialVersionUID = -6269604753546906848L;
	
	private int csdtmtId;
	private Causal csdtmtCausal;
	private DetalleMatricula csdtmtDetalleMatricula;
	
	public CausalDetalleMatricula() {
	}

	public CausalDetalleMatricula(int csdtmtId) {
		this.csdtmtId = csdtmtId;
	}

	
	public CausalDetalleMatricula(int csdtmtId,  Causal csdtmtCausal, DetalleMatricula	csdtmtDetalleMatricula) {
		this.csdtmtId = csdtmtId;
		this.csdtmtCausal = csdtmtCausal;
		this.csdtmtDetalleMatricula = csdtmtDetalleMatricula;
	
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CSDTMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCsdtmtId() {
		return this.csdtmtId;
	}

	public void setCsdtmtId(int csdtmtId) {
		this.csdtmtId = csdtmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CSL_ID")
	public Causal getCsdtmtCausal() {
		return this.csdtmtCausal;
	}

	public void setCsdtmtCausal(Causal csdtmtCausal) {
		this.csdtmtCausal = csdtmtCausal;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTMT_ID")
	public DetalleMatricula getCsdtmtDetalleMatricula() {
		return this.csdtmtDetalleMatricula;
	}

	public void setCsdtmtDetalleMatricula(DetalleMatricula csdtmtDetalleMatricula) {
		this.csdtmtDetalleMatricula = csdtmtDetalleMatricula;
	}

	

}
