package ec.edu.uce.academico.jpa.entidades.publico;
// Manual 17/01/2018 16:05:22 by MQ

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Causal generated by hbm2java
 */
@Entity
@Table(name = "CAUSAL", schema = ConstantesJpa.SCHEMA)
public class Causal implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8577735696861737371L;
	private int cslId;
	private TipoCausal cslTipoCausal;
	private String cslDescripcion;
	private String cslCodigo;
	private Integer cslEstado;
	
	private List<SolicitudTerceraMatricula> cslSolicitudesTerceraMatricula = new ArrayList<SolicitudTerceraMatricula>(0);
	private List<CausalDetalleMatricula> cslCausalDetalleMatriculas = new ArrayList<CausalDetalleMatricula>(0);
	
	
	public Causal() {
	}

	public Causal(int cslId) {
		this.cslId = cslId;
	}

	public Causal(int cslId, TipoCausal cslTipoCausal,  String cslDescripcion,String cslCodigo, Integer cslEstado, List<SolicitudTerceraMatricula> cslSolicitudesTerceraMatricula, List<CausalDetalleMatricula> cslCausalDetalleMatriculas) {
		this.cslId = cslId;
		this.cslTipoCausal = cslTipoCausal;
		this.cslDescripcion = cslDescripcion;
		this.cslCodigo = cslCodigo;
		this.cslEstado = cslEstado;
		
		this.cslSolicitudesTerceraMatricula = cslSolicitudesTerceraMatricula; 
		this.cslCausalDetalleMatriculas = cslCausalDetalleMatriculas; 
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CSL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCslId() {
		return this.cslId;
	}

	public void setCslId(int cslId) {
		this.cslId = cslId;
	}

	@ManyToOne
	@JoinColumn(name = "TICS_ID")
	public TipoCausal getCslTipoCausal() {
		return this.cslTipoCausal;
	}

	public void setCslTipoCausal(TipoCausal cslTipoCausal) {
		this.cslTipoCausal = cslTipoCausal;
	}
	
	@Column(name = "CSL_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getCslDescripcion() {
		return this.cslDescripcion;
	}

	public void setCslDescripcion(String cslDescripcion) {
		this.cslDescripcion = cslDescripcion;
	}

	
	
	@Column(name = "CSL_CODIGO", length = 10)
	@Length(max = 10)
	public String getCslCodigo() {
		return this.cslCodigo;
	}

	public void setCslCodigo(String cslCodigo) {
		this.cslCodigo = cslCodigo;
	}
	
	@Column(name = "CSL_ESTADO", precision = 22, scale = 0)
	public Integer getCslEstado() {
		return this.cslEstado;
	}

	public void setCslEstado(Integer cslEstado) {
		this.cslEstado = cslEstado;
	}

	

	@OneToMany( mappedBy = "sltrmtCausal")
	public List<SolicitudTerceraMatricula> getCslSolicitudesTerceraMatricula() {
		return this.cslSolicitudesTerceraMatricula;
	}

	public void setCslSolicitudesTerceraMatricula(List<SolicitudTerceraMatricula> cslSolicitudesTerceraMatricula) {
		this.cslSolicitudesTerceraMatricula = cslSolicitudesTerceraMatricula;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "csdtmtCausal")
	public List<CausalDetalleMatricula> getCslCausalDetalleMatriculas() {
		return this.cslCausalDetalleMatriculas;
	}

	public void setCslCausalDetalleMatriculas(List<CausalDetalleMatricula> cslCausalDetalleMatriculas) {
		this.cslCausalDetalleMatriculas = cslCausalDetalleMatriculas;
	}

}
