package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Competencia generated by hbm2java
 */
@Entity
@Table(name = "COMPETENCIA", schema = ConstantesJpa.SCHEMA)
public class Competencia implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6138324416920081913L;
	private int cmpId;
	private String cmpDenominacion;
	private String cmpDefinicion;
	private Integer cmpTipo;
	private List<NivelCompetencia> cmpNivelCompetencias = new ArrayList<NivelCompetencia>(0);

	public Competencia() {
	}

	public Competencia(int cmpId) {
		this.cmpId = cmpId;
	}

	public Competencia(int cmpId, String cmpDenominacion, String cmpDefinicion, Integer cmpTipo,
			List<NivelCompetencia> cmpNivelCompetencias) {
		this.cmpId = cmpId;
		this.cmpDenominacion = cmpDenominacion;
		this.cmpDefinicion = cmpDefinicion;
		this.cmpTipo = cmpTipo;
		this.cmpNivelCompetencias = cmpNivelCompetencias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CMP_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCmpId() {
		return this.cmpId;
	}

	public void setCmpId(int cmpId) {
		this.cmpId = cmpId;
	}

	@Column(name = "CMP_DENOMINACION", length = 512)
	@Length(max = 512)
	public String getCmpDenominacion() {
		return this.cmpDenominacion;
	}

	public void setCmpDenominacion(String cmpDenominacion) {
		this.cmpDenominacion = cmpDenominacion;
	}

	@Column(name = "CMP_DEFINICION", length = 512)
	@Length(max = 512)
	public String getCmpDefinicion() {
		return this.cmpDefinicion;
	}

	public void setCmpDefinicion(String cmpDefinicion) {
		this.cmpDefinicion = cmpDefinicion;
	}

	@Column(name = "CMP_TIPO", precision = 22, scale = 0)
	public Integer getCmpTipo() {
		return this.cmpTipo;
	}

	public void setCmpTipo(Integer cmpTipo) {
		this.cmpTipo = cmpTipo;
	}

	@OneToMany( mappedBy = "nvcmCompetencia")
	public List<NivelCompetencia> getCmpNivelCompetencias() {
		return this.cmpNivelCompetencias;
	}

	public void setCmpNivelCompetencias(List<NivelCompetencia> cmpNivelCompetencias) {
		this.cmpNivelCompetencias = cmpNivelCompetencias;
	}

}
