package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * CompetenciaPuesto generated by hbm2java
 */
@Entity
@Table(name = "COMPETENCIA_PUESTO", schema = ConstantesJpa.SCHEMA)
public class CompetenciaPuesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4153222722798754233L;
	private int cmpsId;
	private NivelCompetencia cmpsNivelCompetencia;
	private Puesto cmpsPuesto;

	public CompetenciaPuesto() {
	}

	public CompetenciaPuesto(int cmpsId) {
		this.cmpsId = cmpsId;
	}

	public CompetenciaPuesto(int cmpsId, NivelCompetencia cmpsNivelCompetencia, Puesto cmpsPuesto) {
		this.cmpsId = cmpsId;
		this.cmpsNivelCompetencia = cmpsNivelCompetencia;
		this.cmpsPuesto = cmpsPuesto;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "CMPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCmpsId() {
		return this.cmpsId;
	}

	public void setCmpsId(int cmpsId) {
		this.cmpsId = cmpsId;
	}

	@ManyToOne
	@JoinColumn(name = "NVCM_ID")
	public NivelCompetencia getCmpsNivelCompetencia() {
		return this.cmpsNivelCompetencia;
	}

	public void setCmpsNivelCompetencia(NivelCompetencia cmpsNivelCompetencia) {
		this.cmpsNivelCompetencia = cmpsNivelCompetencia;
	}

	@ManyToOne
	@JoinColumn(name = "PST_ID")
	public Puesto getCmpsPuesto() {
		return this.cmpsPuesto;
	}

	public void setCmpsPuesto(Puesto cmpsPuesto) {
		this.cmpsPuesto = cmpsPuesto;
	}

}
