package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ConfiguracionCarrera generated by hbm2java
 */
@Entity
@Table(name = "CONFIGURACION_CARRERA", schema = ConstantesJpa.SCHEMA)
public class ConfiguracionCarrera implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7655980633982267729L;
	private int cncrId;
	private Ubicacion cncrUbicacion;
	private TipoSede cncrTipoSede;
	private Titulo cncrTitulo;
	private TipoFormacion cncrTipoFormacion;
	private Carrera cncrCarrera;
	private Duracion cncrDuracion;
	private Vigencia cncrVigencia;
	private Modalidad cncrModalidad;
	private List<FichaInscripcion> cncrFichaInscripciones= new ArrayList<FichaInscripcion>(0);

	public ConfiguracionCarrera() {
	}

	public ConfiguracionCarrera(int cncrId) {
		this.cncrId = cncrId;
	}

	public ConfiguracionCarrera(int cncrId, Ubicacion cncrUbicacion, TipoSede cncrTipoSede, Titulo cncrTitulo,
			TipoFormacion cncrTipoFormacion, Carrera cncrCarrera, Duracion cncrDuracion, Vigencia cncrVigencia, 
			Modalidad cncrModalidad, List<FichaInscripcion> cncrFichaInscripciones) {
		this.cncrId = cncrId;
		this.cncrUbicacion = cncrUbicacion;
		this.cncrTipoSede = cncrTipoSede;
		this.cncrTitulo = cncrTitulo;
		this.cncrTipoFormacion = cncrTipoFormacion;
		this.cncrCarrera = cncrCarrera;
		this.cncrDuracion = cncrDuracion;
		this.cncrVigencia = cncrVigencia;
		this.cncrModalidad = cncrModalidad;
		this.cncrFichaInscripciones = cncrFichaInscripciones;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CNCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCncrId() {
		return this.cncrId;
	}

	public void setCncrId(int cncrId) {
		this.cncrId = cncrId;
	}

	@ManyToOne
	@JoinColumn(name = "UBC_ID")
	public Ubicacion getCncrUbicacion() {
		return this.cncrUbicacion;
	}

	public void setCncrUbicacion(Ubicacion cncrUbicacion) {
		this.cncrUbicacion = cncrUbicacion;
	}

	@ManyToOne
	@JoinColumn(name = "TISE_ID")
	public TipoSede getCncrTipoSede() {
		return this.cncrTipoSede;
	}

	public void setCncrTipoSede(TipoSede cncrTipoSede) {
		this.cncrTipoSede = cncrTipoSede;
	}

	@ManyToOne
	@JoinColumn(name = "TTL_ID")
	public Titulo getCncrTitulo() {
		return this.cncrTitulo;
	}

	public void setCncrTitulo(Titulo cncrTitulo) {
		this.cncrTitulo = cncrTitulo;
	}

	@ManyToOne
	@JoinColumn(name = "TIFR_ID")
	public TipoFormacion getCncrTipoFormacion() {
		return this.cncrTipoFormacion;
	}

	public void setCncrTipoFormacion(TipoFormacion cncrTipoFormacion) {
		this.cncrTipoFormacion = cncrTipoFormacion;
	}

	@ManyToOne
	@JoinColumn(name = "CRR_ID")
	public Carrera getCncrCarrera() {
		return this.cncrCarrera;
	}

	public void setCncrCarrera(Carrera cncrCarrera) {
		this.cncrCarrera = cncrCarrera;
	}

	@ManyToOne
	@JoinColumn(name = "DRC_ID")
	public Duracion getCncrDuracion() {
		return this.cncrDuracion;
	}

	public void setCncrDuracion(Duracion cncrDuracion) {
		this.cncrDuracion = cncrDuracion;
	}

	@ManyToOne
	@JoinColumn(name = "VGN_ID")
	public Vigencia getCncrVigencia() {
		return this.cncrVigencia;
	}

	public void setCncrVigencia(Vigencia cncrVigencia) {
		this.cncrVigencia = cncrVigencia;
	}

	@ManyToOne
	@JoinColumn(name = "MDL_ID")
	public Modalidad getCncrModalidad() {
		return this.cncrModalidad;
	}

	public void setCncrModalidad(Modalidad cncrModalidad) {
		this.cncrModalidad = cncrModalidad;
	}

	@OneToMany(mappedBy = "fcinConfiguracionCarrera")
	public List<FichaInscripcion> getCncrFichaInscripciones() {
		return cncrFichaInscripciones;
	}

	public void setCncrFichaInscripciones(List<FichaInscripcion> cncrFichaInscripciones) {
		this.cncrFichaInscripciones = cncrFichaInscripciones;
	}

}
