package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ConocimientoPuesto generated by hbm2java
 */
@Entity
@Table(name = "CONOCIMIENTO_PUESTO", schema = ConstantesJpa.SCHEMA)
public class ConocimientoPuesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4528369538757915204L;
	private int cnpsId;
	private Puesto cnpsPuesto;
	private Conocimiento cnpsConocimiento;

	public ConocimientoPuesto() {
	}

	public ConocimientoPuesto(int cnpsId) {
		this.cnpsId = cnpsId;
	}

	public ConocimientoPuesto(int cnpsId, Puesto cnpsPuesto, Conocimiento cnpsConocimiento) {
		this.cnpsId = cnpsId;
		this.cnpsPuesto = cnpsPuesto;
		this.cnpsConocimiento = cnpsConocimiento;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "CNPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCnpsId() {
		return this.cnpsId;
	}

	public void setCnpsId(int cnpsId) {
		this.cnpsId = cnpsId;
	}

	@ManyToOne
	@JoinColumn(name = "PST_ID")
	public Puesto getCnpsPuesto() {
		return this.cnpsPuesto;
	}

	public void setCnpsPuesto(Puesto cnpsPuesto) {
		this.cnpsPuesto = cnpsPuesto;
	}

	@ManyToOne
	@JoinColumn(name = "CNC_ID")
	public Conocimiento getCnpsConocimiento() {
		return this.cnpsConocimiento;
	}

	public void setCnpsConocimiento(Conocimiento cnpsConocimiento) {
		this.cnpsConocimiento = cnpsConocimiento;
	}

}
