package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Conocimiento generated by hbm2java
 */
@Entity
@Table(name = "CONOCIMIENTO", schema = ConstantesJpa.SCHEMA)
public class Conocimiento implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1615179204129671313L;
	private int cncId;
	private String cncDescripcion;
	private List<ConocimientoPuesto> cncConocimientoPuestos = new ArrayList<ConocimientoPuesto>(0);

	public Conocimiento() {
	}

	public Conocimiento(int cncId) {
		this.cncId = cncId;
	}

	public Conocimiento(int cncId, String cncDescripcion, List<ConocimientoPuesto> cncConocimientoPuestos) {
		this.cncId = cncId;
		this.cncDescripcion = cncDescripcion;
		this.cncConocimientoPuestos = cncConocimientoPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CNC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCncId() {
		return this.cncId;
	}

	public void setCncId(int cncId) {
		this.cncId = cncId;
	}

	@Column(name = "CNC_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getCncDescripcion() {
		return this.cncDescripcion;
	}

	public void setCncDescripcion(String cncDescripcion) {
		this.cncDescripcion = cncDescripcion;
	}

	@OneToMany( mappedBy = "cnpsConocimiento")
	public List<ConocimientoPuesto> getCncConocimientoPuestos() {
		return this.cncConocimientoPuestos;
	}

	public void setCncConocimientoPuestos(List<ConocimientoPuesto> cncConocimientoPuestos) {
		this.cncConocimientoPuestos = cncConocimientoPuestos;
	}

}
