package ec.edu.uce.academico.jpa.entidades.publico;
// Manual 11/05/2018 11:14:22 by MQ
import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**MQ
 * SolicitudTerceraMatricula generated by hbm2java
 */
@Entity
@Table(name = "CONTROL_PROCESO", schema = ConstantesJpa.SCHEMA)
public class ControlProceso implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1828910417871903627L;
	private int cnprId;
	private UsuarioRol cnprUsuarioRol; //relacion en Usuario rol(muchos)
	private TipoProceso cnprTipoProceso;  //relacion en tipo proceso(muchos)
	private String cnprDetalleProceso;
	private Integer cnprTipoAccion; //Insertar, modificar, borrar
	private Timestamp cnprFechaAccion;
	private String cnprObservacionAccion;
	
	public ControlProceso() {
	}

	public ControlProceso(int cnprId) {
		this.cnprId = cnprId;
	}

	public ControlProceso(int cnprId, UsuarioRol cnprUsuarioRol, TipoProceso cnprTipoProceso,
			String cnprDetalleProceso,Integer cnprTipoAccion, Timestamp cnprFechaAccion,  String cnprObservacionAccion) {
		this.cnprId = cnprId;
		this.cnprUsuarioRol = cnprUsuarioRol;
		this.cnprTipoProceso = cnprTipoProceso;
		this.cnprDetalleProceso = cnprDetalleProceso;
		this.cnprTipoAccion = cnprTipoAccion;
		this.cnprFechaAccion = cnprFechaAccion;
		this.cnprObservacionAccion = cnprObservacionAccion;
			
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CNPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCnprId() {
		return this.cnprId;
	}

	public void setCnprId(int cnprId) {
		this.cnprId = cnprId;
	}

	@ManyToOne
	@JoinColumn(name = "TIPR_ID")
	public TipoProceso getCnprTipoProceso() {
		return this.cnprTipoProceso;
	}

	public void setCnprTipoProceso(TipoProceso cnprTipoProceso) {
		this.cnprTipoProceso = cnprTipoProceso;
	}

	@ManyToOne
	@JoinColumn(name = "USRO_ID")
	public UsuarioRol getCnprUsuarioRol() {
		return this.cnprUsuarioRol;
	}

	public void setCnprUsuarioRol(UsuarioRol cnprUsuarioRol) {
		this.cnprUsuarioRol = cnprUsuarioRol;
	}

	
	@Column(name = "CNPR_DETALLE_PROCESO", length = 512)
	@Length(max = 512)
	public String getCnprDetalleProceso() {
		return this.cnprDetalleProceso;
	}

	public void setCnprDetalleProceso(String cnprDetalleProceso) {
		this.cnprDetalleProceso = cnprDetalleProceso;
	}
	
	@Column(name = "CNPR_TIPO_ACCION", precision = 2, scale = 0)
	public Integer getCnprTipoAccion() {
		return this.cnprTipoAccion;
	}

	public void setCnprTipoAccion(Integer cnprTipoAccion) {
		this.cnprTipoAccion = cnprTipoAccion;
	}

	@Column(name = "CNPR_FECHA_ACCION")
	public Timestamp getCnprFechaAccion() {
		return cnprFechaAccion;
	}

	public void setCnprFechaAccion(Timestamp cnprFechaAccion) {
		this.cnprFechaAccion = cnprFechaAccion;
	}
	
	
	@Column(name = "CNPR_OBSERVACION_ACCION", length = 512)
	@Length(max = 512)
	public String getCnprObservacionAccion() {
		return this.cnprObservacionAccion;
	}

	public void setCnprObservacionAccion(String cnprObservacionAccion) {
		this.cnprObservacionAccion = cnprObservacionAccion;
	}
	
	
	

	
	
	
	
}
