package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "CONTRATO", schema = ConstantesJpa.SCHEMA)
public class Contrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4181179806781539348L;
	private int cntId;
	private TipoFinanciamiento cntTipoFinanciamiento;
	private TipoContrato cntTipoContrato;
	private List<DetalleTramiteContrato> cntDetalleTramiteContratos = new ArrayList<DetalleTramiteContrato>(0);

	public Contrato() {
	}

	public Contrato(int cntId) {
		this.cntId = cntId;
	}

	public Contrato(int cntId, TipoFinanciamiento cntTipoFinanciamiento, TipoContrato cntTipoContrato,
			List<DetalleTramiteContrato> cntDetalleTramiteContratos) {
		this.cntId = cntId;
		this.cntTipoFinanciamiento = cntTipoFinanciamiento;
		this.cntTipoContrato = cntTipoContrato;
		this.cntDetalleTramiteContratos = cntDetalleTramiteContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CNT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCntId() {
		return this.cntId;
	}

	public void setCntId(int cntId) {
		this.cntId = cntId;
	}

	@ManyToOne
	@JoinColumn(name = "TIFN_ID")
	public TipoFinanciamiento getCntTipoFinanciamiento() {
		return this.cntTipoFinanciamiento;
	}

	public void setCntTipoFinanciamiento(TipoFinanciamiento cntTipoFinanciamiento) {
		this.cntTipoFinanciamiento = cntTipoFinanciamiento;
	}

	@ManyToOne
	@JoinColumn(name = "TICN_ID")
	public TipoContrato getCntTipoContrato() {
		return this.cntTipoContrato;
	}

	public void setCntTipoContrato(TipoContrato cntTipoContrato) {
		this.cntTipoContrato = cntTipoContrato;
	}

	@OneToMany( mappedBy = "dttrcnContrato")
	public List<DetalleTramiteContrato> getCntDetalleTramiteContratos() {
		return this.cntDetalleTramiteContratos;
	}

	public void setCntDetalleTramiteContratos(List<DetalleTramiteContrato> cntDetalleTramiteContratos) {
		this.cntDetalleTramiteContratos = cntDetalleTramiteContratos;
	}

}
