package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Corequisito generated by hbm2java
 */
@Entity
@Table(name = "COREQUISITO", schema = ConstantesJpa.SCHEMA)
public class Corequisito implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3568003768793977337L;
	private int crqId;
	private Materia crqMateriaCorequisito;
	private Materia crqMateria;
	private String crqCodigo;
	private String crqDescripcion;
	private Integer crqEstado;

	public Corequisito() {
	}

	public Corequisito(int crqId) {
		this.crqId = crqId;
	}

	public Corequisito(int crqId, Materia crqMateriaCorequisito, Materia crqMateria, String crqCodigo,
			String crqDescripcion, Integer crqEstado) {
		this.crqId = crqId;
		this.crqMateriaCorequisito = crqMateriaCorequisito;
		this.crqMateria = crqMateria;
		this.crqCodigo = crqCodigo;
		this.crqDescripcion = crqDescripcion;
		this.crqEstado = crqEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CRQ_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCrqId() {
		return this.crqId;
	}

	public void setCrqId(int crqId) {
		this.crqId = crqId;
	}

	@ManyToOne
	@JoinColumn(name = "MTR_COREQUISITO_ID")
	public Materia getCrqMateriaCorequisito() {
		return this.crqMateriaCorequisito;
	}

	public void setCrqMateriaCorequisito(Materia crqMateriaCorequisito) {
		this.crqMateriaCorequisito = crqMateriaCorequisito;
	}

	@ManyToOne
	@JoinColumn(name = "MTR_ID")
	public Materia getCrqMateria() {
		return this.crqMateria;
	}

	public void setCrqMateria(Materia crqMateria) {
		this.crqMateria = crqMateria;
	}

	@Column(name = "CRQ_CODIGO", length = 128)
	@Length(max = 128)
	public String getCrqCodigo() {
		return this.crqCodigo;
	}

	public void setCrqCodigo(String crqCodigo) {
		this.crqCodigo = crqCodigo;
	}

	@Column(name = "CRQ_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getCrqDescripcion() {
		return this.crqDescripcion;
	}

	public void setCrqDescripcion(String crqDescripcion) {
		this.crqDescripcion = crqDescripcion;
	}

	@Column(name = "CRQ_ESTADO", precision = 22, scale = 0)
	public Integer getCrqEstado() {
		return this.crqEstado;
	}

	public void setCrqEstado(Integer crqEstado) {
		this.crqEstado = crqEstado;
	}

}
