package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * CronogramaProcesoFlujo generated by hbm2java
 */
@Entity
@Table(name = "CRONOGRAMA_PROCESO_FLUJO", schema = ConstantesJpa.SCHEMA)
public class CronogramaProcesoFlujo implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1072807910507918524L;
	private int crprflId;
	private Integer crprflOrdinal;
	private ProcesoFlujo crprProcesoFlujo;
	private Cronograma crprCronograma;
	private List<PlanificacionCronograma> crnPlanificacionCronogramas = new ArrayList<PlanificacionCronograma>(0);

	public CronogramaProcesoFlujo() {
	}

	public CronogramaProcesoFlujo(int crprflId) {
		this.crprflId = crprflId;
	}

	public CronogramaProcesoFlujo(int crprflId, ProcesoFlujo crprProcesoFlujo, Cronograma crprCronograma,
			List<PlanificacionCronograma> crnPlanificacionCronogramas) {
		this.crprflId = crprflId;
		this.crprProcesoFlujo = crprProcesoFlujo;
		this.crprCronograma = crprCronograma;
		this.crnPlanificacionCronogramas = crnPlanificacionCronogramas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CRPRFL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCrprflId() {
		return this.crprflId;
	}

	public void setCrprflId(int crprflId) {
		this.crprflId = crprflId;
	}

	@ManyToOne
	@JoinColumn(name = "PRFL_ID")
	public ProcesoFlujo getCrprProcesoFlujo() {
		return this.crprProcesoFlujo;
	}

	public void setCrprProcesoFlujo(ProcesoFlujo crprProcesoFlujo) {
		this.crprProcesoFlujo = crprProcesoFlujo;
	}

	@ManyToOne
	@JoinColumn(name = "CRN_ID")
	public Cronograma getCrprCronograma() {
		return this.crprCronograma;
	}

	public void setCrprCronograma(Cronograma crprCronograma) {
		this.crprCronograma = crprCronograma;
	}

	@OneToMany( mappedBy = "plcrCronogramaProcesoFlujo")
	public List<PlanificacionCronograma> getCrprPlanificacionCronogramas() {
		return this.crnPlanificacionCronogramas;
	}

	public void setCrprPlanificacionCronogramas(List<PlanificacionCronograma> crnPlanificacionCronogramas) {
		this.crnPlanificacionCronogramas = crnPlanificacionCronogramas;
	}

	@Column(name = "CRPRFL_ORDINAL")
	public Integer getCrprflOrdinal() {
		return crprflOrdinal;
	}

	public void setCrprflOrdinal(Integer crprflOrdinal) {
		this.crprflOrdinal = crprflOrdinal;
	}
	
	

}
