package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Cronograma generated by hbm2java
 */
@Entity
@Table(name = "CRONOGRAMA", schema = ConstantesJpa.SCHEMA)
public class Cronograma implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 5925347519691077446L;
	private int crnId;
	private PeriodoAcademico crnPeriodoAcademico;
	private Integer crnTipo;
	private String crnDescripcion;
	private Integer crnEstado;
	private List<CronogramaProcesoFlujo> crnCronogramaProcesoFlujos = new ArrayList<CronogramaProcesoFlujo>(0);

	public Cronograma() {
	}

	public Cronograma(int crnId) {
		this.crnId = crnId;
	}

	public Cronograma(int crnId, PeriodoAcademico crnPeriodoAcademico, Integer crnTipo, String crnDescripcion,
			Integer crnEstado, List<CronogramaProcesoFlujo> crnCronogramaProcesoFlujos) {
		this.crnId = crnId;
		this.crnPeriodoAcademico = crnPeriodoAcademico;
		this.crnTipo = crnTipo;
		this.crnDescripcion = crnDescripcion;
		this.crnEstado = crnEstado;
		this.crnCronogramaProcesoFlujos = crnCronogramaProcesoFlujos;
	}

	
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "CRN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCrnId() {
		return this.crnId;
	}

	public void setCrnId(int crnId) {
		this.crnId = crnId;
	}

	@ManyToOne
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getCrnPeriodoAcademico() {
		return this.crnPeriodoAcademico;
	}

	public void setCrnPeriodoAcademico(PeriodoAcademico crnPeriodoAcademico) {
		this.crnPeriodoAcademico = crnPeriodoAcademico;
	}

	@Column(name = "CRN_TIPO", precision = 22, scale = 0)
	public Integer getCrnTipo() {
		return this.crnTipo;
	}

	public void setCrnTipo(Integer crnTipo) {
		this.crnTipo = crnTipo;
	}

	@Column(name = "CRN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getCrnDescripcion() {
		return this.crnDescripcion;
	}

	public void setCrnDescripcion(String crnDescripcion) {
		this.crnDescripcion = crnDescripcion;
	}

	@Column(name = "CRN_ESTADO", precision = 22, scale = 0)
	public Integer getCrnEstado() {
		return this.crnEstado;
	}

	public void setCrnEstado(Integer crnEstado) {
		this.crnEstado = crnEstado;
	}

	@OneToMany( mappedBy = "crprCronograma")
	public List<CronogramaProcesoFlujo> getCrnCronogramaProcesoFlujos() {
		return this.crnCronogramaProcesoFlujos;
	}

	public void setCrnCronogramaProcesoFlujos(List<CronogramaProcesoFlujo> crnCronogramaProcesoFlujos) {
		this.crnCronogramaProcesoFlujos = crnCronogramaProcesoFlujos;
	}

}
