package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * DetalleCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_CARGA_HORARIA", schema = ConstantesJpa.SCHEMA)
public class DetalleCargaHoraria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3960672067043728010L;
	private int dtcrhrId;
	private CargaHoraria dtcrhrCargaHoraria;
	private Date dtcrhrFechaInicio;
	private Date dtcrhrFechaFin;
	private Integer dtcrhrNumProyecto;
	private String dtcrhrArea;
	private String dtcrhrSubarea;
	private String dtcrhrUnidadAcademica;
	private String dtcrhrAsignaturaClinicas;
	private Integer dtcrhrNumAlumnosClinicas;
	private String dtcrhrUniversidadDoctorado;
	private String dtcrhrTituloDoctorado;
	private Integer dtcrhrNivelProyecto1;
	private String dtcrhrProyecto1;
	private Integer dtcrhrProyecto1Horas;
	private Integer dtcrhrNivelProyecto2;
	private String dtcrhrProyecto2;
	private Integer dtcrhrProyecto2Horas;
	private Integer dtcrhrNivelProyecto3;
	private String dtcrhrProyecto3;
	private Integer dtcrhrProyecto3Horas;
	private Integer dtcrhrNivelProyecto4;
	private String dtcrhrProyecto4;
	private Integer dtcrhrProyecto4Horas;
	private Integer dtcrhrNivelProyecto5;
	private String dtcrhrProyecto5;
	private Integer dtcrhrProyecto5Horas;
	private Integer dtcrhrNivelProyecto6;
	private String dtcrhrProyecto6;
	private Integer dtcrhrProyecto6Horas;
	private Integer dtcrhrNivelProyecto7;
	private String dtcrhrProyecto7;
	private Integer dtcrhrProyecto7Horas;
	private Integer dtcrhrNivelProyecto8;
	private String dtcrhrProyecto8;
	private Integer dtcrhrProyecto8Horas;
	private Integer dtcrhrCarreraId;
	private Integer dtcrhrEstado;
	private Integer dtcrhrEstadoEliminacion;
	private Integer dtcrhrNumHoras;
	private String dtcrhrNombreProyecto;
	private String dtcrhrFuncion;
	private Integer dtcrhrNumAlumnosTitulacion;
	
	
	public DetalleCargaHoraria() {
	}

	public DetalleCargaHoraria(int dtcrhrId) {
		this.dtcrhrId = dtcrhrId;
	}


	
	

	public DetalleCargaHoraria(int dtcrhrId, CargaHoraria dtcrhrCargaHoraria, Date dtcrhrFechaInicio,
			Date dtcrhrFechaFin, Integer dtcrhrNumProyecto, String dtcrhrArea, String dtcrhrSubarea,
			String dtcrhrUnidadAcademica, String dtcrhrAsignaturaClinicas, Integer dtcrhrNumAlumnosClinicas,
			String dtcrhrUniversidadDoctorado, String dtcrhrTituloDoctorado, Integer dtcrhrNivelProyecto1,
			String dtcrhrProyecto1, Integer dtcrhrProyecto1Horas, Integer dtcrhrNivelProyecto2, String dtcrhrProyecto2,
			Integer dtcrhrProyecto2Horas, Integer dtcrhrNivelProyecto3, String dtcrhrProyecto3,
			Integer dtcrhrProyecto3Horas, Integer dtcrhrNivelProyecto4, String dtcrhrProyecto4,
			Integer dtcrhrProyecto4Horas, Integer dtcrhrNivelProyecto5, String dtcrhrProyecto5,
			Integer dtcrhrProyecto5Horas, Integer dtcrhrNivelProyecto6, String dtcrhrProyecto6,
			Integer dtcrhrProyecto6Horas, Integer dtcrhrNivelProyecto7, String dtcrhrProyecto7,
			Integer dtcrhrProyecto7Horas, Integer dtcrhrNivelProyecto8, String dtcrhrProyecto8,
			Integer dtcrhrProyecto8Horas, Integer dtcrhrCarreraId, Integer dtcrhrEstado,
			Integer dtcrhrEstadoEliminacion, Integer dtcrhrNumHoras, String dtcrhrNombreProyecto, String dtcrhrFuncion,
			Integer dtcrhrNumAlumnosTitulacion) {
		this.dtcrhrId = dtcrhrId;
		this.dtcrhrCargaHoraria = dtcrhrCargaHoraria;
		this.dtcrhrFechaInicio = dtcrhrFechaInicio;
		this.dtcrhrFechaFin = dtcrhrFechaFin;
		this.dtcrhrNumProyecto = dtcrhrNumProyecto;
		this.dtcrhrArea = dtcrhrArea;
		this.dtcrhrSubarea = dtcrhrSubarea;
		this.dtcrhrUnidadAcademica = dtcrhrUnidadAcademica;
		this.dtcrhrAsignaturaClinicas = dtcrhrAsignaturaClinicas;
		this.dtcrhrNumAlumnosClinicas = dtcrhrNumAlumnosClinicas;
		this.dtcrhrUniversidadDoctorado = dtcrhrUniversidadDoctorado;
		this.dtcrhrTituloDoctorado = dtcrhrTituloDoctorado;
		this.dtcrhrNivelProyecto1 = dtcrhrNivelProyecto1;
		this.dtcrhrProyecto1 = dtcrhrProyecto1;
		this.dtcrhrProyecto1Horas = dtcrhrProyecto1Horas;
		this.dtcrhrNivelProyecto2 = dtcrhrNivelProyecto2;
		this.dtcrhrProyecto2 = dtcrhrProyecto2;
		this.dtcrhrProyecto2Horas = dtcrhrProyecto2Horas;
		this.dtcrhrNivelProyecto3 = dtcrhrNivelProyecto3;
		this.dtcrhrProyecto3 = dtcrhrProyecto3;
		this.dtcrhrProyecto3Horas = dtcrhrProyecto3Horas;
		this.dtcrhrNivelProyecto4 = dtcrhrNivelProyecto4;
		this.dtcrhrProyecto4 = dtcrhrProyecto4;
		this.dtcrhrProyecto4Horas = dtcrhrProyecto4Horas;
		this.dtcrhrNivelProyecto5 = dtcrhrNivelProyecto5;
		this.dtcrhrProyecto5 = dtcrhrProyecto5;
		this.dtcrhrProyecto5Horas = dtcrhrProyecto5Horas;
		this.dtcrhrNivelProyecto6 = dtcrhrNivelProyecto6;
		this.dtcrhrProyecto6 = dtcrhrProyecto6;
		this.dtcrhrProyecto6Horas = dtcrhrProyecto6Horas;
		this.dtcrhrNivelProyecto7 = dtcrhrNivelProyecto7;
		this.dtcrhrProyecto7 = dtcrhrProyecto7;
		this.dtcrhrProyecto7Horas = dtcrhrProyecto7Horas;
		this.dtcrhrNivelProyecto8 = dtcrhrNivelProyecto8;
		this.dtcrhrProyecto8 = dtcrhrProyecto8;
		this.dtcrhrProyecto8Horas = dtcrhrProyecto8Horas;
		this.dtcrhrCarreraId = dtcrhrCarreraId;
		this.dtcrhrEstado = dtcrhrEstado;
		this.dtcrhrEstadoEliminacion = dtcrhrEstadoEliminacion;
		this.dtcrhrNumHoras = dtcrhrNumHoras;
		this.dtcrhrNombreProyecto = dtcrhrNombreProyecto;
		this.dtcrhrFuncion = dtcrhrFuncion;
		this.dtcrhrNumAlumnosTitulacion = dtcrhrNumAlumnosTitulacion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "DTCRHR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDtcrhrId() {
		return this.dtcrhrId;
	}

	public void setDtcrhrId(int dtcrhrId) {
		this.dtcrhrId = dtcrhrId;
	}

	@ManyToOne
	@JoinColumn(name = "CRHR_ID")
	public CargaHoraria getDtcrhrCargaHoraria() {
		return this.dtcrhrCargaHoraria;
	}

	public void setDtcrhrCargaHoraria(CargaHoraria dtcrhrCargaHoraria) {
		this.dtcrhrCargaHoraria = dtcrhrCargaHoraria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCRHR_FECHA_INICIO", length = 7)
	public Date getDtcrhrFechaInicio() {
		return this.dtcrhrFechaInicio;
	}

	public void setDtcrhrFechaInicio(Date dtcrhrFechaInicio) {
		this.dtcrhrFechaInicio = dtcrhrFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCRHR_FECHA_FIN", length = 7)
	public Date getDtcrhrFechaFin() {
		return this.dtcrhrFechaFin;
	}

	public void setDtcrhrFechaFin(Date dtcrhrFechaFin) {
		this.dtcrhrFechaFin = dtcrhrFechaFin;
	}

	@Column(name = "DTCRHR_NUM_PROYECTO", precision = 2, scale = 0)
	public Integer getDtcrhrNumProyecto() {
		return this.dtcrhrNumProyecto;
	}

	public void setDtcrhrNumProyecto(Integer dtcrhrNumProyecto) {
		this.dtcrhrNumProyecto = dtcrhrNumProyecto;
	}

	@Column(name = "DTCRHR_AREA", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrArea() {
		return this.dtcrhrArea;
	}

	public void setDtcrhrArea(String dtcrhrArea) {
		this.dtcrhrArea = dtcrhrArea;
	}

	@Column(name = "DTCRHR_SUBAREA", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrSubarea() {
		return this.dtcrhrSubarea;
	}

	public void setDtcrhrSubarea(String dtcrhrSubarea) {
		this.dtcrhrSubarea = dtcrhrSubarea;
	}

	@Column(name = "DTCRHR_UNIDAD_ACADEMICA", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrUnidadAcademica() {
		return this.dtcrhrUnidadAcademica;
	}

	public void setDtcrhrUnidadAcademica(String dtcrhrUnidadAcademica) {
		this.dtcrhrUnidadAcademica = dtcrhrUnidadAcademica;
	}

	@Column(name = "DTCRHR_ASIGNATURA_CLINICAS", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrAsignaturaClinicas() {
		return this.dtcrhrAsignaturaClinicas;
	}

	public void setDtcrhrAsignaturaClinicas(String dtcrhrAsignaturaClinicas) {
		this.dtcrhrAsignaturaClinicas = dtcrhrAsignaturaClinicas;
	}

	@Column(name = "DTCRHR_NUM_ALUMNOS_CLINICAS", precision = 2, scale = 0)
	public Integer getDtcrhrNumAlumnosClinicas() {
		return this.dtcrhrNumAlumnosClinicas;
	}

	public void setDtcrhrNumAlumnosClinicas(Integer dtcrhrNumAlumnosClinicas) {
		this.dtcrhrNumAlumnosClinicas = dtcrhrNumAlumnosClinicas;
	}

	@Column(name = "DTCRHR_UNIVERSIDAD_DOCTORADO", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrUniversidadDoctorado() {
		return this.dtcrhrUniversidadDoctorado;
	}

	public void setDtcrhrUniversidadDoctorado(String dtcrhrUniversidadDoctorado) {
		this.dtcrhrUniversidadDoctorado = dtcrhrUniversidadDoctorado;
	}

	@Column(name = "DTCRHR_TITULO_DOCTORADO", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrTituloDoctorado() {
		return this.dtcrhrTituloDoctorado;
	}

	public void setDtcrhrTituloDoctorado(String dtcrhrTituloDoctorado) {
		this.dtcrhrTituloDoctorado = dtcrhrTituloDoctorado;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO1")
	public Integer getDtcrhrNivelProyecto1() {
		return this.dtcrhrNivelProyecto1;
	}

	public void setDtcrhrNivelProyecto1(Integer dtcrhrNivelProyecto1) {
		this.dtcrhrNivelProyecto1 = dtcrhrNivelProyecto1;
	}

	@Column(name = "DTCRHR_PROYECTO1", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto1() {
		return this.dtcrhrProyecto1;
	}

	public void setDtcrhrProyecto1(String dtcrhrProyecto1) {
		this.dtcrhrProyecto1 = dtcrhrProyecto1;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO2")
	public Integer getDtcrhrNivelProyecto2() {
		return this.dtcrhrNivelProyecto2;
	}

	public void setDtcrhrNivelProyecto2(Integer dtcrhrNivelProyecto2) {
		this.dtcrhrNivelProyecto2 = dtcrhrNivelProyecto2;
	}

	@Column(name = "DTCRHR_PROYECTO2", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto2() {
		return this.dtcrhrProyecto2;
	}

	public void setDtcrhrProyecto2(String dtcrhrProyecto2) {
		this.dtcrhrProyecto2 = dtcrhrProyecto2;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO3")
	public Integer getDtcrhrNivelProyecto3() {
		return this.dtcrhrNivelProyecto3;
	}

	public void setDtcrhrNivelProyecto3(Integer dtcrhrNivelProyecto3) {
		this.dtcrhrNivelProyecto3 = dtcrhrNivelProyecto3;
	}

	@Column(name = "DTCRHR_PROYECTO3", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto3() {
		return this.dtcrhrProyecto3;
	}

	public void setDtcrhrProyecto3(String dtcrhrProyecto3) {
		this.dtcrhrProyecto3 = dtcrhrProyecto3;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO4")
	public Integer getDtcrhrNivelProyecto4() {
		return this.dtcrhrNivelProyecto4;
	}

	public void setDtcrhrNivelProyecto4(Integer dtcrhrNivelProyecto4) {
		this.dtcrhrNivelProyecto4 = dtcrhrNivelProyecto4;
	}

	@Column(name = "DTCRHR_PROYECTO4", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto4() {
		return this.dtcrhrProyecto4;
	}

	public void setDtcrhrProyecto4(String dtcrhrProyecto4) {
		this.dtcrhrProyecto4 = dtcrhrProyecto4;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO5")
	public Integer getDtcrhrNivelProyecto5() {
		return this.dtcrhrNivelProyecto5;
	}

	public void setDtcrhrNivelProyecto5(Integer dtcrhrNivelProyecto5) {
		this.dtcrhrNivelProyecto5 = dtcrhrNivelProyecto5;
	}

	@Column(name = "DTCRHR_PROYECTO5", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto5() {
		return this.dtcrhrProyecto5;
	}

	public void setDtcrhrProyecto5(String dtcrhrProyecto5) {
		this.dtcrhrProyecto5 = dtcrhrProyecto5;
	}


	@Column(name = "DTCRHR_NIVEL_PROYECTO6")
	public Integer getDtcrhrNivelProyecto6() {
		return this.dtcrhrNivelProyecto6;
	}

	public void setDtcrhrNivelProyecto6(Integer dtcrhrNivelProyecto6) {
		this.dtcrhrNivelProyecto6 = dtcrhrNivelProyecto6;
	}

	@Column(name = "DTCRHR_PROYECTO6", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto6() {
		return this.dtcrhrProyecto6;
	}

	public void setDtcrhrProyecto6(String dtcrhrProyecto6) {
		this.dtcrhrProyecto6 = dtcrhrProyecto6;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO7")
	public Integer getDtcrhrNivelProyecto7() {
		return this.dtcrhrNivelProyecto7;
	}

	public void setDtcrhrNivelProyecto7(Integer dtcrhrNivelProyecto7) {
		this.dtcrhrNivelProyecto7 = dtcrhrNivelProyecto7;
	}

	@Column(name = "DTCRHR_PROYECTO7", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto7() {
		return this.dtcrhrProyecto7;
	}

	public void setDtcrhrProyecto7(String dtcrhrProyecto7) {
		this.dtcrhrProyecto7 = dtcrhrProyecto7;
	}

	@Column(name = "DTCRHR_NIVEL_PROYECTO8")
	public Integer getDtcrhrNivelProyecto8() {
		return this.dtcrhrNivelProyecto8;
	}

	public void setDtcrhrNivelProyecto8(Integer dtcrhrNivelProyecto8) {
		this.dtcrhrNivelProyecto8 = dtcrhrNivelProyecto8;
	}

	@Column(name = "DTCRHR_PROYECTO8", length = 2000)
	@Length(max = 2000)
	public String getDtcrhrProyecto8() {
		return this.dtcrhrProyecto8;
	}

	public void setDtcrhrProyecto8(String dtcrhrProyecto8) {
		this.dtcrhrProyecto8 = dtcrhrProyecto8;
	}

	@Column(name= "DTCRHR_CARRERA_ID")
	public Integer getDtcrhrCarreraId() {
		return dtcrhrCarreraId;
	}

	public void setDtcrhrCarreraId(Integer dtcrhrCarreraId) {
		this.dtcrhrCarreraId = dtcrhrCarreraId;
	}

	@Column(name= "DTCRHR_PROYECTO1_HORAS")
	public Integer getDtcrhrProyecto1Horas() {
		return dtcrhrProyecto1Horas;
	}

	public void setDtcrhrProyecto1Horas(Integer dtcrhrProyecto1Horas) {
		this.dtcrhrProyecto1Horas = dtcrhrProyecto1Horas;
	}

	@Column(name= "DTCRHR_PROYECTO2_HORAS")
	public Integer getDtcrhrProyecto2Horas() {
		return dtcrhrProyecto2Horas;
	}

	public void setDtcrhrProyecto2Horas(Integer dtcrhrProyecto2Horas) {
		this.dtcrhrProyecto2Horas = dtcrhrProyecto2Horas;
	}

	@Column(name= "DTCRHR_PROYECTO3_HORAS")
	public Integer getDtcrhrProyecto3Horas() {
		return dtcrhrProyecto3Horas;
	}

	public void setDtcrhrProyecto3Horas(Integer dtcrhrProyecto3Horas) {
		this.dtcrhrProyecto3Horas = dtcrhrProyecto3Horas;
	}

	@Column(name= "DTCRHR_PROYECTO4_HORAS")
	public Integer getDtcrhrProyecto4Horas() {
		return dtcrhrProyecto4Horas;
	}

	public void setDtcrhrProyecto4Horas(Integer dtcrhrProyecto4Horas) {
		this.dtcrhrProyecto4Horas = dtcrhrProyecto4Horas;
	}

	@Column(name= "DTCRHR_PROYECTO5_HORAS")
	public Integer getDtcrhrProyecto5Horas() {
		return dtcrhrProyecto5Horas;
	}

	public void setDtcrhrProyecto5Horas(Integer dtcrhrProyecto5Horas) {
		this.dtcrhrProyecto5Horas = dtcrhrProyecto5Horas;
	}

	@Column(name= "DTCRHR_PROYECTO6_HORAS")
	public Integer getDtcrhrProyecto6Horas() {
		return dtcrhrProyecto6Horas;
	}

	public void setDtcrhrProyecto6Horas(Integer dtcrhrProyecto6Horas) {
		this.dtcrhrProyecto6Horas = dtcrhrProyecto6Horas;
	}

	@Column(name= "DTCRHR_PROYECTO7_HORAS")
	public Integer getDtcrhrProyecto7Horas() {
		return dtcrhrProyecto7Horas;
	}

	public void setDtcrhrProyecto7Horas(Integer dtcrhrProyecto7Horas) {
		this.dtcrhrProyecto7Horas = dtcrhrProyecto7Horas;
	}

	@Column(name= "DTCRHR_PROYECTO8_HORAS")
	public Integer getDtcrhrProyecto8Horas() {
		return dtcrhrProyecto8Horas;
	}

	public void setDtcrhrProyecto8Horas(Integer dtcrhrProyecto8Horas) {
		this.dtcrhrProyecto8Horas = dtcrhrProyecto8Horas;
	}

	@Column(name= "DTCRHR_ESTADO")
	public Integer getDtcrhrEstado() {
		return dtcrhrEstado;
	}

	public void setDtcrhrEstado(Integer dtcrhrEstado) {
		this.dtcrhrEstado = dtcrhrEstado;
	}

	@Column(name= "DTCRHR_ESTADO_ELIMINACION")
	public Integer getDtcrhrEstadoEliminacion() {
		return dtcrhrEstadoEliminacion;
	}

	public void setDtcrhrEstadoEliminacion(Integer dtcrhrEstadoEliminacion) {
		this.dtcrhrEstadoEliminacion = dtcrhrEstadoEliminacion;
	}

	
	@Column(name= "DTCRHR_NUM_HORAS")
	public Integer getDtcrhrNumHoras() {
		return dtcrhrNumHoras;
	}

	public void setDtcrhrNumHoras(Integer dtcrhrNumHoras) {
		this.dtcrhrNumHoras = dtcrhrNumHoras;
	}

	@Column(name= "DTCRHR_NOMBRE_PROYECTO" , length=2000)
	public String getDtcrhrNombreProyecto() {
		return dtcrhrNombreProyecto;
	}

	public void setDtcrhrNombreProyecto(String dtcrhrNombreProyecto) {
		this.dtcrhrNombreProyecto = dtcrhrNombreProyecto;
	}

	@Column(name= "DTCRHR_FUNCION", length=2000)
	public String getDtcrhrFuncion() {
		return dtcrhrFuncion;
	}

	public void setDtcrhrFuncion(String dtcrhrFuncion) {
		this.dtcrhrFuncion = dtcrhrFuncion;
	}

	@Column(name= "DTCRHR_NUM_ALUMNOS_TITULACION")
	public Integer getDtcrhrNumAlumnosTitulacion() {
		return dtcrhrNumAlumnosTitulacion;
	}

	public void setDtcrhrNumAlumnosTitulacion(Integer dtcrhrNumAlumnosTitulacion) {
		this.dtcrhrNumAlumnosTitulacion = dtcrhrNumAlumnosTitulacion;
	}
 
}
