package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * DetalleTramiteContrato generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_TRAMITE_CONTRATO", schema = ConstantesJpa.SCHEMA)
public class DetalleTramiteContrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2983806943151722981L;
	private int dttrcnId;
	private Tramite dttrcnTramite;
	private DetalleTramiteContrato dttrcnDetalleTramiteContrato;
	private Contrato dttrcnContrato;
	private DetallePuesto dttrcnDetallePuesto;
	private String dttrcnNumTramite;
	private Integer dttrcnEstadoTramite;
	private Integer dttrcnEstadoProceso;
	private String dttrcnObservacion;
	private Date dttrcnFechaInicio;
	private Date dttrcnFechaFin;
	private String dttrcnArchivoResolucion;
	private List<DetalleTramiteContrato> dttrcnDetalleTramiteContratos = new ArrayList<DetalleTramiteContrato>(0);
	private List<ProcesoTramiteContrato> dttrcnProcesoTramiteContratos = new ArrayList<ProcesoTramiteContrato>(0);

	public DetalleTramiteContrato() {
	}

	public DetalleTramiteContrato(int dttrcnId) {
		this.dttrcnId = dttrcnId;
	}

	public DetalleTramiteContrato(int dttrcnId, Tramite dttrcnTramite, DetalleTramiteContrato dttrcnDetalleTramiteContrato,
			Contrato dttrcnContrato, DetallePuesto dttrcnDetallePuesto, String dttrcnNumTramite, Integer dttrcnEstadoTramite,
			Integer dttrcnEstadoProceso, String dttrcnObservacion, Date dttrcnFechaInicio, Date dttrcnFechaFin,
			String dttrcnArchivoResolucion, List<DetalleTramiteContrato> dttrcnDetalleTramiteContratos,
			List<ProcesoTramiteContrato> dttrcnProcesoTramiteContratos) {
		this.dttrcnId = dttrcnId;
		this.dttrcnTramite = dttrcnTramite;
		this.dttrcnDetalleTramiteContrato = dttrcnDetalleTramiteContrato;
		this.dttrcnContrato = dttrcnContrato;
		this.dttrcnDetallePuesto = dttrcnDetallePuesto;
		this.dttrcnNumTramite = dttrcnNumTramite;
		this.dttrcnEstadoTramite = dttrcnEstadoTramite;
		this.dttrcnEstadoProceso = dttrcnEstadoProceso;
		this.dttrcnObservacion = dttrcnObservacion;
		this.dttrcnFechaInicio = dttrcnFechaInicio;
		this.dttrcnFechaFin = dttrcnFechaFin;
		this.dttrcnArchivoResolucion = dttrcnArchivoResolucion;
		this.dttrcnDetalleTramiteContratos = dttrcnDetalleTramiteContratos;
		this.dttrcnProcesoTramiteContratos = dttrcnProcesoTramiteContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "DTTRCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDttrcnId() {
		return this.dttrcnId;
	}

	public void setDttrcnId(int dttrcnId) {
		this.dttrcnId = dttrcnId;
	}

	@ManyToOne
	@JoinColumn(name = "TRM_ID")
	public Tramite getDttrcnTramite() {
		return this.dttrcnTramite;
	}

	public void setDttrcnTramite(Tramite dttrcnTramite) {
		this.dttrcnTramite = dttrcnTramite;
	}

	@ManyToOne
	@JoinColumn(name = "DTTRCN_SUB_ID")
	public DetalleTramiteContrato getDttrcnDetalleTramiteContrato() {
		return this.dttrcnDetalleTramiteContrato;
	}

	public void setDttrcnDetalleTramiteContrato(DetalleTramiteContrato dttrcnDetalleTramiteContrato) {
		this.dttrcnDetalleTramiteContrato = dttrcnDetalleTramiteContrato;
	}

	@ManyToOne
	@JoinColumn(name = "CNT_ID")
	public Contrato getDttrcnContrato() {
		return this.dttrcnContrato;
	}

	public void setDttrcnContrato(Contrato dttrcnContrato) {
		this.dttrcnContrato = dttrcnContrato;
	}

	@ManyToOne
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDttrcnDetallePuesto() {
		return this.dttrcnDetallePuesto;
	}

	public void setDttrcnDetallePuesto(DetallePuesto dttrcnDetallePuesto) {
		this.dttrcnDetallePuesto = dttrcnDetallePuesto;
	}

	@Column(name = "DTTRCN_NUM_TRAMITE", length = 32)
	@Length(max = 32)
	public String getDttrcnNumTramite() {
		return this.dttrcnNumTramite;
	}

	public void setDttrcnNumTramite(String dttrcnNumTramite) {
		this.dttrcnNumTramite = dttrcnNumTramite;
	}

	@Column(name = "DTTRCN_ESTADO_TRAMITE", precision = 22, scale = 0)
	public Integer getDttrcnEstadoTramite() {
		return this.dttrcnEstadoTramite;
	}

	public void setDttrcnEstadoTramite(Integer dttrcnEstadoTramite) {
		this.dttrcnEstadoTramite = dttrcnEstadoTramite;
	}

	@Column(name = "DTTRCN_ESTADO_PROCESO", precision = 22, scale = 0)
	public Integer getDttrcnEstadoProceso() {
		return this.dttrcnEstadoProceso;
	}

	public void setDttrcnEstadoProceso(Integer dttrcnEstadoProceso) {
		this.dttrcnEstadoProceso = dttrcnEstadoProceso;
	}

	@Column(name = "DTTRCN_OBSERVACION", length = 512)
	@Length(max = 512)
	public String getDttrcnObservacion() {
		return this.dttrcnObservacion;
	}

	public void setDttrcnObservacion(String dttrcnObservacion) {
		this.dttrcnObservacion = dttrcnObservacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTTRCN_FECHA_INICIO", length = 7)
	public Date getDttrcnFechaInicio() {
		return this.dttrcnFechaInicio;
	}

	public void setDttrcnFechaInicio(Date dttrcnFechaInicio) {
		this.dttrcnFechaInicio = dttrcnFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTTRCN_FECHA_FIN", length = 7)
	public Date getDttrcnFechaFin() {
		return this.dttrcnFechaFin;
	}

	public void setDttrcnFechaFin(Date dttrcnFechaFin) {
		this.dttrcnFechaFin = dttrcnFechaFin;
	}

	@Column(name = "DTTRCN_ARCHIVO_RESOLUCION", length = 256)
	@Length(max = 256)
	public String getDttrcnArchivoResolucion() {
		return this.dttrcnArchivoResolucion;
	}

	public void setDttrcnArchivoResolucion(String dttrcnArchivoResolucion) {
		this.dttrcnArchivoResolucion = dttrcnArchivoResolucion;
	}

	@OneToMany( mappedBy = "dttrcnDetalleTramiteContrato")
	public List<DetalleTramiteContrato> getDttrcnDetalleTramiteContratos() {
		return this.dttrcnDetalleTramiteContratos;
	}

	public void setDttrcnDetalleTramiteContratos(List<DetalleTramiteContrato> dttrcnDetalleTramiteContratos) {
		this.dttrcnDetalleTramiteContratos = dttrcnDetalleTramiteContratos;
	}

	@OneToMany( mappedBy = "prtrcnDetalleTramiteContrato")
	public List<ProcesoTramiteContrato> getDttrcnProcesoTramiteContratos() {
		return this.dttrcnProcesoTramiteContratos;
	}

	public void setDttrcnProcesoTramiteContratos(List<ProcesoTramiteContrato> dttrcnProcesoTramiteContratos) {
		this.dttrcnProcesoTramiteContratos = dttrcnProcesoTramiteContratos;
	}

}
