package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * DetalleMatricula generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_MATRICULA", schema = ConstantesJpa.SCHEMA)
public class DetalleMatricula implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1828910417871903627L;
	private int dtmtId;
	private MallaCurricularParalelo dtmtMallaCurricularParalelo;
	private Arancel dtmtArancel;
	private ComprobantePago dtmtComprobantePago;
	private Integer dtmtNumero;
	private Integer dtmtEstado;
	private String dtmtArchivoEstudiantes;
	private Integer dtmtEstadoHistorico;
	private Integer dtmtEstadoCambio;
	private String dtmtObservacionHistorico;
	private String dtmtObservacionCambio;
	private BigDecimal dtmtValorParcial;
	private BigDecimal dtmtValorPorMateria;
	private Timestamp dtmtFechaHistorico;
	private Timestamp dtmtFechaCambio;
	private String dtmtUsuario;
	private Timestamp dtmtModificacion;
	private Integer dtmtEstadoSolicitud;
	private Integer dtmtEstadoRespuesta;
	private Timestamp dtmtFechaSolicitud;
	private Timestamp dtmtFechaRespuesta;
	private Integer dtmtCslRetiroId;
	private Timestamp dtmtFechaVerificacionRetiro;
	private String dtmtArchivoRespuesta;
	
	private String dtmtObservacionFinalRetiro;
	private Integer dtmtTipoAnulacion;
	private Timestamp dtmtFechaAnulacion;
	private String dtmtArchivoAnulacion;
	private String dtmtRegistranteAnulacion;
	private String dtmtObservacionAnulacion;
	
	private List<CausalDetalleMatricula> dtmtCausalDetalleMatriculas = new ArrayList<CausalDetalleMatricula>(0);
	
	
	public DetalleMatricula() {
	}

	public DetalleMatricula(int dtmtId) {
		this.dtmtId = dtmtId;
	}

	public DetalleMatricula(int dtmtId, MallaCurricularParalelo dtmtMallaCurricularParalelo, Arancel dtmtArancel,
			ComprobantePago dtmtComprobantePago, Integer dtmtNumero, Integer dtmtEstado, String dtmtArchivoEstudiantes,
			Integer dtmtEstadoHistorico, Integer dtmtEstadoCambio, String dtmtObservacionHistorico,
			String dtmtObservacionCambio, BigDecimal dtmtValorParcial, Timestamp dtmtFechaHistorico,
			Timestamp dtmtFechaCambio, Integer dtmtCslRetiroId, Timestamp dtmtFechaVerificacionRetiro,
			String dtmtArchivoRespuesta, String dtmtObservacionFinalRetiro, Integer dtmtTipoAnulacion,
			Timestamp dtmtFechaAnulacion,String dtmtArchivoAnulacion,String dtmtRegistranteAnulacion, String dtmtObservacionAnulacion, List<CausalDetalleMatricula> dtmtCausalDetalleMatriculas   ) {
		this.dtmtId = dtmtId;
		this.dtmtMallaCurricularParalelo = dtmtMallaCurricularParalelo;
		this.dtmtArancel = dtmtArancel;
		this.dtmtComprobantePago = dtmtComprobantePago;
		this.dtmtNumero = dtmtNumero;
		this.dtmtEstado = dtmtEstado;
		this.dtmtArchivoEstudiantes = dtmtArchivoEstudiantes;
		this.dtmtEstadoHistorico = dtmtEstadoHistorico;
		this.dtmtEstadoCambio = dtmtEstadoCambio;
		this.dtmtObservacionHistorico = dtmtObservacionHistorico;
		this.dtmtObservacionCambio = dtmtObservacionCambio;
		this.dtmtValorParcial = dtmtValorParcial;
		this.dtmtFechaHistorico = dtmtFechaHistorico;
		this.dtmtFechaCambio = dtmtFechaCambio;
		this.dtmtCslRetiroId = dtmtCslRetiroId;
		this.dtmtFechaVerificacionRetiro = dtmtFechaVerificacionRetiro;
		this.dtmtArchivoRespuesta = dtmtArchivoRespuesta;
		this.dtmtCausalDetalleMatriculas = dtmtCausalDetalleMatriculas;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "DTMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDtmtId() {
		return this.dtmtId;
	}

	public void setDtmtId(int dtmtId) {
		this.dtmtId = dtmtId;
	}

	@ManyToOne
	@JoinColumn(name = "MLCRPR_ID")
	public MallaCurricularParalelo getDtmtMallaCurricularParalelo() {
		return this.dtmtMallaCurricularParalelo;
	}

	public void setDtmtMallaCurricularParalelo(MallaCurricularParalelo dtmtMallaCurricularParalelo) {
		this.dtmtMallaCurricularParalelo = dtmtMallaCurricularParalelo;
	}

	@ManyToOne
	@JoinColumn(name = "ARN_ID")
	public Arancel getDtmtArancel() {
		return this.dtmtArancel;
	}

	public void setDtmtArancel(Arancel dtmtArancel) {
		this.dtmtArancel = dtmtArancel;
	}

	@ManyToOne
	@JoinColumn(name = "CMPA_ID")
	public ComprobantePago getDtmtComprobantePago() {
		return this.dtmtComprobantePago;
	}

	public void setDtmtComprobantePago(ComprobantePago dtmtComprobantePago) {
		this.dtmtComprobantePago = dtmtComprobantePago;
	}

	@Column(name = "DTMT_NUMERO", precision = 2, scale = 0)
	public Integer getDtmtNumero() {
		return this.dtmtNumero;
	}

	public void setDtmtNumero(Integer dtmtNumero) {
		this.dtmtNumero = dtmtNumero;
	}

	@Column(name = "DTMT_ESTADO", precision = 2, scale = 0)
	public Integer getDtmtEstado() {
		return this.dtmtEstado;
	}

	public void setDtmtEstado(Integer dtmtEstado) {
		this.dtmtEstado = dtmtEstado;
	}

	@Column(name = "DTMT_ARCHIVO_ESTUDIANTES", length = 512)
	@Length(max = 512)
	public String getDtmtArchivoEstudiantes() {
		return this.dtmtArchivoEstudiantes;
	}

	public void setDtmtArchivoEstudiantes(String dtmtArchivoEstudiantes) {
		this.dtmtArchivoEstudiantes = dtmtArchivoEstudiantes;
	}

	@Column(name = "DTMT_ESTADO_HISTORICO", precision = 2, scale = 0)
	public Integer getDtmtEstadoHistorico() {
		return this.dtmtEstadoHistorico;
	}

	public void setDtmtEstadoHistorico(Integer dtmtEstadoHistorico) {
		this.dtmtEstadoHistorico = dtmtEstadoHistorico;
	}

	@Column(name = "DTMT_ESTADO_CAMBIO", precision = 2, scale = 0)
	public Integer getDtmtEstadoCambio() {
		return this.dtmtEstadoCambio;
	}

	public void setDtmtEstadoCambio(Integer dtmtEstadoCambio) {
		this.dtmtEstadoCambio = dtmtEstadoCambio;
	}

	@Column(name = "DTMT_OBSERVACION_HISTORICO", length = 512)
	@Length(max = 512)
	public String getDtmtObservacionHistorico() {
		return this.dtmtObservacionHistorico;
	}

	public void setDtmtObservacionHistorico(String dtmtObservacionHistorico) {
		this.dtmtObservacionHistorico = dtmtObservacionHistorico;
	}

	@Column(name = "DTMT_OBSERVACION_CAMBIO", length = 512)
	@Length(max = 512)
	public String getDtmtObservacionCambio() {
		return this.dtmtObservacionCambio;
	}

	public void setDtmtObservacionCambio(String dtmtObservacionCambio) {
		this.dtmtObservacionCambio = dtmtObservacionCambio;
	}

	@Column(name = "DTMT_VALOR_PARCIAL", precision = 2)
	public BigDecimal getDtmtValorParcial() {
		return this.dtmtValorParcial;
	}

	public void setDtmtValorParcial(BigDecimal dtmtValorParcial) {
		this.dtmtValorParcial = dtmtValorParcial;
	}

	@Column(name = "DTMT_FECHA_HISTORICO")
	public Timestamp getDtmtFechaHistorico() {
		return dtmtFechaHistorico;
	}

	public void setDtmtFechaHistorico(Timestamp dtmtFechaHistorico) {
		this.dtmtFechaHistorico = dtmtFechaHistorico;
	}

	@Column(name = "DTMT_FECHA_CAMBIO")
	public Timestamp getDtmtFechaCambio() {
		return dtmtFechaCambio;
	}

	public void setDtmtFechaCambio(Timestamp dtmtFechaCambio) {
		this.dtmtFechaCambio = dtmtFechaCambio;
	}

	@Column(name = "DTMT_VALOR_POR_MATERIA")
	public BigDecimal getDtmtValorPorMateria() {
		return dtmtValorPorMateria;
	}

	public void setDtmtValorPorMateria(BigDecimal dtmtValorPorMateria) {
		this.dtmtValorPorMateria = dtmtValorPorMateria;
	}

	@Column(name = "DTMT_USUARIO", length = 256)
	@Length(max = 256)
	public String getDtmtUsuario() {
		return dtmtUsuario;
	}

	public void setDtmtUsuario(String dtmtUsuario) {
		this.dtmtUsuario = dtmtUsuario;
	}

	@Column(name = "DTMT_MODIFICACION")
	public Timestamp getDtmtModificacion() {
		return dtmtModificacion;
	}

	public void setDtmtModificacion(Timestamp dtmtModificacion) {
		this.dtmtModificacion = dtmtModificacion;
	}

	@Column(name = "DTMT_ESTADO_SOLICITUD", precision = 2, scale = 0)
	public Integer getDtmtEstadoSolicitud() {
		return dtmtEstadoSolicitud;
	}

	public void setDtmtEstadoSolicitud(Integer dtmtEstadoSolicitud) {
		this.dtmtEstadoSolicitud = dtmtEstadoSolicitud;
	}

	@Column(name = "DTMT_ESTADO_RESPUESTA", precision = 2, scale = 0)
	public Integer getDtmtEstadoRespuesta() {
		return dtmtEstadoRespuesta;
	}

	public void setDtmtEstadoRespuesta(Integer dtmtEstadoRespuesta) {
		this.dtmtEstadoRespuesta = dtmtEstadoRespuesta;
	}

	@Column(name = "DTMT_FECHA_SOLICITUD")
	public Timestamp getDtmtFechaSolicitud() {
		return dtmtFechaSolicitud;
	}

	public void setDtmtFechaSolicitud(Timestamp dtmtFechaSolicitud) {
		this.dtmtFechaSolicitud = dtmtFechaSolicitud;
	}

	@Column(name = "DTMT_FECHA_RESPUESTA")
	public Timestamp getDtmtFechaRespuesta() {
		return dtmtFechaRespuesta;
	}

	public void setDtmtFechaRespuesta(Timestamp dtmtFechaRespuesta) {
		this.dtmtFechaRespuesta = dtmtFechaRespuesta;
	}
	
	@Column(name = "CSL_RETIRO_ID", precision = 2, scale = 0)
	public Integer getDtmtCslRetiroId() {
		return this.dtmtCslRetiroId;
	}

	public void setDtmtCslRetiroId(Integer dtmtCslRetiroId) {
		this.dtmtCslRetiroId = dtmtCslRetiroId;
	}

	
	
	@Column(name = "DTMT_FECHA_VERIFICACION_RETIRO")
	public Timestamp getDtmtFechaVerificacionRetiro() {
		return dtmtFechaVerificacionRetiro;
	}

	public void setDtmtFechaVerificacionRetiro(Timestamp dtmtFechaVerificacionRetiro) {
		this.dtmtFechaVerificacionRetiro = dtmtFechaVerificacionRetiro;
	}
	
	@Column(name = "DTMT_ARCHIVO_RESPUESTA", length = 512)
	@Length(max = 512)
	public String getDtmtArchivoRespuesta() {
		return this.dtmtArchivoRespuesta;
	}

	public void setDtmtArchivoRespuesta(String dtmtArchivoRespuesta) {
		this.dtmtArchivoRespuesta = dtmtArchivoRespuesta;
	}
	
	
	@Column(name = "DTMT_OBSERVACION_ANULACION", length = 512)
	@Length(max = 512)
	public String getDtmtObservacionAnulacion() {
		return this.dtmtObservacionAnulacion;
	}

	public void setDtmtObservacionAnulacion(String dtmtObservacionAnulacion) {
		this.dtmtObservacionAnulacion = dtmtObservacionAnulacion;
	}
	
	@Column(name = "DTMT_OBSERVACION_FINAL_RETIRO", length = 512)
	@Length(max = 512)
	public String getDtmtObservacionFinalRetiro() {
		return this.dtmtObservacionFinalRetiro;
	}

	public void setDtmtObservacionFinalRetiro(String dtmtObservacionFinalRetiro) {
		this.dtmtObservacionFinalRetiro = dtmtObservacionFinalRetiro;
	}
	
	@Column(name = "DTMT_ARCHIVO_ANULACION", length = 512)
	@Length(max = 512)
	public String getDtmtArchivoAnulacion() {
		return this.dtmtArchivoAnulacion;
	}

	public void setDtmtArchivoAnulacion(String dtmtArchivoAnulacion) {
		this.dtmtArchivoAnulacion = dtmtArchivoAnulacion;
	}
	
	@Column(name = "DTMT_REGISTRANTE_ANULACION", length = 512)
	@Length(max = 512)
	public String getDtmtRegistranteAnulacion() {
		return this.dtmtRegistranteAnulacion;
	}

	public void setDtmtRegistranteAnulacion(String dtmtRegistranteAnulacion) {
		this.dtmtRegistranteAnulacion = dtmtRegistranteAnulacion;
	}
	
	@Column(name = "DTMT_FECHA_ANULACION")
	public Timestamp getDtmtFechaAnulacion() {
		return dtmtFechaAnulacion;
	}

	public void setDtmtFechaAnulacion(Timestamp dtmtFechaAnulacion) {
		this.dtmtFechaAnulacion = dtmtFechaAnulacion;
	}
	
	
	@Column(name = "DTMT_TIPO_ANULACION", precision = 2, scale = 0)
	public Integer getDtmtTipoAnulacion() {
		return this.dtmtTipoAnulacion;
	}

	public void setDtmtTipoAnulacion(Integer dtmtTipoAnulacion) {
		this.dtmtTipoAnulacion = dtmtTipoAnulacion;
	}
	
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "csdtmtDetalleMatricula")
	public List<CausalDetalleMatricula> getDtmtCausalDetalleMatriculas() {
		return this.dtmtCausalDetalleMatriculas;
	}

	public void setDtmtCausalDetalleMatriculas(List<CausalDetalleMatricula> dtmtCausalDetalleMatriculas) {
		this.dtmtCausalDetalleMatriculas = dtmtCausalDetalleMatriculas;
	}
	
	
}
