package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Duracion generated by hbm2java
 */
@Entity
@Table(name = "DURACION", schema = ConstantesJpa.SCHEMA)
public class Duracion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7021142786360398609L;
	private int drcId;
	private Integer drcTipo;
	private Integer drcTiempo;
	private String drcTipoSniese;
	private List<ConfiguracionCarrera> drcConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public Duracion() {
	}

	public Duracion(int drcId) {
		this.drcId = drcId;
	}

	public Duracion(int drcId, Integer drcTipo, Integer drcTiempo, String drcTipoSniese,
			List<ConfiguracionCarrera> drcConfiguracionCarreras) {
		this.drcId = drcId;
		this.drcTipo = drcTipo;
		this.drcTiempo = drcTiempo;
		this.drcTipoSniese = drcTipoSniese;
		this.drcConfiguracionCarreras = drcConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "DRC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDrcId() {
		return this.drcId;
	}

	public void setDrcId(int drcId) {
		this.drcId = drcId;
	}

	@Column(name = "DRC_TIPO", precision = 22, scale = 0)
	public Integer getDrcTipo() {
		return this.drcTipo;
	}

	public void setDrcTipo(Integer drcTipo) {
		this.drcTipo = drcTipo;
	}

	@Column(name = "DRC_TIEMPO", precision = 22, scale = 0)
	public Integer getDrcTiempo() {
		return this.drcTiempo;
	}
	
	@Column(name = "DRC_TIPO_SNIESE", length = 6)
	@Length(max = 6)
	public String getDrcTipoSniese() {
		return this.drcTipoSniese;
	}

	public void setDrcTipoSniese(String drcTipoSniese) {
		this.drcTipoSniese = drcTipoSniese;
	}
	
	public void setDrcTiempo(Integer drcTiempo) {
		this.drcTiempo = drcTiempo;
	}

	@OneToMany( mappedBy = "cncrDuracion")
	public List<ConfiguracionCarrera> getDrcConfiguracionCarreras() {
		return this.drcConfiguracionCarreras;
	}

	public void setDrcConfiguracionCarreras(List<ConfiguracionCarrera> drcConfiguracionCarreras) {
		this.drcConfiguracionCarreras = drcConfiguracionCarreras;
	}

}
