package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Edificio generated by hbm2java
 */
@Entity
@Table(name = "EDIFICIO", schema = ConstantesJpa.SCHEMA)
public class Edificio implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3573426124885402047L;
	private int edfId;
	private Dependencia edfDependencia;
	private String edfDescripcion;
	private Integer edfEstado;
	private String edfCodigo;
	private Integer edfLocalizacion;
	private List<Aula> edfAulas = new ArrayList<Aula>(0);

	public Edificio() {
	}

	public Edificio(int edfId) {
		this.edfId = edfId;
	}

	public Edificio(int edfId, Dependencia edfDependencia, String edfDescripcion, Integer edfEstado, String edfCodigo,
			Integer edfLocalizacion, List<Aula> edfAulas) {
		this.edfId = edfId;
		this.edfDependencia = edfDependencia;
		this.edfDescripcion = edfDescripcion;
		this.edfEstado = edfEstado;
		this.edfCodigo = edfCodigo;
		this.edfLocalizacion = edfLocalizacion;
		this.edfAulas = edfAulas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "EDF_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getEdfId() {
		return this.edfId;
	}

	public void setEdfId(int edfId) {
		this.edfId = edfId;
	}

	@ManyToOne
	@JoinColumn(name = "DPN_ID")
	public Dependencia getEdfDependencia() {
		return this.edfDependencia;
	}

	public void setEdfDependencia(Dependencia edfDependencia) {
		this.edfDependencia = edfDependencia;
	}

	@Column(name = "EDF_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getEdfDescripcion() {
		return this.edfDescripcion;
	}

	public void setEdfDescripcion(String edfDescripcion) {
		this.edfDescripcion = edfDescripcion;
	}

	@Column(name = "EDF_ESTADO", precision = 22, scale = 0)
	public Integer getEdfEstado() {
		return this.edfEstado;
	}

	public void setEdfEstado(Integer edfEstado) {
		this.edfEstado = edfEstado;
	}

	@Column(name = "EDF_CODIGO", length = 256)
	@Length(max = 256)
	public String getEdfCodigo() {
		return this.edfCodigo;
	}

	public void setEdfCodigo(String edfCodigo) {
		this.edfCodigo = edfCodigo;
	}

	@Column(name = "EDF_LOCALIZACION", precision = 22, scale = 0)
	public Integer getEdfLocalizacion() {
		return this.edfLocalizacion;
	}

	public void setEdfLocalizacion(Integer edfLocalizacion) {
		this.edfLocalizacion = edfLocalizacion;
	}

	@OneToMany( mappedBy = "alaEdificio")
	public List<Aula> getEdfAulas() {
		return this.edfAulas;
	}

	public void setEdfAulas(List<Aula> edfAulas) {
		this.edfAulas = edfAulas;
	}

}
