package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ExperienciaLaboralContr generated by hbm2java
 */
@Entity
@Table(name = "EXPERIENCIA_LABORAL_CONTR", schema = ConstantesJpa.SCHEMA)
public class ExperienciaLaboralContr implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3866520419974859485L;
	private int exlbcnId;
	private CandidatoContrato exlbcnCandidatoContrato;
	private Integer exlbcnTipoInstitucion;
	private String exlbcnDescripcion;
	private String exlbcnUnidad;
	private String exlbcnPuesto;
	private Date exlbcnFechaIngreso;
	private Date exlbcnFechaSalida;
	private Integer exlbcnMotivoIngreso;
	private Integer exlbcnMotivoSalida;
	private Integer exlbcnTipo;

	public ExperienciaLaboralContr() {
	}

	public ExperienciaLaboralContr(int exlbcnId) {
		this.exlbcnId = exlbcnId;
	}

	public ExperienciaLaboralContr(int exlbcnId, CandidatoContrato exlbcnCandidatoContrato, Integer exlbcnTipoInstitucion,
			String exlbcnDescripcion, String exlbcnUnidad, String exlbcnPuesto, Date exlbcnFechaIngreso,
			Date exlbcnFechaSalida, Integer exlbcnMotivoIngreso, Integer exlbcnMotivoSalida,
			Integer exlbcnTipo) {
		this.exlbcnId = exlbcnId;
		this.exlbcnCandidatoContrato = exlbcnCandidatoContrato;
		this.exlbcnTipoInstitucion = exlbcnTipoInstitucion;
		this.exlbcnDescripcion = exlbcnDescripcion;
		this.exlbcnUnidad = exlbcnUnidad;
		this.exlbcnPuesto = exlbcnPuesto;
		this.exlbcnFechaIngreso = exlbcnFechaIngreso;
		this.exlbcnFechaSalida = exlbcnFechaSalida;
		this.exlbcnMotivoIngreso = exlbcnMotivoIngreso;
		this.exlbcnMotivoSalida = exlbcnMotivoSalida;
		this.exlbcnTipo = exlbcnTipo;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "EXLBCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getExlbcnId() {
		return this.exlbcnId;
	}

	public void setExlbcnId(int exlbcnId) {
		this.exlbcnId = exlbcnId;
	}

	@ManyToOne
	@JoinColumn(name = "CNCN_ID")
	public CandidatoContrato getExlbcnCandidatoContrato() {
		return this.exlbcnCandidatoContrato;
	}

	public void setExlbcnCandidatoContrato(CandidatoContrato exlbcnCandidatoContrato) {
		this.exlbcnCandidatoContrato = exlbcnCandidatoContrato;
	}

	@Column(name = "EXLBCN_TIPO_INSTITUCION", precision = 22, scale = 0)
	public Integer getExlbcnTipoInstitucion() {
		return this.exlbcnTipoInstitucion;
	}

	public void setExlbcnTipoInstitucion(Integer exlbcnTipoInstitucion) {
		this.exlbcnTipoInstitucion = exlbcnTipoInstitucion;
	}

	@Column(name = "EXLBCN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getExlbcnDescripcion() {
		return this.exlbcnDescripcion;
	}

	public void setExlbcnDescripcion(String exlbcnDescripcion) {
		this.exlbcnDescripcion = exlbcnDescripcion;
	}

	@Column(name = "EXLBCN_UNIDAD", length = 256)
	@Length(max = 256)
	public String getExlbcnUnidad() {
		return this.exlbcnUnidad;
	}

	public void setExlbcnUnidad(String exlbcnUnidad) {
		this.exlbcnUnidad = exlbcnUnidad;
	}

	@Column(name = "EXLBCN_PUESTO", length = 256)
	@Length(max = 256)
	public String getExlbcnPuesto() {
		return this.exlbcnPuesto;
	}

	public void setExlbcnPuesto(String exlbcnPuesto) {
		this.exlbcnPuesto = exlbcnPuesto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXLBCN_FECHA_INGRESO", length = 7)
	public Date getExlbcnFechaIngreso() {
		return this.exlbcnFechaIngreso;
	}

	public void setExlbcnFechaIngreso(Date exlbcnFechaIngreso) {
		this.exlbcnFechaIngreso = exlbcnFechaIngreso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXLBCN_FECHA_SALIDA", length = 7)
	public Date getExlbcnFechaSalida() {
		return this.exlbcnFechaSalida;
	}

	public void setExlbcnFechaSalida(Date exlbcnFechaSalida) {
		this.exlbcnFechaSalida = exlbcnFechaSalida;
	}

	@Column(name = "EXLBCN_MOTIVO_INGRESO", precision = 22, scale = 0)
	public Integer getExlbcnMotivoIngreso() {
		return this.exlbcnMotivoIngreso;
	}

	public void setExlbcnMotivoIngreso(Integer exlbcnMotivoIngreso) {
		this.exlbcnMotivoIngreso = exlbcnMotivoIngreso;
	}

	@Column(name = "EXLBCN_MOTIVO_SALIDA", precision = 22, scale = 0)
	public Integer getExlbcnMotivoSalida() {
		return this.exlbcnMotivoSalida;
	}

	public void setExlbcnMotivoSalida(Integer exlbcnMotivoSalida) {
		this.exlbcnMotivoSalida = exlbcnMotivoSalida;
	}

	@Column(name = "EXLBCN_TIPO", precision = 22, scale = 0)
	public Integer getExlbcnTipo() {
		return this.exlbcnTipo;
	}

	public void setExlbcnTipo(Integer exlbcnTipo) {
		this.exlbcnTipo = exlbcnTipo;
	}

}
