package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * FichaEstudiante generated by hbm2java
 */
@Entity
@Table(name = "FICHA_ESTUDIANTE", schema = ConstantesJpa.SCHEMA)
public class FichaEstudiante implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1517300103148349243L;
	private int fcesId;
	private Persona fcesPersona;
	private InstitucionAcademica fcesInstitucionAcademica;
	private FichaInscripcion fcesFichaInscripcion;
	private Date fcesFechaInicio;
	private Date fcesFechaEgresamiento;
	private Date fcesFechaActaGrado;
	private String fcesNumActaGrado;
	private Date fcesFechaRefrendacion;
	private String fcesNumRefrendacion;
	private String fcesCrrEstudPrevios;
	private Integer fcesTiempoEstudRec;
	private Integer fcesTipoDuracRec;
	private Integer fcesTipoColegio;
	private String fcesTipoColegioSniese;
	private BigDecimal fcesNotaPromAcumulado;
	private BigDecimal fcesNotaTrabTitulacion;
	private String fcesLinkTesis;
	private Integer fcesRecEstudPrevios;
	private String fcesRecEstudPrevSniese;
	private Timestamp fcesFechaCreacion;
	private Integer fcesEstadoUniversitario;
	private Integer fcesEstadoMatricula;
	private String fcesObservacion;
	private String fcesTituloBachiller;
	private Float fcesNotaGradoSecundaria;
	private Integer fcesInacTtlId;
	private Integer fcesUbcColegio;
	private Integer fcesColegioId;  
	private Integer fcesTipoUnivEstudPrev;
	private Integer fcesEstadoEstudPrev;
	private Integer fcesUnivEstudPrevId;  
	private Integer fcesTitEstudPrevId;
	private String fcesRegTituloPrev;
			
	private Timestamp fcesFechaActualizacionDatos;
	private List<RecordEstudiante> fcesRecordEstudiantes = new ArrayList<RecordEstudiante>(0);
	private List<Gratuidad> fcesGratuidads = new ArrayList<Gratuidad>(0);
	private List<ProcesoEstudiante> fcesProcesoEstudiantes = new ArrayList<ProcesoEstudiante>(0);
	private List<FichaMatricula> fcesFichaMatriculas = new ArrayList<FichaMatricula>(0);

	public FichaEstudiante() {
	}

	public FichaEstudiante(int fcesId) {
		this.fcesId = fcesId;
	}

	public FichaEstudiante(int fcesId, Persona fcesPersona, InstitucionAcademica fcesInstitucionAcademica, FichaInscripcion fcesFichaInscripcion,
			Date fcesFechaInicio, Date fcesFechaEgresamiento,
			Date fcesFechaActaGrado, String fcesNumActaGrado, Date fcesFechaRefrendacion, String fcesNumRefrendacion,
			String fcesCrrEstudPrevios, Integer fcesTiempoEstudRec, Integer fcesTipoDuracRec,
			Integer fcesTipoColegio, String fcesTipoColegioSniese, BigDecimal fcesNotaPromAcumulado,
			BigDecimal fcesNotaTrabTitulacion, String fcesLinkTesis, Integer fcesRecEstudPrevios,
			String fcesRecEstudPrevSniese, Timestamp fcesFechaCreacion, Integer fcesEstadoUniversitario,
			Integer fcesEstadoMatricula, String fcesObservacion, String fcesTituloBachiller,Float fcesNotaGradoSecundaria, Integer fcesInacTtlId,
			Integer fcesUbcColegio, Integer fcesColegioId, Integer fcesUnivEstudPrevId, Integer fcesTitEstudPrevId, String fcesRegTituloPrev,
			Integer fcesTipoUnivEstudPrev,Integer fcesEstadoEstudPrev, Timestamp fcesFechaActualizacionDatos,List<RecordEstudiante> fcesRecordEstudiantes,
			List<Gratuidad> fcesGratuidads, List<ProcesoEstudiante> fcesProcesoEstudiantes,
			List<FichaMatricula> fcesFichaMatriculas) {
		this.fcesId = fcesId;
		this.fcesPersona = fcesPersona;
		this.fcesInstitucionAcademica = fcesInstitucionAcademica;
		this.fcesFichaInscripcion = fcesFichaInscripcion;
		this.fcesFechaInicio = fcesFechaInicio;
		this.fcesFechaEgresamiento = fcesFechaEgresamiento;
		this.fcesFechaActaGrado = fcesFechaActaGrado;
		this.fcesNumActaGrado = fcesNumActaGrado;
		this.fcesFechaRefrendacion = fcesFechaRefrendacion;
		this.fcesNumRefrendacion = fcesNumRefrendacion;
		this.fcesCrrEstudPrevios = fcesCrrEstudPrevios;
		this.fcesTiempoEstudRec = fcesTiempoEstudRec;
		this.fcesTipoDuracRec = fcesTipoDuracRec;
		this.fcesTipoColegio = fcesTipoColegio;
		this.fcesTipoColegioSniese = fcesTipoColegioSniese;
		this.fcesNotaPromAcumulado = fcesNotaPromAcumulado;
		this.fcesNotaTrabTitulacion = fcesNotaTrabTitulacion;
		this.fcesLinkTesis = fcesLinkTesis;
		this.fcesRecEstudPrevios = fcesRecEstudPrevios;
		this.fcesEstadoEstudPrev = fcesEstadoEstudPrev;
		this.fcesRecEstudPrevSniese = fcesRecEstudPrevSniese;
		this.fcesFechaCreacion = fcesFechaCreacion;
		this.fcesEstadoUniversitario = fcesEstadoUniversitario;
		this.fcesEstadoMatricula = fcesEstadoMatricula;
		this.fcesObservacion = fcesObservacion;
		this.fcesTituloBachiller = fcesTituloBachiller;
		this.fcesNotaGradoSecundaria = fcesNotaGradoSecundaria;
		this.fcesInacTtlId = fcesInacTtlId;
		this.fcesUbcColegio = fcesUbcColegio;
		this.fcesColegioId = fcesColegioId;
		this.fcesTipoUnivEstudPrev = fcesTipoUnivEstudPrev;
		
		this.fcesUnivEstudPrevId = fcesUnivEstudPrevId;
		this.fcesTitEstudPrevId = fcesTitEstudPrevId;
		this.fcesRegTituloPrev = fcesRegTituloPrev;
		
		this.fcesFechaActualizacionDatos = fcesFechaActualizacionDatos;
		this.fcesRecordEstudiantes = fcesRecordEstudiantes;
		this.fcesGratuidads = fcesGratuidads;
		this.fcesProcesoEstudiantes = fcesProcesoEstudiantes;
		this.fcesFichaMatriculas = fcesFichaMatriculas;
		
		
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "FCES_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFcesId() {
		return this.fcesId;
	}

	public void setFcesId(int fcesId) {
		this.fcesId = fcesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID")
	public Persona getFcesPersona() {
		return this.fcesPersona;
	}

	public void setFcesPersona(Persona fcesPersona) {
		this.fcesPersona = fcesPersona;
	}
	
	@ManyToOne
	@JoinColumn(name = "INAC_ID")
	public InstitucionAcademica getFcesInstitucionAcademica() {
		return fcesInstitucionAcademica;
	}

	public void setFcesInstitucionAcademica(InstitucionAcademica fcesInstitucionAcademica) {
		this.fcesInstitucionAcademica = fcesInstitucionAcademica;
	}
	
	@ManyToOne
	@JoinColumn(name = "FCIN_ID")
	public FichaInscripcion getFcesFichaInscripcion() {
		return this.fcesFichaInscripcion;
	}

	public void setFcesFichaInscripcion(FichaInscripcion fcesFichaInscripcion) {
		this.fcesFichaInscripcion = fcesFichaInscripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCES_FECHA_INICIO", length = 7)
	public Date getFcesFechaInicio() {
		return this.fcesFechaInicio;
	}

	public void setFcesFechaInicio(Date fcesFechaInicio) {
		this.fcesFechaInicio = fcesFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCES_FECHA_EGRESAMIENTO", length = 7)
	public Date getFcesFechaEgresamiento() {
		return this.fcesFechaEgresamiento;
	}

	public void setFcesFechaEgresamiento(Date fcesFechaEgresamiento) {
		this.fcesFechaEgresamiento = fcesFechaEgresamiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCES_FECHA_ACTA_GRADO", length = 7)
	public Date getFcesFechaActaGrado() {
		return this.fcesFechaActaGrado;
	}

	public void setFcesFechaActaGrado(Date fcesFechaActaGrado) {
		this.fcesFechaActaGrado = fcesFechaActaGrado;
	}

	@Column(name = "FCES_NUM_ACTA_GRADO", length = 40)
	@Length(max = 40)
	public String getFcesNumActaGrado() {
		return this.fcesNumActaGrado;
	}

	public void setFcesNumActaGrado(String fcesNumActaGrado) {
		this.fcesNumActaGrado = fcesNumActaGrado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCES_FECHA_REFRENDACION", length = 7)
	public Date getFcesFechaRefrendacion() {
		return this.fcesFechaRefrendacion;
	}

	public void setFcesFechaRefrendacion(Date fcesFechaRefrendacion) {
		this.fcesFechaRefrendacion = fcesFechaRefrendacion;
	}

	@Column(name = "FCES_NUM_REFRENDACION", length = 20)
	@Length(max = 20)
	public String getFcesNumRefrendacion() {
		return this.fcesNumRefrendacion;
	}

	public void setFcesNumRefrendacion(String fcesNumRefrendacion) {
		this.fcesNumRefrendacion = fcesNumRefrendacion;
	}

	@Column(name = "FCES_CRR_ESTUD_PREVIOS", length = 512)
	@Length(max = 512)
	public String getFcesCrrEstudPrevios() {
		return this.fcesCrrEstudPrevios;
	}

	public void setFcesCrrEstudPrevios(String fcesCrrEstudPrevios) {
		this.fcesCrrEstudPrevios = fcesCrrEstudPrevios;
	}

	@Column(name = "FCES_TIEMPO_ESTUD_REC", precision = 22, scale = 0)
	public Integer getFcesTiempoEstudRec() {
		return this.fcesTiempoEstudRec;
	}

	public void setFcesTiempoEstudRec(Integer fcesTiempoEstudRec) {
		this.fcesTiempoEstudRec = fcesTiempoEstudRec;
	}

	@Column(name = "FCES_TIPO_DURAC_REC", precision = 22, scale = 0)
	public Integer getFcesTipoDuracRec() {
		return this.fcesTipoDuracRec;
	}

	public void setFcesTipoDuracRec(Integer fcesTipoDuracRec) {
		this.fcesTipoDuracRec = fcesTipoDuracRec;
	}

	
	@Column(name = "FCES_ESTADO_ESTUD_PREV", precision = 22, scale = 0)
	public Integer getFcesEstadoEstudPrev() {
		return this.fcesEstadoEstudPrev;
	}

	public void setFcesEstadoEstudPrev(Integer fcesEstadoEstudPrev) {
		this.fcesEstadoEstudPrev = fcesEstadoEstudPrev;
	}
	
	
	@Column(name = "FCES_TIPO_COLEGIO", precision = 22, scale = 0)
	public Integer getFcesTipoColegio() {
		return this.fcesTipoColegio;
	}

	public void setFcesTipoColegio(Integer fcesTipoColegio) {
		this.fcesTipoColegio = fcesTipoColegio;
	}

	@Column(name = "FCES_TIPO_COLEGIO_SNIESE", length = 1)
	@Length(max = 1)
	public String getFcesTipoColegioSniese() {
		return this.fcesTipoColegioSniese;
	}

	public void setFcesTipoColegioSniese(String fcesTipoColegioSniese) {
		this.fcesTipoColegioSniese = fcesTipoColegioSniese;
	}

	@Column(name = "FCES_NOTA_PROM_ACUMULADO", precision = 4)
	public BigDecimal getFcesNotaPromAcumulado() {
		return this.fcesNotaPromAcumulado;
	}

	public void setFcesNotaPromAcumulado(BigDecimal fcesNotaPromAcumulado) {
		this.fcesNotaPromAcumulado = fcesNotaPromAcumulado;
	}

	@Column(name = "FCES_NOTA_TRAB_TITULACION", precision = 4)
	public BigDecimal getFcesNotaTrabTitulacion() {
		return this.fcesNotaTrabTitulacion;
	}

	public void setFcesNotaTrabTitulacion(BigDecimal fcesNotaTrabTitulacion) {
		this.fcesNotaTrabTitulacion = fcesNotaTrabTitulacion;
	}

	@Column(name = "FCES_LINK_TESIS", length = 512)
	@Length(max = 512)
	public String getFcesLinkTesis() {
		return this.fcesLinkTesis;
	}

	public void setFcesLinkTesis(String fcesLinkTesis) {
		this.fcesLinkTesis = fcesLinkTesis;
	}

	@Column(name = "FCES_REC_ESTUD_PREVIOS", precision = 22, scale = 0)
	public Integer getFcesRecEstudPrevios() {
		return this.fcesRecEstudPrevios;
	}

	public void setFcesRecEstudPrevios(Integer fcesRecEstudPrevios) {
		this.fcesRecEstudPrevios = fcesRecEstudPrevios;
	}

	@Column(name = "FCES_REC_ESTUD_PREV_SNIESE", length = 1)
	@Length(max = 1)
	public String getFcesRecEstudPrevSniese() {
		return this.fcesRecEstudPrevSniese;
	}

	public void setFcesRecEstudPrevSniese(String fcesRecEstudPrevSniese) {
		this.fcesRecEstudPrevSniese = fcesRecEstudPrevSniese;
	}

	@Column(name = "FCES_FECHA_CREACION")
	public Timestamp getFcesFechaCreacion() {
		return this.fcesFechaCreacion;
	}

	public void setFcesFechaCreacion(Timestamp fcesFechaCreacion) {
		this.fcesFechaCreacion = fcesFechaCreacion;
	}

	@Column(name = "FCES_ESTADO_UNIVERSITARIO", precision = 22, scale = 0)
	public Integer getFcesEstadoUniversitario() {
		return this.fcesEstadoUniversitario;
	}

	public void setFcesEstadoUniversitario(Integer fcesEstadoUniversitario) {
		this.fcesEstadoUniversitario = fcesEstadoUniversitario;
	}

	@Column(name = "FCES_ESTADO_MATRICULA", precision = 22, scale = 0)
	public Integer getFcesEstadoMatricula() {
		return this.fcesEstadoMatricula;
	}

	public void setFcesEstadoMatricula(Integer fcesEstadoMatricula) {
		this.fcesEstadoMatricula = fcesEstadoMatricula;
	}

	@Column(name = "FCES_OBSERVACION", length = 256)
	@Length(max = 256)
	public String getFcesObservacion() {
		return this.fcesObservacion;
	}

	public void setFcesObservacion(String fcesObservacion) {
		this.fcesObservacion = fcesObservacion;
	}
	
	@Column(name = "FCES_TITULO_BACHILLER", length = 256)
	@Length(max = 256)
	public String getFcesTituloBachiller() {
		return fcesTituloBachiller;
	}

	public void setFcesTituloBachiller(String fcesTituloBachiller) {
		this.fcesTituloBachiller = fcesTituloBachiller;
	}

	@Column(name="FCES_NOTA_GRADO_SECUNDARIA", precision=126)
	public Float getFcesNotaGradoSecundaria() {
		return this.fcesNotaGradoSecundaria;
	}

	public void setFcesNotaGradoSecundaria(Float fcesNotaGradoSecundaria) {
		this.fcesNotaGradoSecundaria = fcesNotaGradoSecundaria;
	}
	
	
	@Column(name = "FCES_INAC_TTL_ID", precision = 22, scale = 0)
	public Integer getFcesInacTtlId() {
		return this.fcesInacTtlId;
	}

	public void setFcesInacTtlId(Integer fcesInacTtlId) {
		this.fcesInacTtlId = fcesInacTtlId;
	}
	
	

	@Column(name = "FCES_UBC_COLEGIO", precision = 22, scale = 0)
	public Integer getFcesUbcColegio() {
		return this.fcesUbcColegio;
	}

	public void setFcesUbcColegio(Integer fcesUbcColegio) {
		this.fcesUbcColegio = fcesUbcColegio;
	}
		
	
	@Column(name = "FCES_COLEGIO_ID", precision = 22, scale = 0)
	public Integer getFcesColegioId() {
		return this.fcesColegioId;
	}

	public void setFcesColegioId(Integer fcesColegioId) {
		this.fcesColegioId = fcesColegioId;
	}
	@Column(name = "FCES_TIPO_UNIV_ESTUD_PREV", precision = 22, scale = 0)
	public Integer getFcesTipoUnivEstudPrev() {
		return this.fcesTipoUnivEstudPrev;
	}

	public void setFcesTipoUnivEstudPrev(Integer fcesTipoUnivEstudPrev) {
		this.fcesTipoUnivEstudPrev = fcesTipoUnivEstudPrev;
	}
	
	@Column(name = "FCES_FECHA_ACTUALIZACION_DATOS")
	public Timestamp getFcesFechaActualizacionDatos() {
		return this.fcesFechaActualizacionDatos;
	}

	public void setFcesFechaActualizacionDatos(Timestamp fcesFechaActualizacionDatos) {
		this.fcesFechaActualizacionDatos = fcesFechaActualizacionDatos;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rcesFichaEstudiante")
	public List<RecordEstudiante> getFcesRecordEstudiantes() {
		return this.fcesRecordEstudiantes;
	}

	public void setFcesRecordEstudiantes(List<RecordEstudiante> fcesRecordEstudiantes) {
		this.fcesRecordEstudiantes = fcesRecordEstudiantes;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grtFichaEstudiante")
	public List<Gratuidad> getFcesGratuidads() {
		return this.fcesGratuidads;
	}

	public void setFcesGratuidads(List<Gratuidad> fcesGratuidads) {
		this.fcesGratuidads = fcesGratuidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "presFichaEstudiante")
	public List<ProcesoEstudiante> getFcesProcesoEstudiantes() {
		return this.fcesProcesoEstudiantes;
	}

	public void setFcesProcesoEstudiantes(List<ProcesoEstudiante> fcesProcesoEstudiantes) {
		this.fcesProcesoEstudiantes = fcesProcesoEstudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcmtFichaEstudiante")
	public List<FichaMatricula> getFcesFichaMatriculas() {
		return this.fcesFichaMatriculas;
	}

	public void setFcesFichaMatriculas(List<FichaMatricula> fcesFichaMatriculas) {
		this.fcesFichaMatriculas = fcesFichaMatriculas;
	}

	

	
	
	@Column(name = "FCES_UNIV_ESTUD_PREV_ID", precision = 22, scale = 0)
	public Integer getFcesUnivEstudPrevId() {
		return this.fcesUnivEstudPrevId;
	}

	public void setFcesUnivEstudPrevId(Integer fcesUnivEstudPrevId) {
		this.fcesUnivEstudPrevId = fcesUnivEstudPrevId;
	}
		
	
	@Column(name = "FCES_TIT_ESTUD_PREV_ID", precision = 22, scale = 0)
	public Integer getFcesTitEstudPrevId() {
		return this.fcesTitEstudPrevId;
	}

	public void setFcesTitEstudPrevId(Integer fcesTitEstudPrevId) {
		this.fcesTitEstudPrevId = fcesTitEstudPrevId;
	}
	
	
	
	@Column(name = "FCES_REG_TITULO_PREV", length = 128)
	@Length(max = 128)
	public String getFcesRegTituloPrev() {
		return fcesRegTituloPrev;
	}

	public void setFcesRegTituloPrev(String fcesRegTituloPrev) {
		this.fcesRegTituloPrev = fcesRegTituloPrev;
	}
	
}
