package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * FichaEmpleado generated by hbm2java
 */
@Entity
@Table(name = "FICHA_EMPLEADO", schema = ConstantesJpa.SCHEMA)
public class FichaEmpleado implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7325798325736640887L;
	private int fcemId;
	private Persona fcemPersona;
	private List<DetallePuesto> fcemDetallePuestos = new ArrayList<DetallePuesto>(0);

	public FichaEmpleado() {
	}

	public FichaEmpleado(int fcemId) {
		this.fcemId = fcemId;
	}

	public FichaEmpleado(int fcemId, Persona fcemPersona, List<DetallePuesto> fcemDetallePuestos) {
		this.fcemId = fcemId;
		this.fcemPersona = fcemPersona;
		this.fcemDetallePuestos = fcemDetallePuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "FCEM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFcemId() {
		return this.fcemId;
	}

	public void setFcemId(int fcemId) {
		this.fcemId = fcemId;
	}

	@ManyToOne
	@JoinColumn(name = "PRS_ID")
	public Persona getFcemPersona() {
		return this.fcemPersona;
	}

	public void setFcemPersona(Persona fcemPersona) {
		this.fcemPersona = fcemPersona;
	}

	@OneToMany( mappedBy = "dtpsFichaEmpleado")
	public List<DetallePuesto> getFcemDetallePuestos() {
		return this.fcemDetallePuestos;
	}

	public void setFcemDetallePuestos(List<DetallePuesto> fcemDetallePuestos) {
		this.fcemDetallePuestos = fcemDetallePuestos;
	}

}
