package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * FichaMatricula generated by hbm2java
 */
@Entity
@Table(name = "FICHA_MATRICULA", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "FichaMatricula.findAll", query = "SELECT m FROM FichaMatricula m"),
				@NamedQuery(name = "FichaMatricula.findPorFcesIdPracId", query = "SELECT m FROM FichaMatricula m WHERE m.fcmtFichaEstudiante.fcesId = :fcesId and m.fcmtPracId = :periodoId") })
public class FichaMatricula implements java.io.Serializable {

	private static final long serialVersionUID = 6109638437575704559L;
	
	private int fcmtId;
	private PlanificacionCronograma fcmtPlanificacionCronograma;
	private FichaEstudiante fcmtFichaEstudiante;
	private Integer fcmtNivelUbicacion;
	private Integer fcmtEstado;
	private Date fcmtFechaConvalidacion;
	private Integer fcmtTipo;
	private Integer fcmtModalidad;
	private BigDecimal fcmtValorTotal;
	private Timestamp fcmtFechaMatricula;
	private Timestamp fcmtFechaEstado;
	private Integer fcmtPracId;
	private List<ComprobantePago> fcmtComprobantePagos = new ArrayList<ComprobantePago>(0);
	private List<Gratuidad> fcmtGratuidads = new ArrayList<Gratuidad>(0);

	public FichaMatricula() {
	}

	public FichaMatricula(int fcmtId) {
		this.fcmtId = fcmtId;
	}

	public FichaMatricula(int fcmtId, PlanificacionCronograma fcmtPlanificacionCronograma,
			FichaEstudiante fcmtFichaEstudiante, Integer fcmtNivelUbicacion, Integer fcmtEstado,
			Date fcmtFechaConvalidacion, Integer fcmtTipo, Integer fcmtModalidad, BigDecimal fcmtValorTotal,
			Timestamp fcmtFechaMatricula, Timestamp fcmtFechaEstado, List<ComprobantePago> fcmtComprobantePagos,
			List<Gratuidad> fcmtGratuidads) {
		this.fcmtId = fcmtId;
		this.fcmtPlanificacionCronograma = fcmtPlanificacionCronograma;
		this.fcmtFichaEstudiante = fcmtFichaEstudiante;
		this.fcmtNivelUbicacion = fcmtNivelUbicacion;
		this.fcmtEstado = fcmtEstado;
		this.fcmtFechaConvalidacion = fcmtFechaConvalidacion;
		this.fcmtTipo = fcmtTipo;
		this.fcmtModalidad = fcmtModalidad;
		this.fcmtValorTotal = fcmtValorTotal;
		this.fcmtFechaMatricula = fcmtFechaMatricula;
		this.fcmtFechaEstado = fcmtFechaEstado;
		this.fcmtComprobantePagos = fcmtComprobantePagos;
		this.fcmtGratuidads = fcmtGratuidads;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "FCMT_ID", unique = true, nullable = false, precision = 2, scale = 0)
	public int getFcmtId() {
		return this.fcmtId;
	}

	public void setFcmtId(int fcmtId) {
		this.fcmtId = fcmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLCR_ID")
	public PlanificacionCronograma getFcmtPlanificacionCronograma() {
		return this.fcmtPlanificacionCronograma;
	}

	public void setFcmtPlanificacionCronograma(PlanificacionCronograma fcmtPlanificacionCronograma) {
		this.fcmtPlanificacionCronograma = fcmtPlanificacionCronograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCES_ID")
	public FichaEstudiante getFcmtFichaEstudiante() {
		return this.fcmtFichaEstudiante;
	}

	public void setFcmtFichaEstudiante(FichaEstudiante fcmtFichaEstudiante) {
		this.fcmtFichaEstudiante = fcmtFichaEstudiante;
	}

	@Column(name = "FCMT_NIVEL_UBICACION", precision = 2, scale = 0)
	public Integer getFcmtNivelUbicacion() {
		return this.fcmtNivelUbicacion;
	}

	public void setFcmtNivelUbicacion(Integer fcmtNivelUbicacion) {
		this.fcmtNivelUbicacion = fcmtNivelUbicacion;
	}

	@Column(name = "FCMT_ESTADO", precision = 2, scale = 0)
	public Integer getFcmtEstado() {
		return this.fcmtEstado;
	}

	public void setFcmtEstado(Integer fcmtEstado) {
		this.fcmtEstado = fcmtEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCMT_FECHA_CONVALIDACION", length = 7)
	public Date getFcmtFechaConvalidacion() {
		return this.fcmtFechaConvalidacion;
	}

	public void setFcmtFechaConvalidacion(Date fcmtFechaConvalidacion) {
		this.fcmtFechaConvalidacion = fcmtFechaConvalidacion;
	}

	@Column(name = "FCMT_TIPO", precision = 2, scale = 0)
	public Integer getFcmtTipo() {
		return this.fcmtTipo;
	}

	public void setFcmtTipo(Integer fcmtTipo) {
		this.fcmtTipo = fcmtTipo;
	}

	@Column(name = "FCMT_MODALIDAD", precision = 2, scale = 0)
	public Integer getFcmtModalidad() {
		return this.fcmtModalidad;
	}

	public void setFcmtModalidad(Integer fcmtModalidad) {
		this.fcmtModalidad = fcmtModalidad;
	}

	@Column(name = "FCMT_VALOR_TOTAL", precision = 2)
	public BigDecimal getFcmtValorTotal() {
		return this.fcmtValorTotal;
	}

	public void setFcmtValorTotal(BigDecimal fcmtValorTotal) {
		this.fcmtValorTotal = fcmtValorTotal;
	}

	@Column(name = "FCMT_FECHA_MATRICULA")
	public Timestamp getFcmtFechaMatricula() {
		return this.fcmtFechaMatricula;
	}

	public void setFcmtFechaMatricula(Timestamp fcmtFechaMatricula) {
		this.fcmtFechaMatricula = fcmtFechaMatricula;
	}

	@Column(name = "FCMT_FECHA_ESTADO")	
	public Timestamp getFcmtFechaEstado() {
		return fcmtFechaEstado;
	}

	public void setFcmtFechaEstado(Timestamp fcmtFechaEstado) {
		this.fcmtFechaEstado = fcmtFechaEstado;
	}


	@Column(name = "FCMT_PRAC_ID")
	public Integer getFcmtPracId() {
		return fcmtPracId;
	}

	public void setFcmtPracId(Integer fcmtPracId) {
		this.fcmtPracId = fcmtPracId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cmpaFichaMatricula")
	public List<ComprobantePago> getFcmtComprobantePagos() {
		return this.fcmtComprobantePagos;
	}

	public void setFcmtComprobantePagos(List<ComprobantePago> fcmtComprobantePagos) {
		this.fcmtComprobantePagos = fcmtComprobantePagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grtFichaMatricula")
	public List<Gratuidad> getFcmtGratuidads() {
		return this.fcmtGratuidads;
	}

	public void setFcmtGratuidads(List<Gratuidad> fcmtGratuidads) {
		this.fcmtGratuidads = fcmtGratuidads;
	}

}
