package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * FuncionCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "FUNCION_CARGA_HORARIA", schema = ConstantesJpa.SCHEMA)
public class FuncionCargaHoraria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6481331313046679227L;
	private int fncrhrId;
	private String fncrhrDescripcion;
	private Integer fncrhrHorasAsignadas;
	private Integer fncrhrHorasMinimo;
	private Integer fncrhrHorasMaximo;
	private Integer fncrhrTiempoDedicacion;
	private List<TipoFuncionCargaHoraria> fncrhrTipoFuncionCargaHorarias = new ArrayList<TipoFuncionCargaHoraria>(0);

	public FuncionCargaHoraria() {
	}

	public FuncionCargaHoraria(int fncrhrId) {
		this.fncrhrId = fncrhrId;
	}

	public FuncionCargaHoraria(int fncrhrId, String fncrhrDescripcion, Integer fncrhrHorasAsignadas,
			Integer fncrhrHorasMinimo, Integer fncrhrHorasMaximo,
			List<TipoFuncionCargaHoraria> fncrhrTipoFuncionCargaHorarias) {
		this.fncrhrId = fncrhrId;
		this.fncrhrDescripcion = fncrhrDescripcion;
		this.fncrhrHorasAsignadas = fncrhrHorasAsignadas;
		this.fncrhrHorasMinimo = fncrhrHorasMinimo;
		this.fncrhrHorasMaximo = fncrhrHorasMaximo;
		this.fncrhrTipoFuncionCargaHorarias = fncrhrTipoFuncionCargaHorarias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "FNCRHR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFncrhrId() {
		return this.fncrhrId;
	}

	public void setFncrhrId(int fncrhrId) {
		this.fncrhrId = fncrhrId;
	}

	@Column(name = "FNCRHR_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getFncrhrDescripcion() {
		return this.fncrhrDescripcion;
	}

	public void setFncrhrDescripcion(String fncrhrDescripcion) {
		this.fncrhrDescripcion = fncrhrDescripcion;
	}

	@Column(name = "FNCRHR_HORAS_ASIGNADAS", precision = 22, scale = 0)
	public Integer getFncrhrHorasAsignadas() {
		return this.fncrhrHorasAsignadas;
	}

	public void setFncrhrHorasAsignadas(Integer fncrhrHorasAsignadas) {
		this.fncrhrHorasAsignadas = fncrhrHorasAsignadas;
	}

	@Column(name = "FNCRHR_HORAS_MINIMO", precision = 22, scale = 0)
	public Integer getFncrhrHorasMinimo() {
		return this.fncrhrHorasMinimo;
	}

	public void setFncrhrHorasMinimo(Integer fncrhrHorasMinimo) {
		this.fncrhrHorasMinimo = fncrhrHorasMinimo;
	}

	@Column(name = "FNCRHR_HORAS_MAXIMO", precision = 22, scale = 0)
	public Integer getFncrhrHorasMaximo() {
		return this.fncrhrHorasMaximo;
	}

	public void setFncrhrHorasMaximo(Integer fncrhrHorasMaximo) {
		this.fncrhrHorasMaximo = fncrhrHorasMaximo;
	}
	
	@Column(name = "FNCRHR_TIEMPO_DEDICACION", precision = 22, scale = 0)
	public Integer getFncrhrTiempoDedicacion() {
		return fncrhrTiempoDedicacion;
	}

	public void setFncrhrTiempoDedicacion(Integer fncrhrTiempoDedicacion) {
		this.fncrhrTiempoDedicacion = fncrhrTiempoDedicacion;
	}

	@OneToMany( mappedBy = "tifncrhrFuncionCargaHoraria")
	public List<TipoFuncionCargaHoraria> getFncrhrTipoFuncionCargaHorarias() {
		return this.fncrhrTipoFuncionCargaHorarias;
	}

	public void setFncrhrTipoFuncionCargaHorarias(List<TipoFuncionCargaHoraria> fncrhrTipoFuncionCargaHorarias) {
		this.fncrhrTipoFuncionCargaHorarias = fncrhrTipoFuncionCargaHorarias;
	}

}
