package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * FuncionPuesto generated by hbm2java
 */
@Entity
@Table(name = "FUNCION_PUESTO", schema = ConstantesJpa.SCHEMA)
public class FuncionPuesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2311970131751210666L;
	private int fnpsId;
	private Puesto fnpsPuesto;
	private Funcion fnpsFuncion;

	public FuncionPuesto() {
	}

	public FuncionPuesto(int fnpsId) {
		this.fnpsId = fnpsId;
	}

	public FuncionPuesto(int fnpsId, Puesto fnpsPuesto, Funcion fnpsFuncion) {
		this.fnpsId = fnpsId;
		this.fnpsPuesto = fnpsPuesto;
		this.fnpsFuncion = fnpsFuncion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "FNPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFnpsId() {
		return this.fnpsId;
	}

	public void setFnpsId(int fnpsId) {
		this.fnpsId = fnpsId;
	}

	@ManyToOne
	@JoinColumn(name = "PST_ID")
	public Puesto getFnpsPuesto() {
		return this.fnpsPuesto;
	}

	public void setFnpsPuesto(Puesto fnpsPuesto) {
		this.fnpsPuesto = fnpsPuesto;
	}

	@ManyToOne
	@JoinColumn(name = "FNC_ID")
	public Funcion getFnpsFuncion() {
		return this.fnpsFuncion;
	}

	public void setFnpsFuncion(Funcion fnpsFuncion) {
		this.fnpsFuncion = fnpsFuncion;
	}

}
