package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name = "FUNCION", schema = ConstantesJpa.SCHEMA)
public class Funcion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3418180963184172995L;
	private int fncId;
	private String fncDescripcion;
	private List<FuncionPuesto> fncFuncionPuestos = new ArrayList<FuncionPuesto>(0);

	public Funcion() {
	}

	public Funcion(int fncId) {
		this.fncId = fncId;
	}

	public Funcion(int fncId, String fncDescripcion, List<FuncionPuesto> fncFuncionPuestos) {
		this.fncId = fncId;
		this.fncDescripcion = fncDescripcion;
		this.fncFuncionPuestos = fncFuncionPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "FNC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFncId() {
		return this.fncId;
	}

	public void setFncId(int fncId) {
		this.fncId = fncId;
	}

	@Column(name = "FNC_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getFncDescripcion() {
		return this.fncDescripcion;
	}

	public void setFncDescripcion(String fncDescripcion) {
		this.fncDescripcion = fncDescripcion;
	}

	@OneToMany( mappedBy = "fnpsFuncion")
	public List<FuncionPuesto> getFncFuncionPuestos() {
		return this.fncFuncionPuestos;
	}

	public void setFncFuncionPuestos(List<FuncionPuesto> fncFuncionPuestos) {
		this.fncFuncionPuestos = fncFuncionPuestos;
	}

}
