package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Gratuidad generated by hbm2java
 */
@Entity
@Table(name = "GRATUIDAD", schema = ConstantesJpa.SCHEMA)
public class Gratuidad implements java.io.Serializable {

	private static final long serialVersionUID = -3029685445470401924L;
	
	private int grtId;
	private TipoGratuidad grtTipoGratuidad;
	private FichaMatricula grtFichaMatricula;
	private FichaEstudiante grtFichaEstudiante;
	private Integer grtEstado;

	public Gratuidad() {
	}

	public Gratuidad(int grtId) {
		this.grtId = grtId;
	}

	public Gratuidad(int grtId, TipoGratuidad grtTipoGratuidad, FichaMatricula grtFichaMatricula,
			FichaEstudiante grtFichaEstudiante, Integer grtEstado) {
		this.grtId = grtId;
		this.grtTipoGratuidad = grtTipoGratuidad;
		this.grtFichaMatricula = grtFichaMatricula;
		this.grtFichaEstudiante = grtFichaEstudiante;
		this.grtEstado = grtEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "GRT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getGrtId() {
		return this.grtId;
	}

	public void setGrtId(int grtId) {
		this.grtId = grtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIGR_ID")
	public TipoGratuidad getGrtTipoGratuidad() {
		return this.grtTipoGratuidad;
	}

	public void setGrtTipoGratuidad(TipoGratuidad grtTipoGratuidad) {
		this.grtTipoGratuidad = grtTipoGratuidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCMT_ID")
	public FichaMatricula getGrtFichaMatricula() {
		return this.grtFichaMatricula;
	}

	public void setGrtFichaMatricula(FichaMatricula grtFichaMatricula) {
		this.grtFichaMatricula = grtFichaMatricula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCES_ID")
	public FichaEstudiante getGrtFichaEstudiante() {
		return this.grtFichaEstudiante;
	}

	public void setGrtFichaEstudiante(FichaEstudiante grtFichaEstudiante) {
		this.grtFichaEstudiante = grtFichaEstudiante;
	}

	@Column(name = "GRT_ESTADO", precision = 22, scale = 0)
	public Integer getGrtEstado() {
		return this.grtEstado;
	}

	public void setGrtEstado(Integer grtEstado) {
		this.grtEstado = grtEstado;
	}

}
