package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * GrupoOcupacional generated by hbm2java
 */
@Entity
@Table(name = "GRUPO_OCUPACIONAL", schema = ConstantesJpa.SCHEMA)
public class GrupoOcupacional implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7540256586909757300L;
	private int grocId;
	private Regimen grocRegimen;
	private String grocDescripcion;
	private Integer grocGrado;
	private BigDecimal grocRmu;
	private BigDecimal grocRmuHora;
	private List<Puesto> grocPuestos = new ArrayList<Puesto>(0);

	public GrupoOcupacional() {
	}

	public GrupoOcupacional(int grocId) {
		this.grocId = grocId;
	}

	public GrupoOcupacional(int grocId, Regimen grocRegimen, String grocDescripcion, Integer grocGrado,
			BigDecimal grocRmu, BigDecimal grocRmuHora, List<Puesto> grocPuestos) {
		this.grocId = grocId;
		this.grocRegimen = grocRegimen;
		this.grocDescripcion = grocDescripcion;
		this.grocGrado = grocGrado;
		this.grocRmu = grocRmu;
		this.grocRmuHora = grocRmuHora;
		this.grocPuestos = grocPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "GROC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getGrocId() {
		return this.grocId;
	}

	public void setGrocId(int grocId) {
		this.grocId = grocId;
	}

	@ManyToOne
	@JoinColumn(name = "RGM_ID")
	public Regimen getGrocRegimen() {
		return this.grocRegimen;
	}

	public void setGrocRegimen(Regimen grocRegimen) {
		this.grocRegimen = grocRegimen;
	}

	@Column(name = "GROC_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getGrocDescripcion() {
		return this.grocDescripcion;
	}

	public void setGrocDescripcion(String grocDescripcion) {
		this.grocDescripcion = grocDescripcion;
	}

	@Column(name = "GROC_GRADO", precision = 22, scale = 0)
	public Integer getGrocGrado() {
		return this.grocGrado;
	}

	public void setGrocGrado(Integer grocGrado) {
		this.grocGrado = grocGrado;
	}

	@Column(name = "GROC_RMU", precision = 6)
	public BigDecimal getGrocRmu() {
		return this.grocRmu;
	}

	public void setGrocRmu(BigDecimal grocRmu) {
		this.grocRmu = grocRmu;
	}

	@Column(name = "GROC_RMU_HORA", precision = 6)
	public BigDecimal getGrocRmuHora() {
		return this.grocRmuHora;
	}

	public void setGrocRmuHora(BigDecimal grocRmuHora) {
		this.grocRmuHora = grocRmuHora;
	}

	@OneToMany( mappedBy = "pstGrupoOcupacional")
	public List<Puesto> getGrocPuestos() {
		return this.grocPuestos;
	}

	public void setGrocPuestos(List<Puesto> grocPuestos) {
		this.grocPuestos = grocPuestos;
	}

}
