package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 10/07/2019 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * HistorialNotaCorte generated by hbm2java
 */
@Entity
@Table(name = "HISTORIAL_NOTA_CORTE", schema = ConstantesJpa.SCHEMA)
public class HistorialNotaCorte implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4153222722798754233L;
	private int hsnocrId;
	private NotaCorte hsnocrNotaCorte;
	private Timestamp hsnocrFechaRegistro;
	private Integer hsnocrUsrId;
	private Integer hsnocrTipoProceso;
	private Float hsnocrNotaAnterior;
	private String hsnocrUsrNick;

	public HistorialNotaCorte() {
	}

	public HistorialNotaCorte(int hsnocrId) {
		this.hsnocrId = hsnocrId;
	}

	public HistorialNotaCorte(int hsnocrId, NotaCorte hsnocrNotaCorte, Timestamp hsnocrFechaRegistro,Integer hsnocrUsrId, Integer hsnocrTipoProceso, Float hsnocrNotaAnterior, String hsnocrUsrNick) {
		this.hsnocrId = hsnocrId;
		this.hsnocrNotaCorte = hsnocrNotaCorte;
		this.hsnocrFechaRegistro = hsnocrFechaRegistro;
		this.hsnocrUsrId = hsnocrUsrId;
		this.hsnocrTipoProceso = hsnocrTipoProceso;
		this.hsnocrNotaAnterior = hsnocrNotaAnterior;
		this.hsnocrUsrNick = hsnocrUsrNick;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "HSNOCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHsnocrId() {
		return this.hsnocrId;
	}

	public void setHsnocrId(int hsnocrId) {
		this.hsnocrId = hsnocrId;
	}

	
	@ManyToOne
	@JoinColumn(name = "NOCR_ID")
	public NotaCorte getHsnocrNotaCorte() {
		return this.hsnocrNotaCorte;
	}

	public void setHsnocrNotaCorte(NotaCorte hsnocrNotaCorte) {
		this.hsnocrNotaCorte = hsnocrNotaCorte;
	}

	
	
	@Column(name = "HSNOCR_FECHA_REGISTRO")
	public Timestamp getHsnocrFechaRegistro() {
		return this.hsnocrFechaRegistro;
	}

	public void setHsnocrFechaRegistro(Timestamp hsnocrFechaRegistro) {
		this.hsnocrFechaRegistro = hsnocrFechaRegistro;
	}

	
	@Column(name = "HSNOCR_USR_ID ", precision = 22, scale = 0)
	public Integer getHsnocrUsrId() {
		return this.hsnocrUsrId;
	}

	public void setHsnocrUsrId(Integer hsnocrUsrId) {
		this.hsnocrUsrId = hsnocrUsrId;
	}
	
	@Column(name = "HSNOCR_TIPO_PROCESO ", precision = 22, scale = 0)
	public Integer getHsnocrTipoProceso() {
		return this.hsnocrTipoProceso;
	}

	public void setHsnocrTipoProceso(Integer hsnocrTipoProceso) {
		this.hsnocrTipoProceso = hsnocrTipoProceso;
	}
	
	@Column(name="HSNOCR_NOTA_ANTERIOR", precision=126)
	public Float getHsnocrNotaAnterior() {
		return this.hsnocrNotaAnterior;
	}

	public void setHsnocrNotaAnterior(Float hsnocrNotaAnterior) {
		this.hsnocrNotaAnterior = hsnocrNotaAnterior;
	}
	
	@Column(name = "HSNOCR_USR_NICK", length = 128)
	@Length(max = 128)
	public String getHsnocrUsrNick() {
		return this.hsnocrUsrNick;
	}

	public void setHsnocrUsrNick(String hsnocrUsrNick) {
		this.hsnocrUsrNick = hsnocrUsrNick;
	}
}
