package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * HoraClaseAula generated by hbm2java
 */
@Entity
@Table(name = "HORA_CLASE_AULA", schema = ConstantesJpa.SCHEMA)
public class HoraClaseAula implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1068829370510120411L;
	private int hoclalId;
	private Aula hoclalAula;
	private HoraClase hoclalHoraClase;
	private Integer hoclalEstado;
	private List<HorarioAcademico> hoclalHorarioAcademicos = new ArrayList<HorarioAcademico>(0);

	public HoraClaseAula() {
	}

	public HoraClaseAula(int hoclalId) {
		this.hoclalId = hoclalId;
	}

	public HoraClaseAula(int hoclalId, Aula hoclalAula, HoraClase hoclalHoraClase, Integer hoclalEstado,
			List<HorarioAcademico> hoclalHorarioAcademicos) {
		this.hoclalId = hoclalId;
		this.hoclalAula = hoclalAula;
		this.hoclalHoraClase = hoclalHoraClase;
		this.hoclalEstado = hoclalEstado;
		this.hoclalHorarioAcademicos = hoclalHorarioAcademicos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "HOCLAL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHoclalId() {
		return this.hoclalId;
	}

	public void setHoclalId(int hoclalId) {
		this.hoclalId = hoclalId;
	}

	@ManyToOne
	@JoinColumn(name = "ALA_ID")
	public Aula getHoclalAula() {
		return this.hoclalAula;
	}

	public void setHoclalAula(Aula hoclalAula) {
		this.hoclalAula = hoclalAula;
	}

	@ManyToOne
	@JoinColumn(name = "HOCL_ID")
	public HoraClase getHoclalHoraClase() {
		return this.hoclalHoraClase;
	}

	public void setHoclalHoraClase(HoraClase hoclalHoraClase) {
		this.hoclalHoraClase = hoclalHoraClase;
	}

	@Column(name = "HOCLAL_ESTADO", precision = 22, scale = 0)
	public Integer getHoclalEstado() {
		return this.hoclalEstado;
	}

	public void setHoclalEstado(Integer hoclalEstado) {
		this.hoclalEstado = hoclalEstado;
	}

	@OneToMany( mappedBy = "hracHoraClaseAula")
	public List<HorarioAcademico> getHoclalHorarioAcademicos() {
		return this.hoclalHorarioAcademicos;
	}

	public void setHoclalHorarioAcademicos(List<HorarioAcademico> hoclalHorarioAcademicos) {
		this.hoclalHorarioAcademicos = hoclalHorarioAcademicos;
	}

}
