package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * HorarioAcademico generated by hbm2java
 */
@Entity
@Table(name = "HORARIO_ACADEMICO", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "HorarioAcademico.findAll", query="SELECT c FROM HorarioAcademico c"),
				@NamedQuery(name = "HorarioAcademico.findPorDiaHoInicioMlcrprId", query = "SELECT c FROM HorarioAcademico c WHERE c.hracDia = :dia AND c.hracHoraInicio = :horaInicio AND c.hracMallaCurricularParalelo.mlcrprId = :mlcrprId"),
				@NamedQuery(name = "HorarioAcademico.findPorMallaCurricularParaleloId", query = "SELECT c FROM HorarioAcademico c WHERE c.hracMallaCurricularParalelo.mlcrprId = :mlcrprId"),
				@NamedQuery(name = "HorarioAcademico.findHorariosPorMlcrprIdPrincipal", query = "SELECT c FROM HorarioAcademico c WHERE c.mlcrprIdComp = :mlcrprIdPrincipal")})
public class HorarioAcademico implements java.io.Serializable {

	private static final long serialVersionUID = 7079989142090133363L;
	
	private int hracId;
	private MallaCurricularParalelo hracMallaCurricularParalelo;
	private HoraClaseAula hracHoraClaseAula;
	private String hracDescripcion;
	private Integer hracDia;
	private Integer hracHoraInicio;
	private Integer hracHoraFin;
	private Integer hracHoraTipo;
	private Integer hracEstado;
	private Integer mlcrprIdComp;

	public HorarioAcademico() {
	}

	public HorarioAcademico(int hracId) {
		this.hracId = hracId;
	}

	public HorarioAcademico(int hracId, MallaCurricularParalelo hracMallaCurricularParalelo, HoraClaseAula hracHoraClaseAula,
			String hracDescripcion, Integer hracDia, Integer hracHoraInicio, Integer hracHoraFin,
			Integer hracEstado) {
		this.hracId = hracId;
		this.hracMallaCurricularParalelo = hracMallaCurricularParalelo;
		this.hracHoraClaseAula = hracHoraClaseAula;
		this.hracDescripcion = hracDescripcion;
		this.hracDia = hracDia;
		this.hracHoraInicio = hracHoraInicio;
		this.hracHoraFin = hracHoraFin;
		this.hracEstado = hracEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "HRAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHracId() {
		return this.hracId;
	}

	public void setHracId(int hracId) {
		this.hracId = hracId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MLCRPR_ID")
	public MallaCurricularParalelo getHracMallaCurricularParalelo() {
		return this.hracMallaCurricularParalelo;
	}

	public void setHracMallaCurricularParalelo(MallaCurricularParalelo hracMallaCurricularParalelo) {
		this.hracMallaCurricularParalelo = hracMallaCurricularParalelo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "HOCLAL_ID")
	public HoraClaseAula getHracHoraClaseAula() {
		return this.hracHoraClaseAula;
	}

	public void setHracHoraClaseAula(HoraClaseAula hracHoraClaseAula) {
		this.hracHoraClaseAula = hracHoraClaseAula;
	}

	@Column(name = "HRAC_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getHracDescripcion() {
		return this.hracDescripcion;
	}

	public void setHracDescripcion(String hracDescripcion) {
		this.hracDescripcion = hracDescripcion;
	}

	@Column(name = "HRAC_DIA", precision = 22, scale = 0)
	public Integer getHracDia() {
		return this.hracDia;
	}

	public void setHracDia(Integer hracDia) {
		this.hracDia = hracDia;
	}

	@Column(name = "HRAC_HORA_INICIO", precision = 22, scale = 0)
	public Integer getHracHoraInicio() {
		return this.hracHoraInicio;
	}

	public void setHracHoraInicio(Integer hracHoraInicio) {
		this.hracHoraInicio = hracHoraInicio;
	}

	@Column(name = "HRAC_HORA_FIN", precision = 22, scale = 0)
	public Integer getHracHoraFin() {
		return this.hracHoraFin;
	}

	public void setHracHoraFin(Integer hracHoraFin) {
		this.hracHoraFin = hracHoraFin;
	}

	@Column(name = "HRAC_ESTADO", precision = 22, scale = 0)
	public Integer getHracEstado() {
		return this.hracEstado;
	}

	public void setHracEstado(Integer hracEstado) {
		this.hracEstado = hracEstado;
	}

	@Column(name = "MLCRPR_ID_COMP", precision = 22, scale = 0)
	public Integer getMlcrprIdComp() {
		return mlcrprIdComp;
	}

	public void setMlcrprIdComp(Integer mlcrprIdComp) {
		this.mlcrprIdComp = mlcrprIdComp;
	}
	
	@Column(name = "HRAC_HORA_TIPO", precision = 22, scale = 0)
	public Integer getHracHoraTipo() {
		return hracHoraTipo;
	}

	public void setHracHoraTipo(Integer hracHoraTipo) {
		this.hracHoraTipo = hracHoraTipo;
	}
	
	
	

}
