package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * HorarioAcademico generated by hbm2java
 */
@Entity
@Table(name = "HORARIO_FUNCION", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "HorarioFuncion.findAll", query = "SELECT c FROM HorarioFuncion c"),
		@NamedQuery(name = "HorarioFuncion.findPorDiaHoraInicioDtpsId", query = "SELECT c FROM HorarioFuncion c WHERE c.hrfnDia = :dia AND c.hrfnHoraInicio = :horaInicio AND c.hrfnDetallePuesto = :dtpsId") })
public class HorarioFuncion implements java.io.Serializable {

	private static final long serialVersionUID = 7079989142090133363L;
	private int hrfnId;
	private String hrfnDescripcion;
	private Integer hrfnDia;
	private Integer hrfnHoraInicio;
	private Integer hrfnHoraFin;
	private Integer hrfnFuncion;
	private Integer hrfnActividad;
	private Integer hrfnPeriodoAcademico;
	private Integer hrfnDetallePuesto;
	private HoraClase hrfnHoraClase;
	private Integer hrfnEstado;

	public HorarioFuncion() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "HRFN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHrfnId() {
		return hrfnId;
	}

	public void setHrfnId(int hrfnId) {
		this.hrfnId = hrfnId;
	}

	@Column(name = "HRFN_DESCRIPCION", length = 256)
	public String getHrfnDescripcion() {
		return hrfnDescripcion;
	}

	public void setHrfnDescripcion(String hrfnDescripcion) {
		this.hrfnDescripcion = hrfnDescripcion;
	}

	@Column(name = "HRFN_DIA", precision = 22, scale = 0)
	public Integer getHrfnDia() {
		return hrfnDia;
	}

	public void setHrfnDia(Integer hrfnDia) {
		this.hrfnDia = hrfnDia;
	}

	@Column(name = "HRFN_HORA_INICIO", precision = 22, scale = 0)
	public Integer getHrfnHoraInicio() {
		return hrfnHoraInicio;
	}

	public void setHrfnHoraInicio(Integer hrfnHoraInicio) {
		this.hrfnHoraInicio = hrfnHoraInicio;
	}

	@Column(name = "HRFN_HORA_FIN", precision = 22, scale = 0)
	public Integer getHrfnHoraFin() {
		return hrfnHoraFin;
	}

	public void setHrfnHoraFin(Integer hrfnHoraFin) {
		this.hrfnHoraFin = hrfnHoraFin;
	}

	@Column(name = "HRFN_ESTADO", precision = 22, scale = 0)
	public Integer getHrfnEstado() {
		return hrfnEstado;
	}

	public void setHrfnEstado(Integer hrfnEstado) {
		this.hrfnEstado = hrfnEstado;
	}

	@ManyToOne
	@JoinColumn(name = "HOCL_ID")
	public HoraClase getHrfnHoraClase() {
		return hrfnHoraClase;
	}

	public void setHrfnHoraClase(HoraClase hrfnHoraClase) {
		this.hrfnHoraClase = hrfnHoraClase;
	}

	@Column(name = "HRFN_DTPS_ID", precision = 22, scale = 0)
	public Integer getHrfnDetallePuesto() {
		return hrfnDetallePuesto;
	}

	public void setHrfnDetallePuesto(Integer hrfnDetallePuesto) {
		this.hrfnDetallePuesto = hrfnDetallePuesto;
	}

	@Column(name = "HRFN_FUNCION", precision = 22, scale = 0)
	public Integer getHrfnFuncion() {
		return hrfnFuncion;
	}

	public void setHrfnFuncion(Integer hrfnFuncion) {
		this.hrfnFuncion = hrfnFuncion;
	}

	@Column(name = "HRFN_ACTIVIDAD", precision = 22, scale = 0)
	public Integer getHrfnActividad() {
		return hrfnActividad;
	}

	public void setHrfnActividad(Integer hrfnActividad) {
		this.hrfnActividad = hrfnActividad;
	}

	@Column(name = "HRFN_PRAC_ID", precision = 22, scale = 0)
	public Integer getHrfnPeriodoAcademico() {
		return hrfnPeriodoAcademico;
	}

	public void setHrfnPeriodoAcademico(Integer hrfnPeriodoAcademico) {
		this.hrfnPeriodoAcademico = hrfnPeriodoAcademico;
	}

}