package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * HoraClase generated by hbm2java
 */
@Entity
@Table(name = "HORA_CLASE", schema = ConstantesJpa.SCHEMA)
public class HoraClase implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2394577010374161339L;
	private int hoclId;
	private String hoclDescripcion;
	private Integer hoclEstado;
	private Integer hoclHoraInicio;
	private Integer hoclHoraFin;
	private List<HoraClaseAula> hoclHoraClaseAulas = new ArrayList<HoraClaseAula>(0);
	private List<HorarioFuncion> hoclListHorarioFuncion;

	public HoraClase() {
	}

	public HoraClase(int hoclId) {
		this.hoclId = hoclId;
	}

	public HoraClase(int hoclId, String hoclDescripcion, Integer hoclEstado, Integer hoclHoraInicio,
			Integer hoclHoraFin, List<HoraClaseAula> hoclHoraClaseAulas) {
		this.hoclId = hoclId;
		this.hoclDescripcion = hoclDescripcion;
		this.hoclEstado = hoclEstado;
		this.hoclHoraInicio = hoclHoraInicio;
		this.hoclHoraFin = hoclHoraFin;
		this.hoclHoraClaseAulas = hoclHoraClaseAulas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "HOCL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHoclId() {
		return this.hoclId;
	}

	public void setHoclId(int hoclId) {
		this.hoclId = hoclId;
	}

	@Column(name = "HOCL_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getHoclDescripcion() {
		return this.hoclDescripcion;
	}

	public void setHoclDescripcion(String hoclDescripcion) {
		this.hoclDescripcion = hoclDescripcion;
	}

	@Column(name = "HOCL_ESTADO", precision = 22, scale = 0)
	public Integer getHoclEstado() {
		return this.hoclEstado;
	}

	public void setHoclEstado(Integer hoclEstado) {
		this.hoclEstado = hoclEstado;
	}

	@Column(name = "HOCL_HORA_INICIO", precision = 22, scale = 0)
	public Integer getHoclHoraInicio() {
		return this.hoclHoraInicio;
	}

	public void setHoclHoraInicio(Integer hoclHoraInicio) {
		this.hoclHoraInicio = hoclHoraInicio;
	}

	@Column(name = "HOCL_HORA_FIN", precision = 22, scale = 0)
	public Integer getHoclHoraFin() {
		return this.hoclHoraFin;
	}

	public void setHoclHoraFin(Integer hoclHoraFin) {
		this.hoclHoraFin = hoclHoraFin;
	}

	@OneToMany( mappedBy = "hoclalHoraClase")
	public List<HoraClaseAula> getHoclHoraClaseAulas() {
		return this.hoclHoraClaseAulas;
	}

	public void setHoclHoraClaseAulas(List<HoraClaseAula> hoclHoraClaseAulas) {
		this.hoclHoraClaseAulas = hoclHoraClaseAulas;
	}

	@OneToMany( mappedBy = "hrfnHoraClase")
	public List<HorarioFuncion> getHoclListHorarioFuncion() {
		return hoclListHorarioFuncion;
	}

	public void setHoclListHorarioFuncion(List<HorarioFuncion> hoclListHorarioFuncion) {
		this.hoclListHorarioFuncion = hoclListHorarioFuncion;
	}

	
}
