package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * InformeTecnico generated by hbm2java
 */
@Entity
@Table(name = "INFORME_TECNICO", schema = ConstantesJpa.SCHEMA)
public class InformeTecnico implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7116571668379795210L;
	private int intcId;
	private ProcesoTramiteContrato intcProcesoTramiteContrato;
	private String intcObservacion;
	private Integer intcEstado;

	public InformeTecnico() {
	}

	public InformeTecnico(int intcId) {
		this.intcId = intcId;
	}

	public InformeTecnico(int intcId, ProcesoTramiteContrato intcProcesoTramiteContrato, String intcObservacion,
			Integer intcEstado) {
		this.intcId = intcId;
		this.intcProcesoTramiteContrato = intcProcesoTramiteContrato;
		this.intcObservacion = intcObservacion;
		this.intcEstado = intcEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "INTC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getIntcId() {
		return this.intcId;
	}

	public void setIntcId(int intcId) {
		this.intcId = intcId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getIntcProcesoTramiteContrato() {
		return this.intcProcesoTramiteContrato;
	}

	public void setIntcProcesoTramiteContrato(ProcesoTramiteContrato intcProcesoTramiteContrato) {
		this.intcProcesoTramiteContrato = intcProcesoTramiteContrato;
	}

	@Column(name = "INTC_OBSERVACION", length = 512)
	@Length(max = 512)
	public String getIntcObservacion() {
		return this.intcObservacion;
	}

	public void setIntcObservacion(String intcObservacion) {
		this.intcObservacion = intcObservacion;
	}

	@Column(name = "INTC_ESTADO", precision = 22, scale = 0)
	public Integer getIntcEstado() {
		return this.intcEstado;
	}

	public void setIntcEstado(Integer intcEstado) {
		this.intcEstado = intcEstado;
	}

}
