package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * InstitucionAcademica generated by hbm2java
 */
@Entity
@Table(name = "INSTITUCION_ACADEMICA", schema = ConstantesJpa.SCHEMA)
public class InstitucionAcademica implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 9117924823292632939L;
	private int inacId;
	private Ubicacion inacUbicacion;
	private String inacCodigoSniese;
	private String inacDescripcion;
	private Integer inacNivel;
	private Integer inacTipo;
	private String inacTipoSniese;
	private List<FichaEstudiante> inacFichaEstudiantes = new ArrayList<FichaEstudiante>(0);

	public InstitucionAcademica() {
	}

	public InstitucionAcademica(int inacId) {
		this.inacId = inacId;
	}

	public InstitucionAcademica(int inacId, Ubicacion inacUbicacion, String inacCodigoSniese, String inacDescripcion,
			Integer inacNivel, Integer inacTipo, String inacTipoSniese, List<FichaEstudiante> inacFichaEstudiantes) {
		this.inacId = inacId;
		this.inacUbicacion = inacUbicacion;
		this.inacCodigoSniese = inacCodigoSniese;
		this.inacDescripcion = inacDescripcion;
		this.inacNivel = inacNivel;
		this.inacTipo = inacTipo;
		this.inacTipoSniese = inacTipoSniese;
		this.inacFichaEstudiantes = inacFichaEstudiantes;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "INAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getInacId() {
		return this.inacId;
	}

	public void setInacId(int inacId) {
		this.inacId = inacId;
	}

	@ManyToOne
	@JoinColumn(name = "UBC_ID")
	public Ubicacion getInacUbicacion() {
		return this.inacUbicacion;
	}

	public void setInacUbicacion(Ubicacion inacUbicacion) {
		this.inacUbicacion = inacUbicacion;
	}

	@Column(name = "INAC_CODIGO_SNIESE", length = 6)
	@Length(max = 6)
	public String getInacCodigoSniese() {
		return this.inacCodigoSniese;
	}

	public void setInacCodigoSniese(String inacCodigoSniese) {
		this.inacCodigoSniese = inacCodigoSniese;
	}

	@Column(name = "INAC_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getInacDescripcion() {
		return this.inacDescripcion;
	}

	public void setInacDescripcion(String inacDescripcion) {
		this.inacDescripcion = inacDescripcion;
	}

	@Column(name = "INAC_NIVEL", precision = 22, scale = 0)
	public Integer getInacNivel() {
		return this.inacNivel;
	}

	public void setInacNivel(Integer inacNivel) {
		this.inacNivel = inacNivel;
	}

	@Column(name = "INAC_TIPO", precision = 22, scale = 0)
	public Integer getInacTipo() {
		return this.inacTipo;
	}

	public void setInacTipo(Integer inacTipo) {
		this.inacTipo = inacTipo;
	}

	@Column(name = "INAC_TIPO_SNIESE", length = 4)
	@Length(max = 4)
	public String getInacTipoSniese() {
		return this.inacTipoSniese;
	}

	public void setInacTipoSniese(String inacTipoSniese) {
		this.inacTipoSniese = inacTipoSniese;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcesInstitucionAcademica")
	public List<FichaEstudiante> getInacFichaEstudiantes() {
		return inacFichaEstudiantes;
	}

	public void setInacFichaEstudiantes(List<FichaEstudiante> inacFichaEstudiantes) {
		this.inacFichaEstudiantes = inacFichaEstudiantes;
	}
	
}
