package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ItinerarioMallaMateria generated by hbm2java
 */
@Entity
@Table(name = "ITINERARIO_MALLA_MATERIA", schema = ConstantesJpa.SCHEMA)
public class ItinerarioMallaMateria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1409056350642353958L;
	private int itmlmtId;
	private Itinerario itmlmtItinerario;
	private MallaCurricularMateria itmlmtMallaCurricularMateria;
	private Integer itmlmtEstado;

	public ItinerarioMallaMateria() {
	}

	public ItinerarioMallaMateria(int itmlmtId) {
		this.itmlmtId = itmlmtId;
	}

	public ItinerarioMallaMateria(int itmlmtId, Itinerario itmlmtItinerario, MallaCurricularMateria itmlmtMallaCurricularMateria,
			Integer itmlmtEstado) {
		this.itmlmtId = itmlmtId;
		this.itmlmtItinerario = itmlmtItinerario;
		this.itmlmtMallaCurricularMateria = itmlmtMallaCurricularMateria;
		this.itmlmtEstado = itmlmtEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ITMLMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getItmlmtId() {
		return this.itmlmtId;
	}

	public void setItmlmtId(int itmlmtId) {
		this.itmlmtId = itmlmtId;
	}

	@ManyToOne
	@JoinColumn(name = "ITN_ID")
	public Itinerario getItmlmtItinerario() {
		return this.itmlmtItinerario;
	}

	public void setItmlmtItinerario(Itinerario itmlmtItinerario) {
		this.itmlmtItinerario = itmlmtItinerario;
	}

	@ManyToOne
	@JoinColumn(name = "MLCRMT_ID")
	public MallaCurricularMateria getItmlmtMallaCurricularMateria() {
		return this.itmlmtMallaCurricularMateria;
	}

	public void setItmlmtMallaCurricularMateria(MallaCurricularMateria itmlmtMallaCurricularMateria) {
		this.itmlmtMallaCurricularMateria = itmlmtMallaCurricularMateria;
	}

	@Column(name = "ITMLMT_ESTADO", precision = 22, scale = 0)
	public Integer getItmlmtEstado() {
		return this.itmlmtEstado;
	}

	public void setItmlmtEstado(Integer itmlmtEstado) {
		this.itmlmtEstado = itmlmtEstado;
	}

}
