package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Itinerario generated by hbm2java
 */
@Entity
@Table(name = "ITINERARIO", schema = ConstantesJpa.SCHEMA)
public class Itinerario implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5215961430697733592L;
	private int itnId;
	private Carrera itnCarrera;
	private String itnDescripcion;
	private Integer itnEstado;
	private String itnObservacion;
	private List<ItinerarioMallaMateria> itnItinerarioMallaMaterias = new ArrayList<ItinerarioMallaMateria>(0);

	public Itinerario() {
	}

	public Itinerario(int itnId) {
		this.itnId = itnId;
	}

	public Itinerario(int itnId, Carrera itnCarrera, String itnDescripcion, Integer itnEstado, String itnObservacion,
			List<ItinerarioMallaMateria> itnItinerarioMallaMaterias) {
		this.itnId = itnId;
		this.itnCarrera = itnCarrera;
		this.itnDescripcion = itnDescripcion;
		this.itnEstado = itnEstado;
		this.itnObservacion = itnObservacion;
		this.itnItinerarioMallaMaterias = itnItinerarioMallaMaterias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "ITN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getItnId() {
		return this.itnId;
	}

	public void setItnId(int itnId) {
		this.itnId = itnId;
	}

	@ManyToOne
	@JoinColumn(name = "CRR_ID")
	public Carrera getItnCarrera() {
		return this.itnCarrera;
	}

	public void setItnCarrera(Carrera itnCarrera) {
		this.itnCarrera = itnCarrera;
	}

	@Column(name = "ITN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getItnDescripcion() {
		return this.itnDescripcion;
	}

	public void setItnDescripcion(String itnDescripcion) {
		this.itnDescripcion = itnDescripcion;
	}

	@Column(name = "ITN_ESTADO", precision = 22, scale = 0)
	public Integer getItnEstado() {
		return this.itnEstado;
	}

	public void setItnEstado(Integer itnEstado) {
		this.itnEstado = itnEstado;
	}

	@Column(name = "ITN_OBSERVACION", length = 256)
	@Length(max = 256)
	public String getItnObservacion() {
		return this.itnObservacion;
	}

	public void setItnObservacion(String itnObservacion) {
		this.itnObservacion = itnObservacion;
	}

	@OneToMany( mappedBy = "itmlmtItinerario")
	public List<ItinerarioMallaMateria> getItnItinerarioMallaMaterias() {
		return this.itnItinerarioMallaMaterias;
	}

	public void setItnItinerarioMallaMaterias(List<ItinerarioMallaMateria> itnItinerarioMallaMaterias) {
		this.itnItinerarioMallaMaterias = itnItinerarioMallaMaterias;
	}

}
