package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * MallaCurricularMateria generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR_MATERIA", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "MallaCurricularMateria.findAll", query="SELECT c FROM MallaCurricularMateria c"),
				@NamedQuery(name = "MallaCurricularMateria.findPorMateriaId", query = "SELECT c FROM MallaCurricularMateria c WHERE c.mlcrmtMateria.mtrId = :materiaId") })
public class MallaCurricularMateria implements java.io.Serializable {

	private static final long serialVersionUID = -6269604753546906848L;
	
	private int mlcrmtId;
	private Nivel mlcrmtNivelPreRequisito;
	private MallaCurricular mlcrmtMallaCurricular;
	private Nivel mlcrmtNivel;
	private UnidadFormacion mlcrmtUnidadFormacion;
	private Materia mlcrmtMateria;
	private Integer mlcrmtEstado;
	private List<Convalidacion> mlcrmtConvalidacions = new ArrayList<Convalidacion>(0);
	private List<MallaCurricularParalelo> mlcrmtMallaCurricularParalelos = new ArrayList<MallaCurricularParalelo>(0);
	private List<ItinerarioMallaMateria> mlcrmtItinerarioMallaMaterias = new ArrayList<ItinerarioMallaMateria>(0);
	private List<Proyeccion> mlcrmtProyeccions = new ArrayList<Proyeccion>(0);

	public MallaCurricularMateria() {
	}

	public MallaCurricularMateria(int mlcrmtId) {
		this.mlcrmtId = mlcrmtId;
	}

	public MallaCurricularMateria(int mlcrmtId, Nivel mlcrmtNivelPreRequisito, MallaCurricular mlcrmtMallaCurricular,
			Nivel mlcrmtNivel, UnidadFormacion mlcrmtUnidadFormacion, Materia mlcrmtMateria, Integer mlcrmtEstado,
			List<Convalidacion> mlcrmtConvalidacions, List<MallaCurricularParalelo> mlcrmtMallaCurricularParalelos,
			List<ItinerarioMallaMateria> mlcrmtItinerarioMallaMaterias, List<Proyeccion> mlcrmtProyeccions) {
		this.mlcrmtId = mlcrmtId;
		this.mlcrmtNivelPreRequisito = mlcrmtNivelPreRequisito;
		this.mlcrmtMallaCurricular = mlcrmtMallaCurricular;
		this.mlcrmtNivel = mlcrmtNivel;
		this.mlcrmtUnidadFormacion = mlcrmtUnidadFormacion;
		this.mlcrmtMateria = mlcrmtMateria;
		this.mlcrmtEstado = mlcrmtEstado;
		this.mlcrmtConvalidacions = mlcrmtConvalidacions;
		this.mlcrmtMallaCurricularParalelos = mlcrmtMallaCurricularParalelos;
		this.mlcrmtItinerarioMallaMaterias = mlcrmtItinerarioMallaMaterias;
		this.mlcrmtProyeccions = mlcrmtProyeccions;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "MLCRMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMlcrmtId() {
		return this.mlcrmtId;
	}

	public void setMlcrmtId(int mlcrmtId) {
		this.mlcrmtId = mlcrmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVL_SUB_ID")
	public Nivel getMlcrmtNivelPreRequisito() {
		return this.mlcrmtNivelPreRequisito;
	}

	public void setMlcrmtNivelPreRequisito(Nivel mlcrmtNivelPreRequisito) {
		this.mlcrmtNivelPreRequisito = mlcrmtNivelPreRequisito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCR_ID")
	public MallaCurricular getMlcrmtMallaCurricular() {
		return this.mlcrmtMallaCurricular;
	}

	public void setMlcrmtMallaCurricular(MallaCurricular mlcrmtMallaCurricular) {
		this.mlcrmtMallaCurricular = mlcrmtMallaCurricular;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVL_ID")
	public Nivel getMlcrmtNivel() {
		return this.mlcrmtNivel;
	}

	public void setMlcrmtNivel(Nivel mlcrmtNivel) {
		this.mlcrmtNivel = mlcrmtNivel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNFR_ID")
	public UnidadFormacion getMlcrmtUnidadFormacion() {
		return this.mlcrmtUnidadFormacion;
	}

	public void setMlcrmtUnidadFormacion(UnidadFormacion mlcrmtUnidadFormacion) {
		this.mlcrmtUnidadFormacion = mlcrmtUnidadFormacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTR_ID")
	public Materia getMlcrmtMateria() {
		return this.mlcrmtMateria;
	}

	public void setMlcrmtMateria(Materia mlcrmtMateria) {
		this.mlcrmtMateria = mlcrmtMateria;
	}

	@Column(name = "MLCRMT_ESTADO", precision = 22, scale = 0)
	public Integer getMlcrmtEstado() {
		return this.mlcrmtEstado;
	}

	public void setMlcrmtEstado(Integer mlcrmtEstado) {
		this.mlcrmtEstado = mlcrmtEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cnvMallaCurricularMateria")
	public List<Convalidacion> getMlcrmtConvalidacions() {
		return this.mlcrmtConvalidacions;
	}

	public void setMlcrmtConvalidacions(List<Convalidacion> mlcrmtConvalidacions) {
		this.mlcrmtConvalidacions = mlcrmtConvalidacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mlcrprMallaCurricularMateria")
	public List<MallaCurricularParalelo> getMlcrmtMallaCurricularParalelos() {
		return this.mlcrmtMallaCurricularParalelos;
	}

	public void setMlcrmtMallaCurricularParalelos(List<MallaCurricularParalelo> mlcrmtMallaCurricularParalelos) {
		this.mlcrmtMallaCurricularParalelos = mlcrmtMallaCurricularParalelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itmlmtMallaCurricularMateria")
	public List<ItinerarioMallaMateria> getMlcrmtItinerarioMallaMaterias() {
		return this.mlcrmtItinerarioMallaMaterias;
	}

	public void setMlcrmtItinerarioMallaMaterias(List<ItinerarioMallaMateria> mlcrmtItinerarioMallaMaterias) {
		this.mlcrmtItinerarioMallaMaterias = mlcrmtItinerarioMallaMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pryMallaCurricularMateria")
	public List<Proyeccion> getMlcrmtProyeccions() {
		return this.mlcrmtProyeccions;
	}

	public void setMlcrmtProyeccions(List<Proyeccion> mlcrmtProyeccions) {
		this.mlcrmtProyeccions = mlcrmtProyeccions;
	}

}
