package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * MallaPeriodo generated by hbm2java
 */
@Entity
@Table(name = "MALLA_PERIODO", schema = ConstantesJpa.SCHEMA)
public class MallaPeriodo implements java.io.Serializable {

	private static final long serialVersionUID = -5616745470174334438L;
	private int mlprId;
	private MallaCurricular mlprMallaCurricular;
	private PeriodoAcademico mlprPeriodoAcademico;
	private Integer mlprEstado;

	public MallaPeriodo() {
	}

	public MallaPeriodo(int mlprId) {
		this.mlprId = mlprId;
	}

	public MallaPeriodo(int mlprId, MallaCurricular mlprMallaCurricular, PeriodoAcademico mlprPeriodoAcademico,
			Integer mlprEstado) {
		this.mlprId = mlprId;
		this.mlprMallaCurricular = mlprMallaCurricular;
		this.mlprPeriodoAcademico = mlprPeriodoAcademico;
		this.mlprEstado = mlprEstado;
	}

	public MallaPeriodo(MallaCurricular mlprMallaCurricular, PeriodoAcademico mlprPeriodoAcademico,
			Integer mlprEstado) {
		this.mlprMallaCurricular = mlprMallaCurricular;
		this.mlprPeriodoAcademico = mlprPeriodoAcademico;
		this.mlprEstado = mlprEstado;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "MLPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMlprId() {
		return this.mlprId;
	}

	public void setMlprId(int mlprId) {
		this.mlprId = mlprId;
	}

	@ManyToOne
	@JoinColumn(name = "MLCR_ID")
	public MallaCurricular getMlprMallaCurricular() {
		return this.mlprMallaCurricular;
	}

	public void setMlprMallaCurricular(MallaCurricular mlprMallaCurricular) {
		this.mlprMallaCurricular = mlprMallaCurricular;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getMlprPeriodoAcademico() {
		return this.mlprPeriodoAcademico;
	}

	public void setMlprPeriodoAcademico(PeriodoAcademico mlprPeriodoAcademico) {
		this.mlprPeriodoAcademico = mlprPeriodoAcademico;
	}

	@Column(name = "MLPR_ESTADO", precision = 22, scale = 0)
	public Integer getMlprEstado() {
		return this.mlprEstado;
	}

	public void setMlprEstado(Integer mlprEstado) {
		this.mlprEstado = mlprEstado;
	}

}
