package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * MallaCurricularParalelo generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR_PARALELO", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "MallaCurricularParalelo.findAll", query="SELECT m FROM MallaCurricularParalelo m"),
				@NamedQuery(name = "MallaCurricularParalelo.findPorParalelo", query = "SELECT m FROM MallaCurricularParalelo m WHERE m.mlcrprParalelo.prlId = :prlId"),
				@NamedQuery(name = "MallaCurricularParalelo.findPorMlcrmtIdParaleloId", query = "SELECT m FROM MallaCurricularParalelo m WHERE m.mlcrprMallaCurricularMateria.mlcrmtId = :mlcrmtId  AND m.mlcrprParalelo.prlId = :paraleloId")})
public class MallaCurricularParalelo implements java.io.Serializable {

	private static final long serialVersionUID = -3720870946601118825L;

	private int mlcrprId;
	private Integer mlcrprCupo;
	private Integer mlcrprInscritos;
	private Integer mlcrprReservaRepetidos;
	private Integer mlcrprNivelacionCrrId;
	private Integer mlcrprModalidad;
	private Paralelo mlcrprParalelo;
	private MallaCurricularMateria mlcrprMallaCurricularMateria;
	private List<RecordEstudiante> mlcrprRecordEstudiantes = new ArrayList<RecordEstudiante>(0);
	private List<CargaHoraria> mlcrprCargaHorarias = new ArrayList<CargaHoraria>(0);
	private List<DetalleMatricula> mlcrprDetalleMatriculas = new ArrayList<DetalleMatricula>(0);
	private List<HorarioAcademico> mlcrprHorarioAcademicos = new ArrayList<HorarioAcademico>(0);

	public MallaCurricularParalelo() {
	}

	public MallaCurricularParalelo(int mlcrprId) {
		this.mlcrprId = mlcrprId;
	}

	public MallaCurricularParalelo(int mlcrprId, Paralelo mlcrprParalelo, PeriodoAcademico mlcrprPeriodoAcademico,
			MallaCurricularMateria mlcrprMallaCurricularMateria, List<RecordEstudiante> mlcrprRecordEstudiantes,
			List<CargaHoraria> mlcrprCargaHorarias, List<DetalleMatricula> mlcrprDetalleMatriculas,
			List<HorarioAcademico> mlcrprHorarioAcademicos, Integer mlcrprInscritos) {
		this.mlcrprId = mlcrprId;
		this.mlcrprParalelo = mlcrprParalelo;
		this.mlcrprMallaCurricularMateria = mlcrprMallaCurricularMateria;
		this.mlcrprRecordEstudiantes = mlcrprRecordEstudiantes;
		this.mlcrprCargaHorarias = mlcrprCargaHorarias;
		this.mlcrprDetalleMatriculas = mlcrprDetalleMatriculas;
		this.mlcrprHorarioAcademicos = mlcrprHorarioAcademicos;
		this.mlcrprInscritos = mlcrprInscritos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "MLCRPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMlcrprId() {
		return this.mlcrprId;
	}

	public void setMlcrprId(int mlcrprId) {
		this.mlcrprId = mlcrprId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRL_ID")
	public Paralelo getMlcrprParalelo() {
		return this.mlcrprParalelo;
	}

	public void setMlcrprParalelo(Paralelo mlcrprParalelo) {
		this.mlcrprParalelo = mlcrprParalelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRMT_ID")
	public MallaCurricularMateria getMlcrprMallaCurricularMateria() {
		return this.mlcrprMallaCurricularMateria;
	}

	public void setMlcrprMallaCurricularMateria(MallaCurricularMateria mlcrprMallaCurricularMateria) {
		this.mlcrprMallaCurricularMateria = mlcrprMallaCurricularMateria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rcesMallaCurricularParalelo")
	public List<RecordEstudiante> getMlcrprRecordEstudiantes() {
		return this.mlcrprRecordEstudiantes;
	}

	public void setMlcrprRecordEstudiantes(List<RecordEstudiante> mlcrprRecordEstudiantes) {
		this.mlcrprRecordEstudiantes = mlcrprRecordEstudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crhrMallaCurricularParalelo")
	public List<CargaHoraria> getMlcrprCargaHorarias() {
		return this.mlcrprCargaHorarias;
	}

	public void setMlcrprCargaHorarias(List<CargaHoraria> mlcrprCargaHorarias) {
		this.mlcrprCargaHorarias = mlcrprCargaHorarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtmtMallaCurricularParalelo")
	public List<DetalleMatricula> getMlcrprDetalleMatriculas() {
		return this.mlcrprDetalleMatriculas;
	}

	public void setMlcrprDetalleMatriculas(List<DetalleMatricula> mlcrprDetalleMatriculas) {
		this.mlcrprDetalleMatriculas = mlcrprDetalleMatriculas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hracMallaCurricularParalelo")
	public List<HorarioAcademico> getMlcrprHorarioAcademicos() {
		return this.mlcrprHorarioAcademicos;
	}

	public void setMlcrprHorarioAcademicos(List<HorarioAcademico> mlcrprHorarioAcademicos) {
		this.mlcrprHorarioAcademicos = mlcrprHorarioAcademicos;
	}

	@Column(name = "MLCRPR_INSCRITOS", precision = 22, scale = 0)
	public Integer getMlcrprInscritos() {
		return mlcrprInscritos;
	}

	public void setMlcrprInscritos(Integer mlcrprInscritos) {
		this.mlcrprInscritos = mlcrprInscritos;
	}

	@Column(name = "MLCRPR_CUPO")
	public Integer getMlcrprCupo() {
		return mlcrprCupo;
	}

	public void setMlcrprCupo(Integer mlcrprCupo) {
		this.mlcrprCupo = mlcrprCupo;
	}

	@Column(name = "MLCRPR_RESERVA_REPETIDOS")
	public Integer getMlcrprReservaRepetidos() {
		return mlcrprReservaRepetidos;
	}

	public void setMlcrprReservaRepetidos(Integer mlcrprReservaRepetidos) {
		this.mlcrprReservaRepetidos = mlcrprReservaRepetidos;
	}

	@Column(name = "MLCRPR_NIVELACION_CRR_ID")
	public Integer getMlcrprNivelacionCrrId() {
		return mlcrprNivelacionCrrId;
	}

	public void setMlcrprNivelacionCrrId(Integer mlcrprNivelacionCrrId) {
		this.mlcrprNivelacionCrrId = mlcrprNivelacionCrrId;
	}

	@Column(name = "MLCRPR_MODALIDAD")
	public Integer getMlcrprModalidad() {
		return mlcrprModalidad;
	}

	public void setMlcrprModalidad(Integer mlcrprModalidad) {
		this.mlcrprModalidad = mlcrprModalidad;
	}

}
