package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * MallaCurricular generated by hbm2java
 */
@Entity
@Table(name = "MALLA_CURRICULAR", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "MallaCurricular.findAll", query="SELECT c FROM MallaCurricular c"),
					@NamedQuery(name = "MallaCurricular.findPorCarreraEstado", query = "SELECT c FROM MallaCurricular c WHERE c.mlcrCarrera.crrId = :crrId AND c.mlcrEstado = :mlcrEstado") })
public class MallaCurricular implements java.io.Serializable {

	private static final long serialVersionUID = 6462650298357102325L;
	private int mlcrId;
	private Carrera mlcrCarrera;
	private TipoFormacionMalla mlcrTipoFormacionMalla;
	private String mlcrCodigo;
	private String mlcrDescripcion;
	private Integer mlcrEstado;
	private Date mlcrFechaInicio;
	private Date mlcrFechaFin;
	private Integer mlcrTotalHoras;
	private Integer mlcrTotalMaterias;
	private Integer mlcrTipoOrgAprendizaje;
	private Integer mlcrVigente;
	private Integer mlcrTipoAprobacion;
	private List<MallaCurricularMateria> mlcrMallaCurricularMaterias = new ArrayList<MallaCurricularMateria>(0);
	private List<MallaPeriodo> mlcrMallaPeriodos = new ArrayList<MallaPeriodo>(0);
	private List<MallaCurricularNivel> mlcrListMallaCurricularNivel;


	public MallaCurricular() {
	}

	public MallaCurricular(int mlcrId) {
		this.mlcrId = mlcrId;
	}

	public MallaCurricular(int mlcrId, Carrera mlcrCarrera, TipoFormacionMalla mlcrTipoFormacionMalla, String mlcrCodigo,
			String mlcrDescripcion, Integer mlcrEstado, Date mlcrFechaInicio, Date mlcrFechaFin,
			Integer mlcrTotalHoras, Integer mlcrTotalMaterias, Integer mlcrTipoOrgAprendizaje,
			Integer mlcrVigente, Integer mlcrTipoAprobacion,
			List<MallaCurricularMateria> mlcrMallaCurricularMaterias, List<MallaPeriodo> mlcrMallaPeriodos) {
		this.mlcrId = mlcrId;
		this.mlcrCarrera = mlcrCarrera;
		this.mlcrTipoFormacionMalla = mlcrTipoFormacionMalla;
		this.mlcrCodigo = mlcrCodigo;
		this.mlcrDescripcion = mlcrDescripcion;
		this.mlcrEstado = mlcrEstado;
		this.mlcrFechaInicio = mlcrFechaInicio;
		this.mlcrFechaFin = mlcrFechaFin;
		this.mlcrTotalHoras = mlcrTotalHoras;
		this.mlcrTotalMaterias = mlcrTotalMaterias;
		this.mlcrTipoOrgAprendizaje = mlcrTipoOrgAprendizaje;
		this.mlcrVigente = mlcrVigente;
		this.mlcrTipoAprobacion = mlcrTipoAprobacion;
		this.mlcrMallaCurricularMaterias = mlcrMallaCurricularMaterias;
		this.mlcrMallaPeriodos = mlcrMallaPeriodos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "MLCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMlcrId() {
		return this.mlcrId;
	}

	public void setMlcrId(int mlcrId) {
		this.mlcrId = mlcrId;
	}

	@ManyToOne
	@JoinColumn(name = "CRR_ID")
	public Carrera getMlcrCarrera() {
		return this.mlcrCarrera;
	}

	public void setMlcrCarrera(Carrera mlcrCarrera) {
		this.mlcrCarrera = mlcrCarrera;
	}

	@ManyToOne
	@JoinColumn(name = "TIFRML_ID")
	public TipoFormacionMalla getMlcrTipoFormacionMalla() {
		return this.mlcrTipoFormacionMalla;
	}

	public void setMlcrTipoFormacionMalla(TipoFormacionMalla mlcrTipoFormacionMalla) {
		this.mlcrTipoFormacionMalla = mlcrTipoFormacionMalla;
	}

	@Column(name = "MLCR_CODIGO", length = 128)
	@Length(max = 128)
	public String getMlcrCodigo() {
		return this.mlcrCodigo;
	}

	public void setMlcrCodigo(String mlcrCodigo) {
		this.mlcrCodigo = mlcrCodigo;
	}

	@Column(name = "MLCR_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getMlcrDescripcion() {
		return this.mlcrDescripcion;
	}

	public void setMlcrDescripcion(String mlcrDescripcion) {
		this.mlcrDescripcion = mlcrDescripcion;
	}

	@Column(name = "MLCR_ESTADO", precision = 22, scale = 0)
	public Integer getMlcrEstado() {
		return this.mlcrEstado;
	}

	public void setMlcrEstado(Integer mlcrEstado) {
		this.mlcrEstado = mlcrEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MLCR_FECHA_INICIO", length = 7)
	public Date getMlcrFechaInicio() {
		return this.mlcrFechaInicio;
	}

	public void setMlcrFechaInicio(Date mlcrFechaInicio) {
		this.mlcrFechaInicio = mlcrFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MLCR_FECHA_FIN", length = 7)
	public Date getMlcrFechaFin() {
		return this.mlcrFechaFin;
	}

	public void setMlcrFechaFin(Date mlcrFechaFin) {
		this.mlcrFechaFin = mlcrFechaFin;
	}

	@Column(name = "MLCR_TOTAL_HORAS", precision = 22, scale = 0)
	public Integer getMlcrTotalHoras() {
		return this.mlcrTotalHoras;
	}

	public void setMlcrTotalHoras(Integer mlcrTotalHoras) {
		this.mlcrTotalHoras = mlcrTotalHoras;
	}

	@Column(name = "MLCR_TOTAL_MATERIAS", precision = 22, scale = 0)
	public Integer getMlcrTotalMaterias() {
		return this.mlcrTotalMaterias;
	}

	public void setMlcrTotalMaterias(Integer mlcrTotalMaterias) {
		this.mlcrTotalMaterias = mlcrTotalMaterias;
	}

	@Column(name = "MLCR_TIPO_ORG_APRENDIZAJE", precision = 22, scale = 0)
	public Integer getMlcrTipoOrgAprendizaje() {
		return this.mlcrTipoOrgAprendizaje;
	}

	public void setMlcrTipoOrgAprendizaje(Integer mlcrTipoOrgAprendizaje) {
		this.mlcrTipoOrgAprendizaje = mlcrTipoOrgAprendizaje;
	}
	@Column(name = "MLCR_VIGENTE", precision = 22, scale = 0)
	public Integer getMlcrVigente() {
		return mlcrVigente;
	}

	public void setMlcrVigente(Integer mlcrVigente) {
		this.mlcrVigente = mlcrVigente;
	}
	@Column(name = "MLCR_TIPO_APROBACION", precision = 22, scale = 0)
	public Integer getMlcrTipoAprobacion() {
		return mlcrTipoAprobacion;
	}

	public void setMlcrTipoAprobacion(Integer mlcrTipoAprobacion) {
		this.mlcrTipoAprobacion = mlcrTipoAprobacion;
	}

	@OneToMany( mappedBy = "mlcrmtMallaCurricular")
	public List<MallaCurricularMateria> getMlcrMallaCurricularMaterias() {
		return this.mlcrMallaCurricularMaterias;
	}

	public void setMlcrMallaCurricularMaterias(List<MallaCurricularMateria> mlcrMallaCurricularMaterias) {
		this.mlcrMallaCurricularMaterias = mlcrMallaCurricularMaterias;
	}

	@OneToMany( mappedBy = "mlprMallaCurricular", fetch = FetchType.EAGER)
	public List<MallaPeriodo> getMlcrMallaPeriodos() {
		return this.mlcrMallaPeriodos;
	}

	public void setMlcrMallaPeriodos(List<MallaPeriodo> mlcrMallaPeriodos) {
		this.mlcrMallaPeriodos = mlcrMallaPeriodos;
	}
	
	@OneToMany( mappedBy = "mlcrnvMallaCurricular", fetch = FetchType.EAGER)
	public List<MallaCurricularNivel> getMlcrListMallaCurricularNivel() {
		return mlcrListMallaCurricularNivel;
	}

	public void setMlcrListMallaCurricularNivel(List<MallaCurricularNivel> mlcrListMallaCurricularNivel) {
		this.mlcrListMallaCurricularNivel = mlcrListMallaCurricularNivel;
	}
	
	

}
