package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "MATERIA", schema = ConstantesJpa.SCHEMA)
@NamedQueries({ @NamedQuery(name = "Materia.findAll", query="SELECT c FROM Materia c"),
				@NamedQuery(name = "Materia.findPorCodigoMateriaAndCarreraId", query = "SELECT c FROM Materia c WHERE c.mtrCodigo = :mtrCodigo  AND c.mtrCarrera.crrId = :carreraId"),
				@NamedQuery(name = "Materia.findModulosPorMateriaId", query = "SELECT c FROM Materia c WHERE c.mtrMateria.mtrId = :materiaId") })
public class Materia implements java.io.Serializable {

	private static final long serialVersionUID = 2770755558149017909L;
	
	private int mtrId;
	private CampoFormacion mtrCampoFormacion;
	private TipoMateria mtrTipoMateria;
	private Materia mtrMateria;
	private Carrera mtrCarrera;
	private NucleoProblemicoCarrera mtrNucleoProblemicoCarrera;
	private String mtrCodigo;
	private String mtrCodigoSniese;
	private String mtrDescripcion;
	private Integer mtrEstado;
	private Integer mtrHoras;
	private Integer mtrIntegradoraHoras;
	private Integer mtrPreProfesionalHoras;
	private Integer mtrHorasCien;
	private Integer mtrRelacionTrabajo;
	private Integer mtrUnidadMedida;
	private BigDecimal mtrCreditos;
	private BigDecimal mtrHorasPracticas;
	private BigDecimal mtrHorasTrabAutonomo;
	private Integer mtrHorasPracSema;
	private BigDecimal mtrHorasAutonoSema;
	
	private Grupo mtrGrupo;
	private List<Materia> mtrMaterias = new ArrayList<Materia>(0);
	private List<MallaCurricularMateria> mtrMallaCurricularMaterias = new ArrayList<MallaCurricularMateria>(0);
	private List<Corequisito> mtrCorequisitos = new ArrayList<Corequisito>(0);
	private List<Prerequisito> mtrPrerequisitos = new ArrayList<Prerequisito>(0);
	private List<Convalidacion> mtrConvalidacions = new ArrayList<Convalidacion>(0);
	private List<Corequisito> mtrMateriaCorequisitos = new ArrayList<Corequisito>(0);
	private List<Prerequisito> mtrMateriaPrerequisitos = new ArrayList<Prerequisito>(0);

	public Materia() {
	}

	public Materia(int mtrId) {
		this.mtrId = mtrId;
	}

	public Materia(int mtrId, CampoFormacion mtrCampoFormacion, TipoMateria mtrTipoMateria, Materia mtrMateria, Carrera mtrCarrera,
			NucleoProblemicoCarrera mtrNucleoProblemicoCarrera, String mtrCodigo, String mtrCodigoSniese,
			String mtrDescripcion, Integer mtrEstado, Integer mtrHoras, Integer mtrIntegradoraHoras,
			Integer mtrPreProfesionalHoras, Integer mtrHorasCien, Integer mtrRelacionTrabajo,
			Integer mtrHorasPracSema, BigDecimal mtrHorasAutonoSema,
			List<Materia> mtrMaterias, List<MallaCurricularMateria> mtrMallaCurricularMaterias,
			List<Corequisito> mtrCorequisitos, List<Prerequisito> mtrPrerequisitos,
			List<Convalidacion> mtrConvalidacions, List<Corequisito> mtrMateriaCorequisitos,
			List<Prerequisito> mtrMateriaPrerequisitos) {
		this.mtrId = mtrId;
		this.mtrCampoFormacion = mtrCampoFormacion;
		this.mtrTipoMateria = mtrTipoMateria;
		this.mtrMateria = mtrMateria;
		this.mtrCarrera = mtrCarrera;
		this.mtrNucleoProblemicoCarrera = mtrNucleoProblemicoCarrera;
		this.mtrCodigo = mtrCodigo;
		this.mtrCodigoSniese = mtrCodigoSniese;
		this.mtrDescripcion = mtrDescripcion;
		this.mtrEstado = mtrEstado;
		this.mtrHoras = mtrHoras;
		this.mtrIntegradoraHoras = mtrIntegradoraHoras;
		this.mtrPreProfesionalHoras = mtrPreProfesionalHoras;
		this.mtrHorasCien = mtrHorasCien;
		this.mtrRelacionTrabajo = mtrRelacionTrabajo;
		this.mtrHorasPracSema = mtrHorasPracSema;
		this.mtrHorasAutonoSema = mtrHorasAutonoSema;
		this.mtrMaterias = mtrMaterias;
		this.mtrMallaCurricularMaterias = mtrMallaCurricularMaterias;
		this.mtrCorequisitos = mtrCorequisitos;
		this.mtrPrerequisitos = mtrPrerequisitos;
		this.mtrConvalidacions = mtrConvalidacions;
		this.mtrMateriaCorequisitos = mtrMateriaCorequisitos;
		this.mtrMateriaPrerequisitos = mtrMateriaPrerequisitos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "MTR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMtrId() {
		return this.mtrId;
	}

	public void setMtrId(int mtrId) {
		this.mtrId = mtrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMFR_ID")
	public CampoFormacion getmtrCampoFormacion() {
		return this.mtrCampoFormacion;
	}

	public void setmtrCampoFormacion(CampoFormacion mtrCampoFormacion) {
		this.mtrCampoFormacion = mtrCampoFormacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIMT_ID")
	public TipoMateria getMtrTipoMateria() {
		return this.mtrTipoMateria;
	}

	public void setMtrTipoMateria(TipoMateria mtrTipoMateria) {
		this.mtrTipoMateria = mtrTipoMateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTR_SUB_ID")
	public Materia getMtrMateria() {
		return this.mtrMateria;
	}

	public void setMtrMateria(Materia mtrMateria) {
		this.mtrMateria = mtrMateria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CRR_ID")
	public Carrera getMtrCarrera() {
		return this.mtrCarrera;
	}

	public void setMtrCarrera(Carrera mtrCarrera) {
		this.mtrCarrera = mtrCarrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NCPRCR_ID")
	public NucleoProblemicoCarrera getMtrNucleoProblemicoCarrera() {
		return this.mtrNucleoProblemicoCarrera;
	}

	public void setMtrNucleoProblemicoCarrera(NucleoProblemicoCarrera mtrNucleoProblemicoCarrera) {
		this.mtrNucleoProblemicoCarrera = mtrNucleoProblemicoCarrera;
	}

	@Column(name = "MTR_CODIGO", length = 128)
	@Length(max = 128)
	public String getMtrCodigo() {
		return this.mtrCodigo;
	}

	public void setMtrCodigo(String mtrCodigo) {
		this.mtrCodigo = mtrCodigo;
	}

	@Column(name = "MTR_CODIGO_SNIESE", length = 128)
	@Length(max = 128)
	public String getMtrCodigoSniese() {
		return this.mtrCodigoSniese;
	}

	public void setMtrCodigoSniese(String mtrCodigoSniese) {
		this.mtrCodigoSniese = mtrCodigoSniese;
	}

	@Column(name = "MTR_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getMtrDescripcion() {
		return this.mtrDescripcion;
	}

	public void setMtrDescripcion(String mtrDescripcion) {
		this.mtrDescripcion = mtrDescripcion;
	}

	@Column(name = "MTR_ESTADO", precision = 22, scale = 0)
	public Integer getMtrEstado() {
		return this.mtrEstado;
	}

	public void setMtrEstado(Integer mtrEstado) {
		this.mtrEstado = mtrEstado;
	}

	@Column(name = "MTR_HORAS", precision = 22, scale = 0)
	public Integer getMtrHoras() {
		return this.mtrHoras;
	}

	public void setMtrHoras(Integer mtrHoras) {
		this.mtrHoras = mtrHoras;
	}

	@Column(name = "MTR_INTEGRADORA_HORAS", precision = 22, scale = 0)
	public Integer getMtrIntegradoraHoras() {
		return this.mtrIntegradoraHoras;
	}

	public void setMtrIntegradoraHoras(Integer mtrIntegradoraHoras) {
		this.mtrIntegradoraHoras = mtrIntegradoraHoras;
	}

	@Column(name = "MTR_PRE_PROFESIONAL_HORAS", precision = 22, scale = 0)
	public Integer getMtrPreProfesionalHoras() {
		return this.mtrPreProfesionalHoras;
	}

	public void setMtrPreProfesionalHoras(Integer mtrPreProfesionalHoras) {
		this.mtrPreProfesionalHoras = mtrPreProfesionalHoras;
	}

	@Column(name = "MTR_HORAS_CIEN", precision = 22, scale = 0)
	public Integer getMtrHorasCien() {
		return this.mtrHorasCien;
	}

	public void setMtrHorasCien(Integer mtrHorasCien) {
		this.mtrHorasCien = mtrHorasCien;
	}

	@Column(name = "MTR_RELACION_TRABAJO", precision = 22, scale = 0)
	public Integer getMtrRelacionTrabajo() {
		return this.mtrRelacionTrabajo;
	}

	public void setMtrRelacionTrabajo(Integer mtrRelacionTrabajo) {
		this.mtrRelacionTrabajo = mtrRelacionTrabajo;
	}
	
	@Column(name = "MTR_HORAS_PRAC_SEMA", precision = 22, scale = 0)
	public Integer getMtrHorasPracSema() {
		return mtrHorasPracSema;
	}

	public void setMtrHorasPracSema(Integer mtrHorasPracSema) {
		this.mtrHorasPracSema = mtrHorasPracSema;
	}

	@Column(name = "MTR_HORAS_AUTONO_SEMA", precision = 22, scale = 0)
	public BigDecimal getMtrHorasAutonoSema() {
		return mtrHorasAutonoSema;
	}

	public void setMtrHorasAutonoSema(BigDecimal mtrHorasAutonoSema) {
		this.mtrHorasAutonoSema = mtrHorasAutonoSema;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mtrMateria")
	public List<Materia> getMaterias() {
		return this.mtrMaterias;
	}

	public void setMaterias(List<Materia> mtrMaterias) {
		this.mtrMaterias = mtrMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mlcrmtMateria")
	public List<MallaCurricularMateria> getMtrMallaCurricularMaterias() {
		return this.mtrMallaCurricularMaterias;
	}

	public void setMtrMallaCurricularMaterias(List<MallaCurricularMateria> mtrMallaCurricularMaterias) {
		this.mtrMallaCurricularMaterias = mtrMallaCurricularMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crqMateria")
	public List<Corequisito> getMtrCorequisitos() {
		return this.mtrCorequisitos;
	}

	public void setMtrCorequisitos(List<Corequisito> mtrCorequisitos) {
		this.mtrCorequisitos = mtrCorequisitos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prrMateriaPrerequisito")
	public List<Prerequisito> getMtrPrerequisitos() {
		return this.mtrPrerequisitos;
	}

	public void setMtrPrerequisitos(List<Prerequisito> mtrPrerequisitos) {
		this.mtrPrerequisitos = mtrPrerequisitos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cnvMateria")
	public List<Convalidacion> getMtrConvalidacions() {
		return this.mtrConvalidacions;
	}

	public void setMtrConvalidacions(List<Convalidacion> mtrConvalidacions) {
		this.mtrConvalidacions = mtrConvalidacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crqMateriaCorequisito")
	public List<Corequisito> getMtrMateriaCorequisitos() {
		return this.mtrMateriaCorequisitos;
	}

	public void setMtrMateriaCorequisitos(List<Corequisito> mtrMateriaCorequisitos) {
		this.mtrMateriaCorequisitos = mtrMateriaCorequisitos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prrMateria")
	public List<Prerequisito> getMtrMateriaPrerequisitos() {
		return this.mtrMateriaPrerequisitos;
	}

	public void setMtrMateriaPrerequisitos(List<Prerequisito> mtrMateriaPrerequisitos) {
		this.mtrMateriaPrerequisitos = mtrMateriaPrerequisitos;
	}
	
	@Column(name = "MTR_UNIDAD_MEDIDA")
	public Integer getMtrUnidadMedida() {
		return mtrUnidadMedida;
	}

	public void setMtrUnidadMedida(Integer mtrUnidadMedida) {
		this.mtrUnidadMedida = mtrUnidadMedida;
	}
	@Column(name = "MTR_CREDITOS", precision=2)
	public BigDecimal getMtrCreditos() {
		return mtrCreditos;
	}

	public void setMtrCreditos(BigDecimal mtrCreditos) {
		this.mtrCreditos = mtrCreditos;
	}

	@Column(name = "MTR_HORAS_PRACTICAS", precision=2)
	public BigDecimal getMtrHorasPracticas() {
		return mtrHorasPracticas;
	}

	public void setMtrHorasPracticas(BigDecimal mtrHorasPracticas) {
		this.mtrHorasPracticas = mtrHorasPracticas;
	}

	@Column(name = "MTR_HORAS_TRAB_AUTONOMO", precision=2)
	public BigDecimal getMtrHorasTrabAutonomo() {
		return mtrHorasTrabAutonomo;
	}

	public void setMtrHorasTrabAutonomo(BigDecimal mtrHorasTrabAutonomo) {
		this.mtrHorasTrabAutonomo = mtrHorasTrabAutonomo;
	}

	//bi-directional many-to-one association to Grupo
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="GRP_ID")
	public Grupo getMtrGrupo() {
		return this.mtrGrupo;
	}

	public void setMtrGrupo(Grupo mtrGrupo) {
		this.mtrGrupo = mtrGrupo;
	}
	
	
	
}
