package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Modalidad generated by hbm2java
 */
@Entity
@Table(name = "MODALIDAD", schema = ConstantesJpa.SCHEMA)
public class Modalidad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7077538482630656088L;
	private int mdlId;
	private String mdlDescripcion;
	private List<ConfiguracionCarrera> mdlConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);
	private List<Arancel> mdlArancels = new ArrayList<Arancel>(0);

	public Modalidad() {
	}

	public Modalidad(int mdlId) {
		this.mdlId = mdlId;
	}

	public Modalidad(int mdlId, String mdlDescripcion, List<ConfiguracionCarrera> mdlConfiguracionCarreras,
			List<Arancel> mdlArancels) {
		this.mdlId = mdlId;
		this.mdlDescripcion = mdlDescripcion;
		this.mdlConfiguracionCarreras = mdlConfiguracionCarreras;
		this.mdlArancels = mdlArancels;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "MDL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMdlId() {
		return this.mdlId;
	}

	public void setMdlId(int mdlId) {
		this.mdlId = mdlId;
	}

	@Column(name = "MDL_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getMdlDescripcion() {
		return this.mdlDescripcion;
	}

	public void setMdlDescripcion(String mdlDescripcion) {
		this.mdlDescripcion = mdlDescripcion;
	}

	@OneToMany( mappedBy = "cncrModalidad")
	public List<ConfiguracionCarrera> getMdlConfiguracionCarreras() {
		return this.mdlConfiguracionCarreras;
	}

	public void setMdlConfiguracionCarreras(List<ConfiguracionCarrera> mdlConfiguracionCarreras) {
		this.mdlConfiguracionCarreras = mdlConfiguracionCarreras;
	}

	@OneToMany( mappedBy = "arnModalidad")
	public List<Arancel> getMdlArancels() {
		return this.mdlArancels;
	}

	public void setMdlArancels(List<Arancel> mdlArancels) {
		this.mdlArancels = mdlArancels;
	}

}
