package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NivelFormacion generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_FORMACION", schema = ConstantesJpa.SCHEMA)
public class NivelFormacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3376354125369813513L;
	private int nvfrId;
	private RegimenAcademico nvfrRegimenAcademico;
	private String nvfrDescripcion;
	private List<TipoFormacion> nvfrTipoFormacions = new ArrayList<TipoFormacion>(0);

	public NivelFormacion() {
	}

	public NivelFormacion(int nvfrId) {
		this.nvfrId = nvfrId;
	}

	public NivelFormacion(int nvfrId, RegimenAcademico nvfrRegimenAcademico, String nvfrDescripcion,
			List<TipoFormacion> nvfrTipoFormacions) {
		this.nvfrId = nvfrId;
		this.nvfrRegimenAcademico = nvfrRegimenAcademico;
		this.nvfrDescripcion = nvfrDescripcion;
		this.nvfrTipoFormacions = nvfrTipoFormacions;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NVFR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvfrId() {
		return this.nvfrId;
	}

	public void setNvfrId(int nvfrId) {
		this.nvfrId = nvfrId;
	}

	@ManyToOne
	@JoinColumn(name = "RGAC_ID")
	public RegimenAcademico getNvfrRegimenAcademico() {
		return this.nvfrRegimenAcademico;
	}

	public void setNvfrRegimenAcademico(RegimenAcademico nvfrRegimenAcademico) {
		this.nvfrRegimenAcademico = nvfrRegimenAcademico;
	}

	@Column(name = "NVFR_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getNvfrDescripcion() {
		return this.nvfrDescripcion;
	}

	public void setNvfrDescripcion(String nvfrDescripcion) {
		this.nvfrDescripcion = nvfrDescripcion;
	}

	@OneToMany( mappedBy = "tifrNivelFormacion")
	public List<TipoFormacion> getNvfrTipoFormacions() {
		return this.nvfrTipoFormacions;
	}

	public void setNvfrTipoFormacions(List<TipoFormacion> nvfrTipoFormacions) {
		this.nvfrTipoFormacions = nvfrTipoFormacions;
	}

}
