package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NivelInstruccion generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_INSTRUCCION", schema = ConstantesJpa.SCHEMA)
public class NivelInstruccion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8811582144420665410L;
	private int nvinId;
	private String nvinDescripcion;
	private List<InstruccionPuesto> nvinInstruccionPuestos = new ArrayList<InstruccionPuesto>(0);

	public NivelInstruccion() {
	}

	public NivelInstruccion(int nvinId) {
		this.nvinId = nvinId;
	}

	public NivelInstruccion(int nvinId, String nvinDescripcion, List<InstruccionPuesto> nvinInstruccionPuestos) {
		this.nvinId = nvinId;
		this.nvinDescripcion = nvinDescripcion;
		this.nvinInstruccionPuestos = nvinInstruccionPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NVIN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvinId() {
		return this.nvinId;
	}

	public void setNvinId(int nvinId) {
		this.nvinId = nvinId;
	}

	@Column(name = "NVIN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getNvinDescripcion() {
		return this.nvinDescripcion;
	}

	public void setNvinDescripcion(String nvinDescripcion) {
		this.nvinDescripcion = nvinDescripcion;
	}

	@OneToMany( mappedBy = "inpsNivelInstruccion")
	public List<InstruccionPuesto> getNvinInstruccionPuestos() {
		return this.nvinInstruccionPuestos;
	}

	public void setNvinInstruccionPuestos(List<InstruccionPuesto> nvinInstruccionPuestos) {
		this.nvinInstruccionPuestos = nvinInstruccionPuestos;
	}

}
