package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NivelCompetencia generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_COMPETENCIA", schema = ConstantesJpa.SCHEMA)
public class NivelCompetencia implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4308387838373019365L;
	private int nvcmId;
	private Competencia nvcmCompetencia;
	private Integer nvcmDescripcion;
	private String nvcmComportamiento;
	private List<CompetenciaPuesto> nvcmCompetenciaPuestos = new ArrayList<CompetenciaPuesto>(0);

	public NivelCompetencia() {
	}

	public NivelCompetencia(int nvcmId) {
		this.nvcmId = nvcmId;
	}

	public NivelCompetencia(int nvcmId, Competencia nvcmCompetencia, Integer nvcmDescripcion, String nvcmComportamiento,
			List<CompetenciaPuesto> nvcmCompetenciaPuestos) {
		this.nvcmId = nvcmId;
		this.nvcmCompetencia = nvcmCompetencia;
		this.nvcmDescripcion = nvcmDescripcion;
		this.nvcmComportamiento = nvcmComportamiento;
		this.nvcmCompetenciaPuestos = nvcmCompetenciaPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NVCM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvcmId() {
		return this.nvcmId;
	}

	public void setNvcmId(int nvcmId) {
		this.nvcmId = nvcmId;
	}

	@ManyToOne
	@JoinColumn(name = "CMP_ID")
	public Competencia getNvcmCompetencia() {
		return this.nvcmCompetencia;
	}

	public void setNvcmCompetencia(Competencia nvcmCompetencia) {
		this.nvcmCompetencia = nvcmCompetencia;
	}

	@Column(name = "NVCM_DESCRIPCION", precision = 22, scale = 0)
	public Integer getNvcmDescripcion() {
		return this.nvcmDescripcion;
	}

	public void setNvcmDescripcion(Integer nvcmDescripcion) {
		this.nvcmDescripcion = nvcmDescripcion;
	}

	@Column(name = "NVCM_COMPORTAMIENTO", length = 512)
	@Length(max = 512)
	public String getNvcmComportamiento() {
		return this.nvcmComportamiento;
	}

	public void setNvcmComportamiento(String nvcmComportamiento) {
		this.nvcmComportamiento = nvcmComportamiento;
	}

	@OneToMany( mappedBy = "cmpsNivelCompetencia")
	public List<CompetenciaPuesto> getNvcmCompetenciaPuestos() {
		return this.nvcmCompetenciaPuestos;
	}

	public void setNvcmCompetenciaPuestos(List<CompetenciaPuesto> nvcmCompetenciaPuestos) {
		this.nvcmCompetenciaPuestos = nvcmCompetenciaPuestos;
	}

}
