package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NivelApertura generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_APERTURA", schema = ConstantesJpa.SCHEMA)
public class NivelApertura implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8255393830837908434L;
	private int nvapId;
	private String nvapDescripcion;
	private Integer nvapNumeral;
	private Integer crrId;
	private List<TipoNivelApertura> nvapTipoNivelAperturas = new ArrayList<TipoNivelApertura>(0);

	public NivelApertura() {
	}

	public NivelApertura(int nvapId) {
		this.nvapId = nvapId;
	}

	public NivelApertura(int nvapId, String nvapDescripcion, List<TipoNivelApertura> nvapTipoNivelAperturas) {
		this.nvapId = nvapId;
		this.nvapDescripcion = nvapDescripcion;
		this.nvapTipoNivelAperturas = nvapTipoNivelAperturas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "NVAP_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvapId() {
		return this.nvapId;
	}

	public void setNvapId(int nvapId) {
		this.nvapId = nvapId;
	}

	@Column(name = "NVAP_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getNvapDescripcion() {
		return this.nvapDescripcion;
	}

	public void setNvapDescripcion(String nvapDescripcion) {
		this.nvapDescripcion = nvapDescripcion;
	}

	@Column(name = "NVAP_NUMERAL")
	public Integer getNvapNumeral() {
		return nvapNumeral;
	}

	public void setNvapNumeral(Integer nvapNumeral) {
		this.nvapNumeral = nvapNumeral;
	}
	
	
	@Column(name = "CRR_ID")
	public Integer getCrrId() {
		return crrId;
	}

	public void setCrrId(Integer crrId) {
		this.crrId = crrId;
	}

	@OneToMany(mappedBy = "tinvapNivelApertura")
	public List<TipoNivelApertura> getNvapTipoNivelAperturas() {
		return this.nvapTipoNivelAperturas;
	}

	public void setNvapTipoNivelAperturas(List<TipoNivelApertura> nvapTipoNivelAperturas) {
		this.nvapTipoNivelAperturas = nvapTipoNivelAperturas;
	}

}
