package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 10/07/2019 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NotaCorte generated by hbm2java
 */
@Entity
@Table(name = "NOTA_CORTE", schema = ConstantesJpa.SCHEMA)
public class NotaCorte implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4308387838373019365L;
	private int nocrId;
	private Carrera nocrCarrera;
	private Integer nocrEstado;
	private Float nocrNota;
	private Integer nocrPracId;
	private List<HistorialNotaCorte> nocrHistorialNotaCortes = new ArrayList<HistorialNotaCorte>(0);

	public NotaCorte() {
	}

	public NotaCorte(int nocrId) {
		this.nocrId = nocrId;
	}

	public NotaCorte(int nocrId, Carrera nocrCarrera, Integer nocrEstado, Float nocrNota,Integer nocrPracId,
			List<HistorialNotaCorte> nocrHistorialNotaCortes) {
		this.nocrId = nocrId;
		this.nocrCarrera = nocrCarrera;
		this.nocrEstado = nocrEstado;
		this.nocrNota = nocrNota;
		this.nocrPracId = nocrPracId;		
		this.nocrHistorialNotaCortes = nocrHistorialNotaCortes;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NOCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNocrId() {
		return this.nocrId;
	}

	public void setNocrId(int nocrId) {
		this.nocrId = nocrId;
	}

	
	@ManyToOne
	@JoinColumn(name = "CRR_ID")
	public Carrera getNocrCarrera() {
		return this.nocrCarrera;
	}

	public void setNocrCarrera(Carrera nocrCarrera) {
		this.nocrCarrera = nocrCarrera;
	}

	@Column(name = "NOCR_PRAC_ID", precision = 22, scale = 0)
	public Integer getNocrPracId() {
		return this.nocrPracId;
	}

	public void setNocrPracId(Integer nocrPracId) {
		this.nocrPracId = nocrPracId;
	}

	
	@Column(name = "NOCR_ESTADO", precision = 22, scale = 0)
	public Integer getNocrEstado() {
		return this.nocrEstado;
	}

	public void setNocrEstado(Integer nocrEstado) {
		this.nocrEstado = nocrEstado;
	}
	
	
	@Column(name="NOCR_NOTA", precision=126)
	public Float getNocrNota() {
		return this.nocrNota;
	}

	public void setNocrNota(Float nocrNota) {
		this.nocrNota = nocrNota;
	}
	
	@OneToMany( mappedBy = "hsnocrNotaCorte")
	public List<HistorialNotaCorte> getNocrHistorialNotaCortes() {
		return this.nocrHistorialNotaCortes;
	}

	public void setNocrHistorialNotaCortes(List<HistorialNotaCorte> nocrHistorialNotaCortes) {
		this.nocrHistorialNotaCortes = nocrHistorialNotaCortes;
	}

}
