package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NucleoProblemicoCarrera generated by hbm2java
 */
@Entity
@Table(name = "NUCLEO_PROBLEMICO_CARRERA", schema = ConstantesJpa.SCHEMA)
public class NucleoProblemicoCarrera implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 715664419306199607L;
	private int ncprcrId;
	private Carrera ncprcrCarrera;
	private NucleoProblemico ncprcrNucleoProblemico;
	private Integer ncprcrEstado;
	private List<Materia> ncprcrMaterias = new ArrayList<Materia>(0);

	public NucleoProblemicoCarrera() {
	}

	public NucleoProblemicoCarrera(int ncprcrId) {
		this.ncprcrId = ncprcrId;
	}

	public NucleoProblemicoCarrera(int ncprcrId, Carrera ncprcrCarrera, NucleoProblemico ncprcrNucleoProblemico,
			Integer ncprcrEstado, List<Materia> ncprcrMaterias) {
		this.ncprcrId = ncprcrId;
		this.ncprcrCarrera = ncprcrCarrera;
		this.ncprcrNucleoProblemico = ncprcrNucleoProblemico;
		this.ncprcrEstado = ncprcrEstado;
		this.ncprcrMaterias = ncprcrMaterias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NCPRCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNcprcrId() {
		return this.ncprcrId;
	}

	public void setNcprcrId(int ncprcrId) {
		this.ncprcrId = ncprcrId;
	}

	@ManyToOne
	@JoinColumn(name = "CRR_ID")
	public Carrera getNcprcrCarrera() {
		return this.ncprcrCarrera;
	}

	public void setNcprcrCarrera(Carrera ncprcrCarrera) {
		this.ncprcrCarrera = ncprcrCarrera;
	}

	@ManyToOne
	@JoinColumn(name = "NCPR_ID")
	public NucleoProblemico getNcprcrNucleoProblemico() {
		return this.ncprcrNucleoProblemico;
	}

	public void setNcprcrNucleoProblemico(NucleoProblemico ncprcrNucleoProblemico) {
		this.ncprcrNucleoProblemico = ncprcrNucleoProblemico;
	}

	@Column(name = "NCPRCR_ESTADO", precision = 22, scale = 0)
	public Integer getNcprcrEstado() {
		return this.ncprcrEstado;
	}

	public void setNcprcrEstado(Integer ncprcrEstado) {
		this.ncprcrEstado = ncprcrEstado;
	}

	@OneToMany( mappedBy = "mtrNucleoProblemicoCarrera")
	public List<Materia> getMateriasMaterias() {
		return this.ncprcrMaterias;
	}

	public void setMateriasMaterias(List<Materia> ncprcrMaterias) {
		this.ncprcrMaterias = ncprcrMaterias;
	}

}
