package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * NucleoProblemico generated by hbm2java
 */
@Entity
@Table(name = "NUCLEO_PROBLEMICO", schema = ConstantesJpa.SCHEMA)
public class NucleoProblemico implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5878924052336841701L;
	private int ncprId;
	private String ncprDescripcion;
	private Integer ncprEstado;
	private List<NucleoProblemicoCarrera> ncprNucleoProblemicoCarreras = new ArrayList<NucleoProblemicoCarrera>(0);

	public NucleoProblemico() {
	}

	public NucleoProblemico(int ncprId) {
		this.ncprId = ncprId;
	}

	public NucleoProblemico(int ncprId, String ncprDescripcion, Integer ncprEstado,
			List<NucleoProblemicoCarrera> ncprNucleoProblemicoCarreras) {
		this.ncprId = ncprId;
		this.ncprDescripcion = ncprDescripcion;
		this.ncprEstado = ncprEstado;
		this.ncprNucleoProblemicoCarreras = ncprNucleoProblemicoCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "NCPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNcprId() {
		return this.ncprId;
	}

	public void setNcprId(int ncprId) {
		this.ncprId = ncprId;
	}

	@Column(name = "NCPR_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getNcprDescripcion() {
		return this.ncprDescripcion;
	}

	public void setNcprDescripcion(String ncprDescripcion) {
		this.ncprDescripcion = ncprDescripcion;
	}

	@Column(name = "NCPR_ESTADO", precision = 22, scale = 0)
	public Integer getNcprEstado() {
		return this.ncprEstado;
	}

	public void setNcprEstado(Integer ncprEstado) {
		this.ncprEstado = ncprEstado;
	}

	@OneToMany( mappedBy = "ncprcrNucleoProblemico")
	public List<NucleoProblemicoCarrera> getNcprNucleoProblemicoCarreras() {
		return this.ncprNucleoProblemicoCarreras;
	}

	public void setNcprNucleoProblemicoCarreras(List<NucleoProblemicoCarrera> ncprNucleoProblemicoCarreras) {
		this.ncprNucleoProblemicoCarreras = ncprNucleoProblemicoCarreras;
	}

}
