package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Paralelo generated by hbm2java
 */
@Entity
@Table(name = "PARALELO", schema = ConstantesJpa.SCHEMA)
public class Paralelo implements java.io.Serializable {

	private static final long serialVersionUID = 8070259586952797821L;

	private int prlId;
	private String prlCodigo;
	private String prlDescripcion;
	private Integer prlEstado;
	private Carrera prlCarrera;
	private PeriodoAcademico prlPeriodoAcademico;
	private Integer prlCupo;
	private Timestamp prlFecha;//fecha de creacion
	private Timestamp prlInicioClase;
	private Timestamp prlFinClase;
	private List<MallaCurricularParalelo> prlMallaCurricularParalelos;

	public Paralelo() {
	}

	public Paralelo(int prlId) {
		this.prlId = prlId;
	}

	public Paralelo(int prlId, String prlCodigo, String prlDescripcion, Integer prlEstado,
			List<MallaCurricularParalelo> prlMallaCurricularParalelos, Carrera prlCarrera,
			PeriodoAcademico prlPeriodoAcademico, Integer prlCupo) {
		this.prlId = prlId;
		this.prlCodigo = prlCodigo;
		this.prlDescripcion = prlDescripcion;
		this.prlEstado = prlEstado;
		this.prlMallaCurricularParalelos = prlMallaCurricularParalelos;
		this.prlCarrera = prlCarrera;
		this.prlPeriodoAcademico = prlPeriodoAcademico;
		this.prlCupo = prlCupo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "PRL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrlId() {
		return this.prlId;
	}

	public void setPrlId(int prlId) {
		this.prlId = prlId;
	}

	@Column(name = "PRL_CODIGO", length = 128)
	@Length(max = 128)
	public String getPrlCodigo() {
		return this.prlCodigo;
	}

	public void setPrlCodigo(String prlCodigo) {
		this.prlCodigo = prlCodigo;
	}

	@Column(name = "PRL_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPrlDescripcion() {
		return this.prlDescripcion;
	}

	public void setPrlDescripcion(String prlDescripcion) {
		this.prlDescripcion = prlDescripcion;
	}

	@Column(name = "PRL_ESTADO", precision = 22, scale = 0)
	public Integer getPrlEstado() {
		return this.prlEstado;
	}

	public void setPrlEstado(Integer prlEstado) {
		this.prlEstado = prlEstado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mlcrprParalelo")
	public List<MallaCurricularParalelo> getPrlMallaCurricularParalelos() {
		return this.prlMallaCurricularParalelos;
	}

	public void setPrlMallaCurricularParalelos(List<MallaCurricularParalelo> prlMallaCurricularParalelos) {
		this.prlMallaCurricularParalelos = prlMallaCurricularParalelos;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CRR_ID")
	public Carrera getPrlCarrera() {
		return prlCarrera;
	}

	public void setPrlCarrera(Carrera prlCarrera) {
		this.prlCarrera = prlCarrera;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getPrlPeriodoAcademico() {
		return prlPeriodoAcademico;
	}

	public void setPrlPeriodoAcademico(PeriodoAcademico prlPeriodoAcademico) {
		this.prlPeriodoAcademico = prlPeriodoAcademico;
	}

	@Column(name = "PRL_CUPO", precision = 22, scale = 0)
	public Integer getPrlCupo() {
		return prlCupo;
	}

	public void setPrlCupo(Integer prlCupo) {
		this.prlCupo = prlCupo;
	}

	@Column(name = "PRL_FECHA")
	public Timestamp getPrlFecha() {
		return prlFecha;
	}

	public void setPrlFecha(Timestamp prlFecha) {
		this.prlFecha = prlFecha;
	}

	@Column(name = "PRL_INICIO_CLASE")
	public Timestamp getPrlInicioClase() {
		return prlInicioClase;
	}

	public void setPrlInicioClase(Timestamp prlInicioClase) {
		this.prlInicioClase = prlInicioClase;
	}

	@Column(name = "PRL_FIN_CLASE")
	public Timestamp getPrlFinClase() {
		return prlFinClase;
	}

	public void setPrlFinClase(Timestamp prlFinClase) {
		this.prlFinClase = prlFinClase;
	}

	
}
