package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "PERSONA", schema = ConstantesJpa.SCHEMA)
public class Persona implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8146503111534118921L;
	private int prsId;
	private Ubicacion prsUbicacionNacimiento;
	private Ubicacion prsUbicacionResidencia;
	private Etnia prsEtnia;
	private Integer prsTipoIdentificacion;
	private Integer prsTipoIdentificacionSniese;
	private String prsIdentificacion;
	private String prsPrimerApellido;
	private String prsSegundoApellido;
	private String prsNombres;
	private Integer prsSexo;
	private Integer prsSexoSniese;
	private String prsMailPersonal;
	private String prsMailInstitucional;
	private String prsTelefono;
	private Date prsFechaNacimiento;
	private String prsCallePrincipal;
	private String prsCalleSecundaria;
	private String prsSectorDomicilio;
	private String prsNumeroCasa;
	private String prsReferenciaDomicilio;
	private String prsCelular;
	private Integer prsDiscapacidad;
	private Integer prsTipoDiscapacidad;
	private Integer prsPorceDiscapacidad;
	private Integer prsCarnetConadis;
	private String prsNumCarnetConadis;
	private Integer prsEstadoCivil;
	private Timestamp prsFechaActualizacionDatos;
	private Date prsFechaVinculacionSeguro;
	private Timestamp prsFechaRegistroSeguro;
	private Integer prsEstadoSeguro;
	private String prsFormularioSeguro;
	private Timestamp prsFechaFormularioSeguro;
	private List<FichaDocente> prsFichaDocentes = new ArrayList<FichaDocente>(0);
	private List<FichaEmpleado> prsFichaEmpleados = new ArrayList<FichaEmpleado>(0);
	private List<Usuario> prsUsuarios = new ArrayList<Usuario>(0);
	private List<CandidatoContrato> prsCandidatoContratos = new ArrayList<CandidatoContrato>(0);
	private List<FichaEstudiante> prsFichaEstudiantes = new ArrayList<FichaEstudiante>(0);
	private List<Referencia> prsReferencias = new ArrayList<Referencia>(0);

	
	
	public Persona() {
	}

	public Persona(int prsId) {
		this.prsId = prsId;
	}

	public Persona(int prsId, Ubicacion prsUbicacionNacimiento, Ubicacion prsUbicacionResidencia, Etnia prsEtnia, Integer prsTipoIdentificacion,
			Integer prsTipoIdentificacionSniese, String prsIdentificacion, String prsPrimerApellido,
			String prsSegundoApellido, String prsNombres, Integer prsSexo, Integer prsSexoSniese,
			String prsMailPersonal, String prsMailInstitucional, String prsTelefono, Date prsFechaNacimiento,
			String prsCallePrincipal, String prsCalleSecundaria, String prsSectorDomicilio, String prsNumeroCasa, 
			String prsReferenciaDomicilio, String prsCelular, Integer prsDiscapacidad,	Integer prsTipoDiscapacidad, Integer prsPorceDiscapacidad,
			Integer prsCarnetConadis, String prsNumCarnetConadis, Integer prsEstadoCivil, Timestamp prsFechaActualizacionDatos, 
			Date prsFechaVinculacionSeguro, Timestamp prsFechaRegistroSeguro, Integer prsEstadoSeguro, String prsFormularioSeguro, Timestamp prsFechaFormularioSeguro,
			List<FichaDocente> prsFichaDocentes, List<FichaEmpleado> prsFichaEmpleados, List<Usuario> prsUsuarios, List<Referencia> prsReferencias,
			List<CandidatoContrato> prsCandidatoContratos, List<FichaEstudiante> prsFichaEstudiantes) {
		this.prsId = prsId;
		this.prsUbicacionNacimiento = prsUbicacionNacimiento;
		this.prsUbicacionResidencia = prsUbicacionResidencia;
		this.prsEtnia = prsEtnia;
		this.prsTipoIdentificacion = prsTipoIdentificacion;
		this.prsTipoIdentificacionSniese = prsTipoIdentificacionSniese;
		this.prsIdentificacion = prsIdentificacion;
		this.prsPrimerApellido = prsPrimerApellido;
		this.prsSegundoApellido = prsSegundoApellido;
		this.prsNombres = prsNombres;
		this.prsSexo = prsSexo;
		this.prsSexoSniese = prsSexoSniese;
		this.prsMailPersonal = prsMailPersonal;
		this.prsMailInstitucional = prsMailInstitucional;
		this.prsTelefono = prsTelefono;
		this.prsFechaNacimiento = prsFechaNacimiento;
		this.prsCallePrincipal = prsCallePrincipal;
		this.prsCalleSecundaria = prsCalleSecundaria;
		this.prsSectorDomicilio = prsSectorDomicilio;
		this.prsNumeroCasa = prsNumeroCasa;
		this.prsReferenciaDomicilio = prsReferenciaDomicilio;
		this.prsCelular = prsCelular;
		this.prsDiscapacidad = prsDiscapacidad;
		this.prsTipoDiscapacidad = prsTipoDiscapacidad;
		this.prsPorceDiscapacidad = prsPorceDiscapacidad;
		this.prsCarnetConadis = prsCarnetConadis;
		this.prsNumCarnetConadis = prsNumCarnetConadis;
		this.prsEstadoCivil = prsEstadoCivil;
		this.prsFechaActualizacionDatos = prsFechaActualizacionDatos;
		this.prsFechaVinculacionSeguro = prsFechaVinculacionSeguro;
		this.prsFechaRegistroSeguro = prsFechaRegistroSeguro;
		this.prsEstadoSeguro = prsEstadoSeguro;
		this.prsFormularioSeguro = prsFormularioSeguro;
		this.prsFechaFormularioSeguro = prsFechaFormularioSeguro;
		this.prsFichaDocentes = prsFichaDocentes;
		this.prsFichaEmpleados = prsFichaEmpleados;
		this.prsUsuarios = prsUsuarios;
		this.prsCandidatoContratos = prsCandidatoContratos;
		this.prsFichaEstudiantes = prsFichaEstudiantes;
		this.prsReferencias = prsReferencias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrsId() {
		return this.prsId;
	}

	public void setPrsId(int prsId) {
		this.prsId = prsId;
	}

	@ManyToOne
	@JoinColumn(name = "UBC_NACIMIENTO")
	public Ubicacion getPrsUbicacionNacimiento() {
		return prsUbicacionNacimiento;
	}

	public void setPrsUbicacionNacimiento(Ubicacion prsUbicacionNacimiento) {
		this.prsUbicacionNacimiento = prsUbicacionNacimiento;
	}

	@ManyToOne
	@JoinColumn(name = "UBC_RESIDENCIA")
	public Ubicacion getPrsUbicacionResidencia() {
		return prsUbicacionResidencia;
	}

	public void setPrsUbicacionResidencia(Ubicacion prsUbicacionResidencia) {
		this.prsUbicacionResidencia = prsUbicacionResidencia;
	}

	
	@ManyToOne
	@JoinColumn(name = "ETN_ID")
	public Etnia getPrsEtnia() {
		return this.prsEtnia;
	}

	public void setPrsEtnia(Etnia prsEtnia) {
		this.prsEtnia = prsEtnia;
	}

	@Column(name = "PRS_TIPO_IDENTIFICACION", precision = 22, scale = 0)
	public Integer getPrsTipoIdentificacion() {
		return this.prsTipoIdentificacion;
	}

	public void setPrsTipoIdentificacion(Integer prsTipoIdentificacion) {
		this.prsTipoIdentificacion = prsTipoIdentificacion;
	}

	@Column(name = "PRS_TIPO_IDENTIFICACION_SNIESE", precision = 22, scale = 0)
	public Integer getPrsTipoIdentificacionSniese() {
		return this.prsTipoIdentificacionSniese;
	}

	public void setPrsTipoIdentificacionSniese(Integer prsTipoIdentificacionSniese) {
		this.prsTipoIdentificacionSniese = prsTipoIdentificacionSniese;
	}

	@Column(name = "PRS_IDENTIFICACION", length = 13)
	@Length(max = 13)
	public String getPrsIdentificacion() {
		return this.prsIdentificacion;
	}

	public void setPrsIdentificacion(String prsIdentificacion) {
		this.prsIdentificacion = prsIdentificacion;
	}

	@Column(name = "PRS_PRIMER_APELLIDO", length = 32)
	@Length(max = 32)
	public String getPrsPrimerApellido() {
		return this.prsPrimerApellido;
	}

	public void setPrsPrimerApellido(String prsPrimerApellido) {
		this.prsPrimerApellido = prsPrimerApellido;
	}

	@Column(name = "PRS_SEGUNDO_APELLIDO", length = 32)
	@Length(max = 32)
	public String getPrsSegundoApellido() {
		return this.prsSegundoApellido;
	}

	public void setPrsSegundoApellido(String prsSegundoApellido) {
		this.prsSegundoApellido = prsSegundoApellido;
	}

	@Column(name = "PRS_NOMBRES", length = 50)
	@Length(max = 50)
	public String getPrsNombres() {
		return this.prsNombres;
	}

	public void setPrsNombres(String prsNombres) {
		this.prsNombres = prsNombres;
	}

	@Column(name = "PRS_SEXO", precision = 22, scale = 0)
	public Integer getPrsSexo() {
		return this.prsSexo;
	}

	public void setPrsSexo(Integer prsSexo) {
		this.prsSexo = prsSexo;
	}

	@Column(name = "PRS_SEXO_SNIESE", precision = 22, scale = 0)
	public Integer getPrsSexoSniese() {
		return this.prsSexoSniese;
	}

	public void setPrsSexoSniese(Integer prsSexoSniese) {
		this.prsSexoSniese = prsSexoSniese;
	}

	@Column(name = "PRS_MAIL_PERSONAL", length = 50)
	@Length(max = 50)
	public String getPrsMailPersonal() {
		return this.prsMailPersonal;
	}

	public void setPrsMailPersonal(String prsMailPersonal) {
		this.prsMailPersonal = prsMailPersonal;
	}

	@Column(name = "PRS_MAIL_INSTITUCIONAL", length = 50)
	@Length(max = 50)
	public String getPrsMailInstitucional() {
		return this.prsMailInstitucional;
	}

	public void setPrsMailInstitucional(String prsMailInstitucional) {
		this.prsMailInstitucional = prsMailInstitucional;
	}

	@Column(name = "PRS_TELEFONO", length = 10)
	@Length(max = 10)
	public String getPrsTelefono() {
		return this.prsTelefono;
	}

	public void setPrsTelefono(String prsTelefono) {
		this.prsTelefono = prsTelefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRS_FECHA_NACIMIENTO", length = 7)
	public Date getPrsFechaNacimiento() {
		return this.prsFechaNacimiento;
	}

	public void setPrsFechaNacimiento(Date prsFechaNacimiento) {
		this.prsFechaNacimiento = prsFechaNacimiento;
	}
	
	@Column(name = "PRS_CALLE_PRINCIPAL", length = 256)
	@Length(max = 256)
	public String getPrsCallePrincipal() {
		return prsCallePrincipal;
	}

	public void setPrsCallePrincipal(String prsCallePrincipal) {
		this.prsCallePrincipal = prsCallePrincipal;
	}

	@Column(name = "PRS_CALLE_SECUNDARIA", length = 256)
	@Length(max = 256)
	public String getPrsCalleSecundaria() {
		return prsCalleSecundaria;
	}

	public void setPrsCalleSecundaria(String prsCalleSecundaria) {
		this.prsCalleSecundaria = prsCalleSecundaria;
	}

	@Column(name = "PRS_SECTOR_DOMICILIO", length = 256)
	@Length(max = 256)
	public String getPrsSectorDomicilio() {
		return prsSectorDomicilio;
	}

	public void setPrsSectorDomicilio(String prsSectorDomicilio) {
		this.prsSectorDomicilio = prsSectorDomicilio;
	}

	@Column(name = "PRS_NUMERO_CASA", length = 32)
	@Length(max = 10)
	public String getPrsNumeroCasa() {
		return prsNumeroCasa;
	}

	public void setPrsNumeroCasa(String prsNumeroCasa) {
		this.prsNumeroCasa = prsNumeroCasa;
	}

	@Column(name = "PRS_REFERENCIA_DOMICILIO", length = 256)
	@Length(max = 256)
	public String getPrsReferenciaDomicilio() {
		return prsReferenciaDomicilio;
	}

	public void setPrsReferenciaDomicilio(String prsReferenciaDomicilio) {
		this.prsReferenciaDomicilio = prsReferenciaDomicilio;
	}

	@Column(name = "PRS_CELULAR", length = 10)
	@Length(max = 10)
	public String getPrsCelular() {
		return prsCelular;
	}

	public void setPrsCelular(String prsCelular) {
		this.prsCelular = prsCelular;
	}

	
	@Column(name = "PRS_DISCAPACIDAD", precision = 22, scale = 0)
	public Integer getPrsDiscapacidad() {
		return this.prsDiscapacidad;
	}

	public void setPrsDiscapacidad(Integer prsDiscapacidad) {
		this.prsDiscapacidad = prsDiscapacidad;
	}
	
	@Column(name = "PRS_TIPO_DISCAPACIDAD", precision = 22, scale = 0)
	public Integer getPrsTipoDiscapacidad() {
		return this.prsTipoDiscapacidad;
	}

	public void setPrsTipoDiscapacidad(Integer prsTipoDiscapacidad) {
		this.prsTipoDiscapacidad = prsTipoDiscapacidad;
	}
	
	@Column(name = "PRS_CARNET_CONADIS", precision = 22, scale = 0)
	public Integer getPrsCarnetConadis() {
		return this.prsCarnetConadis;
	}

	public void setPrsCarnetConadis(Integer prsCarnetConadis) {
		this.prsCarnetConadis = prsCarnetConadis;
	}
	
	@Column(name = "PRS_PORCE_DISCAPACIDAD", precision = 22, scale = 0)
	public Integer getPrsPorceDiscapacidad() {
		return this.prsPorceDiscapacidad;
	}

	public void setPrsPorceDiscapacidad(Integer prsPorceDiscapacidad) {
		this.prsPorceDiscapacidad = prsPorceDiscapacidad;
	}
	
	@Column(name = "PRS_NUM_CARNET_CONADIS", length = 10)
	@Length(max = 10)
	public String getPrsNumCarnetConadis() {
		return prsNumCarnetConadis;
	}

	public void setPrsNumCarnetConadis(String prsNumCarnetConadis) {
		this.prsNumCarnetConadis = prsNumCarnetConadis;
	}
	
	
	@Column(name = "PRS_ESTADO_CIVIL", precision = 22, scale = 0)
	public Integer getPrsEstadoCivil() {
		return this.prsEstadoCivil;
	}

	public void setPrsEstadoCivil(Integer prsEstadoCivil) {
		this.prsEstadoCivil = prsEstadoCivil;
	}
	
	@Column(name = "PRS_FECHA_ACTUALIZACION_DATOS")
	public Timestamp getPrsFechaActualizacionDatos() {
		return this.prsFechaActualizacionDatos;
	}

	public void setPrsFechaActualizacionDatos(Timestamp prsFechaActualizacionDatos) {
		this.prsFechaActualizacionDatos = prsFechaActualizacionDatos;
	}
	
	@Column(name = "PRS_FECHA_VINCULACION_SEGURO")
	public Date getPrsFechaVinculacionSeguro() {
		return prsFechaVinculacionSeguro;
	}

	public void setPrsFechaVinculacionSeguro(Date prsFechaVinculacionSeguro) {
		this.prsFechaVinculacionSeguro = prsFechaVinculacionSeguro;
	}

	@Column(name = "PRS_FECHA_REGISTRO_SEGURO")
	public Timestamp getPrsFechaRegistroSeguro() {
		return prsFechaRegistroSeguro;
	}

	public void setPrsFechaRegistroSeguro(Timestamp prsFechaRegistroSeguro) {
		this.prsFechaRegistroSeguro = prsFechaRegistroSeguro;
	}

	@Column(name = "PRS_ESTADO_SEGURO")
	public Integer getPrsEstadoSeguro() {
		return prsEstadoSeguro;
	}
	
	public void setPrsEstadoSeguro(Integer prsEstadoSeguro) {
		this.prsEstadoSeguro = prsEstadoSeguro;
	}

	@Column(name = "PRS_FORMULARIO_SEGURO", length = 256)
	@Length(max = 256)
	public String getPrsFormularioSeguro() {
		return prsFormularioSeguro;
	}

	public void setPrsFormularioSeguro(String prsFormularioSeguro) {
		this.prsFormularioSeguro = prsFormularioSeguro;
	}

	@Column(name = "PRS_FECHA_FORMULARIO_SEGURO")
	public Timestamp getPrsFechaFormularioSeguro() {
		return prsFechaFormularioSeguro;
	}

	public void setPrsFechaFormularioSeguro(Timestamp prsFechaFormularioSeguro) {
		this.prsFechaFormularioSeguro = prsFechaFormularioSeguro;
	}

	@OneToMany( mappedBy = "fcdcPersona")
	public List<FichaDocente> getPrsFichaDocentes() {
		return this.prsFichaDocentes;
	}

	public void setPrsFichaDocentes(List<FichaDocente> prsFichaDocentes) {
		this.prsFichaDocentes = prsFichaDocentes;
	}

	@OneToMany( mappedBy = "fcemPersona")
	public List<FichaEmpleado> getPrsFichaEmpleados() {
		return this.prsFichaEmpleados;
	}

	public void setPrsFichaEmpleados(List<FichaEmpleado> prsFichaEmpleados) {
		this.prsFichaEmpleados = prsFichaEmpleados;
	}

	@OneToMany( mappedBy = "usrPersona")
	public List<Usuario> getPrsUsuarios() {
		return this.prsUsuarios;
	}

	public void setPrsUsuarios(List<Usuario> prsUsuarios) {
		this.prsUsuarios = prsUsuarios;
	}

	@OneToMany( mappedBy = "cncnPersona")
	public List<CandidatoContrato> getPrsCandidatoContratos() {
		return this.prsCandidatoContratos;
	}

	public void setPrsCandidatoContratos(List<CandidatoContrato> prsCandidatoContratos) {
		this.prsCandidatoContratos = prsCandidatoContratos;
	}

	@OneToMany( mappedBy = "fcesPersona")
	public List<FichaEstudiante> getPrsFichaEstudiantes() {
		return this.prsFichaEstudiantes;
	}

	public void setPrsFichaEstudiantes(List<FichaEstudiante> prsFichaEstudiantes) {
		this.prsFichaEstudiantes = prsFichaEstudiantes;
	}

	@OneToMany( mappedBy = "rfrPersona")
	public List<Referencia> getPrsReferencias() {
		return prsReferencias;
	}

	public void setPrsReferencias(List<Referencia> prsReferencias) {
		this.prsReferencias = prsReferencias;
	}

	

}
