package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * PlanificacionCronograma generated by hbm2java
 */
@Entity
@Table(name = "PLANIFICACION_CRONOGRAMA", schema = ConstantesJpa.SCHEMA)
public class PlanificacionCronograma implements java.io.Serializable {

	private static final long serialVersionUID = 2142047841292274132L;
	
	private int plcrId;
	private CronogramaProcesoFlujo plcrCronogramaProcesoFlujo;
	private Integer plcrEstado;
	private Timestamp plcrFechaInicio;
	private Timestamp plcrFechaFin;
	private List<FichaMatricula> plcrFichaMatriculas = new ArrayList<FichaMatricula>(0);
	private List<TipoNivelApertura> plcrTipoNivelAperturas = new ArrayList<TipoNivelApertura>(0);

	public PlanificacionCronograma() {
	}

	public PlanificacionCronograma(int plcrId) {
		this.plcrId = plcrId;
	}

	public PlanificacionCronograma(int plcrId, CronogramaProcesoFlujo plcrCronogramaProcesoFlujo, Integer plcrEstado,
			Timestamp plcrFechaInicio, Timestamp plcrFechaFin, List<FichaMatricula> plcrFichaMatriculas,
			List<TipoNivelApertura> plcrTipoNivelAperturas) {
		this.plcrId = plcrId;
		this.plcrCronogramaProcesoFlujo = plcrCronogramaProcesoFlujo;
		this.plcrEstado = plcrEstado;
		this.plcrFechaInicio = plcrFechaInicio;
		this.plcrFechaFin = plcrFechaFin;
		this.plcrFichaMatriculas = plcrFichaMatriculas;
		this.plcrTipoNivelAperturas = plcrTipoNivelAperturas;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PLCR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPlcrId() {
		return this.plcrId;
	}

	public void setPlcrId(int plcrId) {
		this.plcrId = plcrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRPRFL_ID")
	public CronogramaProcesoFlujo getPlcrCronogramaProcesoFlujo() {
		return this.plcrCronogramaProcesoFlujo;
	}

	public void setPlcrCronogramaProcesoFlujo(CronogramaProcesoFlujo plcrCronogramaProcesoFlujo) {
		this.plcrCronogramaProcesoFlujo = plcrCronogramaProcesoFlujo;
	}

	@Column(name = "PLCR_ESTADO", precision = 22, scale = 0)
	public Integer getPlcrEstado() {
		return this.plcrEstado;
	}

	public void setPlcrEstado(Integer plcrEstado) {
		this.plcrEstado = plcrEstado;
	}

	@Column(name = "PLCR_FECHA_INICIO")
	public Timestamp getPlcrFechaInicio() {
		return this.plcrFechaInicio;
	}

	public void setPlcrFechaInicio(Timestamp plcrFechaInicio) {
		this.plcrFechaInicio = plcrFechaInicio;
	}

	@Column(name = "PLCR_FECHA_FIN")
	public Timestamp getPlcrFechaFin() {
		return this.plcrFechaFin;
	}

	public void setPlcrFechaFin(Timestamp plcrFechaFin) {
		this.plcrFechaFin = plcrFechaFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcmtPlanificacionCronograma")
	public List<FichaMatricula> getPlcrFichaMatriculas() {
		return this.plcrFichaMatriculas;
	}

	public void setPlcrFichaMatriculas(List<FichaMatricula> plcrFichaMatriculas) {
		this.plcrFichaMatriculas = plcrFichaMatriculas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinvapPlanificacionCronograma")
	public List<TipoNivelApertura> getPlcrTipoNivelAperturas() {
		return this.plcrTipoNivelAperturas;
	}

	public void setPlcrTipoNivelAperturas(List<TipoNivelApertura> plcrTipoNivelAperturas) {
		this.plcrTipoNivelAperturas = plcrTipoNivelAperturas;
	}

}
