package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * PorcentajeGratuidad generated by hbm2java
 */
@Entity
@Table(name = "PORCENTAJE_GRATUIDAD", schema = ConstantesJpa.SCHEMA)
public class PorcentajeGratuidad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2791225786727369873L;
	private int prgrId;
	private TipoGratuidad prgrTipoGratuidad;
	private String prgrDescripcion;
	private BigDecimal prgrValor;
	private Integer prgrEstado;

	public PorcentajeGratuidad() {
	}

	public PorcentajeGratuidad(int prgrId) {
		this.prgrId = prgrId;
	}

	public PorcentajeGratuidad(int prgrId, TipoGratuidad prgrTipoGratuidad, String prgrDescripcion, BigDecimal prgrValor,
			Integer prgrEstado) {
		this.prgrId = prgrId;
		this.prgrTipoGratuidad = prgrTipoGratuidad;
		this.prgrDescripcion = prgrDescripcion;
		this.prgrValor = prgrValor;
		this.prgrEstado = prgrEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRGR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrgrId() {
		return this.prgrId;
	}

	public void setPrgrId(int prgrId) {
		this.prgrId = prgrId;
	}

	@ManyToOne
	@JoinColumn(name = "TIGR_ID")
	public TipoGratuidad getPrgrTipoGratuidad() {
		return this.prgrTipoGratuidad;
	}

	public void setPrgrTipoGratuidad(TipoGratuidad prgrTipoGratuidad) {
		this.prgrTipoGratuidad = prgrTipoGratuidad;
	}

	@Column(name = "PRGR_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPrgrDescripcion() {
		return this.prgrDescripcion;
	}

	public void setPrgrDescripcion(String prgrDescripcion) {
		this.prgrDescripcion = prgrDescripcion;
	}

	@Column(name = "PRGR_VALOR", precision = 6)
	public BigDecimal getPrgrValor() {
		return this.prgrValor;
	}

	public void setPrgrValor(BigDecimal prgrValor) {
		this.prgrValor = prgrValor;
	}

	@Column(name = "PRGR_ESTADO", precision = 22, scale = 0)
	public Integer getPrgrEstado() {
		return this.prgrEstado;
	}

	public void setPrgrEstado(Integer prgrEstado) {
		this.prgrEstado = prgrEstado;
	}

}
