package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Prerequisito generated by hbm2java
 */
@Entity
@Table(name = "PREREQUISITO", schema = ConstantesJpa.SCHEMA)
public class Prerequisito implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6960588595012066768L;
	private int prrId;
	private Materia prrMateriaPrerequisito;
	private Materia prrMateria;
	private Integer prrCodigo;
	private String prrDescripcion;
	private Integer prrEstado;

	public Prerequisito() {
	}

	public Prerequisito(int prrId) {
		this.prrId = prrId;
	}

	public Prerequisito(int prrId, Materia prrMateriaPrerequisito, Materia prrMateria, Integer prrCodigo,
			String prrDescripcion, Integer prrEstado) {
		this.prrId = prrId;
		this.prrMateriaPrerequisito = prrMateriaPrerequisito;
		this.prrMateria = prrMateria;
		this.prrCodigo = prrCodigo;
		this.prrDescripcion = prrDescripcion;
		this.prrEstado = prrEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrrId() {
		return this.prrId;
	}

	public void setPrrId(int prrId) {
		this.prrId = prrId;
	}

	@ManyToOne
	@JoinColumn(name = "MTR_PREREQUISITO_ID")
	public Materia getPrrMateriaPrerequisito() {
		return this.prrMateriaPrerequisito;
	}

	public void setPrrMateriaPrerequisito(Materia prrMateriaPrerequisito) {
		this.prrMateriaPrerequisito = prrMateriaPrerequisito;
	}

	@ManyToOne
	@JoinColumn(name = "MTR_ID")
	public Materia getPrrMateria() {
		return this.prrMateria;
	}

	public void setPrrMateria(Materia prrMateria) {
		this.prrMateria = prrMateria;
	}

	@Column(name = "PRR_CODIGO", precision = 22, scale = 0)
	public Integer getPrrCodigo() {
		return this.prrCodigo;
	}

	public void setPrrCodigo(Integer prrCodigo) {
		this.prrCodigo = prrCodigo;
	}

	@Column(name = "PRR_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPrrDescripcion() {
		return this.prrDescripcion;
	}

	public void setPrrDescripcion(String prrDescripcion) {
		this.prrDescripcion = prrDescripcion;
	}

	@Column(name = "PRR_ESTADO", precision = 22, scale = 0)
	public Integer getPrrEstado() {
		return this.prrEstado;
	}

	public void setPrrEstado(Integer prrEstado) {
		this.prrEstado = prrEstado;
	}

}
