package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ComprobantePago generated by hbm2java
 */
@Entity
@Table(name = "PROCESO_CALIFICACION", schema = ConstantesJpa.SCHEMA)
public class ProcesoCalificacion implements java.io.Serializable {

	private static final long serialVersionUID = -5088029760306617729L;
	
	private int prclId;
	private Timestamp prclFecha;
	private Integer prclTipoProceso;
	private String prclObservacion;
	
	private Float prclNota1;
	private Float prclNota2;
	private Float prclExamen;
	private Float prclSupletorio;
	private Float prclAsistencia1;
	private Float prclAsistencia2;
	private Float prclTotalAsistencia1;
	private Float prclTotalAsistencia2;
	private Float prclPromedioNotas;
	private Float prclPromedioAsistencia;
	private Float prclAsistenciaTotal;
	private Float prclParamRecuperacion1;
	private Float prclParamRecuperacion2;
	private Float prclNotaFinalSemestre;	
	private Float prclAsistenciaDocente1;
	private Float prclAsistenciaDocente2;
	private Timestamp prclFechaNota2;
	private Timestamp prclFechaRecuperacion;
	private String prclObservacion2;
	private String prclObservacion3;
	private Float prclSumaP1P2;
	private Float prclAsistenciaTotalDoc;
	
	private Calificacion prclCalificacion; //Objeto Calificacion
	private CalificacionModulo prclCalificacionModulo; //Objeto CalificacionModulo
	public ProcesoCalificacion() {
	}

	public ProcesoCalificacion(int prclId) {
		this.prclId = prclId;
	}


	
	public ProcesoCalificacion(int prclId, Timestamp prclFecha, Integer prclTipoProceso, String prclObservacion,
			Float prclNota1, Float prclNota2, Float prclExamen, Float prclSupletorio, Float prclAsistencia1,
			Float prclAsistencia2, Float prclTotalAsistencia1, Float prclTotalAsistencia2, Float prclPromedioNotas,
			Float prclPromedioAsistencia, Float prclAsistenciaTotal, Float prclParamRecuperacion1,
			Float prclParamRecuperacion2, Float prclNotaFinalSemestre, Float prclAsistenciaDocente1,
			Float prclAsistenciaDocente2, Timestamp prclFechaNota2, Timestamp prclFechaRecuperacion,
			String prclObservacion2, String prclObservacion3, Float prclSumaP1P2, Float prclAsistenciaTotalDoc,
			Calificacion prclCalificacion) {
		this.prclId = prclId;
		this.prclFecha = prclFecha;
		this.prclTipoProceso = prclTipoProceso;
		this.prclObservacion = prclObservacion;
		this.prclNota1 = prclNota1;
		this.prclNota2 = prclNota2;
		this.prclExamen = prclExamen;
		this.prclSupletorio = prclSupletorio;
		this.prclAsistencia1 = prclAsistencia1;
		this.prclAsistencia2 = prclAsistencia2;
		this.prclTotalAsistencia1 = prclTotalAsistencia1;
		this.prclTotalAsistencia2 = prclTotalAsistencia2;
		this.prclPromedioNotas = prclPromedioNotas;
		this.prclPromedioAsistencia = prclPromedioAsistencia;
		this.prclAsistenciaTotal = prclAsistenciaTotal;
		this.prclParamRecuperacion1 = prclParamRecuperacion1;
		this.prclParamRecuperacion2 = prclParamRecuperacion2;
		this.prclNotaFinalSemestre = prclNotaFinalSemestre;
		this.prclAsistenciaDocente1 = prclAsistenciaDocente1;
		this.prclAsistenciaDocente2 = prclAsistenciaDocente2;
		this.prclFechaNota2 = prclFechaNota2;
		this.prclFechaRecuperacion = prclFechaRecuperacion;
		this.prclObservacion2 = prclObservacion2;
		this.prclObservacion3 = prclObservacion3;
		this.prclSumaP1P2 = prclSumaP1P2;
		this.prclAsistenciaTotalDoc = prclAsistenciaTotalDoc;
		this.prclCalificacion = prclCalificacion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRCL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrclId() {
		return this.prclId;
	}

	public void setPrclId(int prclId) {
		this.prclId = prclId;
	}

	
	@Column(name = "PRCL_FECHA")
	public Timestamp getPrclFecha() {
		return this.prclFecha;
	}

	public void setPrclFecha(Timestamp prclFecha) {
		this.prclFecha = prclFecha;
	}

	

	@Column(name = "PRCL_TIPO_PROCESO", precision = 22, scale = 0)
	public Integer getPrclTipoProceso() {
		return this.prclTipoProceso;
	}

	public void setPrclTipoProceso(Integer prclTipoProceso) {
		this.prclTipoProceso = prclTipoProceso;
	}

	@Column(name = "PRCL_OBSERVACION", length = 1024)
	@Length(max = 1024)
	public String getPrclObservacion() {
		return this.prclObservacion;
	}

	public void setPrclObservacion(String prclObservacion) {
		this.prclObservacion = prclObservacion;
	}
	
	// ManyToOne  con tabla Calificacion
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLF_ID")
	public Calificacion getPrclCalificacion() {
		return this.prclCalificacion;
	}

	public void setPrclCalificacion(Calificacion prclCalificacion) {
		this.prclCalificacion = prclCalificacion;
	}

	@Column(name="PRCL_NOTA1", precision=126)
	public Float getPrclNota1() {
		return prclNota1;
	}

	public void setPrclNota1(Float prclNota1) {
		this.prclNota1 = prclNota1;
	}

	@Column(name="PRCL_NOTA2", precision=126)
	public Float getPrclNota2() {
		return prclNota2;
	}

	public void setPrclNota2(Float prclNota2) {
		this.prclNota2 = prclNota2;
	}

	@Column(name="PRCL_EXAMEN", precision=126)
	public Float getPrclExamen() {
		return prclExamen;
	}

	public void setPrclExamen(Float prclExamen) {
		this.prclExamen = prclExamen;
	}

	@Column(name="PRCL_SUPLETORIO", precision=126)
	public Float getPrclSupletorio() {
		return prclSupletorio;
	}

	public void setPrclSupletorio(Float prclSupletorio) {
		this.prclSupletorio = prclSupletorio;
	}

	@Column(name="PRCL_ASISTENCIA1", precision=126)
	public Float getPrclAsistencia1() {
		return prclAsistencia1;
	}

	public void setPrclAsistencia1(Float prclAsistencia1) {
		this.prclAsistencia1 = prclAsistencia1;
	}

	@Column(name="PRCL_ASISTENCIA2", precision=126)
	public Float getPrclAsistencia2() {
		return prclAsistencia2;
	}

	public void setPrclAsistencia2(Float prclAsistencia2) {
		this.prclAsistencia2 = prclAsistencia2;
	}

	@Column(name="PRCL_TOTAL_ASISTENCIA1", precision=126)
	public Float getPrclTotalAsistencia1() {
		return prclTotalAsistencia1;
	}

	public void setPrclTotalAsistencia1(Float prclTotalAsistencia1) {
		this.prclTotalAsistencia1 = prclTotalAsistencia1;
	}

	@Column(name="PRCL_TOTAL_ASISTENCIA2", precision=126)
	public Float getPrclTotalAsistencia2() {
		return prclTotalAsistencia2;
	}

	public void setPrclTotalAsistencia2(Float prclTotalAsistencia2) {
		this.prclTotalAsistencia2 = prclTotalAsistencia2;
	}

	@Column(name="PRCL_PROMEDIO_NOTAS", precision=126)
	public Float getPrclPromedioNotas() {
		return prclPromedioNotas;
	}

	public void setPrclPromedioNotas(Float prclPromedioNotas) {
		this.prclPromedioNotas = prclPromedioNotas;
	}

	@Column(name="PRCL_PROMEDIO_ASISTENCIA", precision=126)
	public Float getPrclPromedioAsistencia() {
		return prclPromedioAsistencia;
	}

	public void setPrclPromedioAsistencia(Float prclPromedioAsistencia) {
		this.prclPromedioAsistencia = prclPromedioAsistencia;
	}

	@Column(name="PRCL_ASISTENCIA_TOTAL", precision=126)
	public Float getPrclAsistenciaTotal() {
		return prclAsistenciaTotal;
	}

	public void setPrclAsistenciaTotal(Float prclAsistenciaTotal) {
		this.prclAsistenciaTotal = prclAsistenciaTotal;
	}

	@Column(name="PRCL_PARAM_RECUPERACION1", precision=126)
	public Float getPrclParamRecuperacion1() {
		return prclParamRecuperacion1;
	}

	public void setPrclParamRecuperacion1(Float prclParamRecuperacion1) {
		this.prclParamRecuperacion1 = prclParamRecuperacion1;
	}

	@Column(name="PRCL_PARAM_RECUPERACION2", precision=126)
	public Float getPrclParamRecuperacion2() {
		return prclParamRecuperacion2;
	}

	public void setPrclParamRecuperacion2(Float prclParamRecuperacion2) {
		this.prclParamRecuperacion2 = prclParamRecuperacion2;
	}

	@Column(name="PRCL_NOTA_FINAL_SEMESTRE", precision=126)
	public Float getPrclNotaFinalSemestre() {
		return prclNotaFinalSemestre;
	}

	public void setPrclNotaFinalSemestre(Float prclNotaFinalSemestre) {
		this.prclNotaFinalSemestre = prclNotaFinalSemestre;
	}

	@Column(name="PRCL_ASISTENCIA_DOCENTE1", precision=126)
	public Float getPrclAsistenciaDocente1() {
		return prclAsistenciaDocente1;
	}

	public void setPrclAsistenciaDocente1(Float prclAsistenciaDocente1) {
		this.prclAsistenciaDocente1 = prclAsistenciaDocente1;
	}

	@Column(name="PRCL_ASISTENCIA_DOCENTE2", precision=126)
	public Float getPrclAsistenciaDocente2() {
		return prclAsistenciaDocente2;
	}

	public void setPrclAsistenciaDocente2(Float prclAsistenciaDocente2) {
		this.prclAsistenciaDocente2 = prclAsistenciaDocente2;
	}

	
	@Column(name = "PRCL_FECHA_NOTA2")
	public Timestamp getPrclFechaNota2() {
		return prclFechaNota2;
	}

	public void setPrclFechaNota2(Timestamp prclFechaNota2) {
		this.prclFechaNota2 = prclFechaNota2;
	}

	
	@Column(name = "PRCL_FECHA_RECUPERACION")
	public Timestamp getPrclFechaRecuperacion() {
		return prclFechaRecuperacion;
	}

	public void setPrclFechaRecuperacion(Timestamp prclFechaRecuperacion) {
		this.prclFechaRecuperacion = prclFechaRecuperacion;
	}

	
	@Column(name = "PRCL_OBSERVACION2", length = 1024)
	@Length(max = 1024)
	public String getPrclObservacion2() {
		return prclObservacion2;
	}

	public void setPrclObservacion2(String prclObservacion2) {
		this.prclObservacion2 = prclObservacion2;
	}

	
	@Column(name = "PRCL_OBSERVACION3", length = 1024)
	@Length(max = 102)
	public String getPrclObservacion3() {
		return prclObservacion3;
	}

	public void setPrclObservacion3(String prclObservacion3) {
		this.prclObservacion3 = prclObservacion3;
	}

	@Column(name="PRCL_SUMA_P1_P2", precision=126)
	public Float getPrclSumaP1P2() {
		return prclSumaP1P2;
	}

	public void setPrclSumaP1P2(Float prclSumaP1P2) {
		this.prclSumaP1P2 = prclSumaP1P2;
	}

	@Column(name="PRCL_ASISTENCIA_TOTAL_DOC", precision=126)
	public Float getPrclAsistenciaTotalDoc() {
		return prclAsistenciaTotalDoc;
	}

	public void setPrclAsistenciaTotalDoc(Float prclAsistenciaTotalDoc) {
		this.prclAsistenciaTotalDoc = prclAsistenciaTotalDoc;
	}

	// ManyToOne  con tabla Calificacion
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLMD_ID" )
	public CalificacionModulo getPrclCalificacionModulo() {
		return prclCalificacionModulo;
	}

	public void setPrclCalificacionModulo(CalificacionModulo prclCalificacionModulo) {
		this.prclCalificacionModulo = prclCalificacionModulo;
	}
	
	
	
	
}
