package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ProcesoFlujo generated by hbm2java
 */
@Entity
@Table(name = "PROCESO_FLUJO", schema = ConstantesJpa.SCHEMA)
public class ProcesoFlujo implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7303387286065810359L;
	private int prflId;
	private String prflDescripcion;
	private Integer prflEstado;
	private List<CronogramaProcesoFlujo> prflCronogramaProcesoFlujos = new ArrayList<CronogramaProcesoFlujo>(0);
	private List<PlanificacionEvaluacion> prflListPlanificacionEvaluacion;

	public ProcesoFlujo() {
	}

	public ProcesoFlujo(int prflId) {
		this.prflId = prflId;
	}

	public ProcesoFlujo(int prflId, String prflDescripcion, Integer prflEstado,
			List<CronogramaProcesoFlujo> prflCronogramaProcesoFlujos) {
		this.prflId = prflId;
		this.prflDescripcion = prflDescripcion;
		this.prflEstado = prflEstado;
		this.prflCronogramaProcesoFlujos = prflCronogramaProcesoFlujos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "PRFL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrflId() {
		return this.prflId;
	}

	public void setPrflId(int prflId) {
		this.prflId = prflId;
	}

	@Column(name = "PRFL_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPrflDescripcion() {
		return this.prflDescripcion;
	}

	public void setPrflDescripcion(String prflDescripcion) {
		this.prflDescripcion = prflDescripcion;
	}

	@Column(name = "PRFL_ESTADO", precision = 22, scale = 0)
	public Integer getPrflEstado() {
		return this.prflEstado;
	}

	public void setPrflEstado(Integer prflEstado) {
		this.prflEstado = prflEstado;
	}

	@OneToMany(mappedBy = "crprProcesoFlujo")
	public List<CronogramaProcesoFlujo> getPrflCronogramaProcesoFlujos() {
		return this.prflCronogramaProcesoFlujos;
	}

	public void setPrflCronogramaProcesoFlujos(List<CronogramaProcesoFlujo> prflCronogramaProcesoFlujos) {
		this.prflCronogramaProcesoFlujos = prflCronogramaProcesoFlujos;
	}

	@OneToMany(mappedBy="plevProcesoFlujo")
	public List<PlanificacionEvaluacion> getPrflListPlanificacionEvaluacion() {
		return prflListPlanificacionEvaluacion;
	}

	public void setPrflListPlanificacionEvaluacion(List<PlanificacionEvaluacion> prflListPlanificacionEvaluacion) {
		this.prflListPlanificacionEvaluacion = prflListPlanificacionEvaluacion;
	}

}
