package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "PROCESO", schema = ConstantesJpa.SCHEMA)
public class Proceso implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 276583503189995192L;
	private int prcId;
	private String prcDescripcion;
	private List<Serie> prcSeries = new ArrayList<Serie>(0);

	public Proceso() {
	}

	public Proceso(int prcId) {
		this.prcId = prcId;
	}

	public Proceso(int prcId, String prcDescripcion, List<Serie> prcSeries) {
		this.prcId = prcId;
		this.prcDescripcion = prcDescripcion;
		this.prcSeries = prcSeries;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrcId() {
		return this.prcId;
	}

	public void setPrcId(int prcId) {
		this.prcId = prcId;
	}

	@Column(name = "PRC_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPrcDescripcion() {
		return this.prcDescripcion;
	}

	public void setPrcDescripcion(String prcDescripcion) {
		this.prcDescripcion = prcDescripcion;
	}

	@OneToMany( mappedBy = "serProceso")
	public List<Serie> getPrcSeries() {
		return this.prcSeries;
	}

	public void setPrcSeries(List<Serie> prcSeries) {
		this.prcSeries = prcSeries;
	}

}
