package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ProcesoEstudiante generated by hbm2java
 */
@Entity
@Table(name = "PROCESO_ESTUDIANTE", schema = ConstantesJpa.SCHEMA)
public class ProcesoEstudiante implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4192987624802341309L;
	private int presId;
	private FichaEstudiante presFichaEstudiante;
	private String presDescripcion;
	private Integer presTipo;
	private Integer presEstado;
	private Timestamp presFechaEjecucion;

	public ProcesoEstudiante() {
	}

	public ProcesoEstudiante(int presId) {
		this.presId = presId;
	}

	public ProcesoEstudiante(int presId, FichaEstudiante presFichaEstudiante, String presDescripcion, Integer presTipo,
			Integer presEstado, Timestamp presFechaEjecucion) {
		this.presId = presId;
		this.presFichaEstudiante = presFichaEstudiante;
		this.presDescripcion = presDescripcion;
		this.presTipo = presTipo;
		this.presEstado = presEstado;
		this.presFechaEjecucion = presFechaEjecucion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRES_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPresId() {
		return this.presId;
	}

	public void setPresId(int presId) {
		this.presId = presId;
	}

	@ManyToOne
	@JoinColumn(name = "FCES_ID")
	public FichaEstudiante getPresFichaEstudiante() {
		return this.presFichaEstudiante;
	}

	public void setPresFichaEstudiante(FichaEstudiante presFichaEstudiante) {
		this.presFichaEstudiante = presFichaEstudiante;
	}

	@Column(name = "PRES_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getPresDescripcion() {
		return this.presDescripcion;
	}

	public void setPresDescripcion(String presDescripcion) {
		this.presDescripcion = presDescripcion;
	}

	@Column(name = "PRES_TIPO", precision = 22, scale = 0)
	public Integer getPresTipo() {
		return this.presTipo;
	}

	public void setPresTipo(Integer presTipo) {
		this.presTipo = presTipo;
	}

	@Column(name = "PRES_ESTADO", precision = 22, scale = 0)
	public Integer getPresEstado() {
		return this.presEstado;
	}

	public void setPresEstado(Integer presEstado) {
		this.presEstado = presEstado;
	}

	@Column(name = "PRES_FECHA_EJECUCION")
	public Timestamp getPresFechaEjecucion() {
		return this.presFechaEjecucion;
	}

	public void setPresFechaEjecucion(Timestamp presFechaEjecucion) {
		this.presFechaEjecucion = presFechaEjecucion;
	}

}
