package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * ProcesoTramiteContrato generated by hbm2java
 */
@Entity
@Table(name = "PROCESO_TRAMITE_CONTRATO", schema = ConstantesJpa.SCHEMA)
public class ProcesoTramiteContrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3230419233500067735L;
	private int prtrcnId;
	private DetalleTramiteContrato prtrcnDetalleTramiteContrato;
	private Integer prtrcnTipoProceso;
	private Timestamp prtrcnFechaEjecucion;
	private Integer prtrcnResultadoProceso;
	private List<AsignaPresupuesto> prtrcnAsignaPresupuestos = new ArrayList<AsignaPresupuesto>(0);
	private List<CandidatoContrato> prtrcnCandidatoContratos = new ArrayList<CandidatoContrato>(0);
	private List<Turnero> prtrcnTurneros = new ArrayList<Turnero>(0);
	private List<ApruebaSolicitud> prtrcnApruebaSolicituds = new ArrayList<ApruebaSolicitud>(0);
	private List<InformeTecnico> prtrcnInformeTecnicos = new ArrayList<InformeTecnico>(0);
	private List<CargaHorariaContrato> prtrcnCargaHorariaContratos = new ArrayList<CargaHorariaContrato>(0);
	private List<Requisito> prtrcnRequisitos = new ArrayList<Requisito>(0);

	public ProcesoTramiteContrato() {
	}

	public ProcesoTramiteContrato(int prtrcnId) {
		this.prtrcnId = prtrcnId;
	}

	public ProcesoTramiteContrato(int prtrcnId, DetalleTramiteContrato prtrcnDetalleTramiteContrato,
			Integer prtrcnTipoProceso, Timestamp prtrcnFechaEjecucion, Integer prtrcnResultadoProceso,
			List<AsignaPresupuesto> prtrcnAsignaPresupuestos, List<CandidatoContrato> prtrcnCandidatoContratos, List<Turnero> prtrcnTurneros,
			List<ApruebaSolicitud> prtrcnApruebaSolicituds, List<InformeTecnico> prtrcnInformeTecnicos,
			List<CargaHorariaContrato> prtrcnCargaHorariaContratos, List<Requisito> prtrcnRequisitos) {
		this.prtrcnId = prtrcnId;
		this.prtrcnDetalleTramiteContrato = prtrcnDetalleTramiteContrato;
		this.prtrcnTipoProceso = prtrcnTipoProceso;
		this.prtrcnFechaEjecucion = prtrcnFechaEjecucion;
		this.prtrcnResultadoProceso = prtrcnResultadoProceso;
		this.prtrcnAsignaPresupuestos = prtrcnAsignaPresupuestos;
		this.prtrcnCandidatoContratos = prtrcnCandidatoContratos;
		this.prtrcnTurneros = prtrcnTurneros;
		this.prtrcnApruebaSolicituds = prtrcnApruebaSolicituds;
		this.prtrcnInformeTecnicos = prtrcnInformeTecnicos;
		this.prtrcnCargaHorariaContratos = prtrcnCargaHorariaContratos;
		this.prtrcnRequisitos = prtrcnRequisitos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRTRCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrtrcnId() {
		return this.prtrcnId;
	}

	public void setPrtrcnId(int prtrcnId) {
		this.prtrcnId = prtrcnId;
	}

	@ManyToOne
	@JoinColumn(name = "DTTRCN_ID")
	public DetalleTramiteContrato getPrtrcnDetalleTramiteContrato() {
		return this.prtrcnDetalleTramiteContrato;
	}

	public void setPrtrcnDetalleTramiteContrato(DetalleTramiteContrato prtrcnDetalleTramiteContrato) {
		this.prtrcnDetalleTramiteContrato = prtrcnDetalleTramiteContrato;
	}

	@Column(name = "PRTRCN_TIPO_PROCESO", precision = 22, scale = 0)
	public Integer getPrtrcnTipoProceso() {
		return this.prtrcnTipoProceso;
	}

	public void setPrtrcnTipoProceso(Integer prtrcnTipoProceso) {
		this.prtrcnTipoProceso = prtrcnTipoProceso;
	}

	@Column(name = "PRTRCN_FECHA_EJECUCION")
	public Timestamp getPrtrcnFechaEjecucion() {
		return this.prtrcnFechaEjecucion;
	}

	public void setPrtrcnFechaEjecucion(Timestamp prtrcnFechaEjecucion) {
		this.prtrcnFechaEjecucion = prtrcnFechaEjecucion;
	}

	@Column(name = "PRTRCN_RESULTADO_PROCESO", precision = 22, scale = 0)
	public Integer getPrtrcnResultadoProceso() {
		return this.prtrcnResultadoProceso;
	}

	public void setPrtrcnResultadoProceso(Integer prtrcnResultadoProceso) {
		this.prtrcnResultadoProceso = prtrcnResultadoProceso;
	}

	@OneToMany( mappedBy = "asprProcesoTramiteContrato")
	public List<AsignaPresupuesto> getPrtrcnAsignaPresupuestos() {
		return this.prtrcnAsignaPresupuestos;
	}

	public void setPrtrcnAsignaPresupuestos(List<AsignaPresupuesto> prtrcnAsignaPresupuestos) {
		this.prtrcnAsignaPresupuestos = prtrcnAsignaPresupuestos;
	}

	@OneToMany( mappedBy = "cncnProcesoTramiteContrato")
	public List<CandidatoContrato> getPrtrcnCandidatoContratos() {
		return this.prtrcnCandidatoContratos;
	}

	public void setPrtrcnCandidatoContratos(List<CandidatoContrato> prtrcnCandidatoContratos) {
		this.prtrcnCandidatoContratos = prtrcnCandidatoContratos;
	}

	@OneToMany( mappedBy = "trnProcesoTramiteContrato")
	public List<Turnero> getPrtrcnTurneros() {
		return this.prtrcnTurneros;
	}

	public void setPrtrcnTurneros(List<Turnero> prtrcnTurneros) {
		this.prtrcnTurneros = prtrcnTurneros;
	}

	@OneToMany( mappedBy = "apslProcesoTramiteContrato")
	public List<ApruebaSolicitud> getPrtrcnApruebaSolicituds() {
		return this.prtrcnApruebaSolicituds;
	}

	public void setPrtrcnApruebaSolicituds(List<ApruebaSolicitud> prtrcnApruebaSolicituds) {
		this.prtrcnApruebaSolicituds = prtrcnApruebaSolicituds;
	}

	@OneToMany( mappedBy = "intcProcesoTramiteContrato")
	public List<InformeTecnico> getPrtrcnInformeTecnicos() {
		return this.prtrcnInformeTecnicos;
	}

	public void setPrtrcnInformeTecnicos(List<InformeTecnico> prtrcnInformeTecnicos) {
		this.prtrcnInformeTecnicos = prtrcnInformeTecnicos;
	}

	@OneToMany( mappedBy = "crhrProcesoTramiteContrato")
	public List<CargaHorariaContrato> getPrtrcnCargaHorariaContratos() {
		return this.prtrcnCargaHorariaContratos;
	}

	public void setPrtrcnCargaHorariaContratos(List<CargaHorariaContrato> prtrcnCargaHorariaContratos) {
		this.prtrcnCargaHorariaContratos = prtrcnCargaHorariaContratos;
	}

	@OneToMany( mappedBy = "rqsProcesoTramiteContrato")
	public List<Requisito> getPrtrcnRequisitos() {
		return this.prtrcnRequisitos;
	}

	public void setPrtrcnRequisitos(List<Requisito> prtrcnRequisitos) {
		this.prtrcnRequisitos = prtrcnRequisitos;
	}

}
