package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Proyeccion generated by hbm2java
 */
@Entity
@Table(name = "PROYECCION", schema = ConstantesJpa.SCHEMA)
public class Proyeccion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2121828760297575422L;
	private int pryId;
	private PeriodoAcademico pryPeriodoAcademico;
	private Excedente pryExcedente;
	private MallaCurricularMateria pryMallaCurricularMateria;
	private Integer pryNumNuevo;
	private Integer pryNumRepetido;

	public Proyeccion() {
	}

	public Proyeccion(int pryId) {
		this.pryId = pryId;
	}

	public Proyeccion(int pryId, PeriodoAcademico pryPeriodoAcademico, Excedente pryExcedente,
			MallaCurricularMateria pryMallaCurricularMateria, Integer pryNumNuevo, Integer pryNumRepetido) {
		this.pryId = pryId;
		this.pryPeriodoAcademico = pryPeriodoAcademico;
		this.pryExcedente = pryExcedente;
		this.pryMallaCurricularMateria = pryMallaCurricularMateria;
		this.pryNumNuevo = pryNumNuevo;
		this.pryNumRepetido = pryNumRepetido;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PRY_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPryId() {
		return this.pryId;
	}

	public void setPryId(int pryId) {
		this.pryId = pryId;
	}

	@ManyToOne
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getPryPeriodoAcademico() {
		return this.pryPeriodoAcademico;
	}

	public void setPryPeriodoAcademico(PeriodoAcademico pryPeriodoAcademico) {
		this.pryPeriodoAcademico = pryPeriodoAcademico;
	}

	@ManyToOne
	@JoinColumn(name = "EXC_ID")
	public Excedente getPryExcedente() {
		return this.pryExcedente;
	}

	public void setPryExcedente(Excedente pryExcedente) {
		this.pryExcedente = pryExcedente;
	}

	@ManyToOne
	@JoinColumn(name = "MLCRMT_ID")
	public MallaCurricularMateria getPryMallaCurricularMateria() {
		return this.pryMallaCurricularMateria;
	}

	public void setPryMallaCurricularMateria(MallaCurricularMateria pryMallaCurricularMateria) {
		this.pryMallaCurricularMateria = pryMallaCurricularMateria;
	}

	@Column(name = "PRY_NUM_NUEVO", precision = 22, scale = 0)
	public Integer getPryNumNuevo() {
		return this.pryNumNuevo;
	}

	public void setPryNumNuevo(Integer pryNumNuevo) {
		this.pryNumNuevo = pryNumNuevo;
	}

	@Column(name = "PRY_NUM_REPETIDO", precision = 22, scale = 0)
	public Integer getPryNumRepetido() {
		return this.pryNumRepetido;
	}

	public void setPryNumRepetido(Integer pryNumRepetido) {
		this.pryNumRepetido = pryNumRepetido;
	}

}
