package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Puesto generated by hbm2java
 */
@Entity
@Table(name = "PUESTO", schema = ConstantesJpa.SCHEMA)
public class Puesto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8154443425282511805L;
	private int pstId;
	private Serie pstSerie;
	private TiempoDedicacion pstTiempoDedicacion;
	private TipoPuesto pstTipoPuesto;
	private GrupoOcupacional pstGrupoOcupacional;
	private String pstDenominacion;
	private Integer pstEstado;
	private Integer pstAmbito;
	private String pstCodigo;
	private Integer pstNivel;
	private String pstMision;
	private String pstResponsabilidad;
	private String pstDescripcionExperiencia;
	private String pstInterfaz;
	private Date pstFechaCreacion;
	private Integer pstNivelRangoGradual;
	private Integer pstCategoriaDocente;
	private List<FuncionPuesto> pstFuncionPuestos = new ArrayList<FuncionPuesto>(0);
	private List<ActividadPuesto> pstActividadPuestos = new ArrayList<ActividadPuesto>(0);
	private List<InstruccionPuesto> pstInstruccionPuestos = new ArrayList<InstruccionPuesto>(0);
	private List<CompetenciaPuesto> pstCompetenciaPuestos = new ArrayList<CompetenciaPuesto>(0);
	private List<DestrezaPuesto> pstDestrezaPuestos = new ArrayList<DestrezaPuesto>(0);
	private List<DetallePuesto> pstDetallePuestos = new ArrayList<DetallePuesto>(0);
	private List<PuestoAreaConocimiento> pstPuestoAreaConocimientos = new ArrayList<PuestoAreaConocimiento>(0);
	private List<ConocimientoPuesto> pstConocimientoPuestos = new ArrayList<ConocimientoPuesto>(0);

	public Puesto() {
	}

	public Puesto(int pstId) {
		this.pstId = pstId;
	}

	public Puesto(int pstId, Serie pstSerie, TiempoDedicacion pstTiempoDedicacion, TipoPuesto pstTipoPuesto,
			GrupoOcupacional pstGrupoOcupacional, String pstDenominacion, Integer pstEstado, Integer pstAmbito,
			String pstCodigo, Integer pstNivel, String pstMision, String pstResponsabilidad,
			String pstDescripcionExperiencia, String pstInterfaz, Date pstFechaCreacion,
			Integer pstNivelRangoGradual, Integer pstCategoriaDocente, List<FuncionPuesto> pstFuncionPuestos, List<ActividadPuesto> pstActividadPuestos,
			List<InstruccionPuesto> pstInstruccionPuestos, List<CompetenciaPuesto> pstCompetenciaPuestos,
			List<DestrezaPuesto> pstDestrezaPuestos, List<DetallePuesto> pstDetallePuestos,
			List<PuestoAreaConocimiento> pstPuestoAreaConocimientos, List<ConocimientoPuesto> pstConocimientoPuestos) {
		this.pstId = pstId;
		this.pstSerie = pstSerie;
		this.pstTiempoDedicacion = pstTiempoDedicacion;
		this.pstTipoPuesto = pstTipoPuesto;
		this.pstGrupoOcupacional = pstGrupoOcupacional;
		this.pstDenominacion = pstDenominacion;
		this.pstEstado = pstEstado;
		this.pstAmbito = pstAmbito;
		this.pstCodigo = pstCodigo;
		this.pstNivel = pstNivel;
		this.pstMision = pstMision;
		this.pstResponsabilidad = pstResponsabilidad;
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
		this.pstInterfaz = pstInterfaz;
		this.pstFechaCreacion = pstFechaCreacion;
		this.pstNivelRangoGradual = pstNivelRangoGradual;
		this.pstCategoriaDocente = pstCategoriaDocente;
		this.pstFuncionPuestos = pstFuncionPuestos;
		this.pstActividadPuestos = pstActividadPuestos;
		this.pstInstruccionPuestos = pstInstruccionPuestos;
		this.pstCompetenciaPuestos = pstCompetenciaPuestos;
		this.pstDestrezaPuestos = pstDestrezaPuestos;
		this.pstDetallePuestos = pstDetallePuestos;
		this.pstPuestoAreaConocimientos = pstPuestoAreaConocimientos;
		this.pstConocimientoPuestos = pstConocimientoPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "PST_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPstId() {
		return this.pstId;
	}

	public void setPstId(int pstId) {
		this.pstId = pstId;
	}

	@ManyToOne
	@JoinColumn(name = "SER_ID")
	public Serie getPstSerie() {
		return this.pstSerie;
	}

	public void setPstSerie(Serie pstSerie) {
		this.pstSerie = pstSerie;
	}

	@ManyToOne
	@JoinColumn(name = "TMDD_ID")
	public TiempoDedicacion getPstTiempoDedicacion() {
		return this.pstTiempoDedicacion;
	}

	public void setPstTiempoDedicacion(TiempoDedicacion pstTiempoDedicacion) {
		this.pstTiempoDedicacion = pstTiempoDedicacion;
	}

	@ManyToOne
	@JoinColumn(name = "TIPS_ID")
	public TipoPuesto getPstTipoPuesto() {
		return this.pstTipoPuesto;
	}

	public void setPstTipoPuesto(TipoPuesto pstTipoPuesto) {
		this.pstTipoPuesto = pstTipoPuesto;
	}

	@ManyToOne
	@JoinColumn(name = "GROC_ID")
	public GrupoOcupacional getPstGrupoOcupacional() {
		return this.pstGrupoOcupacional;
	}

	public void setPstGrupoOcupacional(GrupoOcupacional pstGrupoOcupacional) {
		this.pstGrupoOcupacional = pstGrupoOcupacional;
	}

	@Column(name = "PST_DENOMINACION", length = 256)
	@Length(max = 256)
	public String getPstDenominacion() {
		return this.pstDenominacion;
	}

	public void setPstDenominacion(String pstDenominacion) {
		this.pstDenominacion = pstDenominacion;
	}

	@Column(name = "PST_ESTADO", precision = 22, scale = 0)
	public Integer getPstEstado() {
		return this.pstEstado;
	}

	public void setPstEstado(Integer pstEstado) {
		this.pstEstado = pstEstado;
	}

	@Column(name = "PST_AMBITO", precision = 22, scale = 0)
	public Integer getPstAmbito() {
		return this.pstAmbito;
	}

	public void setPstAmbito(Integer pstAmbito) {
		this.pstAmbito = pstAmbito;
	}

	@Column(name = "PST_CODIGO", length = 256)
	@Length(max = 256)
	public String getPstCodigo() {
		return this.pstCodigo;
	}

	public void setPstCodigo(String pstCodigo) {
		this.pstCodigo = pstCodigo;
	}

	@Column(name = "PST_NIVEL", precision = 22, scale = 0)
	public Integer getPstNivel() {
		return this.pstNivel;
	}

	public void setPstNivel(Integer pstNivel) {
		this.pstNivel = pstNivel;
	}

	@Column(name = "PST_MISION", length = 512)
	@Length(max = 512)
	public String getPstMision() {
		return this.pstMision;
	}

	public void setPstMision(String pstMision) {
		this.pstMision = pstMision;
	}

	@Column(name = "PST_RESPONSABILIDAD", length = 512)
	@Length(max = 512)
	public String getPstResponsabilidad() {
		return this.pstResponsabilidad;
	}

	public void setPstResponsabilidad(String pstResponsabilidad) {
		this.pstResponsabilidad = pstResponsabilidad;
	}

	@Column(name = "PST_DESCRIPCION_EXPERIENCIA", length = 512)
	@Length(max = 512)
	public String getPstDescripcionExperiencia() {
		return this.pstDescripcionExperiencia;
	}

	public void setPstDescripcionExperiencia(String pstDescripcionExperiencia) {
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
	}

	@Column(name = "PST_INTERFAZ", length = 512)
	@Length(max = 512)
	public String getPstInterfaz() {
		return this.pstInterfaz;
	}

	public void setPstInterfaz(String pstInterfaz) {
		this.pstInterfaz = pstInterfaz;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PST_FECHA_CREACION", length = 7)
	public Date getPstFechaCreacion() {
		return this.pstFechaCreacion;
	}

	public void setPstFechaCreacion(Date pstFechaCreacion) {
		this.pstFechaCreacion = pstFechaCreacion;
	}

	@Column(name = "PST_NIVEL_RANGO_GRADUAL", precision = 22, scale = 0)
	public Integer getPstNivelRangoGradual() {
		return this.pstNivelRangoGradual;
	}

	public void setPstNivelRangoGradual(Integer pstNivelRangoGradual) {
		this.pstNivelRangoGradual = pstNivelRangoGradual;
	}
	
	@Column(name = "PST_CATEGORIA_DOCENTE", precision = 22, scale = 0)
	public Integer getPstCategoriaDocente() {
		return pstCategoriaDocente;
	}

	public void setPstCategoriaDocente(Integer pstCategoriaDocente) {
		this.pstCategoriaDocente = pstCategoriaDocente;
	}

	@OneToMany( mappedBy = "fnpsPuesto")
	public List<FuncionPuesto> getPstFuncionPuestos() {
		return this.pstFuncionPuestos;
	}

	public void setPstFuncionPuestos(List<FuncionPuesto> pstFuncionPuestos) {
		this.pstFuncionPuestos = pstFuncionPuestos;
	}

	@OneToMany( mappedBy = "acpsPuesto")
	public List<ActividadPuesto> getPstActividadPuestos() {
		return this.pstActividadPuestos;
	}

	public void setPstActividadPuestos(List<ActividadPuesto> pstActividadPuestos) {
		this.pstActividadPuestos = pstActividadPuestos;
	}

	@OneToMany( mappedBy = "inpsPuesto")
	public List<InstruccionPuesto> getPstInstruccionPuestos() {
		return this.pstInstruccionPuestos;
	}

	public void setPstInstruccionPuestos(List<InstruccionPuesto> pstInstruccionPuestos) {
		this.pstInstruccionPuestos = pstInstruccionPuestos;
	}

	@OneToMany( mappedBy = "cmpsPuesto")
	public List<CompetenciaPuesto> getPstCompetenciaPuestos() {
		return this.pstCompetenciaPuestos;
	}

	public void setPstCompetenciaPuestos(List<CompetenciaPuesto> pstCompetenciaPuestos) {
		this.pstCompetenciaPuestos = pstCompetenciaPuestos;
	}

	@OneToMany( mappedBy = "dspsPuesto")
	public List<DestrezaPuesto> getPstDestrezaPuestos() {
		return this.pstDestrezaPuestos;
	}

	public void setPstDestrezaPuestos(List<DestrezaPuesto> pstDestrezaPuestos) {
		this.pstDestrezaPuestos = pstDestrezaPuestos;
	}

	@OneToMany( mappedBy = "dtpsPuesto")
	public List<DetallePuesto> getPstDetallePuestos() {
		return this.pstDetallePuestos;
	}

	public void setPstDetallePuestos(List<DetallePuesto> pstDetallePuestos) {
		this.pstDetallePuestos = pstDetallePuestos;
	}

	@OneToMany( mappedBy = "psarcnPuesto")
	public List<PuestoAreaConocimiento> getPstPuestoAreaConocimientos() {
		return this.pstPuestoAreaConocimientos;
	}

	public void setPstPuestoAreaConocimientos(List<PuestoAreaConocimiento> pstPuestoAreaConocimientos) {
		this.pstPuestoAreaConocimientos = pstPuestoAreaConocimientos;
	}

	@OneToMany( mappedBy = "cnpsPuesto")
	public List<ConocimientoPuesto> getPstConocimientoPuestos() {
		return this.pstConocimientoPuestos;
	}

	public void setPstConocimientoPuestos(List<ConocimientoPuesto> pstConocimientoPuestos) {
		this.pstConocimientoPuestos = pstConocimientoPuestos;
	}

}
