package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 09/03/2017 11:32:19 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * RecordEstudiante generated by hbm2java
 */
@Entity
@Table(name = "RECORD_ESTUDIANTE", schema = ConstantesJpa.SCHEMA)
public class RecordEstudiante implements java.io.Serializable {

	private static final long serialVersionUID = -2026335519533743148L;

	private int rcesId;
	private MallaCurricularParalelo rcesMallaCurricularParalelo;
	private FichaEstudiante rcesFichaEstudiante;
	private Integer rcesEstado;
	private String rcesObservacion;
	private Integer rcesIngresoNota;
	private Integer rcesIngresoNota2;
	private Integer rcesIngresoNota3;
	private String rcesUsuario;
	private Timestamp rcesModificacion;
	private Integer rcesModoAprobacion;
	// private Integer rcesEstadoTerceraMatri;

	private List<Calificacion> calificacions;
	private List<SolicitudTerceraMatricula> rcesSolicitudesTerceraMatricula;

	public RecordEstudiante() {
	}

	public RecordEstudiante(int rcesId) {
		this.rcesId = rcesId;
	}

	public RecordEstudiante(int rcesId, MallaCurricularParalelo rcesMallaCurricularParalelo,
			FichaEstudiante rcesFichaEstudiante, Integer rcesEstado, String rcesObservacion, Integer rcesIngresoNota,
			Integer rcesIngresoNota2, Integer rcesIngresoNota3, List<Calificacion> calificacions,
			List<SolicitudTerceraMatricula> rcesSolicitudesTerceraMatricula, Integer rcesModoAprobacion) {
		this.rcesId = rcesId;
		this.rcesMallaCurricularParalelo = rcesMallaCurricularParalelo;
		this.rcesFichaEstudiante = rcesFichaEstudiante;
		this.rcesEstado = rcesEstado;
		this.rcesObservacion = rcesObservacion;
		this.rcesIngresoNota = rcesIngresoNota;
		this.rcesIngresoNota2 = rcesIngresoNota2;
		this.rcesIngresoNota3 = rcesIngresoNota3;
		this.calificacions = calificacions;
		this.rcesModoAprobacion = rcesModoAprobacion;
		this.rcesSolicitudesTerceraMatricula = rcesSolicitudesTerceraMatricula;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "RCES_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRcesId() {
		return this.rcesId;
	}

	public void setRcesId(int rcesId) {
		this.rcesId = rcesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRPR_ID")
	public MallaCurricularParalelo getRcesMallaCurricularParalelo() {
		return this.rcesMallaCurricularParalelo;
	}

	public void setRcesMallaCurricularParalelo(MallaCurricularParalelo rcesMallaCurricularParalelo) {
		this.rcesMallaCurricularParalelo = rcesMallaCurricularParalelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCES_ID")
	public FichaEstudiante getRcesFichaEstudiante() {
		return this.rcesFichaEstudiante;
	}

	public void setRcesFichaEstudiante(FichaEstudiante rcesFichaEstudiante) {
		this.rcesFichaEstudiante = rcesFichaEstudiante;
	}

	@Column(name = "RCES_ESTADO", precision = 22, scale = 0)
	public Integer getRcesEstado() {
		return this.rcesEstado;
	}

	public void setRcesEstado(Integer rcesEstado) {
		this.rcesEstado = rcesEstado;
	}

	@Column(name = "RCES_OBSERVACION", length = 256)
	@Length(max = 256)
	public String getRcesObservacion() {
		return this.rcesObservacion;
	}

	public void setRcesObservacion(String rcesObservacion) {
		this.rcesObservacion = rcesObservacion;
	}

	@OneToMany(mappedBy = "sltrmtRecordEstudiante")
	public List<SolicitudTerceraMatricula> getRcesSolicitudesTerceraMatricula() {
		return this.rcesSolicitudesTerceraMatricula;
	}

	public void setRcesSolicitudesTerceraMatricula(List<SolicitudTerceraMatricula> rcesSolicitudesTerceraMatricula) {
		this.rcesSolicitudesTerceraMatricula = rcesSolicitudesTerceraMatricula;
	}

	@Column(name = "RCES_INGRESO_NOTA", precision = 22, scale = 0)
	public Integer getRcesIngresoNota() {
		return rcesIngresoNota;
	}

	public void setRcesIngresoNota(Integer rcesIngresoNota) {
		this.rcesIngresoNota = rcesIngresoNota;
	}

	@Column(name = "RCES_INGRESO_NOTA2", precision = 22, scale = 0)
	public Integer getRcesIngresoNota2() {
		return rcesIngresoNota2;
	}

	public void setRcesIngresoNota2(Integer rcesIngresoNota2) {
		this.rcesIngresoNota2 = rcesIngresoNota2;
	}

	@Column(name = "RCES_INGRESO_NOTA3", precision = 22, scale = 0)
	public Integer getRcesIngresoNota3() {
		return rcesIngresoNota3;
	}

	public void setRcesIngresoNota3(Integer rcesIngresoNota3) {
		this.rcesIngresoNota3 = rcesIngresoNota3;
	}

	@OneToMany(mappedBy = "recordEstudiante")
	public List<Calificacion> getCalificacions() {
		return this.calificacions;
	}

	public void setCalificacions(List<Calificacion> calificacions) {
		this.calificacions = calificacions;
	}

	@Column(name = "RCES_USUARIO", length = 256)
	@Length(max = 256)
	public String getRcesUsuario() {
		return rcesUsuario;
	}

	public void setRcesUsuario(String rcesUsuario) {
		this.rcesUsuario = rcesUsuario;
	}

	@Column(name = "RCES_MODIFICACION")
	public Timestamp getRcesModificacion() {
		return rcesModificacion;
	}

	public void setRcesModificacion(Timestamp rcesModificacion) {
		this.rcesModificacion = rcesModificacion;
	}
	@Column(name = "RCES_MODO_APROBACION", precision = 22, scale = 0)
	public Integer getRcesModoAprobacion() {
		return this.rcesModoAprobacion;
	}

	public void setRcesModoAprobacion(Integer rcesModoAprobacion) {
		this.rcesModoAprobacion = rcesModoAprobacion;
	}
	
}
