package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Referencia generated by hbm2java
 */
@Entity
@Table(name = "REFERENCIA", schema = ConstantesJpa.SCHEMA)
public class Referencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4863821976691407006L;
	private int rfrId;
	private String rfrCedula;
	private String rfrNombre;
	private String rfrDireccion;
	private Integer rfrParentesco;
	private Float rfrPorcentaje;
	private Integer rfrEstado;
	private Integer rfrTipo;
	private Persona rfrPersona;

	public Referencia() {
	}

	public Referencia(int rfrId) {
		this.rfrId = rfrId;
	}

	public Referencia(int rfrId, String rfrCedula, String rfrNombre, String rfrDireccion, Integer rfrParentesco, Float rfrPorcentaje, Integer rfrEstado, Integer rfrTipo,  Persona rfrPersona) {
		this.rfrId = rfrId;
		this.rfrCedula = rfrCedula;
		this.rfrNombre = rfrNombre;
		this.rfrDireccion = rfrDireccion;
		this.rfrParentesco = rfrParentesco;
		this.rfrPorcentaje = rfrPorcentaje;
		this.rfrEstado = rfrEstado;
		this.rfrTipo = rfrTipo;
		this.rfrPersona = rfrPersona;
	}
	
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "RFR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRfrId() {
		return rfrId;
	}

	public void setRfrId(int rfrId) {
		this.rfrId = rfrId;
	}

	@Column(name="rfr_cedula", length = 256)
	public String getRfrCedula() {
		return rfrCedula;
	}

	public void setRfrCedula(String rfrCedula) {
		this.rfrCedula = rfrCedula;
	}

	@Column(name="rfr_nombre", length = 512)
	public String getRfrNombre() {
		return rfrNombre;
	}

	public void setRfrNombre(String rfrNombre) {
		this.rfrNombre = rfrNombre;
	}

	@Column(name="rfr_direccion", length = 512)
	public String getRfrDireccion() {
		return rfrDireccion;
	}

	public void setRfrDireccion(String rfrDireccion) {
		this.rfrDireccion = rfrDireccion;
	}

	@Column(name="rfr_parentesco", precision = 22, scale = 0)
	public Integer getRfrParentesco() {
		return rfrParentesco;
	}

	public void setRfrParentesco(Integer rfrParentesco) {
		this.rfrParentesco = rfrParentesco;
	}

	@Column(name="rfr_porcentaje", precision=126)
	public Float getRfrPorcentaje() {
		return rfrPorcentaje;
	}

	public void setRfrPorcentaje(Float rfrPorcentaje) {
		this.rfrPorcentaje = rfrPorcentaje;
	}

	@Column(name="rfr_estado", precision = 22, scale = 0)
	public Integer getRfrEstado() {
		return rfrEstado;
	}

	public void setRfrEstado(Integer rfrEstado) {
		this.rfrEstado = rfrEstado;
	}

	@Column(name="rfr_tipo")
	public Integer getRfrTipo() {
		return rfrTipo;
	}

	public void setRfrTipo(Integer rfrTipo) {
		this.rfrTipo = rfrTipo;
	}

	@ManyToOne
	@JoinColumn(name = "PRS_ID")
	public Persona getRfrPersona() {
		return rfrPersona;
	}

	public void setRfrPersona(Persona rfrPersona) {
		this.rfrPersona = rfrPersona;
	}

}
