package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * RegimenAcademico generated by hbm2java
 */
@Entity
@Table(name = "REGIMEN_ACADEMICO", schema = ConstantesJpa.SCHEMA)
public class RegimenAcademico implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2533424547998775623L;
	private int rgacId;
	private String rgacDescripcion;
	private Integer rgacEstado;
	private List<NivelFormacion> rgacNivelFormacions = new ArrayList<NivelFormacion>(0);
	private List<TipoSede> rgacTipoSedes = new ArrayList<TipoSede>(0);

	public RegimenAcademico() {
	}

	public RegimenAcademico(int rgacId) {
		this.rgacId = rgacId;
	}

	public RegimenAcademico(int rgacId, String rgacDescripcion, Integer rgacEstado,
			List<NivelFormacion> rgacNivelFormacions, List<TipoSede> rgacTipoSedes) {
		this.rgacId = rgacId;
		this.rgacDescripcion = rgacDescripcion;
		this.rgacEstado = rgacEstado;
		this.rgacNivelFormacions = rgacNivelFormacions;
		this.rgacTipoSedes = rgacTipoSedes;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "RGAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRgacId() {
		return this.rgacId;
	}

	public void setRgacId(int rgacId) {
		this.rgacId = rgacId;
	}

	@Column(name = "RGAC_DESCRIPCION", length = 32)
	@Length(max = 32)
	public String getRgacDescripcion() {
		return this.rgacDescripcion;
	}

	public void setRgacDescripcion(String rgacDescripcion) {
		this.rgacDescripcion = rgacDescripcion;
	}

	@Column(name = "RGAC_ESTADO", precision = 22, scale = 0)
	public Integer getRgacEstado() {
		return this.rgacEstado;
	}

	public void setRgacEstado(Integer rgacEstado) {
		this.rgacEstado = rgacEstado;
	}

	@OneToMany( mappedBy = "nvfrRegimenAcademico")
	public List<NivelFormacion> getRgacNivelFormacions() {
		return this.rgacNivelFormacions;
	}

	public void setRgacNivelFormacions(List<NivelFormacion> rgacNivelFormacions) {
		this.rgacNivelFormacions = rgacNivelFormacions;
	}

	@OneToMany( mappedBy = "tiseRegimenAcademico")
	public List<TipoSede> getRgacTipoSedes() {
		return this.rgacTipoSedes;
	}

	public void setRgacTipoSedes(List<TipoSede> rgacTipoSedes) {
		this.rgacTipoSedes = rgacTipoSedes;
	}

}
