package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * RelacionLaboral generated by hbm2java
 */
@Entity
@Table(name = "RELACION_LABORAL", schema = ConstantesJpa.SCHEMA)
public class RelacionLaboral implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3417239924766011500L;
	private int rllbId;
	private String rllbDescripcion;
	private Integer rllbEstado;
	private List<DetallePuesto> rllbDetallePuestos = new ArrayList<DetallePuesto>(0);

	public RelacionLaboral() {
	}

	public RelacionLaboral(int rllbId) {
		this.rllbId = rllbId;
	}

	public RelacionLaboral(int rllbId, String rllbDescripcion, Integer rllbEstado,
			List<DetallePuesto> rllbDetallePuestos) {
		this.rllbId = rllbId;
		this.rllbDescripcion = rllbDescripcion;
		this.rllbEstado = rllbEstado;
		this.rllbDetallePuestos = rllbDetallePuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "RLLB_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRllbId() {
		return this.rllbId;
	}

	public void setRllbId(int rllbId) {
		this.rllbId = rllbId;
	}

	@Column(name = "RLLB_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getRllbDescripcion() {
		return this.rllbDescripcion;
	}

	public void setRllbDescripcion(String rllbDescripcion) {
		this.rllbDescripcion = rllbDescripcion;
	}

	@Column(name = "RLLB_ESTADO", precision = 22, scale = 0)
	public Integer getRllbEstado() {
		return this.rllbEstado;
	}

	public void setRllbEstado(Integer rllbEstado) {
		this.rllbEstado = rllbEstado;
	}

	@OneToMany( mappedBy = "dtpsRelacionLaboral")
	public List<DetallePuesto> getRllbDetallePuestos() {
		return this.rllbDetallePuestos;
	}

	public void setRllbDetallePuestos(List<DetallePuesto> rllbDetallePuestos) {
		this.rllbDetallePuestos = rllbDetallePuestos;
	}

}
