package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Requisito generated by hbm2java
 */
@Entity
@Table(name = "REQUISITO", schema = ConstantesJpa.SCHEMA)
public class Requisito implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1539688171947474821L;
	private int rqsId;
	private ProcesoTramiteContrato rqsProcesoTramiteContrato;
	private Integer rqsPublicaciones;
	private Integer rqsExpericiaDocente;
	private Integer rqsExpericiaLaboral;
	private Integer rqsCapacitacion;
	private Integer rqsMecanizadoIess;
	private Integer rqsDeclaracionBienes;
	private Integer rqsPluriempleo;
	private Integer rqsNepotismo;
	private Integer rqsCertificacionBancaria;
	private Integer rqsCertificadoAfiliadoIess;
	private Integer rqsEstado;

	public Requisito() {
	}

	public Requisito(int rqsId) {
		this.rqsId = rqsId;
	}

	public Requisito(int rqsId, ProcesoTramiteContrato rqsProcesoTramiteContrato, Integer rqsPublicaciones,
			Integer rqsExpericiaDocente, Integer rqsExpericiaLaboral, Integer rqsCapacitacion,
			Integer rqsMecanizadoIess, Integer rqsDeclaracionBienes, Integer rqsPluriempleo,
			Integer rqsNepotismo, Integer rqsCertificacionBancaria, Integer rqsCertificadoAfiliadoIess,
			Integer rqsEstado) {
		this.rqsId = rqsId;
		this.rqsProcesoTramiteContrato = rqsProcesoTramiteContrato;
		this.rqsPublicaciones = rqsPublicaciones;
		this.rqsExpericiaDocente = rqsExpericiaDocente;
		this.rqsExpericiaLaboral = rqsExpericiaLaboral;
		this.rqsCapacitacion = rqsCapacitacion;
		this.rqsMecanizadoIess = rqsMecanizadoIess;
		this.rqsDeclaracionBienes = rqsDeclaracionBienes;
		this.rqsPluriempleo = rqsPluriempleo;
		this.rqsNepotismo = rqsNepotismo;
		this.rqsCertificacionBancaria = rqsCertificacionBancaria;
		this.rqsCertificadoAfiliadoIess = rqsCertificadoAfiliadoIess;
		this.rqsEstado = rqsEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "RQS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRqsId() {
		return this.rqsId;
	}

	public void setRqsId(int rqsId) {
		this.rqsId = rqsId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getRqsProcesoTramiteContrato() {
		return this.rqsProcesoTramiteContrato;
	}

	public void setRqsProcesoTramiteContrato(ProcesoTramiteContrato rqsProcesoTramiteContrato) {
		this.rqsProcesoTramiteContrato = rqsProcesoTramiteContrato;
	}

	@Column(name = "RQS_PUBLICACIONES", precision = 22, scale = 0)
	public Integer getRqsPublicaciones() {
		return this.rqsPublicaciones;
	}

	public void setRqsPublicaciones(Integer rqsPublicaciones) {
		this.rqsPublicaciones = rqsPublicaciones;
	}

	@Column(name = "RQS_EXPERICIA_DOCENTE", precision = 22, scale = 0)
	public Integer getRqsExpericiaDocente() {
		return this.rqsExpericiaDocente;
	}

	public void setRqsExpericiaDocente(Integer rqsExpericiaDocente) {
		this.rqsExpericiaDocente = rqsExpericiaDocente;
	}

	@Column(name = "RQS_EXPERICIA_LABORAL", precision = 22, scale = 0)
	public Integer getRqsExpericiaLaboral() {
		return this.rqsExpericiaLaboral;
	}

	public void setRqsExpericiaLaboral(Integer rqsExpericiaLaboral) {
		this.rqsExpericiaLaboral = rqsExpericiaLaboral;
	}

	@Column(name = "RQS_CAPACITACION", precision = 22, scale = 0)
	public Integer getRqsCapacitacion() {
		return this.rqsCapacitacion;
	}

	public void setRqsCapacitacion(Integer rqsCapacitacion) {
		this.rqsCapacitacion = rqsCapacitacion;
	}

	@Column(name = "RQS_MECANIZADO_IESS", precision = 22, scale = 0)
	public Integer getRqsMecanizadoIess() {
		return this.rqsMecanizadoIess;
	}

	public void setRqsMecanizadoIess(Integer rqsMecanizadoIess) {
		this.rqsMecanizadoIess = rqsMecanizadoIess;
	}

	@Column(name = "RQS_DECLARACION_BIENES", precision = 22, scale = 0)
	public Integer getRqsDeclaracionBienes() {
		return this.rqsDeclaracionBienes;
	}

	public void setRqsDeclaracionBienes(Integer rqsDeclaracionBienes) {
		this.rqsDeclaracionBienes = rqsDeclaracionBienes;
	}

	@Column(name = "RQS_PLURIEMPLEO", precision = 22, scale = 0)
	public Integer getRqsPluriempleo() {
		return this.rqsPluriempleo;
	}

	public void setRqsPluriempleo(Integer rqsPluriempleo) {
		this.rqsPluriempleo = rqsPluriempleo;
	}

	@Column(name = "RQS_NEPOTISMO", precision = 22, scale = 0)
	public Integer getRqsNepotismo() {
		return this.rqsNepotismo;
	}

	public void setRqsNepotismo(Integer rqsNepotismo) {
		this.rqsNepotismo = rqsNepotismo;
	}

	@Column(name = "RQS_CERTIFICACION_BANCARIA", precision = 22, scale = 0)
	public Integer getRqsCertificacionBancaria() {
		return this.rqsCertificacionBancaria;
	}

	public void setRqsCertificacionBancaria(Integer rqsCertificacionBancaria) {
		this.rqsCertificacionBancaria = rqsCertificacionBancaria;
	}

	@Column(name = "RQS_CERTIFICADO_AFILIADO_IESS", precision = 22, scale = 0)
	public Integer getRqsCertificadoAfiliadoIess() {
		return this.rqsCertificadoAfiliadoIess;
	}

	public void setRqsCertificadoAfiliadoIess(Integer rqsCertificadoAfiliadoIess) {
		this.rqsCertificadoAfiliadoIess = rqsCertificadoAfiliadoIess;
	}

	@Column(name = "RQS_ESTADO", precision = 22, scale = 0)
	public Integer getRqsEstado() {
		return this.rqsEstado;
	}

	public void setRqsEstado(Integer rqsEstado) {
		this.rqsEstado = rqsEstado;
	}

}
