package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Serie generated by hbm2java
 */
@Entity
@Table(name = "SERIE", schema = ConstantesJpa.SCHEMA)
public class Serie implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8577735696861737371L;
	private int serId;
	private Proceso serProceso;
	private String serCodigo;
	private String serDescripcion;
	private List<Puesto> serPuestos = new ArrayList<Puesto>(0);

	public Serie() {
	}

	public Serie(int serId) {
		this.serId = serId;
	}

	public Serie(int serId, Proceso serProceso, String serCodigo, String serDescripcion, List<Puesto> serPuestos) {
		this.serId = serId;
		this.serProceso = serProceso;
		this.serCodigo = serCodigo;
		this.serDescripcion = serDescripcion;
		this.serPuestos = serPuestos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "SER_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getSerId() {
		return this.serId;
	}

	public void setSerId(int serId) {
		this.serId = serId;
	}

	@ManyToOne
	@JoinColumn(name = "PRC_ID")
	public Proceso getSerProceso() {
		return this.serProceso;
	}

	public void setSerProceso(Proceso serProceso) {
		this.serProceso = serProceso;
	}

	@Column(name = "SER_CODIGO", length = 8)
	@Length(max = 8)
	public String getSerCodigo() {
		return this.serCodigo;
	}

	public void setSerCodigo(String serCodigo) {
		this.serCodigo = serCodigo;
	}

	@Column(name = "SER_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getSerDescripcion() {
		return this.serDescripcion;
	}

	public void setSerDescripcion(String serDescripcion) {
		this.serDescripcion = serDescripcion;
	}

	@OneToMany( mappedBy = "pstSerie")
	public List<Puesto> getPuestos() {
		return this.serPuestos;
	}

	public void setPuestos(List<Puesto> serPuestos) {
		this.serPuestos = serPuestos;
	}

}
