package ec.edu.uce.academico.jpa.entidades.publico;
// Manual 17/01/2018 15:14:22 by MQ
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**MQ
 * SolicitudTerceraMatricula generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_TERCERA_MATRICULA", schema = ConstantesJpa.SCHEMA)
public class SolicitudTerceraMatricula implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1828910417871903627L;
	private int sltrmtId;
	private PeriodoAcademico sltrmtPeriodoAcademico;
	private Causal sltrmtCausal; 
	private RecordEstudiante sltrmtRecordEstudiante;
	private SolicitudTerceraMatricula sltrmtSubId;
	private Integer sltrmtEstado;
	private Integer sltrmtEstadoRegistro;
	private Timestamp sltrmtFechaSolicitud;
	private String sltrmtDocumentoSolicitud;
	private Timestamp sltrmtFechaVerificacion;
	private Timestamp sltrmtFechaRespSolicitud;
	private String sltrmtDocumentoResolucion;
	private String sltrmtObservacion;
	private String sltrmtObservacionFinal;
	private Integer sltrmtTipo;
	private Integer sltrmtFcesId;
	private Integer sltrmtMtrId;
	
	private List<SolicitudTerceraMatricula> sltrmtSolicitudes = new ArrayList<SolicitudTerceraMatricula>(0);
	
	public SolicitudTerceraMatricula() {
	}

	public SolicitudTerceraMatricula(int sltrmtId) {
		this.sltrmtId = sltrmtId;
	}

	public SolicitudTerceraMatricula(int sltrmtId, PeriodoAcademico sltrmtPeriodoAcademico, Causal sltrmtCausal,
			RecordEstudiante sltrmtRecordEstudiante,SolicitudTerceraMatricula sltrmtSubId, Integer sltrmtEstado,  Integer sltrmtTipo,String sltrmtDocumentoSolicitud,
			Timestamp sltrmtFechaVerificacion,Timestamp sltrmtFechaRespSolicitud, String sltrmtDocumentoResolucion, String sltrmtObservacion, String sltrmtObservacionFinal, Timestamp sltrmtFechaSolicitud, 
			Integer sltrmtFcesId,Integer sltrmtMtrId, Integer sltrmtEstadoRegistro, List<SolicitudTerceraMatricula> sltrmtSolicitudes) {
		this.sltrmtId = sltrmtId;
		this.sltrmtPeriodoAcademico = sltrmtPeriodoAcademico;
		this.sltrmtCausal = sltrmtCausal;
		this.sltrmtRecordEstudiante = sltrmtRecordEstudiante;
		this.sltrmtSubId = sltrmtSubId;
		this.sltrmtEstado = sltrmtEstado;
		this.sltrmtTipo = sltrmtTipo;
		this.sltrmtFechaSolicitud = sltrmtFechaSolicitud;
		this.sltrmtDocumentoSolicitud = sltrmtDocumentoSolicitud;
		this.sltrmtFechaVerificacion = sltrmtFechaVerificacion;
		this.sltrmtFechaRespSolicitud = sltrmtFechaRespSolicitud;
		this.sltrmtDocumentoResolucion = sltrmtDocumentoResolucion;
		this.sltrmtObservacion = sltrmtObservacion;
		this.sltrmtObservacionFinal = sltrmtObservacionFinal;
		this.sltrmtFcesId = sltrmtFcesId;
		this.sltrmtMtrId = sltrmtMtrId;
		this.sltrmtEstadoRegistro = sltrmtEstadoRegistro;
		this.sltrmtSolicitudes = sltrmtSolicitudes;
	
		
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "SLTRMT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getSltrmtId() {
		return this.sltrmtId;
	}

	public void setSltrmtId(int sltrmtId) {
		this.sltrmtId = sltrmtId;
	}

	@ManyToOne
	@JoinColumn(name = "PRAC_ID")
	public PeriodoAcademico getSltrmtPeriodoAcademico() {
		return this.sltrmtPeriodoAcademico;
	}

	public void setSltrmtPeriodoAcademico(PeriodoAcademico sltrmtPeriodoAcademico) {
		this.sltrmtPeriodoAcademico = sltrmtPeriodoAcademico;
	}

	@ManyToOne
	@JoinColumn(name = "CSL_ID")
	public Causal getSltrmtCausal() {
		return this.sltrmtCausal;
	}

	public void setSltrmtCausal(Causal sltrmtCausal) {
		this.sltrmtCausal = sltrmtCausal;
	}

	@ManyToOne
	@JoinColumn(name = "RCES_ID")
	public RecordEstudiante getSltrmtRecordEstudiante() {
		return this.sltrmtRecordEstudiante;
	}

	public void setSltrmtRecordEstudiante(RecordEstudiante sltrmtRecordEstudiante) {
		this.sltrmtRecordEstudiante = sltrmtRecordEstudiante;
	}
	
	
	@ManyToOne
	@JoinColumn(name = "SLTRMT_SUB_ID")
	public SolicitudTerceraMatricula getSltrmtSubId() {
		return this.sltrmtSubId;
	}

	public void setSltrmtSubId(SolicitudTerceraMatricula sltrmtSubId) {
		this.sltrmtSubId = sltrmtSubId;
	}

	@Column(name = "SLTRMT_ESTADO", precision = 2, scale = 0)
	public Integer getSltrmtEstado() {
		return this.sltrmtEstado;
	}

	public void setSltrmtEstado(Integer sltrmtEstado) {
		this.sltrmtEstado = sltrmtEstado;
	}

	
	@Column(name = "SLTRMT_TIPO", precision = 2, scale = 0)
	public Integer getSltrmtTipo() {
		return this.sltrmtTipo;
	}

	public void setSltrmtTipo(Integer sltrmtTipo) {
		this.sltrmtTipo = sltrmtTipo;
	}
	
	@Column(name = "SLTRMT_DOCUMENTO_SOLICITUD", length = 256)
	@Length(max = 256)
	public String getSltrmtDocumentoSolicitud() {
		return this.sltrmtDocumentoSolicitud;
	}

	public void setSltrmtDocumentoSolicitud(String sltrmtDocumentoSolicitud) {
		this.sltrmtDocumentoSolicitud = sltrmtDocumentoSolicitud;
	}

	@Column(name = "SLTRMT_DOCUMENTO_RESOLUCION", length = 256)
	@Length(max = 256)
	public String getSltrmtDocumentoResolucion() {
		return this.sltrmtDocumentoResolucion;
	}

	public void setSltrmtDocumentoResolucion(String sltrmtDocumentoResolucion) {
		this.sltrmtDocumentoResolucion = sltrmtDocumentoResolucion;
	}

	@Column(name = "SLTRMT_OBSERVACION", length = 256)
	@Length(max = 256)
	public String getSltrmtObservacion() {
		return this.sltrmtObservacion;
	}

	public void setSltrmtObservacion(String sltrmtObservacion) {
		this.sltrmtObservacion = sltrmtObservacion;
	}

	
	@Column(name = "SLTRMT_OBSERVACION_FINAL", length = 512)
	@Length(max = 512)
	public String getSltrmtObservacionFinal() {
		return this.sltrmtObservacionFinal;
	}

	public void setSltrmtObservacionFinal(String sltrmtObservacionFinal) {
		this.sltrmtObservacionFinal = sltrmtObservacionFinal;
	}
	
	
	@Column(name = "SLTRMT_FECHA_SOLICITUD")
	public Timestamp getSltrmtFechaSolicitud() {
		return sltrmtFechaSolicitud;
	}

	public void setSltrmtFechaSolicitud(Timestamp sltrmtFechaSolicitud) {
		this.sltrmtFechaSolicitud = sltrmtFechaSolicitud;
	}

	
//	@Column(name = "SLTRMT_FECHA_VERIF_SOLICITUD")
//	public Timestamp getSltrmtFechaVerifSolicitud() {
//		return sltrmtFechaVerificacion;
//	}
//
//	public void setSltrmtFechaVerifSolicitud(Timestamp sltrmtFechaVerificacion) {
//		this.sltrmtFechaVerificacion = sltrmtFechaVerificacion;
//	}

	
	
	@Column(name = "SLTRMT_FECHA_VERIF_SOLICITUD")
	public Timestamp getSltrmtFechaVerificacion() {
		return sltrmtFechaVerificacion;
	}

	public void setSltrmtFechaVerificacion(Timestamp sltrmtFechaVerificacion) {
		this.sltrmtFechaVerificacion = sltrmtFechaVerificacion;
	}

	@Column(name = "SLTRMT_FECHA_RESP_SOLICITUD")
	public Timestamp getSltrmtFechaRespSolicitud() {
		return sltrmtFechaRespSolicitud;
	}

	public void setSltrmtFechaRespSolicitud(Timestamp sltrmtFechaRespSolicitud) {
		this.sltrmtFechaRespSolicitud = sltrmtFechaRespSolicitud;
	}
	
		
	@OneToMany( mappedBy = "sltrmtSubId", fetch=FetchType.EAGER)
	public List<SolicitudTerceraMatricula> getSltrmtSolicitudes() {
		return this.sltrmtSolicitudes;
	}

	public void setSltrmtSolicitudes(List<SolicitudTerceraMatricula> sltrmtSolicitudes) {
		this.sltrmtSolicitudes = sltrmtSolicitudes;
	}
	
	
	@Column(name = "SLTRMT_FCES_ID", precision = 6, scale = 0)
	public Integer getSltrmtFcesId() {
		return this.sltrmtFcesId;
	}

	public void setSltrmtFcesId(Integer sltrmtFcesId) {
		this.sltrmtFcesId = sltrmtFcesId;
	}
	
	@Column(name = "SLTRMT_MTR_ID", precision = 6, scale = 0)
	public Integer getSltrmtMtrId() {
		return this.sltrmtMtrId;
	}

	public void setSltrmtMtrId(Integer sltrmtMtrId) {
		this.sltrmtMtrId = sltrmtMtrId;
	}
	
	@Column(name = "SLTRMT_ESTADO_REGISTRO")
	public Integer getSltrmtEstadoRegistro() {
		return this.sltrmtEstadoRegistro;
	}

	public void setSltrmtEstadoRegistro(Integer sltrmtEstadoRegistro) {
		this.sltrmtEstadoRegistro = sltrmtEstadoRegistro;
	}

	
}
