package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoFuncionario generated by hbm2java
 */
@Entity
@Table(name = "TIPO_EMPLEADO", schema = ConstantesJpa.SCHEMA)
public class TipoEmpleado implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8125699364586916447L;
	private int tiemId;
	private String tiemDescripcion;
	private Integer tiemEstado;
	private List<TipoContrato> tiemTipoContratos = new ArrayList<TipoContrato>(0);

	public TipoEmpleado() {
	}

	public TipoEmpleado(int tiemId) {
		this.tiemId = tiemId;
	}

	public TipoEmpleado(int tiemId, String tiemDescripcion, Integer tiemEstado, List<TipoContrato> tiemTipoContratos) {
		this.tiemId = tiemId;
		this.tiemDescripcion = tiemDescripcion;
		this.tiemEstado = tiemEstado;
		this.tiemTipoContratos = tiemTipoContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIEM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTiemId() {
		return this.tiemId;
	}

	public void setTiemId(int tiemId) {
		this.tiemId = tiemId;
	}

	@Column(name = "TIEM_DESCRIPCION", length = 100)
	@Length(max = 100)
	public String getTiemDescripcion() {
		return this.tiemDescripcion;
	}

	public void setTiemDescripcion(String tiemDescripcion) {
		this.tiemDescripcion = tiemDescripcion;
	}

	@Column(name = "TIEM_ESTADO", precision = 22, scale = 0)
	public Integer getTiemEstado() {
		return this.tiemEstado;
	}

	public void setTiemEstado(Integer tiemEstado) {
		this.tiemEstado = tiemEstado;
	}

	@OneToMany( mappedBy = "ticnTipoEmpleado")
	public List<TipoContrato> getTiemTipoContratos() {
		return this.tiemTipoContratos;
	}

	public void setTiemTipoContratos(List<TipoContrato> tiemTipoContratos) {
		this.tiemTipoContratos = tiemTipoContratos;
	}

}
