package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoNivelApertura generated by hbm2java
 */
@Entity
@Table(name = "TIPO_NIVEL_APERTURA", schema = ConstantesJpa.SCHEMA)
public class TipoNivelApertura implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 935335555932497552L;
	private int tinvapId;
	private TipoApertura tinvapTipoApertura;
	private PlanificacionCronograma tinvapPlanificacionCronograma;
	private NivelApertura tinvapNivelApertura;
	private Timestamp tinvapFechaInicio;
	private Timestamp tinvapFechaFin;
	private Integer tinvapEstado;
	private String tinvapObservacion;

	public TipoNivelApertura() {
	}

	public TipoNivelApertura(int tinvapId) {
		this.tinvapId = tinvapId;
	}

	public TipoNivelApertura(int tinvapId, TipoApertura tinvapTipoApertura, PlanificacionCronograma tinvapPlanificacionCronograma,
			NivelApertura tinvapNivelApertura, Timestamp tinvapFechaInicio, Timestamp tinvapFechaFin,
			Integer tinvapEstado, String tinvapObservacion) {
		this.tinvapId = tinvapId;
		this.tinvapTipoApertura = tinvapTipoApertura;
		this.tinvapPlanificacionCronograma = tinvapPlanificacionCronograma;
		this.tinvapNivelApertura = tinvapNivelApertura;
		this.tinvapFechaInicio = tinvapFechaInicio;
		this.tinvapFechaFin = tinvapFechaFin;
		this.tinvapEstado = tinvapEstado;
		this.tinvapObservacion = tinvapObservacion;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TINVAP_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTinvapId() {
		return this.tinvapId;
	}

	public void setTinvapId(int tinvapId) {
		this.tinvapId = tinvapId;
	}

	@ManyToOne
	@JoinColumn(name = "TIAP_ID")
	public TipoApertura getTinvapTipoApertura() {
		return this.tinvapTipoApertura;
	}

	public void setTinvapTipoApertura(TipoApertura tinvapTipoApertura) {
		this.tinvapTipoApertura = tinvapTipoApertura;
	}

	@ManyToOne
	@JoinColumn(name = "PLCR_ID")
	public PlanificacionCronograma getTinvapPlanificacionCronograma() {
		return this.tinvapPlanificacionCronograma;
	}

	public void setTinvapPlanificacionCronograma(PlanificacionCronograma tinvapPlanificacionCronograma) {
		this.tinvapPlanificacionCronograma = tinvapPlanificacionCronograma;
	}

	@ManyToOne
	@JoinColumn(name = "NVAP_ID")
	public NivelApertura getTinvapNivelApertura() {
		return this.tinvapNivelApertura;
	}

	public void setTinvapNivelApertura(NivelApertura tinvapNivelApertura) {
		this.tinvapNivelApertura = tinvapNivelApertura;
	}

	@Column(name = "TINVAP_FECHA_INICIO")
	public Timestamp getTinvapFechaInicio() {
		return this.tinvapFechaInicio;
	}

	public void setTinvapFechaInicio(Timestamp tinvapFechaInicio) {
		this.tinvapFechaInicio = tinvapFechaInicio;
	}

	@Column(name = "TINVAP_FECHA_FIN")
	public Timestamp getTinvapFechaFin() {
		return this.tinvapFechaFin;
	}

	public void setTinvapFechaFin(Timestamp tinvapFechaFin) {
		this.tinvapFechaFin = tinvapFechaFin;
	}

	@Column(name = "TINVAP_ESTADO", precision = 22, scale = 0)
	public Integer getTinvapEstado() {
		return this.tinvapEstado;
	}

	public void setTinvapEstado(Integer tinvapEstado) {
		this.tinvapEstado = tinvapEstado;
	}

	@Column(name = "TINVAP_OBSERVACION", length = 512)
	@Length(max = 512)
	public String getTinvapObservacion() {
		return this.tinvapObservacion;
	}

	public void setTinvapObservacion(String tinvapObservacion) {
		this.tinvapObservacion = tinvapObservacion;
	}

}
