package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CONTRATO", schema = ConstantesJpa.SCHEMA)
public class TipoContrato implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8480728164074058750L;
	private int ticnId;
	private TipoEmpleado ticnTipoEmpleado;
	private String ticnDescripcion;
	private Integer ticnEstado;
	private List<Contrato> ticnContratos = new ArrayList<Contrato>(0);
	private List<FormatoContrato> ticnFormatoContratos = new ArrayList<FormatoContrato>(0);

	public TipoContrato() {
	}

	public TipoContrato(int ticnId) {
		this.ticnId = ticnId;
	}

	public TipoContrato(int ticnId, TipoEmpleado ticnTipoEmpleado, String ticnDescripcion, Integer ticnEstado,
			List<Contrato> ticnContratos, List<FormatoContrato> ticnFormatoContratos) {
		this.ticnId = ticnId;
		this.ticnTipoEmpleado = ticnTipoEmpleado;
		this.ticnDescripcion = ticnDescripcion;
		this.ticnEstado = ticnEstado;
		this.ticnContratos = ticnContratos;
		this.ticnFormatoContratos = ticnFormatoContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TICN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTicnId() {
		return this.ticnId;
	}

	public void setTicnId(int ticnId) {
		this.ticnId = ticnId;
	}

	@ManyToOne
	@JoinColumn(name = "TIEM_ID")
	public TipoEmpleado getTicnTipoEmpleado() {
		return this.ticnTipoEmpleado;
	}

	public void setTicnTipoEmpleado(TipoEmpleado ticnTipoEmpleado) {
		this.ticnTipoEmpleado = ticnTipoEmpleado;
	}

	@Column(name = "TICN_DESCRIPCION", length = 200)
	@Length(max = 200)
	public String getTicnDescripcion() {
		return this.ticnDescripcion;
	}

	public void setTicnDescripcion(String ticnDescripcion) {
		this.ticnDescripcion = ticnDescripcion;
	}

	@Column(name = "TICN_ESTADO", precision = 22, scale = 0)
	public Integer getTicnEstado() {
		return this.ticnEstado;
	}

	public void setTicnEstado(Integer ticnEstado) {
		this.ticnEstado = ticnEstado;
	}

	@OneToMany( mappedBy = "cntTipoContrato")
	public List<Contrato> getTicnContratos() {
		return this.ticnContratos;
	}

	public void setTicnContratos(List<Contrato> ticnContratos) {
		this.ticnContratos = ticnContratos;
	}

	@OneToMany( mappedBy = "frcnTipoContrato")
	public List<FormatoContrato> getTicnFormatoContratos() {
		return this.ticnFormatoContratos;
	}

	public void setTicnFormatoContratos(List<FormatoContrato> ticnFormatoContratos) {
		this.ticnFormatoContratos = ticnFormatoContratos;
	}

}
