package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoFuncionCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_FUNCION_CARGA_HORARIA", schema = ConstantesJpa.SCHEMA)
public class TipoFuncionCargaHoraria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2230956234318147860L;
	private int tifncrhrId;
	private TipoCargaHoraria tifncrhrTipoCargaHoraria;
	private FuncionCargaHoraria tifncrhrFuncionCargaHoraria;
	private Integer tifncrhrEstado;
	private List<CargaHoraria> tifncrhrCargaHorarias = new ArrayList<CargaHoraria>(0);

	public TipoFuncionCargaHoraria() {
	}

	public TipoFuncionCargaHoraria(int tifncrhrId) {
		this.tifncrhrId = tifncrhrId;
	}

	public TipoFuncionCargaHoraria(int tifncrhrId, TipoCargaHoraria tifncrhrTipoCargaHoraria,
			FuncionCargaHoraria tifncrhrFuncionCargaHoraria, Integer tifncrhrEstado, List<CargaHoraria> tifncrhrCargaHorarias) {
		this.tifncrhrId = tifncrhrId;
		this.tifncrhrTipoCargaHoraria = tifncrhrTipoCargaHoraria;
		this.tifncrhrFuncionCargaHoraria = tifncrhrFuncionCargaHoraria;
		this.tifncrhrEstado = tifncrhrEstado;
		this.tifncrhrCargaHorarias = tifncrhrCargaHorarias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIFNCRHR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTifncrhrId() {
		return this.tifncrhrId;
	}

	public void setTifncrhrId(int tifncrhrId) {
		this.tifncrhrId = tifncrhrId;
	}

	@ManyToOne
	@JoinColumn(name = "TICRHR_ID")
	public TipoCargaHoraria getTifncrhrTipoCargaHoraria() {
		return this.tifncrhrTipoCargaHoraria;
	}

	public void setTifncrhrTipoCargaHoraria(TipoCargaHoraria tifncrhrTipoCargaHoraria) {
		this.tifncrhrTipoCargaHoraria = tifncrhrTipoCargaHoraria;
	}

	@ManyToOne
	@JoinColumn(name = "FNCRHR_ID")
	public FuncionCargaHoraria getTifncrhrFuncionCargaHoraria() {
		return this.tifncrhrFuncionCargaHoraria;
	}

	public void setTifncrhrFuncionCargaHoraria(FuncionCargaHoraria tifncrhrFuncionCargaHoraria) {
		this.tifncrhrFuncionCargaHoraria = tifncrhrFuncionCargaHoraria;
	}

	@Column(name = "TIFNCRHR_ESTADO", precision = 22, scale = 0)
	public Integer getTifncrhrEstado() {
		return this.tifncrhrEstado;
	}

	public void setTifncrhrEstado(Integer tifncrhrEstado) {
		this.tifncrhrEstado = tifncrhrEstado;
	}

	@OneToMany( mappedBy = "crhrTipoFuncionCargaHoraria")
	public List<CargaHoraria> getTifncrhrCargaHorarias() {
		return this.tifncrhrCargaHorarias;
	}

	public void setTifncrhrCargaHorarias(List<CargaHoraria> tifncrhrCargaHorarias) {
		this.tifncrhrCargaHorarias = tifncrhrCargaHorarias;
	}

}
