package ec.edu.uce.academico.jpa.entidades.publico;
// Manual 17/01/2018 15:07:00   MQ

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoCausal generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CAUSAL", schema = ConstantesJpa.SCHEMA)
public class TipoCausal implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7478138203501619219L;
	private int ticsId;
	private String ticsDescripcion;
	private Integer ticsEstado;
	private List<Causal> ticsCausales = new ArrayList<Causal>(0);

	public TipoCausal() {
	}

	public TipoCausal(int ticsId) {
		this.ticsId = ticsId;
	}

	public TipoCausal(int ticsId, String ticsDescripcion, Integer ticsEstado, List<Causal> ticsCausales) {
		this.ticsId = ticsId;
		this.ticsDescripcion = ticsDescripcion;
		this.ticsEstado = ticsEstado;
		this.ticsCausales = ticsCausales;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TICS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTicsId() {
		return this.ticsId;
	}

	public void setTicsId(int ticsId) {
		this.ticsId = ticsId;
	}

	@Column(name = "TICS_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getTicsDescripcion() {
		return this.ticsDescripcion;
	}

	public void setTicsDescripcion(String ticsDescripcion) {
		this.ticsDescripcion = ticsDescripcion;
	}

	@Column(name = "TICS_ESTADO", precision = 22, scale = 0)
	public Integer getTicsEstado() {
		return this.ticsEstado;
	}

	public void setTicsEstado(Integer ticsEstado) {
		this.ticsEstado = ticsEstado;
	}

	@OneToMany( mappedBy = "cslTipoCausal")
	public List<Causal> getTicsCausales() {
		return this.ticsCausales;
	}

	public void setTicsCausales(List<Causal> ticsCausales) {
		this.ticsCausales = ticsCausales;
	}

}
