package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CARGA_HORARIA", schema = ConstantesJpa.SCHEMA)
public class TipoCargaHoraria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4909239539027219440L;
	private int ticrhrId;
	private String ticrhrDescripcion;
	private Integer ticrhrEstado;
	private List<TipoFuncionCargaHoraria> ticrhrTipoFuncionCargaHorarias = new ArrayList<TipoFuncionCargaHoraria>(0);

	public TipoCargaHoraria() {
	}

	public TipoCargaHoraria(int ticrhrId) {
		this.ticrhrId = ticrhrId;
	}

	public TipoCargaHoraria(int ticrhrId, String ticrhrDescripcion, Integer ticrhrEstado,
			List<TipoFuncionCargaHoraria> ticrhrTipoFuncionCargaHorarias) {
		this.ticrhrId = ticrhrId;
		this.ticrhrDescripcion = ticrhrDescripcion;
		this.ticrhrEstado = ticrhrEstado;
		this.ticrhrTipoFuncionCargaHorarias = ticrhrTipoFuncionCargaHorarias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TICRHR_ID", unique = true, nullable = false, precision = 2, scale = 0)
	public int getTicrhrId() {
		return this.ticrhrId;
	}

	public void setTicrhrId(int ticrhrId) {
		this.ticrhrId = ticrhrId;
	}

	@Column(name = "TICRHR_DESCRIPCION" , length= 128)
	public String getTicrhrDescripcion() {
		return this.ticrhrDescripcion;
	}

	public void setTicrhrDescripcion(String ticrhrDescripcion) {
		this.ticrhrDescripcion = ticrhrDescripcion;
	}

	@Column(name = "TICRHR_ESTADO", precision = 2, scale = 0)
	public Integer getTicrhrEstado() {
		return this.ticrhrEstado;
	}

	public void setTicrhrEstado(Integer ticrhrEstado) {
		this.ticrhrEstado = ticrhrEstado;
	}

	@OneToMany( mappedBy = "tifncrhrTipoCargaHoraria")
	public List<TipoFuncionCargaHoraria> getTicrhrTipoFuncionCargaHorarias() {
		return this.ticrhrTipoFuncionCargaHorarias;
	}

	public void setTicrhrTipoFuncionCargaHorarias(List<TipoFuncionCargaHoraria> ticrhrTipoFuncionCargaHorarias) {
		this.ticrhrTipoFuncionCargaHorarias = ticrhrTipoFuncionCargaHorarias;
	}

}
