package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoFinanciamiento generated by hbm2java
 */
@Entity
@Table(name = "TIPO_FINANCIAMIENTO", schema = ConstantesJpa.SCHEMA)
public class TipoFinanciamiento implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7861217562590676358L;
	private int tifnId;
	private String tifnDescripcion;
	private List<Contrato> tifnContratos = new ArrayList<Contrato>(0);

	public TipoFinanciamiento() {
	}

	public TipoFinanciamiento(int tifnId) {
		this.tifnId = tifnId;
	}

	public TipoFinanciamiento(int tifnId, String tifnDescripcion, List<Contrato> tifnContratos) {
		this.tifnId = tifnId;
		this.tifnDescripcion = tifnDescripcion;
		this.tifnContratos = tifnContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIFN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTifnId() {
		return this.tifnId;
	}

	public void setTifnId(int tifnId) {
		this.tifnId = tifnId;
	}

	@Column(name = "TIFN_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getTifnDescripcion() {
		return this.tifnDescripcion;
	}

	public void setTifnDescripcion(String tifnDescripcion) {
		this.tifnDescripcion = tifnDescripcion;
	}

	@OneToMany( mappedBy = "cntTipoFinanciamiento")
	public List<Contrato> getTifnContratos() {
		return this.tifnContratos;
	}

	public void setTifnContratos(List<Contrato> tifnContratos) {
		this.tifnContratos = tifnContratos;
	}

}
