package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoSede generated by hbm2java
 */
@Entity
@Table(name = "TIPO_SEDE", schema = ConstantesJpa.SCHEMA)
public class TipoSede implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5958749836708560200L;
	private int tiseId;
	private RegimenAcademico tiseRegimenAcademico;
	private String tiseDescripcion;
	private List<ConfiguracionCarrera> tiseConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public TipoSede() {
	}

	public TipoSede(int tiseId) {
		this.tiseId = tiseId;
	}

	public TipoSede(int tiseId, RegimenAcademico tiseRegimenAcademico, String tiseDescripcion,
			List<ConfiguracionCarrera> tiseConfiguracionCarreras) {
		this.tiseId = tiseId;
		this.tiseRegimenAcademico = tiseRegimenAcademico;
		this.tiseDescripcion = tiseDescripcion;
		this.tiseConfiguracionCarreras = tiseConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TISE_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTiseId() {
		return this.tiseId;
	}

	public void setTiseId(int tiseId) {
		this.tiseId = tiseId;
	}

	@ManyToOne
	@JoinColumn(name = "RGAC_ID")
	public RegimenAcademico getTiseRegimenAcademico() {
		return this.tiseRegimenAcademico;
	}

	public void setTiseRegimenAcademico(RegimenAcademico tiseRegimenAcademico) {
		this.tiseRegimenAcademico = tiseRegimenAcademico;
	}

	@Column(name = "TISE_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getTiseDescripcion() {
		return this.tiseDescripcion;
	}

	public void setTiseDescripcion(String tiseDescripcion) {
		this.tiseDescripcion = tiseDescripcion;
	}

	@OneToMany( mappedBy = "cncrTipoSede")
	public List<ConfiguracionCarrera> getTiseConfiguracionCarreras() {
		return this.tiseConfiguracionCarreras;
	}

	public void setTiseConfiguracionCarreras(List<ConfiguracionCarrera> tiseConfiguracionCarreras) {
		this.tiseConfiguracionCarreras = tiseConfiguracionCarreras;
	}

}
