package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "TIPO_DOCUMENTO", schema = ConstantesJpa.SCHEMA)
public class TipoDocumento implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2503048454088121758L;
	private int tidcId;
	private TipoDocumento tidcTipoDocumento;
	private String tidcDescripcion;
	private String tidcNumeroDocumento;
	private Date tidcFechaInicio;
	private Date tidcFechaFin;
	private Integer tidcIngresoConcurso;
	private List<DetallePuesto> tidcDetallePuestos = new ArrayList<DetallePuesto>(0);
	private List<TipoDocumento> tidcTipoDocumentos = new ArrayList<TipoDocumento>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(int tidcId) {
		this.tidcId = tidcId;
	}

	public TipoDocumento(int tidcId, TipoDocumento tidcTipoDocumento, String tidcDescripcion, String tidcNumeroDocumento,
			Date tidcFechaInicio, Date tidcFechaFin, Integer tidcIngresoConcurso, List<DetallePuesto> tidcDetallePuestos,
			List<TipoDocumento> tidcTipoDocumentos) {
		this.tidcId = tidcId;
		this.tidcTipoDocumento = tidcTipoDocumento;
		this.tidcDescripcion = tidcDescripcion;
		this.tidcNumeroDocumento = tidcNumeroDocumento;
		this.tidcFechaInicio = tidcFechaInicio;
		this.tidcFechaFin = tidcFechaFin;
		this.tidcIngresoConcurso = tidcIngresoConcurso;
		this.tidcDetallePuestos = tidcDetallePuestos;
		this.tidcTipoDocumentos = tidcTipoDocumentos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIDC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTidcId() {
		return this.tidcId;
	}

	public void setTidcId(int tidcId) {
		this.tidcId = tidcId;
	}

	@ManyToOne
	@JoinColumn(name = "TIDC_SUB_ID")
	public TipoDocumento getTidcTipoDocumento() {
		return this.tidcTipoDocumento;
	}

	public void setTidcTipoDocumento(TipoDocumento tidcTipoDocumento) {
		this.tidcTipoDocumento = tidcTipoDocumento;
	}

	@Column(name = "TIDC_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getTidcDescripcion() {
		return this.tidcDescripcion;
	}

	public void setTidcDescripcion(String tidcDescripcion) {
		this.tidcDescripcion = tidcDescripcion;
	}

	@Column(name = "TIDC_NUMERO_DOCUMENTO", length = 256)
	@Length(max = 256)
	public String getTidcNumeroDocumento() {
		return this.tidcNumeroDocumento;
	}

	public void setTidcNumeroDocumento(String tidcNumeroDocumento) {
		this.tidcNumeroDocumento = tidcNumeroDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIDC_FECHA_INICIO", length = 7)
	public Date getTidcFechaInicio() {
		return this.tidcFechaInicio;
	}

	public void setTidcFechaInicio(Date tidcFechaInicio) {
		this.tidcFechaInicio = tidcFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TIDC_FECHA_FIN", length = 7)
	public Date getTidcFechaFin() {
		return this.tidcFechaFin;
	}

	public void setTidcFechaFin(Date tidcFechaFin) {
		this.tidcFechaFin = tidcFechaFin;
	}

	@Column(name = "TIDC_INGRESO_CONCURSO", precision = 22, scale = 0)
	public Integer getTidcIngresoConcurso() {
		return this.tidcIngresoConcurso;
	}

	public void setTidcIngresoConcurso(Integer tidcIngresoConcurso) {
		this.tidcIngresoConcurso = tidcIngresoConcurso;
	}

	@OneToMany( mappedBy = "dtpsTipoDocumento")
	public List<DetallePuesto> getTidcDetallePuestos() {
		return this.tidcDetallePuestos;
	}

	public void setTidcDetallePuestos(List<DetallePuesto> tidcDetallePuestos) {
		this.tidcDetallePuestos = tidcDetallePuestos;
	}

	@OneToMany( mappedBy = "tidcTipoDocumento")
	public List<TipoDocumento> getTidcTipoDocumentos() {
		return this.tidcTipoDocumentos;
	}

	public void setTidcTipoDocumentos(List<TipoDocumento> tidcTipoDocumentos) {
		this.tidcTipoDocumentos = tidcTipoDocumentos;
	}

}
