package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoFormacion generated by hbm2java
 */
@Entity
@Table(name = "TIPO_FORMACION", schema = ConstantesJpa.SCHEMA)
public class TipoFormacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2467434068855288196L;
	private int tifrId;
	private NivelFormacion tifrNivelFormacion;
	private String tifrDescripcion;
	private List<ConfiguracionCarrera> tifrConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public TipoFormacion() {
	}

	public TipoFormacion(int tifrId) {
		this.tifrId = tifrId;
	}

	public TipoFormacion(int tifrId, NivelFormacion tifrNivelFormacion, String tifrDescripcion,
			List<ConfiguracionCarrera> tifrConfiguracionCarreras) {
		this.tifrId = tifrId;
		this.tifrNivelFormacion = tifrNivelFormacion;
		this.tifrDescripcion = tifrDescripcion;
		this.tifrConfiguracionCarreras = tifrConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIFR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTifrId() {
		return this.tifrId;
	}

	public void setTifrId(int tifrId) {
		this.tifrId = tifrId;
	}

	@ManyToOne
	@JoinColumn(name = "NVFR_ID")
	public NivelFormacion getTifrNivelFormacion() {
		return this.tifrNivelFormacion;
	}

	public void setTifrNivelFormacion(NivelFormacion tifrNivelFormacion) {
		this.tifrNivelFormacion = tifrNivelFormacion;
	}

	@Column(name = "TIFR_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getTifrDescripcion() {
		return this.tifrDescripcion;
	}

	public void setTifrDescripcion(String tifrDescripcion) {
		this.tifrDescripcion = tifrDescripcion;
	}

	@OneToMany( mappedBy = "cncrTipoFormacion")
	public List<ConfiguracionCarrera> getTifrConfiguracionCarreras() {
		return this.tifrConfiguracionCarreras;
	}

	public void setTifrConfiguracionCarreras(List<ConfiguracionCarrera> tifrConfiguracionCarreras) {
		this.tifrConfiguracionCarreras = tifrConfiguracionCarreras;
	}

}
