package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * TipoGratuidad generated by hbm2java
 */
@Entity
@Table(name = "TIPO_GRATUIDAD", schema = ConstantesJpa.SCHEMA)
public class TipoGratuidad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3817902084437925254L;
	private int tigrId;
	private String tigrDescripcion;
	private Integer tigrEstado;
	private List<Gratuidad> tigrGratuidads = new ArrayList<Gratuidad>(0);
	private List<Arancel> tigrArancels = new ArrayList<Arancel>(0);
	private List<PorcentajeGratuidad> tigrPorcentajeGratuidads = new ArrayList<PorcentajeGratuidad>(0);

	public TipoGratuidad() {
	}

	public TipoGratuidad(int tigrId) {
		this.tigrId = tigrId;
	}

	public TipoGratuidad(int tigrId, Integer tigrTipo, String tigrDescripcion, Integer tigrEstado,
			List<Gratuidad> tigrGratuidads, List<Arancel> tigrArancels, List<PorcentajeGratuidad> tigrPorcentajeGratuidads) {
		this.tigrId = tigrId;
		this.tigrDescripcion = tigrDescripcion;
		this.tigrEstado = tigrEstado;
		this.tigrGratuidads = tigrGratuidads;
		this.tigrArancels = tigrArancels;
		this.tigrPorcentajeGratuidads = tigrPorcentajeGratuidads;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TIGR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTigrId() {
		return this.tigrId;
	}

	public void setTigrId(int tigrId) {
		this.tigrId = tigrId;
	}


	@Column(name = "TIGR_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getTigrDescripcion() {
		return this.tigrDescripcion;
	}

	public void setTigrDescripcion(String tigrDescripcion) {
		this.tigrDescripcion = tigrDescripcion;
	}

	@Column(name = "TIGR_ESTADO", precision = 22, scale = 0)
	public Integer getTigrEstado() {
		return this.tigrEstado;
	}

	public void setTigrEstado(Integer tigrEstado) {
		this.tigrEstado = tigrEstado;
	}

	@OneToMany( mappedBy = "grtTipoGratuidad")
	public List<Gratuidad> getTigrGratuidads() {
		return this.tigrGratuidads;
	}

	public void setTigrGratuidads(List<Gratuidad> tigrGratuidads) {
		this.tigrGratuidads = tigrGratuidads;
	}

	@OneToMany( mappedBy = "arnTipoGratuidad")
	public List<Arancel> getTigrArancels() {
		return this.tigrArancels;
	}

	public void setTigrArancels(List<Arancel> tigrArancels) {
		this.tigrArancels = tigrArancels;
	}

	@OneToMany( mappedBy = "prgrTipoGratuidad", fetch=FetchType.EAGER)
	public List<PorcentajeGratuidad> getTigrPorcentajeGratuidads() {
		return this.tigrPorcentajeGratuidads;
	}

	public void setTigrPorcentajeGratuidads(List<PorcentajeGratuidad> tigrPorcentajeGratuidads) {
		this.tigrPorcentajeGratuidads = tigrPorcentajeGratuidads;
	}

}
