package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name = "TITULO", schema = ConstantesJpa.SCHEMA)
public class Titulo implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1751911300441279751L;
	private int ttlId;
	private String ttlDescripcion;
	private Integer ttlSexo;
	private Integer ttlEstado;
	private Integer ttlTipo;
	private List<ConfiguracionCarrera> ttlConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public Titulo() {
	}

	public Titulo(int ttlId) {
		this.ttlId = ttlId;
	}

	public Titulo(int ttlId, String ttlDescripcion, Integer ttlSexo, Integer ttlEstado, Integer ttlTipo,
			List<ConfiguracionCarrera> ttlConfiguracionCarreras) {
		this.ttlId = ttlId;
		this.ttlDescripcion = ttlDescripcion;
		this.ttlSexo = ttlSexo;
		this.ttlEstado = ttlEstado;
		this.ttlTipo = ttlTipo;
		this.ttlConfiguracionCarreras = ttlConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
	@Column(name = "TTL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTtlId() {
		return this.ttlId;
	}

	public void setTtlId(int ttlId) {
		this.ttlId = ttlId;
	}

	@Column(name = "TTL_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getTtlDescripcion() {
		return this.ttlDescripcion;
	}

	public void setTtlDescripcion(String ttlDescripcion) {
		this.ttlDescripcion = ttlDescripcion;
	}

	@Column(name = "TTL_SEXO", precision = 22, scale = 0)
	public Integer getTtlSexo() {
		return this.ttlSexo;
	}

	public void setTtlSexo(Integer ttlSexo) {
		this.ttlSexo = ttlSexo;
	}

	@Column(name = "TTL_ESTADO", precision = 22, scale = 0)
	public Integer getTtlEstado() {
		return this.ttlEstado;
	}

	public void setTtlEstado(Integer ttlEstado) {
		this.ttlEstado = ttlEstado;
	}

	@Column(name = "TTL_TIPO", precision = 22, scale = 0)
	public Integer getTtlTipo() {
		return this.ttlTipo;
	}

	public void setTtlTipo(Integer ttlTipo) {
		this.ttlTipo = ttlTipo;
	}
	@OneToMany( mappedBy = "cncrTitulo")
	public List<ConfiguracionCarrera> getTtlConfiguracionCarreras() {
		return this.ttlConfiguracionCarreras;
	}

	public void setTtlConfiguracionCarreras(List<ConfiguracionCarrera> ttlConfiguracionCarreras) {
		this.ttlConfiguracionCarreras = ttlConfiguracionCarreras;
	}

}
