package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name = "TRAMITE", schema = ConstantesJpa.SCHEMA)
public class Tramite implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -9080964941783903602L;
	private int trmId;
	private String trmDescripcion;
	private Integer trmEstado;
	private List<DetalleTramiteContrato> trmDetalleTramiteContratos = new ArrayList<DetalleTramiteContrato>(0);

	public Tramite() {
	}

	public Tramite(int trmId) {
		this.trmId = trmId;
	}

	public Tramite(int trmId, String trmDescripcion, Integer trmEstado,
			List<DetalleTramiteContrato> trmDetalleTramiteContratos) {
		this.trmId = trmId;
		this.trmDescripcion = trmDescripcion;
		this.trmEstado = trmEstado;
		this.trmDetalleTramiteContratos = trmDetalleTramiteContratos;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TRM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTrmId() {
		return this.trmId;
	}

	public void setTrmId(int trmId) {
		this.trmId = trmId;
	}

	@Column(name = "TRM_DESCRIPCION", length = 512)
	@Length(max = 512)
	public String getTrmDescripcion() {
		return this.trmDescripcion;
	}

	public void setTrmDescripcion(String trmDescripcion) {
		this.trmDescripcion = trmDescripcion;
	}

	@Column(name = "TRM_ESTADO", precision = 22, scale = 0)
	public Integer getTrmEstado() {
		return this.trmEstado;
	}

	public void setTrmEstado(Integer trmEstado) {
		this.trmEstado = trmEstado;
	}

	@OneToMany( mappedBy = "dttrcnTramite")
	public List<DetalleTramiteContrato> getTrmDetalleTramiteContratos() {
		return this.trmDetalleTramiteContratos;
	}

	public void setTrmDetalleTramiteContratos(List<DetalleTramiteContrato> trmDetalleTramiteContratos) {
		this.trmDetalleTramiteContratos = trmDetalleTramiteContratos;
	}

}
