package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Turnero generated by hbm2java
 */
@Entity
@Table(name = "TURNERO", schema = ConstantesJpa.SCHEMA)
public class Turnero implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5290683008688443142L;
	private int trnId;
	private ProcesoTramiteContrato trnProcesoTramiteContrato;
	private UsuarioRol trnUsuarioRol;
	private Integer trnEstado;

	public Turnero() {
	}

	public Turnero(int trnId) {
		this.trnId = trnId;
	}

	public Turnero(int trnId, ProcesoTramiteContrato trnProcesoTramiteContrato, UsuarioRol trnUsuarioRol,
			Integer trnEstado) {
		this.trnId = trnId;
		this.trnProcesoTramiteContrato = trnProcesoTramiteContrato;
		this.trnUsuarioRol = trnUsuarioRol;
		this.trnEstado = trnEstado;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "TRN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTrnId() {
		return this.trnId;
	}

	public void setTrnId(int trnId) {
		this.trnId = trnId;
	}

	@ManyToOne
	@JoinColumn(name = "PRTRCN_ID")
	public ProcesoTramiteContrato getTrnProcesoTramiteContrato() {
		return this.trnProcesoTramiteContrato;
	}

	public void setTrnProcesoTramiteContrato(ProcesoTramiteContrato trnProcesoTramiteContrato) {
		this.trnProcesoTramiteContrato = trnProcesoTramiteContrato;
	}

	@ManyToOne
	@JoinColumn(name = "USRO_ID")
	public UsuarioRol getTrnUsuarioRol() {
		return this.trnUsuarioRol;
	}

	public void setTrnUsuarioRol(UsuarioRol trnUsuarioRol) {
		this.trnUsuarioRol = trnUsuarioRol;
	}

	@Column(name = "TRN_ESTADO", precision = 22, scale = 0)
	public Integer getTrnEstado() {
		return this.trnEstado;
	}

	public void setTrnEstado(Integer trnEstado) {
		this.trnEstado = trnEstado;
	}

}
