package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * Ubicacion generated by hbm2java
 */
@Entity
@Table(name = "UBICACION", schema = ConstantesJpa.SCHEMA)
public class Ubicacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8074742382202785305L;
	private int ubcId;
	private Ubicacion ubcUbicacion;
	private String ubcDescripcion;
	private Integer ubcJerarquia;
	private String ubcGentilicio;
	private String ubcCodSniese;
	private List<Dependencia> ubcDependencias = new ArrayList<Dependencia>(0);
	private List<Ubicacion> ubcUbicacions = new ArrayList<Ubicacion>(0);
	private List<InstitucionAcademica> ubcInstitucionAcademicas = new ArrayList<InstitucionAcademica>(0);
	private List<Persona> ubcNacimientoPersonas = new ArrayList<Persona>(0);
	private List<Persona> ubcResidenciaPersonas = new ArrayList<Persona>(0);
	private List<ConfiguracionCarrera> ubcConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public Ubicacion() {
	}

	public Ubicacion(int ubcId) {
		this.ubcId = ubcId;
	}

	public Ubicacion(int ubcId, Ubicacion ubcUbicacion, String ubcDescripcion, Integer ubcJerarquia,
			String ubcGentilicio, String ubcCodSniese, List<Dependencia> ubcDependencias, List<Ubicacion> ubcUbicacions,
			List<InstitucionAcademica> ubcInstitucionAcademicas, List<Persona> ubcNacimientoPersonas, List<Persona> ubcResidenciaPersonas,
			List<ConfiguracionCarrera> ubcConfiguracionCarreras) {
		this.ubcId = ubcId;
		this.ubcUbicacion = ubcUbicacion;
		this.ubcDescripcion = ubcDescripcion;
		this.ubcJerarquia = ubcJerarquia;
		this.ubcGentilicio = ubcGentilicio;
		this.ubcCodSniese = ubcCodSniese;
		this.ubcDependencias = ubcDependencias;
		this.ubcUbicacions = ubcUbicacions;
		this.ubcInstitucionAcademicas = ubcInstitucionAcademicas;
		this.ubcNacimientoPersonas = ubcNacimientoPersonas;
		this.ubcResidenciaPersonas = ubcResidenciaPersonas;
		this.ubcConfiguracionCarreras = ubcConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "UBC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getUbcId() {
		return this.ubcId;
	}

	public void setUbcId(int ubcId) {
		this.ubcId = ubcId;
	}

	@ManyToOne
	@JoinColumn(name = "UBC_SUB_ID")
	public Ubicacion getUbcUbicacion() {
		return this.ubcUbicacion;
	}

	public void setUbcUbicacion(Ubicacion ubcUbicacion) {
		this.ubcUbicacion = ubcUbicacion;
	}

	@Column(name = "UBC_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getUbcDescripcion() {
		return this.ubcDescripcion;
	}

	public void setUbcDescripcion(String ubcDescripcion) {
		this.ubcDescripcion = ubcDescripcion;
	}

	@Column(name = "UBC_JERARQUIA", precision = 22, scale = 0)
	public Integer getUbcJerarquia() {
		return this.ubcJerarquia;
	}

	public void setUbcJerarquia(Integer ubcJerarquia) {
		this.ubcJerarquia = ubcJerarquia;
	}

	@Column(name = "UBC_GENTILICIO", length = 128)
	@Length(max = 128)
	public String getUbcGentilicio() {
		return this.ubcGentilicio;
	}

	public void setUbcGentilicio(String ubcGentilicio) {
		this.ubcGentilicio = ubcGentilicio;
	}

	@Column(name = "UBC_COD_SNIESE", length = 32)
	@Length(max = 32)
	public String getUbcCodSniese() {
		return this.ubcCodSniese;
	}

	public void setUbcCodSniese(String ubcCodSniese) {
		this.ubcCodSniese = ubcCodSniese;
	}

	@OneToMany( mappedBy = "dpnUbicacion")
	public List<Dependencia> getUbcDependencias() {
		return this.ubcDependencias;
	}

	public void setUbcDependencias(List<Dependencia> ubcDependencias) {
		this.ubcDependencias = ubcDependencias;
	}

	@OneToMany( mappedBy = "ubcUbicacion")
	public List<Ubicacion> getUbcUbicacions() {
		return this.ubcUbicacions;
	}

	public void setUbcUbicacions(List<Ubicacion> ubcUbicacions) {
		this.ubcUbicacions = ubcUbicacions;
	}

	@OneToMany( mappedBy = "inacUbicacion")
	public List<InstitucionAcademica> getUbcInstitucionAcademicas() {
		return this.ubcInstitucionAcademicas;
	}

	public void setUbcInstitucionAcademicas(List<InstitucionAcademica> ubcInstitucionAcademicas) {
		this.ubcInstitucionAcademicas = ubcInstitucionAcademicas;
	}

	@OneToMany( mappedBy = "prsUbicacionNacimiento")
	public List<Persona> getUbcNacimientoPersonas() {
		return ubcNacimientoPersonas;
	}

	public void setUbcNacimientoPersonas(List<Persona> ubcNacimientoPersonas) {
		this.ubcNacimientoPersonas = ubcNacimientoPersonas;
	}

	@OneToMany( mappedBy = "prsUbicacionResidencia")
	public List<Persona> getUbcResidenciaPersonas() {
		return ubcResidenciaPersonas;
	}

	public void setUbcResidenciaPersonas(List<Persona> ubcResidenciaPersonas) {
		this.ubcResidenciaPersonas = ubcResidenciaPersonas;
	}
	

	@OneToMany( mappedBy = "cncrUbicacion")
	public List<ConfiguracionCarrera> getUbcConfiguracionCarreras() {
		return this.ubcConfiguracionCarreras;
	}

	public void setUbcConfiguracionCarreras(List<ConfiguracionCarrera> ubcConfiguracionCarreras) {
		this.ubcConfiguracionCarreras = ubcConfiguracionCarreras;
	}

}
