package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**
 * UnidadFormacion generated by hbm2java
 */
@Entity
@Table(name = "UNIDAD_FORMACION", schema = ConstantesJpa.SCHEMA)
public class UnidadFormacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 221029276756179674L;
	private int unfrId;
	private String unfrDescripcion;
	private Integer unfrEstado;
	private List<MallaCurricularMateria> unfrMallaCurricularMaterias = new ArrayList<MallaCurricularMateria>(0);

	public UnidadFormacion() {
	}

	public UnidadFormacion(int unfrId) {
		this.unfrId = unfrId;
	}

	public UnidadFormacion(int unfrId, String unfrDescripcion, Integer unfrEstado,
			List<MallaCurricularMateria> unfrMallaCurricularMaterias) {
		this.unfrId = unfrId;
		this.unfrDescripcion = unfrDescripcion;
		this.unfrEstado = unfrEstado;
		this.unfrMallaCurricularMaterias = unfrMallaCurricularMaterias;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "UNFR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getUnfrId() {
		return this.unfrId;
	}

	public void setUnfrId(int unfrId) {
		this.unfrId = unfrId;
	}

	@Column(name = "UNFR_DESCRIPCION", length = 256)
	@Length(max = 256)
	public String getUnfrDescripcion() {
		return this.unfrDescripcion;
	}

	public void setUnfrDescripcion(String unfrDescripcion) {
		this.unfrDescripcion = unfrDescripcion;
	}

	@Column(name = "UNFR_ESTADO", precision = 22, scale = 0)
	public Integer getUnfrEstado() {
		return this.unfrEstado;
	}

	public void setUnfrEstado(Integer unfrEstado) {
		this.unfrEstado = unfrEstado;
	}

	@OneToMany( mappedBy = "mlcrmtUnidadFormacion")
	public List<MallaCurricularMateria> getUnfrMallaCurricularMaterias() {
		return this.unfrMallaCurricularMaterias;
	}

	public void setUnfrMallaCurricularMaterias(List<MallaCurricularMateria> unfrMallaCurricularMaterias) {
		this.unfrMallaCurricularMaterias = unfrMallaCurricularMaterias;
	}

}
