package ec.edu.uce.academico.jpa.entidades.publico;
// Generated 02/03/2017 8:53:22 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

import ec.edu.uce.academico.jpa.entidades.publico.constantes.ConstantesJpa;

/**	
 * Vigencia generated by hbm2java
 */
@Entity
@Table(name = "VIGENCIA", schema = ConstantesJpa.SCHEMA)
public class Vigencia implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4692058069201852905L;
	private int vgnId;
	private String vgnDescripcion;
	private List<ConfiguracionCarrera> vgnConfiguracionCarreras = new ArrayList<ConfiguracionCarrera>(0);

	public Vigencia() {
	}

	public Vigencia(int vgnId) {
		this.vgnId = vgnId;
	}

	public Vigencia(int vgnId, String vgnDescripcion, List<ConfiguracionCarrera> vgnConfiguracionCarreras) {
		this.vgnId = vgnId;
		this.vgnDescripcion = vgnDescripcion;
		this.vgnConfiguracionCarreras = vgnConfiguracionCarreras;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Basic(optional = false)
	@Column(name = "VGN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getVgnId() {
		return this.vgnId;
	}

	public void setVgnId(int vgnId) {
		this.vgnId = vgnId;
	}

	@Column(name = "VGN_DESCRIPCION", length = 128)
	@Length(max = 128)
	public String getVgnDescripcion() {
		return this.vgnDescripcion;
	}

	public void setVgnDescripcion(String vgnDescripcion) {
		this.vgnDescripcion = vgnDescripcion;
	}

	@OneToMany( mappedBy = "cncrVigencia")
	public List<ConfiguracionCarrera> getVgnConfiguracionCarreras() {
		return this.vgnConfiguracionCarreras;
	}

	public void setVgnConfiguracionCarreras(List<ConfiguracionCarrera> vgnConfiguracionCarreras) {
		this.vgnConfiguracionCarreras = vgnConfiguracionCarreras;
	}

}
