package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HoraClase generated by hbm2java
 */
@Entity
@Table(name = "HORA_CLASE")
public class HoraClase implements java.io.Serializable {

	private int hoclId;
	private String hoclDescripcion;
	private BigDecimal hoclEstado;
	private BigDecimal hoclHoraInicio;
	private BigDecimal hoclHoraFin;
	private Set<HoraClaseAula> horaClaseAulas = new HashSet<HoraClaseAula>(0);
	private Set<HorarioFuncion> horarioFuncions = new HashSet<HorarioFuncion>(0);

	public HoraClase() {
	}

	public HoraClase(int hoclId) {
		this.hoclId = hoclId;
	}

	public HoraClase(int hoclId, String hoclDescripcion, BigDecimal hoclEstado, BigDecimal hoclHoraInicio,
			BigDecimal hoclHoraFin, Set<HoraClaseAula> horaClaseAulas, Set<HorarioFuncion> horarioFuncions) {
		this.hoclId = hoclId;
		this.hoclDescripcion = hoclDescripcion;
		this.hoclEstado = hoclEstado;
		this.hoclHoraInicio = hoclHoraInicio;
		this.hoclHoraFin = hoclHoraFin;
		this.horaClaseAulas = horaClaseAulas;
		this.horarioFuncions = horarioFuncions;
	}

	@Id

	@Column(name = "HOCL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHoclId() {
		return this.hoclId;
	}

	public void setHoclId(int hoclId) {
		this.hoclId = hoclId;
	}

	@Column(name = "HOCL_DESCRIPCION", length = 128)
	public String getHoclDescripcion() {
		return this.hoclDescripcion;
	}

	public void setHoclDescripcion(String hoclDescripcion) {
		this.hoclDescripcion = hoclDescripcion;
	}

	@Column(name = "HOCL_ESTADO", precision = 22, scale = 0)
	public BigDecimal getHoclEstado() {
		return this.hoclEstado;
	}

	public void setHoclEstado(BigDecimal hoclEstado) {
		this.hoclEstado = hoclEstado;
	}

	@Column(name = "HOCL_HORA_INICIO", precision = 22, scale = 0)
	public BigDecimal getHoclHoraInicio() {
		return this.hoclHoraInicio;
	}

	public void setHoclHoraInicio(BigDecimal hoclHoraInicio) {
		this.hoclHoraInicio = hoclHoraInicio;
	}

	@Column(name = "HOCL_HORA_FIN", precision = 22, scale = 0)
	public BigDecimal getHoclHoraFin() {
		return this.hoclHoraFin;
	}

	public void setHoclHoraFin(BigDecimal hoclHoraFin) {
		this.hoclHoraFin = hoclHoraFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horaClase")
	public Set<HoraClaseAula> getHoraClaseAulas() {
		return this.horaClaseAulas;
	}

	public void setHoraClaseAulas(Set<HoraClaseAula> horaClaseAulas) {
		this.horaClaseAulas = horaClaseAulas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horaClase")
	public Set<HorarioFuncion> getHorarioFuncions() {
		return this.horarioFuncions;
	}

	public void setHorarioFuncions(Set<HorarioFuncion> horarioFuncions) {
		this.horarioFuncions = horarioFuncions;
	}

}
