package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FichaMatricula generated by hbm2java
 */
@Entity
@Table(name = "FICHA_MATRICULA")
public class FichaMatricula implements java.io.Serializable {

	private BigDecimal fcmtId;
	private PlanificacionCronograma planificacionCronograma;
	private FichaEstudiante fichaEstudiante;
	private BigDecimal fcmtNivelUbicacion;
	private BigDecimal fcmtEstado;
	private Date fcmtFechaConvalidacion;
	private BigDecimal fcmtTipo;
	private BigDecimal fcmtModalidad;
	private BigDecimal fcmtValorTotal;
	private Serializable fcmtFechaMatricula;
	private Serializable fcmtFechaEstado;
	private Short fcmtPracId;
	private Set<ComprobantePago> comprobantePagos = new HashSet<ComprobantePago>(0);

	public FichaMatricula() {
	}

	public FichaMatricula(BigDecimal fcmtId, PlanificacionCronograma planificacionCronograma,
			FichaEstudiante fichaEstudiante) {
		this.fcmtId = fcmtId;
		this.planificacionCronograma = planificacionCronograma;
		this.fichaEstudiante = fichaEstudiante;
	}

	public FichaMatricula(BigDecimal fcmtId, PlanificacionCronograma planificacionCronograma,
			FichaEstudiante fichaEstudiante, BigDecimal fcmtNivelUbicacion, BigDecimal fcmtEstado,
			Date fcmtFechaConvalidacion, BigDecimal fcmtTipo, BigDecimal fcmtModalidad, BigDecimal fcmtValorTotal,
			Serializable fcmtFechaMatricula, Serializable fcmtFechaEstado, Short fcmtPracId,
			Set<ComprobantePago> comprobantePagos) {
		this.fcmtId = fcmtId;
		this.planificacionCronograma = planificacionCronograma;
		this.fichaEstudiante = fichaEstudiante;
		this.fcmtNivelUbicacion = fcmtNivelUbicacion;
		this.fcmtEstado = fcmtEstado;
		this.fcmtFechaConvalidacion = fcmtFechaConvalidacion;
		this.fcmtTipo = fcmtTipo;
		this.fcmtModalidad = fcmtModalidad;
		this.fcmtValorTotal = fcmtValorTotal;
		this.fcmtFechaMatricula = fcmtFechaMatricula;
		this.fcmtFechaEstado = fcmtFechaEstado;
		this.fcmtPracId = fcmtPracId;
		this.comprobantePagos = comprobantePagos;
	}

	@Id

	@Column(name = "FCMT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getFcmtId() {
		return this.fcmtId;
	}

	public void setFcmtId(BigDecimal fcmtId) {
		this.fcmtId = fcmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLCR_ID", nullable = false)
	public PlanificacionCronograma getPlanificacionCronograma() {
		return this.planificacionCronograma;
	}

	public void setPlanificacionCronograma(PlanificacionCronograma planificacionCronograma) {
		this.planificacionCronograma = planificacionCronograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCES_ID", nullable = false)
	public FichaEstudiante getFichaEstudiante() {
		return this.fichaEstudiante;
	}

	public void setFichaEstudiante(FichaEstudiante fichaEstudiante) {
		this.fichaEstudiante = fichaEstudiante;
	}

	@Column(name = "FCMT_NIVEL_UBICACION", precision = 22, scale = 0)
	public BigDecimal getFcmtNivelUbicacion() {
		return this.fcmtNivelUbicacion;
	}

	public void setFcmtNivelUbicacion(BigDecimal fcmtNivelUbicacion) {
		this.fcmtNivelUbicacion = fcmtNivelUbicacion;
	}

	@Column(name = "FCMT_ESTADO", precision = 22, scale = 0)
	public BigDecimal getFcmtEstado() {
		return this.fcmtEstado;
	}

	public void setFcmtEstado(BigDecimal fcmtEstado) {
		this.fcmtEstado = fcmtEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FCMT_FECHA_CONVALIDACION", length = 7)
	public Date getFcmtFechaConvalidacion() {
		return this.fcmtFechaConvalidacion;
	}

	public void setFcmtFechaConvalidacion(Date fcmtFechaConvalidacion) {
		this.fcmtFechaConvalidacion = fcmtFechaConvalidacion;
	}

	@Column(name = "FCMT_TIPO", precision = 22, scale = 0)
	public BigDecimal getFcmtTipo() {
		return this.fcmtTipo;
	}

	public void setFcmtTipo(BigDecimal fcmtTipo) {
		this.fcmtTipo = fcmtTipo;
	}

	@Column(name = "FCMT_MODALIDAD", precision = 22, scale = 0)
	public BigDecimal getFcmtModalidad() {
		return this.fcmtModalidad;
	}

	public void setFcmtModalidad(BigDecimal fcmtModalidad) {
		this.fcmtModalidad = fcmtModalidad;
	}

	@Column(name = "FCMT_VALOR_TOTAL", precision = 8)
	public BigDecimal getFcmtValorTotal() {
		return this.fcmtValorTotal;
	}

	public void setFcmtValorTotal(BigDecimal fcmtValorTotal) {
		this.fcmtValorTotal = fcmtValorTotal;
	}

	@Column(name = "FCMT_FECHA_MATRICULA")
	public Serializable getFcmtFechaMatricula() {
		return this.fcmtFechaMatricula;
	}

	public void setFcmtFechaMatricula(Serializable fcmtFechaMatricula) {
		this.fcmtFechaMatricula = fcmtFechaMatricula;
	}

	@Column(name = "FCMT_FECHA_ESTADO")
	public Serializable getFcmtFechaEstado() {
		return this.fcmtFechaEstado;
	}

	public void setFcmtFechaEstado(Serializable fcmtFechaEstado) {
		this.fcmtFechaEstado = fcmtFechaEstado;
	}

	@Column(name = "FCMT_PRAC_ID", precision = 3, scale = 0)
	public Short getFcmtPracId() {
		return this.fcmtPracId;
	}

	public void setFcmtPracId(Short fcmtPracId) {
		this.fcmtPracId = fcmtPracId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaMatricula")
	public Set<ComprobantePago> getComprobantePagos() {
		return this.comprobantePagos;
	}

	public void setComprobantePagos(Set<ComprobantePago> comprobantePagos) {
		this.comprobantePagos = comprobantePagos;
	}

}
