package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FichaEmpleado generated by hbm2java
 */
@Entity
@Table(name = "FICHA_EMPLEADO")
public class FichaEmpleado implements java.io.Serializable {

	private int fcemId;
	private Persona persona;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public FichaEmpleado() {
	}

	public FichaEmpleado(int fcemId) {
		this.fcemId = fcemId;
	}

	public FichaEmpleado(int fcemId, Persona persona, Set<DetallePuesto> detallePuestos, Set<Usuario> usuarios) {
		this.fcemId = fcemId;
		this.persona = persona;
		this.detallePuestos = detallePuestos;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "FCEM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFcemId() {
		return this.fcemId;
	}

	public void setFcemId(int fcemId) {
		this.fcemId = fcemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEmpleado")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEmpleado")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
