package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InstitucionAcademica generated by hbm2java
 */
@Entity
@Table(name = "INSTITUCION_ACADEMICA")
public class InstitucionAcademica implements java.io.Serializable {

	private int inacId;
	private Ubicacion ubicacion;
	private String inacCodigoSniese;
	private String inacDescripcion;
	private BigDecimal inacNivel;
	private BigDecimal inacTipo;
	private String inacTipoSniese;
	private Set<FichaEstudiante> fichaEstudiantes = new HashSet<FichaEstudiante>(0);

	public InstitucionAcademica() {
	}

	public InstitucionAcademica(int inacId, Ubicacion ubicacion) {
		this.inacId = inacId;
		this.ubicacion = ubicacion;
	}

	public InstitucionAcademica(int inacId, Ubicacion ubicacion, String inacCodigoSniese, String inacDescripcion,
			BigDecimal inacNivel, BigDecimal inacTipo, String inacTipoSniese, Set<FichaEstudiante> fichaEstudiantes) {
		this.inacId = inacId;
		this.ubicacion = ubicacion;
		this.inacCodigoSniese = inacCodigoSniese;
		this.inacDescripcion = inacDescripcion;
		this.inacNivel = inacNivel;
		this.inacTipo = inacTipo;
		this.inacTipoSniese = inacTipoSniese;
		this.fichaEstudiantes = fichaEstudiantes;
	}

	@Id

	@Column(name = "INAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getInacId() {
		return this.inacId;
	}

	public void setInacId(int inacId) {
		this.inacId = inacId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UBC_ID", nullable = false)
	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "INAC_CODIGO_SNIESE", length = 6)
	public String getInacCodigoSniese() {
		return this.inacCodigoSniese;
	}

	public void setInacCodigoSniese(String inacCodigoSniese) {
		this.inacCodigoSniese = inacCodigoSniese;
	}

	@Column(name = "INAC_DESCRIPCION", length = 512)
	public String getInacDescripcion() {
		return this.inacDescripcion;
	}

	public void setInacDescripcion(String inacDescripcion) {
		this.inacDescripcion = inacDescripcion;
	}

	@Column(name = "INAC_NIVEL", precision = 22, scale = 0)
	public BigDecimal getInacNivel() {
		return this.inacNivel;
	}

	public void setInacNivel(BigDecimal inacNivel) {
		this.inacNivel = inacNivel;
	}

	@Column(name = "INAC_TIPO", precision = 22, scale = 0)
	public BigDecimal getInacTipo() {
		return this.inacTipo;
	}

	public void setInacTipo(BigDecimal inacTipo) {
		this.inacTipo = inacTipo;
	}

	@Column(name = "INAC_TIPO_SNIESE", length = 4)
	public String getInacTipoSniese() {
		return this.inacTipoSniese;
	}

	public void setInacTipoSniese(String inacTipoSniese) {
		this.inacTipoSniese = inacTipoSniese;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institucionAcademica")
	public Set<FichaEstudiante> getFichaEstudiantes() {
		return this.fichaEstudiantes;
	}

	public void setFichaEstudiantes(Set<FichaEstudiante> fichaEstudiantes) {
		this.fichaEstudiantes = fichaEstudiantes;
	}

}
