package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCargaHoraria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CARGA_HORARIA")
public class TipoCargaHoraria implements java.io.Serializable {

	private int ticrhrId;
	private String ticrhrDescripcion;
	private BigDecimal ticrhrEstado;
	private Set<TipoFuncionCargaHoraria> tipoFuncionCargaHorarias = new HashSet<TipoFuncionCargaHoraria>(0);

	public TipoCargaHoraria() {
	}

	public TipoCargaHoraria(int ticrhrId) {
		this.ticrhrId = ticrhrId;
	}

	public TipoCargaHoraria(int ticrhrId, String ticrhrDescripcion, BigDecimal ticrhrEstado,
			Set<TipoFuncionCargaHoraria> tipoFuncionCargaHorarias) {
		this.ticrhrId = ticrhrId;
		this.ticrhrDescripcion = ticrhrDescripcion;
		this.ticrhrEstado = ticrhrEstado;
		this.tipoFuncionCargaHorarias = tipoFuncionCargaHorarias;
	}

	@Id

	@Column(name = "TICRHR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTicrhrId() {
		return this.ticrhrId;
	}

	public void setTicrhrId(int ticrhrId) {
		this.ticrhrId = ticrhrId;
	}

	@Column(name = "TICRHR_DESCRIPCION", length = 128)
	public String getTicrhrDescripcion() {
		return this.ticrhrDescripcion;
	}

	public void setTicrhrDescripcion(String ticrhrDescripcion) {
		this.ticrhrDescripcion = ticrhrDescripcion;
	}

	@Column(name = "TICRHR_ESTADO", precision = 22, scale = 0)
	public BigDecimal getTicrhrEstado() {
		return this.ticrhrEstado;
	}

	public void setTicrhrEstado(BigDecimal ticrhrEstado) {
		this.ticrhrEstado = ticrhrEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCargaHoraria")
	public Set<TipoFuncionCargaHoraria> getTipoFuncionCargaHorarias() {
		return this.tipoFuncionCargaHorarias;
	}

	public void setTipoFuncionCargaHorarias(Set<TipoFuncionCargaHoraria> tipoFuncionCargaHorarias) {
		this.tipoFuncionCargaHorarias = tipoFuncionCargaHorarias;
	}

}
