package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HorarioAcademico generated by hbm2java
 */
@Entity
@Table(name = "HORARIO_ACADEMICO")
public class HorarioAcademico implements java.io.Serializable {

	private int hracId;
	private MallaCurricularParalelo mallaCurricularParalelo;
	private HoraClaseAula horaClaseAula;
	private String hracDescripcion;
	private BigDecimal hracDia;
	private BigDecimal hracHoraInicio;
	private BigDecimal hracHoraFin;
	private BigDecimal hracEstado;
	private BigDecimal mlcrprIdComp;
	private BigDecimal hracHoraTipo;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public HorarioAcademico() {
	}

	public HorarioAcademico(int hracId) {
		this.hracId = hracId;
	}

	public HorarioAcademico(int hracId, MallaCurricularParalelo mallaCurricularParalelo, HoraClaseAula horaClaseAula,
			String hracDescripcion, BigDecimal hracDia, BigDecimal hracHoraInicio, BigDecimal hracHoraFin,
			BigDecimal hracEstado, BigDecimal mlcrprIdComp, BigDecimal hracHoraTipo, Set<Asistencia> asistencias) {
		this.hracId = hracId;
		this.mallaCurricularParalelo = mallaCurricularParalelo;
		this.horaClaseAula = horaClaseAula;
		this.hracDescripcion = hracDescripcion;
		this.hracDia = hracDia;
		this.hracHoraInicio = hracHoraInicio;
		this.hracHoraFin = hracHoraFin;
		this.hracEstado = hracEstado;
		this.mlcrprIdComp = mlcrprIdComp;
		this.hracHoraTipo = hracHoraTipo;
		this.asistencias = asistencias;
	}

	@Id

	@Column(name = "HRAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHracId() {
		return this.hracId;
	}

	public void setHracId(int hracId) {
		this.hracId = hracId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MLCRPR_ID")
	public MallaCurricularParalelo getMallaCurricularParalelo() {
		return this.mallaCurricularParalelo;
	}

	public void setMallaCurricularParalelo(MallaCurricularParalelo mallaCurricularParalelo) {
		this.mallaCurricularParalelo = mallaCurricularParalelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HOCLAL_ID")
	public HoraClaseAula getHoraClaseAula() {
		return this.horaClaseAula;
	}

	public void setHoraClaseAula(HoraClaseAula horaClaseAula) {
		this.horaClaseAula = horaClaseAula;
	}

	@Column(name = "HRAC_DESCRIPCION", length = 256)
	public String getHracDescripcion() {
		return this.hracDescripcion;
	}

	public void setHracDescripcion(String hracDescripcion) {
		this.hracDescripcion = hracDescripcion;
	}

	@Column(name = "HRAC_DIA", precision = 38, scale = 0)
	public BigDecimal getHracDia() {
		return this.hracDia;
	}

	public void setHracDia(BigDecimal hracDia) {
		this.hracDia = hracDia;
	}

	@Column(name = "HRAC_HORA_INICIO", precision = 38, scale = 0)
	public BigDecimal getHracHoraInicio() {
		return this.hracHoraInicio;
	}

	public void setHracHoraInicio(BigDecimal hracHoraInicio) {
		this.hracHoraInicio = hracHoraInicio;
	}

	@Column(name = "HRAC_HORA_FIN", precision = 38, scale = 0)
	public BigDecimal getHracHoraFin() {
		return this.hracHoraFin;
	}

	public void setHracHoraFin(BigDecimal hracHoraFin) {
		this.hracHoraFin = hracHoraFin;
	}

	@Column(name = "HRAC_ESTADO", precision = 38, scale = 0)
	public BigDecimal getHracEstado() {
		return this.hracEstado;
	}

	public void setHracEstado(BigDecimal hracEstado) {
		this.hracEstado = hracEstado;
	}

	@Column(name = "MLCRPR_ID_COMP", precision = 38, scale = 0)
	public BigDecimal getMlcrprIdComp() {
		return this.mlcrprIdComp;
	}

	public void setMlcrprIdComp(BigDecimal mlcrprIdComp) {
		this.mlcrprIdComp = mlcrprIdComp;
	}

	@Column(name = "HRAC_HORA_TIPO", precision = 22, scale = 0)
	public BigDecimal getHracHoraTipo() {
		return this.hracHoraTipo;
	}

	public void setHracHoraTipo(BigDecimal hracHoraTipo) {
		this.hracHoraTipo = hracHoraTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioAcademico")
	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

}
