package model;
// Generated 14/07/2019 16:06:12 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "MATERIA")
public class Materia implements java.io.Serializable {

	private int mtrId;
	private Grupo grupo;
	private TipoMateria tipoMateria;
	private Carrera carrera;
	private Materia materia;
	private String mtrNombre;
	private String mtrCodigo;
	private BigDecimal cmfrId;
	private BigDecimal ncprcrId;
	private String mtrCodigoSniese;
	private String mtrDescripcion;
	private BigDecimal mtrEstado;
	private BigDecimal mtrHoras;
	private BigDecimal mtrIntegradoraHoras;
	private BigDecimal mtrPreProfesionalHoras;
	private BigDecimal mtrHorasCien;
	private BigDecimal mtrRelacionTrabajo;
	private BigDecimal mtrUnidadMedida;
	private BigDecimal mtrCreditos;
	private BigDecimal mtrSeqSau;
	private BigDecimal mtrHorasPracticas;
	private BigDecimal mtrHorasTrabAutonomo;
	private BigDecimal mtrHorasPracSema;
	private BigDecimal mtrHorasAutonoSema;
	private Set<Materia> materias = new HashSet<Materia>(0);
	private Set<MallaCurricularMateria> mallaCurricularMaterias = new HashSet<MallaCurricularMateria>(0);
	private Set<Horario> horarios = new HashSet<Horario>(0);
	private Set<Convalidacion> convalidacions = new HashSet<Convalidacion>(0);

	public Materia() {
	}

	public Materia(int mtrId, Carrera carrera, String mtrCodigo) {
		this.mtrId = mtrId;
		this.carrera = carrera;
		this.mtrCodigo = mtrCodigo;
	}

	public Materia(int mtrId, Grupo grupo, TipoMateria tipoMateria, Carrera carrera, Materia materia, String mtrNombre,
			String mtrCodigo, BigDecimal cmfrId, BigDecimal ncprcrId, String mtrCodigoSniese, String mtrDescripcion,
			BigDecimal mtrEstado, BigDecimal mtrHoras, BigDecimal mtrIntegradoraHoras,
			BigDecimal mtrPreProfesionalHoras, BigDecimal mtrHorasCien, BigDecimal mtrRelacionTrabajo,
			BigDecimal mtrUnidadMedida, BigDecimal mtrCreditos, BigDecimal mtrSeqSau, BigDecimal mtrHorasPracticas,
			BigDecimal mtrHorasTrabAutonomo, BigDecimal mtrHorasPracSema, BigDecimal mtrHorasAutonoSema,
			Set<Materia> materias, Set<MallaCurricularMateria> mallaCurricularMaterias, Set<Horario> horarios,
			Set<Convalidacion> convalidacions) {
		this.mtrId = mtrId;
		this.grupo = grupo;
		this.tipoMateria = tipoMateria;
		this.carrera = carrera;
		this.materia = materia;
		this.mtrNombre = mtrNombre;
		this.mtrCodigo = mtrCodigo;
		this.cmfrId = cmfrId;
		this.ncprcrId = ncprcrId;
		this.mtrCodigoSniese = mtrCodigoSniese;
		this.mtrDescripcion = mtrDescripcion;
		this.mtrEstado = mtrEstado;
		this.mtrHoras = mtrHoras;
		this.mtrIntegradoraHoras = mtrIntegradoraHoras;
		this.mtrPreProfesionalHoras = mtrPreProfesionalHoras;
		this.mtrHorasCien = mtrHorasCien;
		this.mtrRelacionTrabajo = mtrRelacionTrabajo;
		this.mtrUnidadMedida = mtrUnidadMedida;
		this.mtrCreditos = mtrCreditos;
		this.mtrSeqSau = mtrSeqSau;
		this.mtrHorasPracticas = mtrHorasPracticas;
		this.mtrHorasTrabAutonomo = mtrHorasTrabAutonomo;
		this.mtrHorasPracSema = mtrHorasPracSema;
		this.mtrHorasAutonoSema = mtrHorasAutonoSema;
		this.materias = materias;
		this.mallaCurricularMaterias = mallaCurricularMaterias;
		this.horarios = horarios;
		this.convalidacions = convalidacions;
	}

	@Id

	@Column(name = "MTR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getMtrId() {
		return this.mtrId;
	}

	public void setMtrId(int mtrId) {
		this.mtrId = mtrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRP_ID")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIMT_ID")
	public TipoMateria getTipoMateria() {
		return this.tipoMateria;
	}

	public void setTipoMateria(TipoMateria tipoMateria) {
		this.tipoMateria = tipoMateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRR_ID", nullable = false)
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MTR_SUB_ID")
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "MTR_NOMBRE", length = 200)
	public String getMtrNombre() {
		return this.mtrNombre;
	}

	public void setMtrNombre(String mtrNombre) {
		this.mtrNombre = mtrNombre;
	}

	@Column(name = "MTR_CODIGO", nullable = false, length = 256)
	public String getMtrCodigo() {
		return this.mtrCodigo;
	}

	public void setMtrCodigo(String mtrCodigo) {
		this.mtrCodigo = mtrCodigo;
	}

	@Column(name = "CMFR_ID", precision = 38, scale = 0)
	public BigDecimal getCmfrId() {
		return this.cmfrId;
	}

	public void setCmfrId(BigDecimal cmfrId) {
		this.cmfrId = cmfrId;
	}

	@Column(name = "NCPRCR_ID", precision = 38, scale = 0)
	public BigDecimal getNcprcrId() {
		return this.ncprcrId;
	}

	public void setNcprcrId(BigDecimal ncprcrId) {
		this.ncprcrId = ncprcrId;
	}

	@Column(name = "MTR_CODIGO_SNIESE", length = 128)
	public String getMtrCodigoSniese() {
		return this.mtrCodigoSniese;
	}

	public void setMtrCodigoSniese(String mtrCodigoSniese) {
		this.mtrCodigoSniese = mtrCodigoSniese;
	}

	@Column(name = "MTR_DESCRIPCION", length = 512)
	public String getMtrDescripcion() {
		return this.mtrDescripcion;
	}

	public void setMtrDescripcion(String mtrDescripcion) {
		this.mtrDescripcion = mtrDescripcion;
	}

	@Column(name = "MTR_ESTADO", precision = 38, scale = 0)
	public BigDecimal getMtrEstado() {
		return this.mtrEstado;
	}

	public void setMtrEstado(BigDecimal mtrEstado) {
		this.mtrEstado = mtrEstado;
	}

	@Column(name = "MTR_HORAS", precision = 38, scale = 0)
	public BigDecimal getMtrHoras() {
		return this.mtrHoras;
	}

	public void setMtrHoras(BigDecimal mtrHoras) {
		this.mtrHoras = mtrHoras;
	}

	@Column(name = "MTR_INTEGRADORA_HORAS", precision = 38, scale = 0)
	public BigDecimal getMtrIntegradoraHoras() {
		return this.mtrIntegradoraHoras;
	}

	public void setMtrIntegradoraHoras(BigDecimal mtrIntegradoraHoras) {
		this.mtrIntegradoraHoras = mtrIntegradoraHoras;
	}

	@Column(name = "MTR_PRE_PROFESIONAL_HORAS", precision = 38, scale = 0)
	public BigDecimal getMtrPreProfesionalHoras() {
		return this.mtrPreProfesionalHoras;
	}

	public void setMtrPreProfesionalHoras(BigDecimal mtrPreProfesionalHoras) {
		this.mtrPreProfesionalHoras = mtrPreProfesionalHoras;
	}

	@Column(name = "MTR_HORAS_CIEN", precision = 38, scale = 0)
	public BigDecimal getMtrHorasCien() {
		return this.mtrHorasCien;
	}

	public void setMtrHorasCien(BigDecimal mtrHorasCien) {
		this.mtrHorasCien = mtrHorasCien;
	}

	@Column(name = "MTR_RELACION_TRABAJO", precision = 38, scale = 0)
	public BigDecimal getMtrRelacionTrabajo() {
		return this.mtrRelacionTrabajo;
	}

	public void setMtrRelacionTrabajo(BigDecimal mtrRelacionTrabajo) {
		this.mtrRelacionTrabajo = mtrRelacionTrabajo;
	}

	@Column(name = "MTR_UNIDAD_MEDIDA", precision = 38, scale = 0)
	public BigDecimal getMtrUnidadMedida() {
		return this.mtrUnidadMedida;
	}

	public void setMtrUnidadMedida(BigDecimal mtrUnidadMedida) {
		this.mtrUnidadMedida = mtrUnidadMedida;
	}

	@Column(name = "MTR_CREDITOS", precision = 6)
	public BigDecimal getMtrCreditos() {
		return this.mtrCreditos;
	}

	public void setMtrCreditos(BigDecimal mtrCreditos) {
		this.mtrCreditos = mtrCreditos;
	}

	@Column(name = "MTR_SEQ_SAU", precision = 22, scale = 0)
	public BigDecimal getMtrSeqSau() {
		return this.mtrSeqSau;
	}

	public void setMtrSeqSau(BigDecimal mtrSeqSau) {
		this.mtrSeqSau = mtrSeqSau;
	}

	@Column(name = "MTR_HORAS_PRACTICAS", precision = 6)
	public BigDecimal getMtrHorasPracticas() {
		return this.mtrHorasPracticas;
	}

	public void setMtrHorasPracticas(BigDecimal mtrHorasPracticas) {
		this.mtrHorasPracticas = mtrHorasPracticas;
	}

	@Column(name = "MTR_HORAS_TRAB_AUTONOMO", precision = 6)
	public BigDecimal getMtrHorasTrabAutonomo() {
		return this.mtrHorasTrabAutonomo;
	}

	public void setMtrHorasTrabAutonomo(BigDecimal mtrHorasTrabAutonomo) {
		this.mtrHorasTrabAutonomo = mtrHorasTrabAutonomo;
	}

	@Column(name = "MTR_HORAS_PRAC_SEMA", precision = 38, scale = 0)
	public BigDecimal getMtrHorasPracSema() {
		return this.mtrHorasPracSema;
	}

	public void setMtrHorasPracSema(BigDecimal mtrHorasPracSema) {
		this.mtrHorasPracSema = mtrHorasPracSema;
	}

	@Column(name = "MTR_HORAS_AUTONO_SEMA", precision = 6)
	public BigDecimal getMtrHorasAutonoSema() {
		return this.mtrHorasAutonoSema;
	}

	public void setMtrHorasAutonoSema(BigDecimal mtrHorasAutonoSema) {
		this.mtrHorasAutonoSema = mtrHorasAutonoSema;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<MallaCurricularMateria> getMallaCurricularMaterias() {
		return this.mallaCurricularMaterias;
	}

	public void setMallaCurricularMaterias(Set<MallaCurricularMateria> mallaCurricularMaterias) {
		this.mallaCurricularMaterias = mallaCurricularMaterias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Horario> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horario> horarios) {
		this.horarios = horarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Convalidacion> getConvalidacions() {
		return this.convalidacions;
	}

	public void setConvalidacions(Set<Convalidacion> convalidacions) {
		this.convalidacions = convalidacions;
	}

}
