package modle;
// Generated 26/06/2019 18:30:23 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePuesto generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_PUESTO")
public class DetallePuesto implements java.io.Serializable {

	private BigDecimal dtpsId;
	private Carrera carrera;
	private FichaDocente fichaDocente;
	private FichaEmpleado fichaEmpleado;
	private String dtpsEstado;

	public DetallePuesto() {
	}

	public DetallePuesto(BigDecimal dtpsId, Carrera carrera) {
		this.dtpsId = dtpsId;
		this.carrera = carrera;
	}

	public DetallePuesto(BigDecimal dtpsId, Carrera carrera, FichaDocente fichaDocente, FichaEmpleado fichaEmpleado,
			String dtpsEstado) {
		this.dtpsId = dtpsId;
		this.carrera = carrera;
		this.fichaDocente = fichaDocente;
		this.fichaEmpleado = fichaEmpleado;
		this.dtpsEstado = dtpsEstado;
	}

	@Id

	@Column(name = "DTPS_ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getDtpsId() {
		return this.dtpsId;
	}

	public void setDtpsId(BigDecimal dtpsId) {
		this.dtpsId = dtpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRR_ID", nullable = false)
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCDC_ID")
	public FichaDocente getFichaDocente() {
		return this.fichaDocente;
	}

	public void setFichaDocente(FichaDocente fichaDocente) {
		this.fichaDocente = fichaDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCEM_ID")
	public FichaEmpleado getFichaEmpleado() {
		return this.fichaEmpleado;
	}

	public void setFichaEmpleado(FichaEmpleado fichaEmpleado) {
		this.fichaEmpleado = fichaEmpleado;
	}

	@Column(name = "DTPS_ESTADO", length = 20)
	public String getDtpsEstado() {
		return this.dtpsEstado;
	}

	public void setDtpsEstado(String dtpsEstado) {
		this.dtpsEstado = dtpsEstado;
	}

}
