/**************************************************************************
 *				(c) Copyright UNIVERSIDAD CENTRAL DEL ECUADOR. 
 *                            www.uce.edu.ec

 * Este programa de computador es propiedad de la UNIVERSIDAD CENTRAL DEL ECUADOR
 * y esta protegido por las leyes y tratados internacionales de derechos de 
 * autor. El uso, reproducción o distribución no autorizada de este programa, 
 * o cualquier porción de él, puede dar lugar a sanciones criminales y 
 * civiles severas, y serán procesadas con el grado máximo contemplado 
 * por la ley.
 
 ************************************************************************* 
   
 ARCHIVO:     ComprobantePagoConstantes.java	  
 DESCRIPCION: Clase que maneja las constantes de la entidad ComprobantePago 
 *************************************************************************
                           	MODIFICACIONES
                            
 FECHA         		     AUTOR          					COMENTARIOS
 27-03-2017          David Arellano                  Emisión Inicial
 ***************************************************************************/
package ec.edu.uce.academico.ejb.utilidades.constantes;

import java.math.BigDecimal;

/**
 * Clase (constantes) ComprobantePagoConstantes.
 * Clase que maneja las constantes de la entidad ComprobantePago.
 * @author darellano.
 * @version 1.0
 */
public class ComprobantePagoConstantes {
	
	// constantes para el correo del encargado de cargar archivo CSV a servipagos
	public static final String CORREO_FINANCIERO = "cfmichilena@uce.edu.ec";
	// constantes para el correo del encargado de cargar archivo CSV a servipagos de parte de DTIC
	public static final String CORREO_SYSREC_DTIC = "jvrosales@uce.edu.ec";
	public static final String USUARIO_CORREO_FINANCIERO = "ADMINISTRADOR SYSREC";
	
	//constantes que indican SI EL COMPROBANTE_PAGO ESTÁ ACTIVA O NO
	public static final int ESTADO_ACTIVO_VALUE = Integer.valueOf(0);
	public static final String ESTADO_ACTIVO_LABEL = "ACTIVO";
	public static final int ESTADO_INACTIVO_VALUE = Integer.valueOf(1);	
	public static final String ESTADO_INACTIVO_LABEL = "INACTIVO";
	public static final int ESTADO_EMITIDO_VALUE = Integer.valueOf(2);
	public static final String ESTADO_EMITIDO_LABEL = "EMITIDO COMPROBANTE";
	public static final int ESTADO_ENVIADO_VALUE = Integer.valueOf(3);	
	public static final String ESTADO_ENVIADO_LABEL = "ENVIADO SERVIPAGOS";
	public static final int ESTADO_ANULADO_VALUE = Integer.valueOf(4);	
	public static final String ESTADO_ANULADO_LABEL = "ANULADO";
	public static final int ESTADO_PAGADO_VALUE = Integer.valueOf(5);	
	public static final String ESTADO_PAGADO_LABEL = "PAGADO";
	public static final int ESTADO_EDITADO_VALUE = Integer.valueOf(6);	
	public static final String ESTADO_EDITADO_LABEL = "EDITADO";
	public static final int ESTADO_EMITIDO_PREGRADO_VALUE = Integer.valueOf(7);	
	public static final String ESTADO_EMITIDO_PREGRADO_LABEL = "EMITIDO PREGRADO";
	public static final int ESTADO_PAGADO_EN_VENTANILLA_VALUE = Integer.valueOf(8);	
	public static final String ESTADO_PAGADO_EN_VENTANILLA_LABEL = "PAGADO EN VENTANILLA";
	public static final int ESTADO_PENDIENTE_GENERACION_VALUE = Integer.valueOf(-99);	
	public static final String ESTADO_PENDIENTE_GENERACION_LABEL = "PENDIENTE GENERACION COMPROBANTE";
	
	public static final String DESCRIPCION_MATRICULA_POSGRADO = "MATRICULA POSGRADO";
	public static final String DESCRIPCION_MATRICULA_NIVELACION = "MATRICULA NIVELACIÓN";
	public static final String DESCRIPCION_MATRICULA_PREGRADO = "MATRICULA PREGRADO";
	// constantes para el total de caracteres de número de comprobante
	public static final int NUM_MAX_CARACTERES_COMPROBANTE = Integer.valueOf(10);
	
	
	// constantes para el campo de cmp_pai_codigo
	public static final int ECUADOR_VALUE_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(69);
	public static final String ECUADOR_VALUE_COMPROBANTE_CARGA_CSV_LABEL = "ECUADOR";
	public static final int NO_ECUADOR_VALUE_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
	public static final String NO_ECUADOR_VALUE_COMPROBANTE_CARGA_CSV_LABEL = "NO ECUADOR";
	
	
		// constantes para el campo de cmp_espe_codigo
		public static final int ESPE_CODIGO_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(69);
		public static final String ESPE_CODIGO_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "CODIGO DE PAIS EN SYSREC";
		
		// TODO revisar constantes para el campo de  cmp_proc_sau para matrículas
		public static final int PROC_SAU_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String PROC_SAU_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "TIPO DE PROCESO PARA FACTURACION";
		
		// constantes para el campo de  cmp_proc_sau
		public static final int APLICA_GRATUIDAD_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String APLICA_GRATUIDAD_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "APLICA GRATUIDAD";

		// constantes para el campo de  cmp_aplica_gratuidad
		public static final int NO_APLICA_GRATUIDAD_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String NO_APLICA_GRATUIDAD_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "NO APLICA GRATUIDAD POSGRADO";
		public static final int NO_APLICA_GRATUIDAD_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String NO_APLICA_GRATUIDAD_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "NO APLICA GRATUIDAD NIVELACION";
		
		// constantes para el campo de  cmp_arancel
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_IMPLANTOLOGIA_ORAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5112);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_IMPLANTOLOGIA_ORAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA IMPLANTOLOGIA ORAL";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ESTETICA_Y_OPERATORIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5113);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ESTETICA_Y_OPERATORIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA ESTETICA Y OPERATORIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_PERIODONCIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5114);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_PERIODONCIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA PERIODONCIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ORTODONCIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5115);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ORTODONCIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA ORTODONCIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_CIRUGIA_ORAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5116);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_CIRUGIA_ORAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA CIRUGIA ORAL";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ENDODONCIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5117);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ENDODONCIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA ENDODONCIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ODONTOPEDIATRIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5118);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_ODONTOPEDIATRIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA ODONTOPEDIATRIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_REHABILITACION_ORAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5119);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ODONTOLOGIA_REHABILITACION_ORAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ODONTOLOGIA REHABILITACION ORAL";
		
		//CAMPOS DE ID ARANCEL PARA MEDICINA
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ANATOMIA_PATOLOGICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5557);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ANATOMIA_PATOLOGICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA ANATOMIA_PATOLOGICA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ANESTESIOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5558);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ANESTESIOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA ANESTESIOLOGIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_CIRUGIA_GENERAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5268);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_CIRUGIA_GENERAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA CIRUGIA_GENERAL";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_CIRUGIA_ONCOLOGICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5269);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_CIRUGIA_ONCOLOGICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA CIRUGIA_ONCOLOGICA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_DERMATOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5556);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_DERMATOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA DERMATOLOGIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_GASTROENTEROLOGIA_Y_ENDOSCOPIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5271);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_GASTROENTEROLOGIA_Y_ENDOSCOPIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA GASTROENTEROLOGIA_Y_ENDOSCOPIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_GINECOLOGIA_Y_OBSTETRICIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5272);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_GINECOLOGIA_Y_OBSTETRICIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA GINECOLOGIA_Y_OBSTETRICIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_IMAGENOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5273);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_IMAGENOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA IMAGENOLOGIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_CRITICA_Y_TERAPIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5274);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_CRITICA_Y_TERAPIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA MEDICINA_CRITICA_Y_TERAPIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_DE_EMERGENCIAS_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5275);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_DE_EMERGENCIAS_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA MEDICINA_DE_EMERGENCIAS";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_INTERNA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5276);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_MEDICINA_INTERNA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA MEDICINA_INTERNA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_NEFROLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5277);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_NEFROLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA NEFROLOGIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_NEUMOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5278);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_NEUMOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA NEUMOLOGIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ONCOLOGIA_CLINICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5279);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ONCOLOGIA_CLINICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA ONCOLOGIA_CLINICA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ORTOPEDIA_Y_TRAUMATOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5280);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_ORTOPEDIA_Y_TRAUMATOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA ORTOPEDIA_Y_TRAUMATOLOGIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_OTORRINOLARINGOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5561);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_OTORRINOLARINGOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA OTORRINOLARINGOLOGIA";
		
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PATOLOGIA_CLINICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5282);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PATOLOGIA_CLINICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA PATOLOGIA_CLINICA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PEDIATRIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5283);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PEDIATRIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA PEDIATRIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PSIQUIATRIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5559);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_PSIQUIATRIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA PSIQUIATRIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_RADIOTERAPIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5285);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_RADIOTERAPIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA RADIOTERAPIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_UROLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5560);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_UROLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA UROLOGIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_OFTALMOLOGIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5554);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_OFTALMOLOGIA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA OFTALMOLOGIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_FAMILIAR_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5553);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_FAMILIAR_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA FAMILIAR";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_FORENSE_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5555);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MEDICINA_FORENSE_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MEDICINA FORENSE";
		
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_INICIAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC FILOSOFIA EDUCACION INICIAL";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_INICIAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5307);
		
//		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_CONSTITUCIONAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC DERECHO CONSTITUCIONAL";
//		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_CONSTITUCIONAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5355);
//		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_PENAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC DERECHO PENAL";
//		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_PENAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5353);
//		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_CONTRATACION_PUBLICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC CONTRATACION PUBLICA";
//		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_CONTRATACION_PUBLICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5354);
//		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_AMBIENTAL_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC DERECHO AMBIENTAL";
//		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_AMBIENTAL_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5356);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_CONSTITUCIONAL_EXTRA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC DERECHO CONSTITUCIONAL EXTRAORDINARIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_CONSTITUCIONAL_EXTRA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5380);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_PENAL_EXTRA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC DERECHO PENAL EXTRAORDINARIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_DERECHO_PENAL_EXTRA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5379);
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_CONTRATACION_PUBLICA_EXTRA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC CONTRATACION PUBLICA EXTRAORDINARIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_CONTRATACION_PUBLICA_EXTRA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5378);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_ENTRENAMIENTO_DEPORTIVO_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC ENTRENAMIENTO DEPORTIVO";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_ENTRENAMIENTO_DEPORTIVO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5401);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_LINGUISTICA_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC EDUCACION LINGUISTICA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_LINGUISTICA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5410);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_MENCION_TIC_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC EDUCACION MENCION TIC";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_EDUCACION_MENCION_TIC_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5411);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_PSICOLOGIA_INTERVENCION_ADICCIONES_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC PSICOLOGIA INTERVENCION ADICCIONES";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_PSICOLOGIA_INTERVENCION_ADICCIONES_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5440);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_INGENIERIA_MAESTRIA_SISTEMAS_MANUFACTURA_CARGA_CSV_LABEL = "ID ARANCEL SYSREC INGENIERIA SISTEMAS DE MANUFACTURA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_INGENIERIA_MAESTRIA_SISTEMAS_MANUFACTURA_CARGA_CSV_VALUE = Integer.valueOf(5432);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_VETERINARIA_EPIDEMIOLOGIA_SALUD_VETERINARIA_CARGA_CSV_LABEL = "ID ARANCEL SYSREC VETERINARIA EPIDEMIOLOGIA Y SALUD VETERINARIA";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_VETERINARIA_EPIDEMIOLOGIA_SALUD_VETERINARIA_CARGA_CSV_VALUE = Integer.valueOf(5591);
		
		public static final String ID_ARANCEL_INSCRIPCION_POSTGRADO_MAESTRIA_CONSTRUCCIONES_OBRAS_CIVILES_COMPROBANTE_CARGA_CSV_LABEL = "ID ARANCEL SYSREC MAESTRIA CONSTRUCCIONES OBRAS CIVILES";
		public static final Integer ID_ARANCEL_INSCRIPCION_POSTGRADO_MAESTRIA_CONSTRUCCIONES_OBRAS_CIVILES_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(-99);
		
		
		//////////////////////////////////////////////////////
		// ID DEL ARANCEL DEL SYSREC PARA NIVELACION
		public static final Integer ID_ARANCEL_SEGUNDA_MATRICULA_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5097);
		public static final String ID_ARANCEL_SEGUNDA_MATRICULA_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "MATRICULA SEGUNDA VEZ - NIVELACION";
		public static final Integer ID_ARANCEL_TERCERA_MATRICULA_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(5098);
		public static final String ID_ARANCEL_TERCERA_MATRICULA_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "MATRICULA TERCERA VEZ - NIVELACION";
		
		
		// constantes para el campo de  cmp_aplica_gratuidad
		public static final int CANTIDAD_MATRICULA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		
		// constantes para el campo de  cmp_arancel
		public static final Integer TIPO_UNIDAD_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(4);
		public static final String TIPO_UNIDAD_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "TIPO UNIDAD POSGRADOS";
		
		public static final Integer TIPO_UNIDAD_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String TIPO_UNIDAD_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "TIPO UNIDAD NIVELACION";
		
		
		// constantes para el campo de  cmp_proc_sau
		public static final BigDecimal TOTAL_FACULTAD_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = BigDecimal.valueOf(0);
		public static final String TOTAL_FACULTAD_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "TOTAL FACULTAD";
		
		// constantes para el campo de  modalidad
		public static final Integer MODALIDAD_NO_APLICA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String MODALIDAD_NO_APLICA_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "NO APLICA";
		public static final Integer MODALIDAD_PRESENCIAL_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String MODALIDAD_PRESENCIAL_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "PRESENCIAL";
		public static final Integer MODALIDAD_SEMIPRESENCIAL_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(2);
		public static final String MODALIDAD_SEMIPRESENCIAL_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "SEMIPRESENCIAL";
		public static final Integer MODALIDAD_DISTANCIA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(3);
		public static final String MODALIDAD_DISTANCIA_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "DISTANCIA";
		public static final Integer MODALIDAD_NO_APLICA_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String MODALIDAD_NO_APLICA_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "NO APLICA";
		public static final Integer MODALIDAD_PRESENCIAL_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String MODALIDAD_PRESENCIAL_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "PRESENCIAL";
		public static final Integer MODALIDAD_SEMIPRESENCIAL_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(2);
		public static final String MODALIDAD_SEMIPRESENCIAL_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "SEMIPRESENCIAL";
		public static final Integer MODALIDAD_DISTANCIA_NIVELACION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(3);
		public static final String MODALIDAD_DISTANCIA_INSCRIPCION_NIVELACION_COMPROBANTE_CARGA_CSV_LABEL = "DISTANCIA";
		
		// constantes para el campo de  matr_tipo
		public static final Integer MATRICULA_TIPO_NO_APLICA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String MATRICULA_TIPO_NO_APLICA_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "NO APLICA";
		public static final Integer MATRICULA_TIPO_ORDINARIA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String MATRICULA_TIPO_ORDINARIA_PRESENCIAL_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "ORDINARIA";
		public static final Integer MATRICULA_TIPO_EXTRAORDINARIA_POSTGRADO_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(2);
		public static final String MATRICULA_TIPO_EXTRAORDINARIA_INSCRIPCION_POSTGRADO_COMPROBANTE_CARGA_CSV_LABEL = "EXTRAORDINARIA";
		
		// constantes para el campo de valor de arancel de matricula de nivelación
		public static final BigDecimal MATRICULA_TIPO_NIVELACION_PRIMERA_MATRICULA_VALUE = new BigDecimal(0);
		public static final String MATRICULA_TIPO_NIVELACION_PRIMERA_MATRICULA_LABEL = "ARANCEL PRIMERA MATRICULA";
		public static final BigDecimal MATRICULA_TIPO_NIVELACION_SEGUNDA_MATRICULA_VALUE = new BigDecimal(108);
		public static final String MATRICULA_TIPO_NIVELACION_SEGUNDA_MATRICULA_LABEL = "ARANCEL SEGUNDA MATRICULA";
		public static final BigDecimal MATRICULA_TIPO_NIVELACION_TERCERA_MATRICULA_VALUE = new BigDecimal(216);
		public static final String MATRICULA_TIPO_NIVELACION_TERCERA_MATRICULA_LABEL = "ARANCEL TERCERA MATRICULA";
		
		
		public static final BigDecimal TOTAL_FACULTAD_COMPROBANTE_CARGA_CSV_VALUE = BigDecimal.valueOf(0);
		public static final String TOTAL_FACULTAD_INSCRIPCION_COMPROBANTE_CARGA_CSV_LABEL = "TOTAL FACULTAD";
		public static final int PROC_SAU_INSCRIPCION_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String PROC_SAU_INSCRIPCION_COMPROBANTE_CARGA_CSV_LABEL = "TIPO DE PROCESO PARA FACTURACION";
		public static final Integer TIPO_UNIDAD_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String TIPO_UNIDAD_COMPROBANTE_CARGA_CSV_LABEL = "TIPO UNIDAD";
		public static final int CANTIDAD_MATRICULA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final int INDEPENDIENTE_GRATUIDAD_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(0);
		public static final String INDEPENDIENTE_GRATUIDAD_COMPROBANTE_CARGA_CSV_LABEL = "INDEPENDIENTE GRATUIDAD";
		
		public static final Integer MATRICULA_TIPO_ORDINARIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(1);
		public static final String MATRICULA_TIPO_ORDINARIA_COMPROBANTE_CARGA_CSV_LABEL = "ORDINARIA";
		public static final Integer MATRICULA_TIPO_EXTRAORDINARIA_COMPROBANTE_CARGA_CSV_VALUE = Integer.valueOf(2);
		public static final String MATRICULA_TIPO_EXTRAORDINARIA_COMPROBANTE_CARGA_CSV_LABEL = "EXTRAORDINARIA";
		 
		
}
